/* HomeStore POS — website chat bubble.  Paste before </body>:
   <script src="https://app.homestorepos.com/chat.js" data-store="YOUR-STORE-ID"></script>
   Opens the store's HomeStore chat (app.homestorepos.com/#chat/<store id>) in a small panel. */
(function(){ var s=document.currentScript||(function(){ var a=document.getElementsByTagName("script"); return a[a.length-1]; })(); if(!s) return; var tid=s.getAttribute("data-store")||""; if(!tid) return;
  var base=(s.getAttribute("data-base")||s.src.replace(/\/chat\.js.*$/,"")).replace(/\/$/,""); var color=s.getAttribute("data-color")||"#2a9d8f"; var label=s.getAttribute("data-label")||"Chat with us";
  var css=document.createElement("style"); css.textContent="#hs-chat-btn{position:fixed;right:18px;bottom:18px;z-index:2147483000;border:0;border-radius:999px;background:"+color+";color:#fff;font:600 15px/1 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;padding:14px 18px;box-shadow:0 8px 24px rgba(0,0,0,.25);cursor:pointer;display:flex;align-items:center;gap:8px}#hs-chat-btn:hover{filter:brightness(1.05)}#hs-chat-panel{position:fixed;right:18px;bottom:84px;width:380px;max-width:calc(100vw - 24px);height:600px;max-height:calc(100vh - 110px);z-index:2147483000;border:0;border-radius:16px;box-shadow:0 16px 48px rgba(0,0,0,.3);background:#fff;display:none}@media (max-width:480px){#hs-chat-panel{right:0;bottom:0;width:100vw;max-width:100vw;height:100vh;max-height:100vh;border-radius:0}#hs-chat-btn.open{display:none}}"; document.head.appendChild(css);
  var btn=document.createElement("button"); btn.id="hs-chat-btn"; btn.type="button"; btn.innerHTML='<span style="font-size:18px">💬</span><span>'+label.replace(/</g,"&lt;")+'</span>'; var frame=null, open=false;
  function toggle(){ open=!open; if(!frame){ frame=document.createElement("iframe"); frame.id="hs-chat-panel"; frame.title="Chat with the store"; frame.src=base+"/#chat/"+encodeURIComponent(tid); frame.setAttribute("allow","clipboard-write"); document.body.appendChild(frame); }
    frame.style.display=open?"block":"none"; btn.className=open?"open":""; btn.innerHTML=open?'<span style="font-size:18px">✕</span><span>Close</span>':'<span style="font-size:18px">💬</span><span>'+label.replace(/</g,"&lt;")+'</span>'; }
  btn.addEventListener("click",toggle); window.addEventListener("message",function(e){ if(e&&e.data==="hs-chat-close"&&open) toggle(); }); document.body.appendChild(btn); })();
