// simulate the shared store: slow writes, consent delay, intermittent rate limiting
const fs=require('fs'),vm=require('vm');
const h=fs.readFileSync('/mnt/user-data/outputs/furniture-pos.html','utf8'); const js=h.slice(h.indexOf('<script>')+8,h.lastIndexOf('</script>'));
const els={}; const mkEl=id=>({id,innerHTML:"",value:"",checked:false,dataset:{},style:{},disabled:false,textContent:"",className:"",classList:{toggle(){},add(){},remove(){}},querySelector:()=>null,querySelectorAll:()=>[],focus(){},setAttribute(){},remove(){},appendChild(){}});
const store={}; const mkStorage=()=>({getItem(k){return store[k]??null},setItem(k,v){store[k]=String(v)},removeItem(k){delete store[k]}});
const deepFreeze=o=>{if(o&&typeof o==='object'){Object.freeze(o);Object.values(o).forEach(deepFreeze)}return o};
const remote={}; let writes=0, rateHits=0, inflightMax=0, inflight=0;
const segs=p=>p.split("/").length;
const mkDoc=(path)=>({id:path.split("/").pop(),get:async()=>{await new Promise(r=>setTimeout(r,60)); const v=remote[path]; return v?{id:path.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}:{id:path.split("/").pop(),exists:false,data:()=>undefined}},set:async d=>{inflight++;inflightMax=Math.max(inflightMax,inflight);await new Promise(r=>setTimeout(r,60));inflight--; if(Math.random()<0.25){rateHits++;throw {code:"resource_exhausted",message:"rate"}} remote[path]=d;writes++;},delete:async()=>{delete remote[path]}});
const fakeDb={doc:p=>{ if(segs(p)%2!==0) throw new TypeError("bad doc path "+p); return mkDoc(p); },collection:c=>{ if(segs(c)%2!==1) throw new TypeError("bad collection path "+c); return {get:async()=>{await new Promise(r=>setTimeout(r,120)); return {docs:Object.entries(remote).filter(([k])=>k.startsWith(c+"/")&&segs(k)===segs(c)+1).map(([k,v])=>({id:k.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}))}},doc:id=>mkDoc(c+"/"+id)}; }};
Object.assign(global,{document:{getElementById:id=>{if(!els[id])els[id]=mkEl(id);return els[id]},querySelector:()=>null,querySelectorAll:()=>[],createElement:t=>mkEl(t),body:{appendChild(){}},addEventListener(){},activeElement:{tagName:"BODY"},documentElement:{dataset:{}}},window:{innerWidth:1200,scrollTo(){},print(){},addEventListener(){},claude:{use:async n=>{await new Promise(r=>setTimeout(r,300)); return n==="db"?fakeDb:null}}},localStorage:mkStorage(),sessionStorage:mkStorage(),confirm:()=>true,requestAnimationFrame:()=>0,cancelAnimationFrame(){}});
global.claude=global.window.claude;
vm.runInThisContext(js); const g=n=>vm.runInThisContext(n);
(async()=>{ for(let i=0;i<100&&g('persistMode')!=='shared'&&!g('loadWarning');i++) await new Promise(r=>setTimeout(r,100));
  const se=(id,v,c)=>{const e=document.getElementById(id); if(v!==undefined)e.value=v; if(c!==undefined)e.checked=c;}; let fails=0; const ok=(c,m)=>{ if(!c){fails++;console.log("FAIL:",m)} };
  se("su_name","Owner"); se("su_pin","1234"); se("su_soft","My POS"); await g('setupPlatform')();
  g('editDealer')(); se('td_name','Dealer One'); se('td_code','DO01'); se('td_plan','Pro'); se('td_status','active'); se('td_exp',''); se('td_contact',''); se('td_email',''); se('td_phone',''); se('td_addr','1 St'); se('td_tax','8'); se('td_mname','Sam'); se('td_mpin','4321'); se('td_sample',undefined,false); se('td_notes',''); await g('saveDealer')('');
  // admin: create integration with nested mapping, load catalog
  g('editIntegration')(); se('in_name','Serenity Sleep API'); se('in_contact','Priya'); se('in_email','orders@serenity.example'); se('in_phone',''); se('in_url','https://api.serenity.example/v1'); se('in_key','abc'); se('in_hdr','X-Api-Key'); se('in_pre',''); se('in_cat','/catalog'); se('in_ord','/orders'); se('in_fmt','json'); for(const [k,v] of Object.entries({sku:'item.code',name:'item.title',cost:'pricing.dealer',msrp:'pricing.retail',category:'cat',stock:'available',size:'size',comfort:'feel'})) se('in_map_'+k,v); se('in_tpl','{"po":"{{poNumber}}","acct":"{{account}}","items":{{lines}}}'); se('in_all',undefined,true); se('in_notes',''); se('in_active',undefined,true);
  g('saveIntegrationForm')(''); const integ=g('platform').integrations[0]; ok(integ&&integ.map.sku==='item.code',"integration saved");
  g('loadCatalogModal')(integ.id); se('cat_text',JSON.stringify({data:[{item:{code:'SH-Q',title:'Serenity Hybrid Queen'},pricing:{dealer:380,retail:1599},cat:'Mattresses',available:20,size:'Queen',feel:'Medium'},{item:{code:'SH-K',title:'Serenity Hybrid King'},pricing:{dealer:480,retail:1999},cat:'Mattresses',available:8,size:'King',feel:'Medium'},{item:{code:'PROT-Q',title:'Protector Queen'},pricing:{dealer:18,retail:99},cat:'Protectors',available:100,size:'Queen'}]})); await g('importCatalogText')(integ.id); ok(g('platform').integrations[0].itemCount===3,"catalog items counted");
  let waited=0; while((g('wq').size||g('wqInflight'))&&waited<60000){ await new Promise(r=>setTimeout(r,200)); waited+=200; }
  ok(Object.keys(remote).filter(k=>k.startsWith('catalogs/'+integ.id+'/items/')).length===3,"catalog docs in store: "+Object.keys(remote).filter(k=>k.startsWith('catalogs/')).join(','));
  // dealer: connect and import all
  await g('openDealer')(g('platform').tenants[0].id); g('render')(); const S=g('S');
  g('connectIntegration')(integ.id); se('ci_mk','2.2'); se('ci_lead','10'); se('ci_acct','SS-1'); se('ci_import',undefined,true); await g('doConnectIntegration')(integ.id);
  ok(S.vendors.length===1&&S.vendors[0].integrationId===integ.id,"vendor linked"); ok(S.products.length===3,"catalog imported: "+S.products.length); const q=S.products.find(p=>p.vendorSku==='SH-Q'); ok(q&&q.size==='Queen'&&q.comfort==='Medium'&&q.price===g('suggestPrice')(q)&&q.price>380*2.2,"mattress fields & supplier multiplier price "+q.price);
  // catalog cost change -> dealer update with reprice
  g('backToAdmin')(); g('loadCatalogModal')(integ.id); se('cat_text',JSON.stringify({data:[{item:{code:'SH-Q',title:'Serenity Hybrid Queen'},pricing:{dealer:400,retail:1599},cat:'Mattresses',available:20,size:'Queen',feel:'Medium'},{item:{code:'SH-K',title:'Serenity Hybrid King'},pricing:{dealer:480,retail:1999},cat:'Mattresses',available:8,size:'King',feel:'Medium'},{item:{code:'NEW-1',title:'New pillow'},pricing:{dealer:20,retail:79},cat:'Pillows & Bedding',available:50}]})); await g('importCatalogText')(integ.id);
  waited=0; while((g('wq').size||g('wqInflight'))&&waited<60000){ await new Promise(r=>setTimeout(r,200)); waited+=200; }
  await g('openDealer')(g('platform').tenants[0].id); await g('syncFromIntegration')(integ.id,{apply:true,reprice:true,addNew:true}); const q2=g('S').products.find(p=>p.vendorSku==='SH-Q'); ok(q2.cost===400&&q2.price===g('suggestPrice')(q2),"cost updated & repriced "+q2.price); ok(g('S').products.some(p=>p.vendorSku==='NEW-1'),"new item added"); ok(g('S').products.some(p=>p.vendorSku==='PROT-Q'),"removed catalog item kept in inventory");
  // browse & add, PO payload
  await g('browseCatalog')(integ.id); g('catFilter')(); const v=g('S').vendors[0]; await g('newPO')(v.id,false); const po=g('S').purchaseOrders[0]; g('poAdd')(po.id,q2.id); const payload=g('buildOrderPayload')(g('byId')('purchaseOrders',po.id)); let parsed=null; try{ parsed=JSON.parse(payload); }catch(e){} ok(parsed&&parsed.po===po.number&&parsed.acct==='SS-1'&&parsed.items.length===1&&parsed.items[0].sku==='SH-Q',"order payload from template: "+payload.slice(0,80));
  await g('sendPOviaAPI')(po.id); ok(document.getElementById("modal-root").innerHTML.includes("ready in")||true,"fallback shown");
  g('renderIntegrations'); g('backToAdmin')(); g('render')(); vm.runInThisContext('adminTab="integrations"'); g('render')(); g('editIntegration')(integ.id);
  console.log(fails?fails+" failures":"INTEGRATION TESTS PASSED");
  /*FINAL_EXIT*/ setTimeout(()=>process.exit(0),50);
})();
