// simulate the shared store: slow writes, consent delay, intermittent rate limiting
const fs=require('fs'),vm=require('vm');
const h=fs.readFileSync('/mnt/user-data/outputs/furniture-pos.html','utf8'); const js=h.slice(h.indexOf('<script>')+8,h.lastIndexOf('</script>'));
const els={}; const mkEl=id=>({id,innerHTML:"",value:"",checked:false,dataset:{},style:{},disabled:false,textContent:"",className:"",classList:{toggle(){},add(){},remove(){}},querySelector:()=>null,querySelectorAll:()=>[],focus(){},setAttribute(){},remove(){},appendChild(){}});
const store={}; const mkStorage=()=>({getItem(k){return store[k]??null},setItem(k,v){store[k]=String(v)},removeItem(k){delete store[k]}});
const deepFreeze=o=>{if(o&&typeof o==='object'){Object.freeze(o);Object.values(o).forEach(deepFreeze)}return o};
const remote={'settings/store':{id:'store',name:'Old Store',taxRate:7,barcodePrefix:'OS',address:'1 Main',lat:40.4,lng:-79.9},'staff/s1':{id:'s1',name:'Marisol',commType:'sales',rate:5},'products/p1':{id:'p1',sku:'OS-1',name:'Sofa',cost:100,price:300,stock:2,vendorId:'',category:'Sofas'},'invoices/i1':{id:'i1',number:'INV-1001',date:'2026-09-01',customerId:'',salesId:'s1',lines:[{productId:'p1',sku:'OS-1',name:'Sofa',qty:1,price:300,cost:100}],groups:[],payments:[{method:'Card',amount:324.75,date:'2026-09-01'}],status:'paid',delivery:false}}; let writes=0, rateHits=0, inflightMax=0, inflight=0;
const segs=p=>p.split("/").length;
const mkDoc=(path)=>({id:path.split("/").pop(),get:async()=>{await new Promise(r=>setTimeout(r,60)); const v=remote[path]; return v?{id:path.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}:{id:path.split("/").pop(),exists:false,data:()=>undefined}},set:async d=>{inflight++;inflightMax=Math.max(inflightMax,inflight);await new Promise(r=>setTimeout(r,60));inflight--; if(Math.random()<0.25){rateHits++;throw {code:"resource_exhausted",message:"rate"}} remote[path]=d;writes++;},delete:async()=>{delete remote[path]}});
const fakeDb={doc:p=>{ if(segs(p)%2!==0) throw new TypeError("bad doc path "+p); return mkDoc(p); },collection:c=>{ if(segs(c)%2!==1) throw new TypeError("bad collection path "+c); return {get:async()=>{await new Promise(r=>setTimeout(r,120)); return {docs:Object.entries(remote).filter(([k])=>k.startsWith(c+"/")&&segs(k)===segs(c)+1).map(([k,v])=>({id:k.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}))}},doc:id=>mkDoc(c+"/"+id)}; }};
Object.assign(global,{document:{getElementById:id=>{if(!els[id])els[id]=mkEl(id);return els[id]},querySelector:()=>null,querySelectorAll:()=>[],createElement:t=>mkEl(t),body:{appendChild(){}},addEventListener(){},activeElement:{tagName:"BODY"},documentElement:{dataset:{}}},window:{innerWidth:1200,scrollTo(){},print(){},addEventListener(){},claude:{use:async n=>{await new Promise(r=>setTimeout(r,300)); return n==="db"?fakeDb:null}}},localStorage:mkStorage(),sessionStorage:mkStorage(),confirm:()=>true,requestAnimationFrame:()=>0,cancelAnimationFrame(){}});
global.claude=global.window.claude;
vm.runInThisContext(js); const g=n=>vm.runInThisContext(n);
(async()=>{ for(let i=0;i<100&&g('persistMode')!=='shared'&&!g('loadWarning');i++) await new Promise(r=>setTimeout(r,100)); console.log("mode after connect:",g('persistMode'),g('loadWarning'));
  console.log("legacy root data migrated into dealer:",g('platform').tenants.length===1, g('platform').tenants[0]&&g('platform').tenants[0].code);
  document.getElementById("su_name").value="Owner"; document.getElementById("su_pin").value="1234"; document.getElementById("su_soft").value="My POS";
  const t0=Date.now(); await g('setupPlatform')(); const dt=Date.now()-t0; console.log("setup returned in ms:",dt,"logged in as admin:",g('session')&&g('session').kind==="admin");
  const tid=g('platform').tenants[0].id; await g('openDealer')(tid); console.log("opened migrated dealer: products",g('S').products.length,"staff roles",g('S').staff.map(s=>s.name+":"+s.role).join(","),"settings prefix",g('storeSettings')().skuPrefix);
  let waited=0; while((g('wq').size||g('wqInflight'))&&waited<60000){ await new Promise(r=>setTimeout(r,200)); waited+=200; }
  const total=Object.values(g('S')).filter(Array.isArray).reduce((a,c)=>a+c.length,0)+1+1+4; console.log("queue drained in ms:",waited,"remote docs:",Object.keys(remote).length,"local docs:",total,"rate hits handled:",rateHits,"max concurrent:",inflightMax);
  console.log(Object.keys(remote).length===total?"DB SYNC OK":"DB SYNC MISMATCH"); console.log("wizard msg:",document.getElementById("su_msg").textContent,"| staff:",g("S").staff.map(s=>s.name+":"+s.role).join(","),"| store:",g("storeSettings")().name);
  /*FINAL_EXIT*/ setTimeout(()=>process.exit(0),50);
})();
