// simulate the shared store: slow writes, consent delay, intermittent rate limiting
const fs=require('fs'),vm=require('vm');
const h=fs.readFileSync('/mnt/user-data/outputs/furniture-pos.html','utf8'); const js=h.slice(h.indexOf('<script>')+8,h.lastIndexOf('</script>'));
const els={}; const mkEl=id=>({id,innerHTML:"",value:"",checked:false,dataset:{},style:{},disabled:false,textContent:"",className:"",classList:{toggle(){},add(){},remove(){}},querySelector:()=>null,querySelectorAll:()=>[],focus(){},setAttribute(){},remove(){},appendChild(){}});
const store={}; const mkStorage=()=>({getItem(k){return store[k]??null},setItem(k,v){store[k]=String(v)},removeItem(k){delete store[k]}});
const deepFreeze=o=>{if(o&&typeof o==='object'){Object.freeze(o);Object.values(o).forEach(deepFreeze)}return o};
const remote={'platform/config':{id:'config',softwareName:'My POS',admins:[{id:'a1',name:'Owner',pin:'1234'}]},'tenants/t1':{id:'t1',code:'HT01',name:'Hearth',status:'active',plan:'Pro'},'tenants/t1/staff/s1':{id:'s1',name:'Jordan',role:'manager',pin:'1234',active:true},'tenants/t1/settings/store':{id:'store',name:'Hearth'}}; let writes=0, rateHits=0, inflightMax=0, inflight=0;
const segs=p=>p.split("/").length;
const mkDoc=(path)=>({id:path.split("/").pop(),get:async()=>{await new Promise(r=>setTimeout(r,60)); const v=remote[path]; return v?{id:path.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}:{id:path.split("/").pop(),exists:false,data:()=>undefined}},set:async d=>{inflight++;inflightMax=Math.max(inflightMax,inflight);await new Promise(r=>setTimeout(r,60));inflight--; if(Math.random()<0.25){rateHits++;throw {code:"resource_exhausted",message:"rate"}} remote[path]=d;writes++;},delete:async()=>{delete remote[path]}});
const fakeDb={doc:p=>{ if(segs(p)%2!==0) throw new TypeError("bad doc path "+p); return mkDoc(p); },collection:c=>{ if(segs(c)%2!==1) throw new TypeError("bad collection path "+c); return {get:async()=>{await new Promise(r=>setTimeout(r,120)); return {docs:Object.entries(remote).filter(([k])=>k.startsWith(c+"/")&&segs(k)===segs(c)+1).map(([k,v])=>({id:k.split("/").pop(),exists:true,data:()=>deepFreeze(JSON.parse(JSON.stringify(v)))}))}},doc:id=>mkDoc(c+"/"+id)}; }};
global.location={hash:'#store/ht01',href:'https://x/y#store/ht01'};
Object.assign(global,{document:{getElementById:id=>{if(!els[id])els[id]=mkEl(id);return els[id]},querySelector:()=>null,querySelectorAll:()=>[],createElement:t=>mkEl(t),body:{appendChild(){}},addEventListener(){},activeElement:{tagName:"BODY"},documentElement:{dataset:{}}},window:{innerWidth:1200,scrollTo(){},print(){},addEventListener(){},claude:{use:async n=>{await new Promise(r=>setTimeout(r,300)); return n==="db"?fakeDb:null}}},localStorage:mkStorage(),sessionStorage:mkStorage(),confirm:()=>true,requestAnimationFrame:()=>0,cancelAnimationFrame(){}});
global.claude=global.window.claude;
vm.runInThisContext(js); const g=n=>vm.runInThisContext(n);
(async()=>{ const root=document.getElementById("root");
  console.log("before connect shows connecting screen:", root.innerHTML.includes("Connecting to your store"), "| no wizard:", !root.innerHTML.includes("SOFTWARE OWNER SETUP"));
  for(let i=0;i<100&&!g('platformLoaded');i++) await new Promise(r=>setTimeout(r,100)); await new Promise(r=>setTimeout(r,800)); for(let i=0;i<60&&(g("loginBusy")||!g("loginTenant"));i++) await new Promise(r=>setTimeout(r,200));
  console.log("mode:",g('deviceMode'),"code:",g('loginCode'),"tenant opened:",g('loginTenant')&&g('loginTenant').code,"| staff tile shown:",root.innerHTML.includes(">Jordan<")||root.innerHTML.includes("Jordan<span"), "| admin hidden:", !root.innerHTML.includes("ADMINISTRATION"));
  vm.runInThisContext("loginSel='s1'"); g('pinKey')('1'); g('pinKey')('2'); g('pinKey')('3'); g('pinKey')('4'); console.log("signed in:", g('session')&&g('session').staffId==='s1', "view:", g('view'));
  /*FINAL_EXIT*/ setTimeout(()=>process.exit(0),50);
})();
