/* ============================================================
   ORDERS BOARD, ETA ALERTS, SPLIT SALES
   ============================================================ */
const HOUSE_ID="house";
function salesShare(inv,staffId){ if(inv.splits&&inv.splits.length){ const s=inv.splits.find(x=>x.staffId===staffId); return s?(+s.pct||0)/100:0; } return inv.salesId===staffId?1:0; }
function splitLabel(inv){ if(inv.splits&&inv.splits.length) return inv.splits.map(s=>`${s.staffId===HOUSE_ID?"House":firstName(staffName(s.staffId))} ${s.pct}%`).join(" / "); return staffName(inv.salesId); }
function splitModal(){ const st=S.staff.filter(s=>s.active!==false&&s.role!=="driver"); const cur0=cur.splits&&cur.splits.length?cur.splits:[{staffId:cur.salesId||"",pct:100}]; window._splits=cur0.map(s=>Object.assign({},s));
  modal(`<h2>Split this sale</h2><p class="muted">Share the credit and commission between salespeople, or with the house. Shares must total 100%.</p><div id="split_rows"></div><div class="row" style="margin-top:8px"><button class="btn s fx" onclick="window._splits.push({staffId:'',pct:0});splitRender()">+ Add person</button><button class="btn s fx" onclick="window._splits.push({staffId:'${HOUSE_ID}',pct:0});splitRender()">+ House</button><button class="btn s fx" onclick="splitEqual()">Split equally</button></div><div class="actions"><button class="btn" onclick="cur.splits=[];closeModal();render()">No split</button><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="splitSave()">Save split</button></div>`);
  splitRender(); }
function splitRender(){ const st=S.staff.filter(s=>s.active!==false&&s.role!=="driver"); const total=window._splits.reduce((a,s)=>a+(+s.pct||0),0); document.getElementById("split_rows").innerHTML=window._splits.map((s,i)=>`<div class="row" style="margin-bottom:6px"><select onchange="window._splits[${i}].staffId=this.value">${s.staffId===HOUSE_ID?`<option value="${HOUSE_ID}" selected>House (no commission)</option>`:opts(st,s.staffId,x=>x.name,x=>x.id,"Choose…")+`<option value="${HOUSE_ID}">House (no commission)</option>`}</select><input type="number" step="1" min="0" max="100" value="${s.pct}" style="max-width:100px" onchange="window._splits[${i}].pct=+this.value||0;splitRender()"><span class="muted fx">%</span><button class="btn s fx" onclick="window._splits.splice(${i},1);splitRender()">✕</button></div>`).join("")+`<div class="muted small" style="margin-top:4px">Total ${total}%${total!==100?' <span class="tag bad">must be 100%</span>':' <span class="tag ok">ok</span>'}</div>`; }
function splitEqual(){ const n=window._splits.length||1; const base=Math.floor(100/n); window._splits.forEach((s,i)=>s.pct=base+(i<100-base*n?1:0)); splitRender(); }
function splitSave(){ const sp=window._splits.filter(s=>s.staffId); const total=sp.reduce((a,s)=>a+(+s.pct||0),0); if(!sp.length) return toast("Add at least one person.",true); if(total!==100) return toast("Shares must total 100%.",true); if(new Set(sp.map(s=>s.staffId)).size!==sp.length) return toast("Each person can appear once.",true); cur.splits=sp.map(s=>({staffId:s.staffId,pct:+s.pct})); const first=sp.find(s=>s.staffId!==HOUSE_ID); cur.salesId=first?first.staffId:cur.salesId; closeModal(); render(); }

/* ---------- ETA alerts ---------- */
function openLinesWithEta(){ const out=[]; for(const inv of S.invoices){ if(["void","quote","draft"].includes(inv.status)) continue; for(const l of inv.lines){ if(!lineOpen(l)) continue; if(!lineBlocked(l)&&!l.delayReason) continue; out.push({inv,l}); } } return out; }
function etaBuckets(){ const st=storeSettings(); const days=st.etaAlertDays||3; const today=todayISO(); const soon=addDays(today,days); const b={overdue:[],soon:[],noEta:[],arrived:[]};
  for(const x of openLinesWithEta()){ if(x.l.specialStatus==="arrived"){ b.arrived.push(x); continue; } if(!x.l.expected) b.noEta.push(x); else if(x.l.expected<today) b.overdue.push(x); else if(x.l.expected<=soon) b.soon.push(x); }
  // arrived-but-not-scheduled: any open line that's in stock/arrived on an order with no scheduled delivery / ready pickup notified
  for(const inv of S.invoices){ if(["void","quote","draft","layaway"].includes(inv.status)) continue; const open=inv.lines.filter(lineOpen); if(!open.length||open.some(lineBlocked)) continue; if(inv.lines.some(l=>l.deliveredAt)||inv.lines.some(l=>l.expected)){ const d=deliveryOf(inv); const p=pickupOf(inv); const waiting=inv.delivery?(d&&["unscheduled","missed","awaiting"].includes(d.status)):(p&&p.status!=="pickedup"&&!p.notified); if(waiting&&!b.arrived.some(x=>x.inv.id===inv.id)) b.arrived.push({inv,l:open[0]}); } }
  return b; }
function renderEtaAlerts(){ const b=etaBuckets(); if(!b.overdue.length&&!b.soon.length&&!b.arrived.length&&!b.noEta.length) return ""; const row=(x,cls,note)=>`<div class="attn"><div class="n ${cls}">${x.l.expected?dateShort(x.l.expected).split(" ")[1]:"?"}</div><div class="t"><b>${esc(x.l.name)} · ${esc(custName(x.inv.customerId))}</b><span>${esc(note)} · <a href="#" onclick="openInvoice('${x.inv.id}');return false">${esc(x.inv.number)}</a>${x.l.delayReason?" · "+esc(x.l.delayReason):""}</span></div><button class="btn s" onclick="etaAction('${x.inv.id}')">${x.l.specialStatus==="arrived"||!lineBlocked(x.l)?(x.inv.delivery?"Schedule":"Notify"):"Update"}</button></div>`;
  return `<div class="card" style="margin-bottom:16px"><div class="row"><h2 style="margin:0">Delayed items — priority</h2><span class="fx muted small">alerts ${storeSettings().etaAlertDays||3} days before an ETA · <a href="#" onclick="ordersFilter='eta';go('orders');return false">open orders board</a></span></div>${b.arrived.slice(0,6).map(x=>row(x,"ok","Arrived / in stock — get it out the door")).join("")}${b.overdue.slice(0,6).map(x=>row(x,"bad","ETA passed with no arrival — chase the vendor")).join("")}${b.soon.slice(0,6).map(x=>row(x,"warn","ETA coming up — confirm arrival and line up the delivery")).join("")}${b.noEta.slice(0,4).map(x=>row(x,"","Outstanding with no ETA")).join("")}</div>`; }
function etaAction(invId){ const inv=byId("invoices",invId); const open=inv.lines.filter(lineOpen); if(open.some(lineBlocked)) return setEta(invId); if(inv.delivery){ const d=deliveryOf(inv); if(d&&["unscheduled","missed","awaiting"].includes(d.status)) return editDelivery(d.id); return openInvoice(invId); } const p=pickupOf(inv); if(p&&p.status!=="pickedup") { delTab="pickups"; go("deliveries"); return; } openInvoice(invId); }

/* ---------- orders board ---------- */
let ordersFilter="open", ordersQ="";
function orderStatusKey(inv){ const l=fulfillmentLabel(inv); if(!l) return ""; if(/^Partially delivered/.test(l)) return "partial_delivered"; if(/^Partially picked/.test(l)) return "partial_pickup"; if(/^Delivered|^Picked up|^Taken/.test(l)) return "done"; if(/awaiting stock|Awaiting/.test(l)) return "awaiting"; if(/Held/.test(l)) return "held"; if(/^Part ready for pickup|· rest part ready/.test(l)) return "partready"; if(/Ready for pickup/.test(l)) return "ready"; if(/To schedule|Missed/.test(l)) return "toschedule"; if(/Scheduled|Loaded|Out/.test(l)) return "scheduled"; return "other"; }
const ORDER_COLS=(today,soon)=>[["Order",x=>`<div style="min-width:150px"><a href="#" onclick="openInvoice('${x.i.id}');return false"><b>${esc(x.i.number)}</b></a><div class="muted small">sold ${dateShort(x.i.date)}</div><div class="muted small">${esc(splitLabel(x.i))}</div></div>`],["Customer",x=>`<div style="min-width:140px"><b>${esc(custName(x.i.customerId))}</b><div class="muted small">${esc(byId("customers",x.i.customerId)?.phone||"")}</div></div>`],["Status",x=>fulfillmentTag(x.i)],["Outstanding items",x=>x.open.length?x.open.map(l=>`${l.qty}× ${esc(l.name)}${lineBlocked(l)?` <span class="tag ${l.expected?(l.expected<today?"bad":l.expected<=soon?"warn":""):"warn"}">${l.expected?"ETA "+dateShort(l.expected):"no ETA"}</span>`:l.delayReason?` <span class="tag warn">${esc(l.delayReason)}</span>`:""}`).join("<br>"):'<span class="muted">all delivered</span>'],["Next",x=>{ if(x.key==="done") return ""; if(x.i.status==="layaway") return '<span class="muted small">held until paid off</span>'; const blocked=x.open.some(lineBlocked); const pkp=pickupOf(x.i); if(blocked&&pkp&&pkp.status==="partready"){ const c=byId("customers",x.i.customerId); return `<div class="bgroup">${c?.phone?`<a class="btn s" href="sms:${esc(c.phone)}?&body=${encodeURIComponent(readyText(x.i,true))}" onclick="markNotified('${pkp.id}')">Text: part in</a>`:""}<button class="btn s p" onclick="completePickup('${pkp.id}')">Pick up what's in</button><button class="btn s" onclick="setEta('${x.i.id}')">${x.eta?"Update ETA":"Set ETA"}</button></div>`; } if(blocked) return `<div class="bgroup"><button class="btn s" onclick="setEta('${x.i.id}')">${x.eta?"Update ETA":"Set ETA"}</button></div>`; if(x.i.delivery){ const d=deliveryOf(x.i); return d&&["unscheduled","missed","awaiting"].includes(d.status)?`<button class="btn s p" onclick="editDelivery('${d.id}')">Schedule</button>`:d?`<span class="muted small">${esc(d.status)}${d.date?" "+dateShort(d.date):""}</span>`:""; } const p=pickupOf(x.i); if(p&&p.status==="ready"){ const c=byId("customers",x.i.customerId); return `<div class="bgroup">${!p.notified&&c?.phone?`<a class="btn s" href="sms:${esc(c.phone)}?&body=${encodeURIComponent(readyText(x.i))}" onclick="markNotified('${p.id}')">Text ready</a>`:""}<button class="btn s p" onclick="completePickup('${p.id}')">Pick up</button></div>`; } return ""; }]];
function renderOrders(){
  const today=todayISO(); const st=storeSettings(); const soon=addDays(today,st.etaAlertDays||3); const q=ordersQ.toLowerCase();
  let list=S.invoices.filter(i=>!["void","quote","draft"].includes(i.status)).map(i=>{ const key=orderStatusKey(i); const open=i.lines.filter(lineOpen); const eta=open.map(l=>l.expected).filter(Boolean).sort()[0]||""; return {i,key,open,eta,label:fulfillmentLabel(i)}; });
  const counts={open:list.filter(x=>x.key!=="done").length,partial_delivered:list.filter(x=>x.key==="partial_delivered").length,partial_pickup:list.filter(x=>x.key==="partial_pickup").length,awaiting:list.filter(x=>x.key==="awaiting").length,ready:list.filter(x=>x.key==="ready").length,partready:list.filter(x=>x.key==="partready").length,toschedule:list.filter(x=>x.key==="toschedule").length,scheduled:list.filter(x=>x.key==="scheduled").length,eta:list.filter(x=>x.eta&&x.eta<=soon&&x.key!=="done").length,done:list.filter(x=>x.key==="done").length};
  list=list.filter(x=>{ if(ordersFilter==="open") return x.key!=="done"; if(ordersFilter==="eta") return x.eta&&x.eta<=soon&&x.key!=="done"; if(ordersFilter==="all") return true; return x.key===ordersFilter; });
  if(q) list=list.filter(x=>[x.i.number,custName(x.i.customerId),x.i.lines.map(l=>l.name).join(" ")].join(" ").toLowerCase().includes(q));
  list.sort((a,b)=>(a.eta||"9999").localeCompare(b.eta||"9999")||b.i.date.localeCompare(a.i.date));
  const tab=(k,l)=>`<button class="${ordersFilter===k?"on":""}" onclick="ordersFilter='${k}';render()">${l}${counts[k]!==undefined?` (${counts[k]})`:""}</button>`;
  const GROUPS=[["eta_over","Needs attention — ETA passed or missing",x=>x.key!=="done"&&x.open.some(l=>lineBlocked(l)&&(!l.expected||l.expected<today))],["ready","Ready for pickup",x=>x.key==="ready"],["partready","Part ready — rest on order",x=>x.key==="partready"],["toschedule","To schedule",x=>x.key==="toschedule"],["scheduled","Scheduled / out for delivery",x=>x.key==="scheduled"],["partial","Partly delivered or picked up — rest outstanding",x=>x.key==="partial_delivered"||x.key==="partial_pickup"],["awaiting","Waiting on the vendor",x=>x.key==="awaiting"],["held","Held (layaway)",x=>x.key==="held"],["other","Other",x=>true]];
  const grouped=ordersFilter==="open"&&!q; const used=new Set(); const sections=grouped?GROUPS.map(([k,l,fn])=>({k,l,rows:list.filter(x=>{ if(used.has(x.i.id)) return false; if(fn(x)){ used.add(x.i.id); return true; } return false; })})).filter(s=>s.rows.length):null;
  return `<div class="topbar"><h1>Orders to fulfill</h1><span class="muted">Sales that still owe the customer something — order, schedule, deliver or hand over</span><input type="search" id="q_ordersQ" placeholder="Search order, customer, item…" value="${esc(ordersQ)}" oninput="ordersQ=this.value;render()" style="max-width:280px"></div>
  <div class="sub">${tab("open","Open — grouped")}${tab("eta","ETA due")}${tab("awaiting","Awaiting stock")}${tab("partial_delivered","Part delivered")}${tab("partial_pickup","Part picked up")}${tab("ready","Ready for pickup")}${tab("partready","Part ready")}${tab("toschedule","To schedule")}${tab("scheduled","Scheduled")}<span style="width:1px;height:22px;background:var(--line);margin:0 4px"></span>${tab("done","Completed (history)")}</div><p class="muted small" style="margin:-8px 0 12px">${ordersFilter==="done"?"Finished orders — everything delivered, picked up or taken at the sale.":"Everything customers are still waiting on, grouped by what needs to happen next."}</p>
  ${grouped?(sections.length?sections.map(s=>`<div class="card" style="margin-bottom:14px"><h2 style="margin:0 0 8px">${s.l} <span class="muted" style="font-weight:600">· ${s.rows.length}</span></h2>${table(s.rows,ORDER_COLS(today,soon),"")}</div>`).join(""):`<div class="card empty">No open customer orders — everything has been delivered or picked up.</div>`):`<div class="card">${table(list,ORDER_COLS(today,soon),ordersFilter==="done"?"No completed orders yet.":"Nothing here.")}</div>`}`;
}
