/* ============================================================
   DEALER THEMES & LOGO PLACEMENT
   ============================================================ */
const PALETTES=[
 {id:"homestore",name:"HomeStore (brand)",sidebar:"#222E38",accent:"#37A598",bg:"#F5F8F8",ink:"#1E2830",secondary:"#A7CECA"},
 {id:"navy",name:"Professional Navy",sidebar:"#1F2C3D",accent:"#2F6FED",bg:"#F4F6F9",ink:"#1B2430",secondary:"#C9D3E0"},
 {id:"slate",name:"Clean Slate",sidebar:"#2C3A47",accent:"#1F9D8A",bg:"#F6F8F8",ink:"#1E2A32",secondary:"#C7D2D8"},
 {id:"sage",name:"Sage & Teal",sidebar:"#356C68",accent:"#78D6B0",bg:"#F8F7F3",ink:"#273238",secondary:"#A9C8B4"},
 {id:"ocean",name:"Ocean",sidebar:"#1F3A5F",accent:"#5BC0EB",bg:"#F6F8FB",ink:"#1E2A38",secondary:"#A7C4E2"},
 {id:"walnut",name:"Walnut & Brass",sidebar:"#4A3325",accent:"#D9A441",bg:"#FBF7F2",ink:"#2B2118",secondary:"#D6C3B0"},
 {id:"forest",name:"Forest",sidebar:"#1F3D2B",accent:"#8BD17C",bg:"#F5F8F4",ink:"#1C2A21",secondary:"#B7D3BC"},
 {id:"charcoal",name:"Charcoal & Orange",sidebar:"#2B2F33",accent:"#F28C38",bg:"#F7F7F7",ink:"#1F2326",secondary:"#C9CDD1"},
 {id:"plum",name:"Plum",sidebar:"#4B2C4F",accent:"#E5A0C8",bg:"#FAF6F9",ink:"#2C1F2E",secondary:"#D3B9D6"},
 {id:"navy",name:"Navy & Gold",sidebar:"#14213D",accent:"#FCA311",bg:"#F8F8F6",ink:"#14213D",secondary:"#C9CFDD"},
 {id:"coral",name:"Slate & Coral",sidebar:"#3B4A5A",accent:"#FF8A80",bg:"#F7F8FA",ink:"#26313B",secondary:"#BFC9D3"},
 {id:"blackred",name:"Black & Red",sidebar:"#141414",accent:"#E03A3E",bg:"#F7F7F7",ink:"#1B1B1B",secondary:"#D9D9D9"},
 {id:"orangeblack",name:"Orange & Black",sidebar:"#1A1A1A",accent:"#F26A21",bg:"#FAF8F5",ink:"#1F1F1F",secondary:"#D8D3CC"},
 {id:"graphitegold",name:"Graphite & Gold",sidebar:"#2A2D34",accent:"#D4A017",bg:"#F8F7F4",ink:"#1E2126",secondary:"#CFD2D6"},
 {id:"burgundy",name:"Burgundy & Cream",sidebar:"#5C1A2B",accent:"#E8B4B8",bg:"#FBF7F4",ink:"#2A1A1E",secondary:"#D9C6C9"},
 {id:"midnight",name:"Midnight & Sky",sidebar:"#0F1C2E",accent:"#4FC3F7",bg:"#F5F8FC",ink:"#15202E",secondary:"#C5D2E0"},
 {id:"espresso",name:"Espresso & Copper",sidebar:"#3B2A22",accent:"#C77B4A",bg:"#FAF6F1",ink:"#2A1E18",secondary:"#D9CBC0"},
 {id:"steel",name:"Steel & Lime",sidebar:"#37474F",accent:"#9CCC65",bg:"#F6F8F7",ink:"#22303A",secondary:"#C8D3D8"},
 {id:"royal",name:"Royal Blue",sidebar:"#1E3A8A",accent:"#93C5FD",bg:"#F8FAFC",ink:"#0F172A",secondary:"#C7D2FE"}];
const hex2rgb=h=>{h=String(h||"").replace("#",""); if(h.length===3) h=h.split("").map(c=>c+c).join(""); const n=parseInt(h,16); if(isNaN(n)||h.length!==6) return null; return [n>>16&255,n>>8&255,n&255]; };
const rgb2hex=r=>"#"+r.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,"0")).join("");
const mix=(a,b,t)=>{ const x=hex2rgb(a), y=hex2rgb(b); if(!x||!y) return a; return rgb2hex(x.map((v,i)=>v+(y[i]-v)*t)); };
const lum=h=>{ const c=hex2rgb(h); if(!c) return 0; const f=v=>{v/=255; return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4)}; return 0.2126*f(c[0])+0.7152*f(c[1])+0.0722*f(c[2]); };
function paletteCSS(p){ if(!p) return ""; const sb=p.sidebar||"#356C68", ac=p.accent||"#78D6B0", bg=p.bg||"#F8F7F3", ink=p.ink||"#273238", sec=p.secondary||"#A9C8B4"; const acDark=lum(ac)<0.35; const onAccent=acDark?"#FFFFFF":ink;
  const light=`:root{--teal:${sb};--teal2:${lum(sb)<0.05?mix(sb,"#FFFFFF",0.12):mix(sb,"#000000",0.18)};--mint:${ac};--mint2:${mix(ac,"#FFFFFF",0.78)};--mint3:${mix(ac,"#000000",0.42)};--bg:${bg};--bg2:${mix(bg,sec,0.3)};--surface:#FFFFFF;--ink:${ink};--ink2:${mix(ink,"#FFFFFF",0.42)};--line:${mix(sec,"#FFFFFF",0.45)};--line2:${mix(sec,"#FFFFFF",0.72)};--sage:${sec};--sage2:${mix(sec,"#FFFFFF",0.62)};--on-accent:${onAccent}}`;
  const dark=`:root[data-theme="dark"],:root:not([data-theme="light"]).sysdark{--teal:${mix(sb,"#000000",0.3)};--teal2:${mix(sb,"#000000",0.42)};--mint:${ac};--mint2:${mix(ac,"#000000",0.65)};--mint3:${mix(ac,"#FFFFFF",0.15)};--bg:${mix(ink,"#000000",0.55)};--bg2:${mix(ink,"#000000",0.42)};--surface:${mix(ink,"#000000",0.35)};--ink:#F0F1EC;--ink2:${mix(sec,"#FFFFFF",0.2)};--line:${mix(ink,"#FFFFFF",0.18)};--line2:${mix(ink,"#FFFFFF",0.1)};--sage:${sec};--sage2:${mix(ink,"#000000",0.25)}}`;
  const accentText=`.btn.p,nav button.on,.stop .num,.brand .logo,.step.done .dot{color:${onAccent}}`;
  return light+dark+accentText; }
function applyPalette(p){ let el=document.getElementById("theme-style"); if(!el){ el=document.createElement("style"); el.id="theme-style"; document.head.appendChild(el); } el.textContent=paletteCSS(p); try{ document.documentElement.classList.toggle("sysdark",window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches); }catch(e){} }
function currentPalette(){ const st=tenantId?S.settings.find(x=>x.id==="store"):null; const p=st&&st.palette; if(!p) return PALETTES[0]; if(p.id&&p.id!=="custom") return PALETTES.find(x=>x.id===p.id)||PALETTES[0]; return p; }
function renderThemeSettings(){ const st=storeSettings(); const cur=st.palette||{id:"homestore"}; const custom=cur.id==="custom"?cur:Object.assign({},PALETTES[0],{id:"custom"});
  const sw=p=>`<button class="theme-card ${cur.id===p.id?"on":""}" onclick="choosePalette('${p.id}')"><span class="sw" style="background:${p.sidebar}"></span><span class="sw" style="background:${p.accent}"></span><span class="sw" style="background:${p.secondary}"></span><span class="sw" style="background:${p.bg};border:1px solid #ddd"></span><b>${esc(p.name)}</b></button>`;
  return `<h3 style="margin:14px 0 6px">Store colors</h3><p class="muted small">Pick a recommended theme, or set your own brand colors. Applies to every screen and sign-in for this store.</p><div class="theme-grid">${PALETTES.map(sw).join("")}</div>
  <details ${cur.id==="custom"?"open":""} style="margin-top:10px"><summary class="btn s" style="display:inline-block">Custom brand colors ▾</summary><div class="grid g4" style="margin-top:10px">${[["sidebar","Sidebar / primary"],["accent","Accent & buttons"],["secondary","Secondary / tints"],["bg","Page background"],["ink","Text"]].map(([k,l])=>`<div class="field"><label class="f">${l}</label><div class="row"><input type="color" id="th_${k}" value="${esc(custom[k]||"#000000")}" style="width:46px;height:36px;padding:2px;flex:none" oninput="document.getElementById('th_${k}_hex').value=this.value;previewCustom()"><input type="text" id="th_${k}_hex" value="${esc(custom[k]||"")}" placeholder="#RRGGBB" oninput="const v=this.value.trim();if(/^#[0-9a-fA-F]{6}$/.test(v)){document.getElementById('th_${k}').value=v;previewCustom()}"></div></div>`).join("")}</div><div class="row"><button class="btn p fx" onclick="saveCustomPalette()">Use these colors</button><button class="btn fx" onclick="previewCustom()">Preview</button><span class="muted small">Tip: sidebar dark, accent bright, text dark on a light background keeps everything readable.</span></div></details>
  <h3 style="margin:16px 0 6px">Logo placement</h3><div class="grid g3"><div class="field"><label class="f">Sidebar</label><select id="th_logo"><option value="wide" ${(st.logoStyle||"wide")==="wide"?"selected":""}>Full logo (wide)</option><option value="tile" ${st.logoStyle==="tile"?"selected":""}>Small tile next to the name</option></select></div><div class="field"><label class="f">Logo background in the sidebar</label><select id="th_logobg"><option value="white" ${(st.logoBg||"white")==="white"?"selected":""}>White box behind the logo</option><option value="transparent" ${st.logoBg==="transparent"?"selected":""}>Transparent — blend with the sidebar color</option></select></div><div class="chk" style="margin-top:20px"><input type="checkbox" id="th_pos" ${st.logoOnPos!==false?"checked":""}><label for="th_pos">Show logo on the register</label></div><div class="chk" style="margin-top:20px"><input type="checkbox" id="th_login" ${st.logoOnLogin!==false?"checked":""}><label for="th_login">Show logo on sign-in</label></div></div><button class="btn p" onclick="saveLogoPlacement()">Save logo placement</button>${st.logo?`<p class="muted small" style="margin-top:6px">Tip: a PNG or SVG with a transparent background looks best. Use a light-colored version of your logo with "Transparent" so it shows on the dark sidebar; the register, sign-in and printed documents have light backgrounds.</p>`:`<p class="muted small" style="margin-top:6px">Upload the logo above first.</p>`}`; }
async function choosePalette(id){ const st=storeSettings(); st.palette={id}; await save("settings",st); applyPalette(currentPalette()); render(); toast("Theme applied"); }
function readCustom(){ const o={id:"custom"}; ["sidebar","accent","secondary","bg","ink"].forEach(k=>{ const v=(fv("th_"+k+"_hex")||fv("th_"+k)||"").trim(); o[k]=/^#[0-9a-fA-F]{6}$/.test(v)?v:PALETTES[0][k]; }); return o; }
function previewCustom(){ applyPalette(readCustom()); }
async function saveCustomPalette(){ const st=storeSettings(); st.palette=readCustom(); await save("settings",st); applyPalette(currentPalette()); render(); toast("Your brand colors are saved"); }
async function saveLogoPlacement(){ const st=storeSettings(); st.logoStyle=fv("th_logo")||"wide"; st.logoBg=fv("th_logobg")||"white"; st.logoOnPos=fchk("th_pos"); st.logoOnLogin=fchk("th_login"); await save("settings",st); render(); toast("Saved"); }
