/* ============================================================
   SALES ANALYTICS — employees, periods, comparisons, charts
   ============================================================ */
let anPreset="month", anFrom=todayISO().slice(0,8)+"01", anTo=todayISO(), anGroup="day", anCompare=true, anStaff="";
const compactMoney=v=>v>=1000?"$"+(v/1000).toFixed(v>=10000?0:1)+"k":"$"+Math.round(v);
const CHART_COLORS=["var(--mint)","var(--teal)","var(--amber)","var(--blue)","var(--red)","var(--sage)","#8E7CC3","#4FB3BF"];
function svgBars(labels,series,opts){ opts=opts||{}; const W=opts.width||720,H=opts.height||220,padL=54,padB=34,padT=14,padR=10; const max=Math.max(1,...series.flatMap(s=>s.values)); const n=labels.length||1; const gw=(W-padL-padR)/n; const bw=Math.max(2,(gw*0.72)/series.length); const y=v=>padT+(H-padT-padB)*(1-v/max); const ticks=4; const fmt=opts.format||compactMoney; const step=Math.max(1,Math.floor(n/(opts.maxLabels||12)));
  return `<svg viewBox="0 0 ${W} ${H}" style="width:100%;height:auto;display:block">${Array.from({length:ticks+1}).map((_,i)=>{const v=max*i/ticks;return `<line x1="${padL}" x2="${W-padR}" y1="${y(v)}" y2="${y(v)}" stroke="var(--line2)"/><text x="${padL-6}" y="${y(v)+4}" font-size="10" text-anchor="end" fill="var(--ink2)">${fmt(v)}</text>`}).join("")}${labels.map((l,i)=>series.map((s,j)=>{const v=s.values[i]||0;const x=padL+gw*i+(gw-bw*series.length)/2+bw*j;return `<rect x="${x}" y="${y(v)}" width="${bw-1}" height="${H-padB-y(v)}" fill="${s.color||CHART_COLORS[j]}" rx="2"><title>${esc(s.name?s.name+" · ":"")}${esc(l)}: ${fmt(v)}</title></rect>`}).join("")+(i%step===0?`<text x="${padL+gw*i+gw/2}" y="${H-padB+14}" font-size="10" text-anchor="middle" fill="var(--ink2)">${esc(String(l))}</text>`:"")).join("")}${series.length>1?series.map((s,j)=>`<rect x="${padL+j*120}" y="${H-10}" width="10" height="10" fill="${s.color||CHART_COLORS[j]}" rx="2"/><text x="${padL+j*120+14}" y="${H-1}" font-size="10" fill="var(--ink2)">${esc(s.name)}</text>`).join(""):""}</svg>`; }
function svgLines(labels,series,opts){ opts=opts||{}; const W=opts.width||720,H=opts.height||220,padL=54,padB=34,padT=14,padR=10; const max=Math.max(1,...series.flatMap(s=>s.values)); const n=Math.max(1,labels.length-1); const x=i=>padL+(W-padL-padR)*(labels.length===1?0.5:i/n); const y=v=>padT+(H-padT-padB)*(1-v/max); const fmt=opts.format||compactMoney; const step=Math.max(1,Math.floor(labels.length/(opts.maxLabels||10)));
  return `<svg viewBox="0 0 ${W} ${H}" style="width:100%;height:auto;display:block">${[0,1,2,3,4].map(i=>{const v=max*i/4;return `<line x1="${padL}" x2="${W-padR}" y1="${y(v)}" y2="${y(v)}" stroke="var(--line2)"/><text x="${padL-6}" y="${y(v)+4}" font-size="10" text-anchor="end" fill="var(--ink2)">${fmt(v)}</text>`}).join("")}${series.map((s,j)=>`<polyline fill="none" stroke="${s.color||CHART_COLORS[j]}" stroke-width="${s.dashed?1.5:2.5}" ${s.dashed?'stroke-dasharray="5 4"':""} points="${s.values.map((v,i)=>`${x(i)},${y(v||0)}`).join(" ")}"/>${s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v||0)}" r="3" fill="${s.color||CHART_COLORS[j]}"><title>${esc(s.name)} · ${esc(String(labels[i]))}: ${fmt(v||0)}</title></circle>`).join("")}`).join("")}${labels.map((l,i)=>i%step===0?`<text x="${x(i)}" y="${H-padB+14}" font-size="10" text-anchor="middle" fill="var(--ink2)">${esc(String(l))}</text>`:"").join("")}${series.map((s,j)=>`<line x1="${padL+j*130}" x2="${padL+j*130+18}" y1="${H-5}" y2="${H-5}" stroke="${s.color||CHART_COLORS[j]}" stroke-width="3" ${s.dashed?'stroke-dasharray="5 4"':""}/><text x="${padL+j*130+22}" y="${H-1}" font-size="10" fill="var(--ink2)">${esc(s.name)}</text>`).join("")}</svg>`; }
function svgHBars(rows,opts){ opts=opts||{}; const max=Math.max(1,...rows.map(r=>r.value)); const fmt=opts.format||money; return `<div>${rows.map((r,i)=>`<div style="display:grid;grid-template-columns:150px 1fr 110px;gap:10px;align-items:center;margin-bottom:6px"><span class="small" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(r.label)}</span><div class="bar" style="height:12px"><i style="width:${r.value/max*100}%;background:${r.color||CHART_COLORS[i%CHART_COLORS.length]}"></i></div><b style="text-align:right" class="small">${fmt(r.value)}${r.delta!==undefined&&r.delta!==null?` <span class="tag ${r.delta>=0?"ok":"bad"}">${r.delta>=0?"+":""}${(r.delta*100).toFixed(0)}%</span>`:""}</b></div>`).join("")||`<div class="empty">No data.</div>`}</div>`; }
function anSet(preset){ anPreset=preset; const t=todayISO(); const d=new Date(t+"T00:00"); if(preset==="today"){anFrom=anTo=t;anGroup="day";} else if(preset==="week"){ const mon=addDays(t,-((d.getDay()+6)%7)); anFrom=mon; anTo=t; anGroup="day"; } else if(preset==="month"){ anFrom=t.slice(0,8)+"01"; anTo=t; anGroup="day"; } else if(preset==="quarter"){ const q=Math.floor(d.getMonth()/3)*3; anFrom=`${d.getFullYear()}-${String(q+1).padStart(2,"0")}-01`; anTo=t; anGroup="week"; } else if(preset==="year"){ anFrom=t.slice(0,4)+"-01-01"; anTo=t; anGroup="month"; } else if(preset==="30"){ anFrom=addDays(t,-29); anTo=t; anGroup="day"; } else if(preset==="90"){ anFrom=addDays(t,-89); anTo=t; anGroup="week"; } else if(preset==="12m"){ anFrom=addDays(t,-364); anTo=t; anGroup="month"; } render(); }
function prevRange(from,to){ const len=daysBetween(from,to)+1; return [addDays(from,-len),addDays(to,-len)]; }
function bucketKey(date,group){ if(group==="month") return date.slice(0,7); if(group==="week"){ const d=new Date(date+"T00:00"); const mon=addDays(date,-((d.getDay()+6)%7)); return mon; } if(group==="year") return date.slice(0,4); return date; }
function bucketLabel(k,group){ if(group==="month"){ const [y,m]=k.split("-"); return new Date(y,m-1,1).toLocaleDateString("en-US",{month:"short",year:"2-digit"}); } if(group==="week") return "wk "+dateShort(k); if(group==="year") return k; return dateShort(k); }
function bucketsBetween(from,to,group){ const out=[]; let k=bucketKey(from,group); const end=bucketKey(to,group); const seen=new Set(); let cur=from; let guard=0; while(guard++<800){ const key=bucketKey(cur,group); if(!seen.has(key)){ seen.add(key); out.push(key); } if(key===end) break; cur=addDays(cur,group==="month"?28:group==="week"?7:group==="year"?365:1); if(cur>to){ if(!seen.has(end)) out.push(end); break; } } return out; }
function salesRows(from,to){ return S.invoices.filter(i=>["paid","open","financed","layaway"].includes(i.status)&&i.date>=from&&i.date<=to); }
function anStaffSales(inv,staffId){ return staffId?invTotals(inv).taxable*salesShare(inv,staffId):invTotals(inv).taxable; }
function renderAnalytics(){
  const staffFilter=(has("commissions_all")||has("reports"))?anStaff:session.staffId; const inv=salesRows(anFrom,anTo).filter(i=>!staffFilter||salesShare(i,staffFilter)>0); const [pf,pt]=prevRange(anFrom,anTo); const pinv=salesRows(pf,pt).filter(i=>!staffFilter||salesShare(i,staffFilter)>0);
  const rets=S.returns.filter(r=>r.date>=anFrom&&r.date<=anTo), prets=S.returns.filter(r=>r.date>=pf&&r.date<=pt);
  const sum=(list,st)=>list.reduce((a,i)=>a+anStaffSales(i,st),0);
  const net=sum(inv,staffFilter)-rets.reduce((a,r)=>a+r.refundSub,0), pnet=sum(pinv,staffFilter)-prets.reduce((a,r)=>a+r.refundSub,0);
  const tickets=inv.length, ptickets=pinv.length; const avg=tickets?net/tickets:0, pavg=ptickets?pnet/ptickets:0; const units=inv.reduce((a,i)=>a+i.lines.filter(l=>!l.service).reduce((x,l)=>x+l.qty,0),0), punits=pinv.reduce((a,i)=>a+i.lines.filter(l=>!l.service).reduce((x,l)=>x+l.qty,0),0);
  const margin=inv.reduce((a,i)=>a+invTotals(i).margin*(staffFilter?salesShare(i,staffFilter):1),0); const mPct=net?margin/net:0; const pmargin=pinv.reduce((a,i)=>a+invTotals(i).margin*(staffFilter?salesShare(i,staffFilter):1),0); const pmPct=pnet?pmargin/pnet:0;
  const delta=(a,b)=>b?((a-b)/b):null; const kpi=(v,l,d,cls)=>`<div class="card stat ${cls||""}"><div class="v">${v}</div><div class="l">${l}${anCompare&&d!==null&&d!==undefined?` · <span class="tag ${d>=0?"ok":"bad"}">${d>=0?"+":""}${(d*100).toFixed(1)}% vs prior</span>`:""}</div></div>`;
  // time series
  const keys=bucketsBetween(anFrom,anTo,anGroup); const series=keys.map(k=>inv.filter(i=>bucketKey(i.date,anGroup)===k).reduce((a,i)=>a+anStaffSales(i,staffFilter),0));
  const pkeys=bucketsBetween(pf,pt,anGroup); const pseries=keys.map((k,i)=>{ const pk=pkeys[i]; return pk?pinv.filter(x=>bucketKey(x.date,anGroup)===pk).reduce((a,x)=>a+anStaffSales(x,staffFilter),0):0; });
  const labels=keys.map(k=>bucketLabel(k,anGroup));
  // employees
  const staff=S.staff.filter(s=>s.role!=="driver"&&(has("commissions_all")||has("reports")||s.id===session.staffId)); const emp=staff.map(s=>{ const mine=inv.filter(i=>salesShare(i,s.id)>0); const cur=mine.reduce((a,i)=>a+anStaffSales(i,s.id),0); const prev=pinv.filter(i=>salesShare(i,s.id)>0).reduce((a,i)=>a+anStaffSales(i,s.id),0); const m=mine.reduce((a,i)=>a+invTotals(i).margin*salesShare(i,s.id),0); const u=mine.reduce((a,i)=>a+i.lines.filter(l=>!l.service).reduce((x,l)=>x+l.qty*salesShare(i,s.id),0),0); return {s,cur,prev,tickets:mine.length,avg:mine.length?cur/mine.length:0,mPct:cur?m/cur:0,units:u,delta:delta(cur,prev),byBucket:keys.map(k=>mine.filter(i=>bucketKey(i.date,anGroup)===k).reduce((a,i)=>a+anStaffSales(i,s.id),0))}; }).filter(e=>e.cur||e.prev).sort((a,b)=>b.cur-a.cur);
  // day of week & hour
  const dow=[0,0,0,0,0,0,0], dowN=[0,0,0,0,0,0,0], hours=Array(24).fill(0); inv.forEach(i=>{ const d=new Date(i.date+"T00:00").getDay(); const v=anStaffSales(i,staffFilter); dow[d]+=v; dowN[d]++; if(i.completedAt){ hours[new Date(i.completedAt).getHours()]+=v; } });
  const dowLabels=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; const hourLabels=hours.map((_,h)=>`${((h+11)%12)+1}${h<12?"a":"p"}`); const hasHours=hours.some(v=>v>0); const hFrom=Math.max(0,hours.findIndex(v=>v>0)-1), hTo=Math.min(23,hours.length-1-[...hours].reverse().findIndex(v=>v>0)+1);
  // year vs last year by month
  const y=anTo.slice(0,4); const months=Array.from({length:12},(_,m)=>`${y}-${String(m+1).padStart(2,"0")}`); const ty=months.map(m=>salesRows(m+"-01",m+"-31").filter(i=>!staffFilter||salesShare(i,staffFilter)>0).reduce((a,i)=>a+anStaffSales(i,staffFilter),0)); const ly=months.map(m=>{const mm=(+y-1)+m.slice(4);return salesRows(mm+"-01",mm+"-31").filter(i=>!staffFilter||salesShare(i,staffFilter)>0).reduce((a,i)=>a+anStaffSales(i,staffFilter),0)});
  const mLabels=months.map(m=>new Date(+y,+m.slice(5)-1,1).toLocaleDateString("en-US",{month:"short"}));
  const groupBtn=(g,l)=>`<button class="btn s ${anGroup===g?"p":""}" onclick="anGroup='${g}';render()">${l}</button>`;
  return `<div class="toolbar"><div class="bgroup">${[["today","Today"],["week","This week"],["month","This month"],["quarter","Quarter"],["year","This year"],["30","30 days"],["90","90 days"],["12m","12 months"]].map(([k,l])=>`<button class="btn s ${anPreset===k?"p":""}" onclick="anSet('${k}')">${l}</button>`).join("")}</div><input type="date" value="${anFrom}" onchange="anFrom=this.value;anPreset='custom';render()" style="max-width:150px"><input type="date" value="${anTo}" onchange="anTo=this.value;anPreset='custom';render()" style="max-width:150px"><span class="grow"></span>${has("commissions_all")||has("reports")?`<select style="max-width:180px" onchange="anStaff=this.value;render()">${opts(S.staff.filter(s=>s.role!=="driver"),anStaff,x=>x.name,x=>x.id,"All salespeople")}</select>`:""}<label class="chk small"><input type="checkbox" ${anCompare?"checked":""} onchange="anCompare=this.checked;render()"> Compare with prior period</label>${dd("Export",[["Employee report (CSV)","exportEmployeeCSV()"],["Sales by period (CSV)","exportPeriodCSV()"],["Print this report","printAnalytics()"]])}</div>
  <p class="muted small">${dateFmt(anFrom)} – ${dateFmt(anTo)}${anCompare?` · compared with ${dateFmt(pf)} – ${dateFmt(pt)}`:""}${staffFilter?" · "+esc(staffName(staffFilter)):""}. Net sales exclude tax and delivery; returns are deducted on their return date.</p>
  <div class="grid g4" style="margin-bottom:16px">${kpi(money(net),"Net sales",delta(net,pnet))}${kpi(tickets,"Tickets",delta(tickets,ptickets),"t")}${kpi(money(avg),"Average ticket",delta(avg,pavg),"a")}${has("margin")?kpi(pct(mPct),"Gross margin",pmPct?(mPct-pmPct)/pmPct:null,"b"):kpi(units,"Units",delta(units,punits),"b")}</div>
  <div class="card" style="margin-bottom:16px"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Sales over time</h2><span class="fx bgroup">${groupBtn("day","Day")}${groupBtn("week","Week")}${groupBtn("month","Month")}</span></div>${anGroup==="day"&&keys.length>31?svgLines(labels,[{name:"This period",values:series},...(anCompare?[{name:"Prior period",values:pseries,dashed:true,color:"var(--sage)"}]:[])]):svgBars(labels,[{name:"This period",values:series},...(anCompare?[{name:"Prior period",values:pseries,color:"var(--sage)"}]:[])],{maxLabels:14})}</div>
  <div class="grid g2" style="margin-bottom:16px"><div class="card"><h2>Sales by employee</h2>${svgHBars(emp.map((e,i)=>({label:e.s.name,value:e.cur,delta:anCompare?e.delta:null})))}</div><div class="card"><h2>Sales by day of week</h2>${svgBars(dowLabels,[{name:"Sales",values:dow},...(anCompare?[{name:"Prior",values:(()=>{const p=[0,0,0,0,0,0,0];pinv.forEach(i=>{p[new Date(i.date+"T00:00").getDay()]+=anStaffSales(i,staffFilter)});return p})(),color:"var(--sage)"}]:[])],{height:200})}<p class="muted small">Tickets: ${dowLabels.map((l,i)=>`${l} ${dowN[i]}`).join(" · ")}</p></div></div>
  <div class="grid g2" style="margin-bottom:16px"><div class="card"><h2>Sales by hour of day</h2>${hasHours?svgBars(hourLabels.slice(hFrom,hTo+1),[{name:"Sales",values:hours.slice(hFrom,hTo+1)}],{height:200,maxLabels:16}):`<div class="empty">Times are recorded as sales are completed at the register — new sales will fill this in.</div>`}</div><div class="card"><h2>${y} vs ${+y-1} by month</h2>${svgBars(mLabels,[{name:y,values:ty},{name:String(+y-1),values:ly,color:"var(--sage)"}],{height:200})}</div></div>
  ${(()=>{ const by={}; inv.forEach(i=>{ const c=byId("customers",i.customerId); const k=(c&&c.referral)||"Not recorded"; by[k]=by[k]||{n:0,sales:0,cust:new Set()}; by[k].n++; by[k].sales+=anStaffSales(i,staffFilter); by[k].cust.add(i.customerId); }); const newC=S.customers.filter(c=>c.createdAt&&c.createdAt>=anFrom&&c.createdAt<=anTo); newC.forEach(c=>{ const k=c.referral||"Not recorded"; by[k]=by[k]||{n:0,sales:0,cust:new Set()}; by[k].newCust=(by[k].newCust||0)+1; }); const rows=Object.entries(by).map(([k,v])=>({k,n:v.n,sales:v.sales,cust:v.cust.size,newCust:v.newCust||0})).sort((a,b)=>b.sales-a.sales); return rows.length?`<div class="card" style="margin-bottom:16px"><h2>Where customers came from</h2>${table(rows,[["Source",r=>`<b>${esc(r.k)}</b>`],["Customers",r=>r.cust,"n"],["New this period",r=>r.newCust||"—","n"],["Tickets",r=>r.n,"n"],["Net sales",r=>money(r.sales),"n"],["Share",r=>pct(net?r.sales/net:0),"n"]],"")}</div>`:""; })()}
  <div class="card"><div class="row" style="margin-bottom:8px"><h2 style="margin:0">Employee performance</h2><span class="fx muted small">by ${anGroup}</span></div><div class="tblwrap"><table><thead><tr><th>Salesperson</th><th class="n">Net sales</th>${anCompare?'<th class="n">Prior</th><th class="n">Change</th>':""}<th class="n">Tickets</th><th class="n">Avg ticket</th><th class="n">Units</th>${has("margin")?'<th class="n">Margin</th>':""}${keys.length<=16?keys.map(k=>`<th class="n">${esc(bucketLabel(k,anGroup))}</th>`).join(""):""}</tr></thead><tbody>${emp.map(e=>`<tr><td><b>${esc(e.s.name)}</b></td><td class="n"><b>${money(e.cur)}</b></td>${anCompare?`<td class="n muted">${money(e.prev)}</td><td class="n">${e.delta===null?"—":`<span class="tag ${e.delta>=0?"ok":"bad"}">${e.delta>=0?"+":""}${(e.delta*100).toFixed(0)}%</span>`}</td>`:""}<td class="n">${e.tickets}</td><td class="n">${money(e.avg)}</td><td class="n">${e.units.toFixed(0)}</td>${has("margin")?`<td class="n">${pct(e.mPct)}</td>`:""}${keys.length<=16?e.byBucket.map(v=>`<td class="n muted small">${v?money(v).replace(/\\.00$/,""):"—"}</td>`).join(""):""}</tr>`).join("")||`<tr><td colspan="9" class="empty">No sales in this range.</td></tr>`}${emp.length>1?`<tr><td><b>Total</b></td><td class="n"><b>${money(emp.reduce((a,e)=>a+e.cur,0))}</b></td>${anCompare?`<td class="n muted">${money(emp.reduce((a,e)=>a+e.prev,0))}</td><td></td>`:""}<td class="n">${emp.reduce((a,e)=>a+e.tickets,0)}</td><td></td><td class="n">${emp.reduce((a,e)=>a+e.units,0).toFixed(0)}</td>${has("margin")?"<td></td>":""}${keys.length<=16?keys.map((k,i)=>`<td class="n small"><b>${money(emp.reduce((a,e)=>a+e.byBucket[i],0)).replace(/\\.00$/,"")}</b></td>`).join(""):""}</tr>`:""}</tbody></table></div>${keys.length>16?`<p class="muted small" style="margin-top:6px">Switch to week or month grouping to see the per-period columns.</p>`:""}</div>`;
}
function exportEmployeeCSV(){ const inv=salesRows(anFrom,anTo); const [pf,pt]=prevRange(anFrom,anTo); const pinv=salesRows(pf,pt); const rows=["Salesperson,Net sales,Prior period,Tickets,Avg ticket,Units"].concat(S.staff.filter(s=>s.role!=="driver").map(s=>{ const mine=inv.filter(i=>salesShare(i,s.id)>0); const cur=mine.reduce((a,i)=>a+anStaffSales(i,s.id),0); const prev=pinv.filter(i=>salesShare(i,s.id)>0).reduce((a,i)=>a+anStaffSales(i,s.id),0); const u=mine.reduce((a,i)=>a+i.lines.filter(l=>!l.service).reduce((x,l)=>x+l.qty*salesShare(i,s.id),0),0); return `"${s.name}",${cur.toFixed(2)},${prev.toFixed(2)},${mine.length},${(mine.length?cur/mine.length:0).toFixed(2)},${u.toFixed(0)}`; })); saveFile(`employee-sales-${anFrom}-to-${anTo}.csv`,rows.join("\n")); }
function exportPeriodCSV(){ const inv=salesRows(anFrom,anTo); const keys=bucketsBetween(anFrom,anTo,anGroup); const staff=S.staff.filter(s=>s.role!=="driver"); const rows=["Period,Total,"+staff.map(s=>`"${s.name}"`).join(",")].concat(keys.map(k=>{ const b=inv.filter(i=>bucketKey(i.date,anGroup)===k); return `${k},${b.reduce((a,i)=>a+invTotals(i).taxable,0).toFixed(2)},`+staff.map(s=>b.reduce((a,i)=>a+anStaffSales(i,s.id),0).toFixed(2)).join(","); })); saveFile(`sales-by-${anGroup}-${anFrom}-to-${anTo}.csv`,rows.join("\n")); }
function printAnalytics(){ const el=document.createElement("div"); el.innerHTML=renderAnalytics(); el.querySelectorAll(".toolbar,.dd,button,select,input,label.chk").forEach(x=>x.remove()); const html=`<div class="page"><h1>Sales report</h1><p>${esc(storeSettings().name)} · ${dateFmt(anFrom)} – ${dateFmt(anTo)} · printed ${dateFmt(todayISO())}</p><style>.card{border:1px solid #ccc;border-radius:8px;padding:10px;margin-bottom:10px} .grid{display:grid;gap:10px} .g2{grid-template-columns:1fr 1fr} .g4{grid-template-columns:repeat(4,1fr)} .stat .v{font-size:20px;font-weight:800} .stat .l{font-size:11px;color:#444} table{width:100%;border-collapse:collapse;font-size:11px} th,td{border-bottom:1px solid #ccc;padding:4px} .n{text-align:right} .tag{font-size:10px} .bar{height:10px;background:#eee;border-radius:99px;overflow:hidden} .bar i{display:block;height:100%;background:#78D6B0} svg text{fill:#333} svg line{stroke:#ddd} h2{font-size:14px;margin:0 0 6px} .muted{color:#555}</style>${el.innerHTML}</div>`; printHTML(html.replace(/var\(--mint\)/g,"#78D6B0").replace(/var\(--teal\)/g,"#356C68").replace(/var\(--sage\)/g,"#A9C8B4").replace(/var\(--amber\)/g,"#B98A2B").replace(/var\(--blue\)/g,"#4A7FA5").replace(/var\(--red\)/g,"#B9564A").replace(/var\(--ink2\)/g,"#555").replace(/var\(--line2\)/g,"#e5e5e5"),"Sales report"); }
