/* ============================================================
   PAYMENTS REPORT — daily collections by tender
   ============================================================ */
let payFrom=todayISO(), payTo=todayISO(), payMethodFilter="", payStaffFilter="";
function tenderName(m){ const s=String(m||"").replace(/ \(on delivery\)| \(at pickup\)/,""); if(/^Financing/.test(s)) return "Financing"; if(/^Lease/.test(s)) return "Lease-to-own"; if(/^Exchange credit/.test(s)) return "Exchange credit"; return s.split(" — ")[0]; }
function paymentEvents(from,to){ const out=[]; for(const i of S.invoices){ if(i.status==="void") continue; for(const p of (i.payments||[])){ if(p.date<from||p.date>to) continue; out.push({date:p.date,invoice:i,customer:custName(i.customerId),method:tenderName(p.method),raw:p.method,amount:+p.amount||0,by:p.by||"",card:p.card||null,terminal:p.card?p.card.terminal:"",where:/on delivery/.test(p.method)?"delivery":/at pickup/.test(p.method)?"pickup":"register",kind:i.status==="layaway"&&i.layaway&&Math.abs(p.amount-i.layaway.deposit)<0.01&&p.date===i.date?"layaway deposit":/^Lease — /.test(p.method)?"leased":(i.terms==="financing"||i.terms==="lease")&&/^Financing/.test(p.method)?"financed":i.layaway?"layaway payment":invTotals(i).total>0&&p.date!==i.date?"balance":"sale"}); } } for(const r of S.returns){ if(r.date<from||r.date>to) continue; if(r.method==="Original payment"&&r.refundTotal>0) out.push({date:r.date,invoice:byId("invoices",r.invoiceId)||{number:r.number,id:""},customer:custName(r.customerId),method:"Refund",raw:"Refund — "+r.reason,amount:-r.refundTotal,by:r.by||"",where:"register",kind:"refund"}); } return out.sort((a,b)=>a.date.localeCompare(b.date)); }
function renderPayments(){
  const ev=paymentEvents(payFrom,payTo).filter(e=>(!payMethodFilter||e.method===payMethodFilter)&&(!payStaffFilter||e.by===payStaffFilter)); const methods=[...new Set(paymentEvents(payFrom,payTo).map(e=>e.method))].sort((a,b)=>a==="Refund"?1:b==="Refund"?-1:a.localeCompare(b));
  const days=[...new Set(ev.map(e=>e.date))].sort(); const byDay=days.map(d=>{ const rows=ev.filter(e=>e.date===d); const m={}; rows.forEach(e=>m[e.method]=(m[e.method]||0)+e.amount); return {d,m,total:rows.reduce((a,e)=>a+e.amount,0),n:rows.filter(e=>e.amount>0).length}; });
  const totals={}; ev.forEach(e=>totals[e.method]=(totals[e.method]||0)+e.amount); const grand=ev.reduce((a,e)=>a+e.amount,0); const collected=ev.filter(e=>e.amount>0).reduce((a,e)=>a+e.amount,0); const refunded=-ev.filter(e=>e.amount<0).reduce((a,e)=>a+e.amount,0);
  const cash=totals["Cash"]||0, cards=totals["Card"]||0, fin=totals["Financing"]||0;
  const kinds={}; ev.forEach(e=>kinds[e.kind]=(kinds[e.kind]||0)+e.amount);
  const preset=(k,l,f,t)=>`<button class="btn s ${payFrom===f&&payTo===t?"p":""}" onclick="payFrom='${f}';payTo='${t}';render()">${l}</button>`; const t=todayISO(); const mon=addDays(t,-((new Date(t+"T00:00").getDay()+6)%7));
  return `<div class="toolbar"><div class="bgroup">${preset("today","Today",t,t)}${preset("yday","Yesterday",addDays(t,-1),addDays(t,-1))}${preset("week","This week",mon,t)}${preset("month","This month",t.slice(0,8)+"01",t)}</div><input type="date" value="${payFrom}" onchange="payFrom=this.value;render()" style="max-width:150px"><input type="date" value="${payTo}" onchange="payTo=this.value;render()" style="max-width:150px"><select style="max-width:170px" onchange="payMethodFilter=this.value;render()">${optsList(methods,payMethodFilter,"All tenders")}</select><select style="max-width:170px" onchange="payStaffFilter=this.value;render()">${opts(S.staff,payStaffFilter,x=>x.name,x=>x.id,"Taken by anyone")}</select><span class="grow"></span>${dd("Export",[["Payments detail (CSV)","exportPaymentsCSV()"],["Daily summary (CSV)","exportPaymentsDailyCSV()"],["Print collections report","printPayments()"]])}</div>
  <div class="grid g4" style="margin-bottom:16px"><div class="card stat"><div class="v">${money(collected)}</div><div class="l">Collected · ${ev.filter(e=>e.amount>0).length} payments${refunded?` · refunds ${money(refunded)}`:""}</div></div><div class="card stat t"><div class="v">${money(cash)}</div><div class="l">Cash to count</div></div><div class="card stat b"><div class="v">${money(cards)}</div><div class="l">Cards to settle</div></div><div class="card stat a"><div class="v">${money(fin)}</div><div class="l">Financed (lender pays)</div></div></div>
  <div class="grid g2" style="margin-bottom:16px"><div class="card"><h2>How customers paid</h2>${svgHBars(Object.entries(totals).filter(([m,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([m,v],i)=>({label:m,value:v})))}${(()=>{const byBrand={};ev.filter(e=>e.card&&e.card.brand).forEach(e=>byBrand[e.card.brand]=(byBrand[e.card.brand]||0)+e.amount);const rows=Object.entries(byBrand);return rows.length?`<p class="muted small" style="margin-top:8px">By card brand: ${rows.sort((a,b)=>b[1]-a[1]).map(([b,v])=>`${esc(b)} ${money(v)}`).join(" · ")}</p>`:""})()}${refunded?`<p class="muted small">Refunds to original payment: ${money(refunded)}</p>`:""}</div><div class="card"><h2>What the money was for</h2>${svgHBars(Object.entries(kinds).filter(([k,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({label:{sale:"Paid at sale",balance:"Balances / deliveries",financed:"Financing funded",leased:"Lease company funded","layaway deposit":"Layaway deposits","layaway payment":"Layaway payments"}[k]||k,value:v})))}</div></div>
  <div class="card" style="margin-bottom:16px"><h2>Daily collections by tender</h2><div class="tblwrap"><table><thead><tr><th>Day</th>${methods.map(m=>`<th class="n">${esc(m)}</th>`).join("")}<th class="n">Total</th><th class="n">#</th></tr></thead><tbody>${byDay.map(r=>`<tr><td><b>${dateShort(r.d)}</b> <span class="muted small">${new Date(r.d+"T00:00").toLocaleDateString("en-US",{weekday:"short"})}</span></td>${methods.map(m=>`<td class="n">${r.m[m]?money(r.m[m]):'<span class="muted">—</span>'}</td>`).join("")}<td class="n"><b>${money(r.total)}</b></td><td class="n">${r.n}</td></tr>`).join("")||`<tr><td colspan="${methods.length+3}" class="empty">No payments in this range.</td></tr>`}${byDay.length>1?`<tr><td><b>Total</b></td>${methods.map(m=>`<td class="n"><b>${money(totals[m]||0)}</b></td>`).join("")}<td class="n"><b>${money(grand)}</b></td><td class="n">${ev.filter(e=>e.amount>0).length}</td></tr>`:""}</tbody></table></div>${byDay.length>1?`<div style="margin-top:12px">${svgBars(byDay.map(r=>dateShort(r.d)),methods.filter(m=>m!=="Refund").slice(0,6).map((m,i)=>({name:m,values:byDay.map(r=>Math.max(0,r.m[m]||0)),color:CHART_COLORS[i]})),{height:200,maxLabels:14})}</div>`:""}</div>
  ${renderBatchRecon()}
  <div class="card"><h2>Payment detail</h2><div class="tblwrap"><table><thead><tr><th>Date</th><th>Invoice</th><th>Customer</th><th>Tender</th><th>For</th><th>Where</th><th>Taken by</th><th class="n">Amount</th></tr></thead><tbody>${ev.slice().reverse().map(e=>`<tr><td>${dateShort(e.date)}</td><td>${e.invoice.id?`<a href="#" onclick="openInvoice('${e.invoice.id}');return false">${esc(e.invoice.number)}</a>`:esc(e.invoice.number)}</td><td>${esc(e.customer)}</td><td>${esc(e.method)}${e.card?`<div class="muted small">${esc(cardLabel({card:e.card}))}</div>`:""}${e.raw!==e.method&&e.method!=="Refund"?`<div class="muted small">${esc(e.raw.replace(/ \\(on delivery\\)| \\(at pickup\\)/,""))}</div>`:e.method==="Refund"?`<div class="muted small">${esc(e.raw.replace("Refund — ",""))}</div>`:""}</td><td class="small">${esc(e.kind)}</td><td class="small">${esc(e.where)}</td><td class="small">${esc(staffName(e.by))}</td><td class="n" style="${e.amount<0?"color:var(--red)":""}"><b>${money(e.amount)}</b></td></tr>`).join("")||`<tr><td colspan="8" class="empty">Nothing here.</td></tr>`}</tbody></table></div></div>`;
}
function exportPaymentsCSV(){ const ev=paymentEvents(payFrom,payTo); if(!ev.length) return toast("No payments in this range.",true); saveFile(`payments-${payFrom}-to-${payTo}.csv`,["Date,Invoice,Customer,Tender,Detail,For,Where,Taken by,Amount,Card,Last4,Auth,Reference,Terminal"].concat(ev.map(e=>[e.date,e.invoice.number,e.customer,e.method,e.raw,e.kind,e.where,staffName(e.by),e.amount.toFixed(2),e.card?e.card.brand:"",e.card?e.card.last4:"",e.card?e.card.auth:"",e.card?e.card.ref:"",e.card?e.card.terminal:""].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","))).join("\n")); }
function exportPaymentsDailyCSV(){ const ev=paymentEvents(payFrom,payTo); const methods=[...new Set(ev.map(e=>e.method))].sort(); const days=[...new Set(ev.map(e=>e.date))].sort(); saveFile(`collections-${payFrom}-to-${payTo}.csv`,["Day,"+methods.join(",")+",Total"].concat(days.map(d=>{const rows=ev.filter(e=>e.date===d);return d+","+methods.map(m=>rows.filter(e=>e.method===m).reduce((a,e)=>a+e.amount,0).toFixed(2)).join(",")+","+rows.reduce((a,e)=>a+e.amount,0).toFixed(2)})).join("\n")); }
function printPayments(){ const ev=paymentEvents(payFrom,payTo); const methods=[...new Set(ev.map(e=>e.method))].sort(); const days=[...new Set(ev.map(e=>e.date))].sort(); const totals={}; ev.forEach(e=>totals[e.method]=(totals[e.method]||0)+e.amount); printHTML(`<div class="page"><h1>Collections report</h1><p>${esc(storeSettings().name)} · ${dateFmt(payFrom)}${payFrom!==payTo?" – "+dateFmt(payTo):""} · printed ${dateFmt(todayISO())} by ${esc(me().name)}</p><table class="ptable"><tr><th>Day</th>${methods.map(m=>`<th class="n">${esc(m)}</th>`).join("")}<th class="n">Total</th></tr>${days.map(d=>{const rows=ev.filter(e=>e.date===d);return `<tr><td>${dateShort(d)}</td>${methods.map(m=>`<td class="n">${money(rows.filter(e=>e.method===m).reduce((a,e)=>a+e.amount,0))}</td>`).join("")}<td class="n"><b>${money(rows.reduce((a,e)=>a+e.amount,0))}</b></td></tr>`}).join("")}<tr><td><b>Total</b></td>${methods.map(m=>`<td class="n"><b>${money(totals[m]||0)}</b></td>`).join("")}<td class="n"><b>${money(ev.reduce((a,e)=>a+e.amount,0))}</b></td></tr></table><h3 style="margin-top:16px">Detail</h3><table class="ptable"><tr><th>Date</th><th>Invoice</th><th>Customer</th><th>Tender</th><th>For</th><th>By</th><th class="n">Amount</th></tr>${ev.map(e=>`<tr><td>${dateShort(e.date)}</td><td>${esc(e.invoice.number)}</td><td>${esc(e.customer)}</td><td>${esc(e.raw.replace(/ \\(on delivery\\)| \\(at pickup\\)/,""))}</td><td>${esc(e.kind)}</td><td>${esc(staffName(e.by))}</td><td class="n">${money(e.amount)}</td></tr>`).join("")}</table><p style="margin-top:26px">Cash counted: ____________ &nbsp; Over/short: ________ &nbsp; Deposited by: ____________ &nbsp; Date: ________</p></div>`,"Collections report"); }
