/* ============================================================
   TOP SELLERS — item / collection / category / sub-category
   ============================================================ */
let tsPreset="month", tsFrom=todayISO().slice(0,8)+"01", tsTo=todayISO(), tsBy="item", tsMetric="qty", tsItem="", tsGroup="month";
function tsSet(k){ tsPreset=k; const t=todayISO(); const d=new Date(t+"T00:00"); if(k==="month"){tsFrom=t.slice(0,8)+"01";tsTo=t;} else if(k==="quarter"){const q=Math.floor(d.getMonth()/3)*3;tsFrom=`${d.getFullYear()}-${String(q+1).padStart(2,"0")}-01`;tsTo=t;} else if(k==="year"){tsFrom=t.slice(0,4)+"-01-01";tsTo=t;} else if(k==="12m"){tsFrom=addDays(t,-364);tsTo=t;} else if(k==="90"){tsFrom=addDays(t,-89);tsTo=t;} render(); }
function soldLines(from,to){ const out=[]; for(const i of S.invoices){ if(!["paid","open","financed","layaway"].includes(i.status)||i.date<from||i.date>to) continue; for(const l of i.lines){ if(l.service) continue; const p=byId("products",l.productId); out.push({inv:i,l,p,qty:l.qty,rev:lineRevenue(i,l),cost:l.cost*l.qty,date:i.date,key:{item:l.productId||l.sku,collection:(p?.collection||l.collection||"(no collection)"),category:(p?.category||l.category||"(none)"),sub:(p?.subcategory||l.subcategory||"(none)")}}); } } for(const r of S.returns){ if(r.date<from||r.date>to) continue; for(const rl of r.lines){ const p=byId("products",rl.productId); out.push({inv:null,l:rl,p,qty:-rl.qty,rev:-rl.unitRefund*rl.qty,cost:-(rl.cost||0)*rl.qty,date:r.date,key:{item:rl.productId||rl.name,collection:(p?.collection||"(no collection)"),category:(p?.category||"(none)"),sub:(p?.subcategory||"(none)")}}); } } return out; }
function svgPie(slices,opts){ opts=opts||{}; const total=slices.reduce((a,s)=>a+s.value,0)||1; const R=80,cx=100,cy=100; let a0=-Math.PI/2; const arcs=slices.map((s,i)=>{ const a1=a0+2*Math.PI*s.value/total; const x0=cx+R*Math.cos(a0),y0=cy+R*Math.sin(a0),x1=cx+R*Math.cos(a1),y1=cy+R*Math.sin(a1); const large=a1-a0>Math.PI?1:0; const d=slices.length===1?`M${cx-R},${cy}a${R},${R} 0 1,0 ${2*R},0a${R},${R} 0 1,0 ${-2*R},0`:`M${cx},${cy}L${x0},${y0}A${R},${R} 0 ${large},1 ${x1},${y1}Z`; const el=`<path d="${d}" fill="${s.color||CHART_COLORS[i%CHART_COLORS.length]}" stroke="var(--surface)" stroke-width="2"><title>${esc(s.label)}: ${opts.format?opts.format(s.value):s.value} (${(s.value/total*100).toFixed(1)}%)</title></path>`; a0=a1; return el; }).join(""); return `<div style="display:grid;grid-template-columns:200px 1fr;gap:12px;align-items:center"><svg viewBox="0 0 200 200" style="width:100%;max-width:200px"><g>${arcs}</g><circle cx="${cx}" cy="${cy}" r="42" fill="var(--surface)"/><text x="${cx}" y="${cy-4}" text-anchor="middle" font-size="11" fill="var(--ink2)">${esc(opts.centerLabel||"total")}</text><text x="${cx}" y="${cy+14}" text-anchor="middle" font-size="14" font-weight="800" fill="var(--ink)">${esc(opts.format?opts.format(total):String(total))}</text></svg><div>${slices.map((s,i)=>`<div class="row small" style="margin-bottom:4px;flex-wrap:nowrap"><span style="width:12px;height:12px;border-radius:3px;background:${s.color||CHART_COLORS[i%CHART_COLORS.length]};flex:none"></span><span style="flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(s.label)}</span><b class="fx">${opts.format?opts.format(s.value):s.value}</b><span class="muted fx" style="width:44px;text-align:right">${(s.value/total*100).toFixed(0)}%</span></div>`).join("")}</div></div>`; }
function renderTopSellers(){
  const lines=soldLines(tsFrom,tsTo); const byKey={}; const label=x=>tsBy==="item"?(x.p?x.p.name:x.l.name):x.key[tsBy]; const keyOf=x=>tsBy==="item"?x.key.item:x.key[tsBy];
  lines.forEach(x=>{ const k=keyOf(x); const g=byKey[k]=byKey[k]||{k,label:label(x),qty:0,rev:0,cost:0,p:x.p,orders:new Set()}; g.qty+=x.qty; g.rev+=x.rev; g.cost+=x.cost; if(x.inv) g.orders.add(x.inv.id); });
  let rows=Object.values(byKey).filter(g=>g.qty>0||g.rev>0).sort((a,b)=>tsMetric==="qty"?b.qty-a.qty||b.rev-a.rev:b.rev-a.rev); const totalQty=rows.reduce((a,g)=>a+g.qty,0), totalRev=rows.reduce((a,g)=>a+g.rev,0);
  const top=rows.slice(0,15); const fmt=tsMetric==="qty"?(v=>String(Math.round(v)))+"":null;
  // category pie always (by revenue or qty per tsMetric)
  const catAgg={}; lines.forEach(x=>{ const c=x.key.category; catAgg[c]=catAgg[c]||{qty:0,rev:0}; catAgg[c].qty+=x.qty; catAgg[c].rev+=x.rev; }); const pieRows=Object.entries(catAgg).map(([c,v])=>({label:c,value:Math.max(0,tsMetric==="qty"?v.qty:v.rev)})).filter(s=>s.value>0).sort((a,b)=>b.value-a.value); const pieTop=pieRows.slice(0,7); const rest=pieRows.slice(7).reduce((a,s)=>a+s.value,0); if(rest>0) pieTop.push({label:"Other",value:rest,color:"#B8BFC4"});
  // item trend
  const item=tsItem?byId("products",tsItem):null; let trend=""; if(item){ const keys=bucketsBetween(tsFrom,tsTo,tsGroup); const q=keys.map(k=>lines.filter(x=>x.key.item===item.id&&bucketKey(x.date,tsGroup)===k).reduce((a,x)=>a+x.qty,0)); const r=keys.map(k=>lines.filter(x=>x.key.item===item.id&&bucketKey(x.date,tsGroup)===k).reduce((a,x)=>a+x.rev,0)); trend=`<div class="card" style="margin-bottom:16px"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">${esc(item.name)} — units sold by ${tsGroup}</h2><span class="fx bgroup">${["day","week","month"].map(g=>`<button class="btn s ${tsGroup===g?"p":""}" onclick="tsGroup='${g}';render()">${g[0].toUpperCase()+g.slice(1)}</button>`).join("")}<button class="btn s" onclick="tsItem='';render()">✕</button></span></div>${svgBars(keys.map(k=>bucketLabel(k,tsGroup)),[{name:"Units",values:q}],{format:v=>String(Math.round(v)),height:200,maxLabels:14})}<p class="muted small">${q.reduce((a,v)=>a+v,0)} units · ${money(r.reduce((a,v)=>a+v,0))} net in this range · ${effStock(item)} in stock now${item.collection?" · "+esc(item.collection):""}</p></div>`; }
  return `<div class="toolbar"><div class="bgroup">${[["month","This month"],["quarter","This quarter"],["year","This year"],["12m","12 months"],["90","90 days"]].map(([k,l])=>`<button class="btn s ${tsPreset===k?"p":""}" onclick="tsSet('${k}')">${l}</button>`).join("")}</div><input type="date" value="${tsFrom}" onchange="tsFrom=this.value;tsPreset='custom';render()" style="max-width:150px"><input type="date" value="${tsTo}" onchange="tsTo=this.value;tsPreset='custom';render()" style="max-width:150px"><span class="grow"></span><div class="bgroup">${[["item","Items"],["collection","Collections"],["category","Categories"],["sub","Sub-categories"]].map(([k,l])=>`<button class="btn s ${tsBy===k?"p":""}" onclick="tsBy='${k}';render()">${l}</button>`).join("")}</div><div class="bgroup"><button class="btn s ${tsMetric==="qty"?"p":""}" onclick="tsMetric='qty';render()">By quantity</button><button class="btn s ${tsMetric==="rev"?"p":""}" onclick="tsMetric='rev';render()">By revenue</button></div>${dd("Export",[["Top sellers (CSV)","exportTopSellersCSV()"],["Print","printTopSellers()"]])}</div>
  <div class="row" style="margin-bottom:12px"><div class="rel" style="max-width:360px"><input type="search" id="ts_q" placeholder="Look up a specific item's trend…" oninput="tsSearch(this.value)" autocomplete="off"><div id="ts_res"></div></div><span class="muted small">${dateFmt(tsFrom)} – ${dateFmt(tsTo)} · ${Math.round(totalQty)} units · ${money(totalRev)} net (returns deducted)</span></div>
  ${trend}
  <div class="grid g2" style="margin-bottom:16px"><div class="card"><h2>Top ${tsBy==="item"?"items":tsBy==="sub"?"sub-categories":tsBy==="collection"?"collections":"categories"} by ${tsMetric==="qty"?"quantity":"revenue"}</h2>${svgHBars(top.map(g=>({label:g.label,value:tsMetric==="qty"?g.qty:g.rev})),{format:tsMetric==="qty"?(v=>Math.round(v)+" units"):money})}</div><div class="card"><h2>Category share (${tsMetric==="qty"?"units":"revenue"})</h2>${pieRows.length?svgPie(pieTop,{format:tsMetric==="qty"?(v=>Math.round(v)+""):money,centerLabel:tsMetric==="qty"?"units":"net"}):`<div class="empty">No sales in this range.</div>`}</div></div>
  <div class="card"><h2>${tsBy==="item"?"Items":tsBy==="sub"?"Sub-categories":tsBy==="collection"?"Collections":"Categories"} sold</h2><div class="tblwrap"><table><thead><tr><th>#</th><th>${tsBy==="item"?"Item":"Name"}</th>${tsBy==="item"?"<th>Collection · category</th>":""}<th class="n">Units</th><th class="n">Share</th><th class="n">Net revenue</th><th class="n">Avg price</th>${has("margin")?'<th class="n">Margin</th>':""}<th class="n">Orders</th>${tsBy==="item"?'<th class="n">In stock</th><th></th>':""}</tr></thead><tbody>${rows.map((g,i)=>`<tr><td class="muted">${i+1}</td><td><b>${esc(g.label)}</b>${tsBy==="item"&&g.p?`<div class="muted small">${esc(g.p.sku)}${g.p.model?" · "+esc(g.p.model):""}</div>`:""}</td>${tsBy==="item"?`<td class="small">${esc(g.p?.collection||"")}${g.p?.collection?" · ":""}${esc(g.p?.category||"")}${g.p?.subcategory?" › "+esc(g.p.subcategory):""}</td>`:""}<td class="n"><b>${Math.round(g.qty)}</b></td><td class="n">${totalQty?pct(g.qty/totalQty):"—"}</td><td class="n">${money(g.rev)}</td><td class="n">${g.qty?money(g.rev/g.qty):"—"}</td>${has("margin")?`<td class="n">${g.rev?pct((g.rev-g.cost)/g.rev):"—"}</td>`:""}<td class="n">${g.orders.size}</td>${tsBy==="item"?`<td class="n">${g.p?effStock(g.p):"—"}</td><td>${g.p?`<button class="btn s" onclick="tsItem='${g.p.id}';render()">Trend</button>`:""}</td>`:""}</tr>`).join("")||`<tr><td colspan="10" class="empty">No sales in this range.</td></tr>`}</tbody></table></div></div>`;
}
function tsSearch(q){ q=q.toLowerCase(); const r=document.getElementById("ts_res"); if(!q){r.innerHTML="";return} const hits=S.products.filter(p=>[p.sku,p.name,p.model,p.collection].join(" ").toLowerCase().includes(q)).slice(0,8); r.innerHTML=hits.length?`<div class="search-res">${hits.map(p=>`<div onmousedown="tsItem='${p.id}';render()"><span><b>${esc(p.sku)}</b> ${esc(p.name)}</span></div>`).join("")}</div>`:""; }
function exportTopSellersCSV(){ const lines=soldLines(tsFrom,tsTo); const byKey={}; lines.forEach(x=>{ const k=tsBy==="item"?x.key.item:x.key[tsBy]; const g=byKey[k]=byKey[k]||{label:tsBy==="item"?(x.p?x.p.name:x.l.name):x.key[tsBy],qty:0,rev:0}; g.qty+=x.qty; g.rev+=x.rev; }); const rows=Object.values(byKey).sort((a,b)=>b.qty-a.qty); saveFile(`top-sellers-${tsBy}-${tsFrom}-to-${tsTo}.csv`,["Name,Units,Net revenue"].concat(rows.map(g=>`"${g.label.replace(/"/g,'""')}",${Math.round(g.qty)},${g.rev.toFixed(2)}`)).join("\n")); }
function printTopSellers(){ const el=document.createElement("div"); el.innerHTML=renderTopSellers(); el.querySelectorAll(".toolbar,.dd,button,input,.rel").forEach(x=>x.remove()); printHTML(`<div class="page"><h1>Top sellers</h1><p>${esc(storeSettings().name)} · ${dateFmt(tsFrom)} – ${dateFmt(tsTo)}</p><style>.card{border:1px solid #ccc;border-radius:8px;padding:10px;margin-bottom:10px} .grid{display:grid;gap:10px} .g2{grid-template-columns:1fr 1fr} table{width:100%;border-collapse:collapse;font-size:11px} th,td{border-bottom:1px solid #ccc;padding:4px} .n{text-align:right} .bar{height:10px;background:#eee;border-radius:99px;overflow:hidden} .bar i{display:block;height:100%;background:#78D6B0} h2{font-size:14px;margin:0 0 6px} .muted{color:#555} svg text{fill:#333}</style>${el.innerHTML.replace(/var\(--surface\)/g,"#fff").replace(/var\(--mint\)/g,"#78D6B0").replace(/var\(--teal\)/g,"#356C68").replace(/var\(--sage\)/g,"#A9C8B4").replace(/var\(--amber\)/g,"#B98A2B").replace(/var\(--blue\)/g,"#4A7FA5").replace(/var\(--red\)/g,"#B9564A").replace(/var\(--ink2?\)/g,"#333")}</div>`,"Top sellers"); }
