/* ============================================================
   ADDRESS SUGGESTIONS — learned from customers + local street list
   ============================================================ */
function parseAddress(a){ const s=String(a||"").trim(); const m=s.match(/^(\d+[A-Za-z]?)\s+(.+?)(?:,\s*([^,]+?))?(?:,\s*([A-Za-z]{2}))?(?:\s+(\d{5}(?:-\d{4})?))?$/); if(!m) return {number:"",street:s,city:"",state:"",zip:""}; return {number:m[1]||"",street:(m[2]||"").trim(),city:(m[3]||"").trim(),state:(m[4]||"").toUpperCase(),zip:m[5]||""}; }
function localeDefaults(){ const st=storeSettings(); const d=st.addressDefaults||{}; if(d.city||d.state||d.zip) return d; const p=parseAddress(st.address||""); return {city:p.city,state:p.state,zip:p.zip}; }
function streetBook(){ const st=storeSettings(); return st.streets||[]; }
function knownAddresses(){ const seen=new Map(); for(const c of S.customers){ if(!c.address) continue; const k=c.address.toLowerCase(); if(!seen.has(k)) seen.set(k,{full:c.address,src:"customer",count:0}); seen.get(k).count++; } return [...seen.values()]; }
function addressSuggestions(q){ q=String(q||"").trim(); if(q.length<2) return []; const lq=q.toLowerCase(); const out=[]; const d=localeDefaults();
  for(const a of knownAddresses()){ if(a.full.toLowerCase().includes(lq)) out.push({text:a.full,note:"previous customer",score:a.full.toLowerCase().startsWith(lq)?3:2}); }
  const p=parseAddress(q); const streetQ=(p.street||"").toLowerCase(); const seenStreets=new Set();
  const streets=streetBook().slice(); for(const a of knownAddresses()){ const pa=parseAddress(a.full); if(pa.street&&!streets.some(s=>s.street.toLowerCase()===pa.street.toLowerCase()&&(s.city||"").toLowerCase()===(pa.city||"").toLowerCase())) streets.push({street:pa.street,city:pa.city,state:pa.state,zip:pa.zip,learned:true}); }
  if(streetQ.length>=2){ for(const s of streets){ const sl=s.street.toLowerCase(); if(!sl.startsWith(streetQ)&&!sl.split(" ").some(w=>w.startsWith(streetQ))) continue; const key=(s.street+"|"+(s.city||"")).toLowerCase(); if(seenStreets.has(key)) continue; seenStreets.add(key); const city=s.city||d.city||"", state=s.state||d.state||"", zip=s.zip||d.zip||""; const full=`${p.number?p.number+" ":""}${s.street}${city?", "+city:""}${state?", "+state:""}${zip?" "+zip:""}`; if(!out.some(o=>o.text.toLowerCase()===full.toLowerCase())) out.push({text:full,note:s.learned?"street seen before":"local street list",score:sl.startsWith(streetQ)?1.5:1}); } }
  out.sort((a,b)=>b.score-a.score||a.text.localeCompare(b.text)); return out.slice(0,8); }
function addrInput(id,value,placeholder){ return `<div class="rel"><input type="text" id="${id}" value="${esc(value||"")}" placeholder="${esc(placeholder||"Start typing — number and street")}" autocomplete="off" oninput="addrSuggest('${id}')" onkeydown="addrKey(event,'${id}')" onblur="setTimeout(()=>{const r=document.getElementById('${id}_sug');if(r)r.innerHTML=''},200)"><div id="${id}_sug"></div></div><div class="muted small" style="margin-top:3px"><a href="#" onclick="addrMaps('${id}');return false">Check on Google Maps ↗</a> · suggestions come from past customers and your street list</div>`; }
const US_STATES=[["AL","Alabama"],["AK","Alaska"],["AZ","Arizona"],["AR","Arkansas"],["CA","California"],["CO","Colorado"],["CT","Connecticut"],["DE","Delaware"],["DC","District of Columbia"],["FL","Florida"],["GA","Georgia"],["HI","Hawaii"],["ID","Idaho"],["IL","Illinois"],["IN","Indiana"],["IA","Iowa"],["KS","Kansas"],["KY","Kentucky"],["LA","Louisiana"],["ME","Maine"],["MD","Maryland"],["MA","Massachusetts"],["MI","Michigan"],["MN","Minnesota"],["MS","Mississippi"],["MO","Missouri"],["MT","Montana"],["NE","Nebraska"],["NV","Nevada"],["NH","New Hampshire"],["NJ","New Jersey"],["NM","New Mexico"],["NY","New York"],["NC","North Carolina"],["ND","North Dakota"],["OH","Ohio"],["OK","Oklahoma"],["OR","Oregon"],["PA","Pennsylvania"],["RI","Rhode Island"],["SC","South Carolina"],["SD","South Dakota"],["TN","Tennessee"],["TX","Texas"],["UT","Utah"],["VT","Vermont"],["VA","Virginia"],["WA","Washington"],["WV","West Virginia"],["WI","Wisconsin"],["WY","Wyoming"],["PR","Puerto Rico"]];
function stateSuggest(id){ const el=document.getElementById(id); const box=document.getElementById(id+"_sug"); if(!el||!box) return; const q=el.value.trim().toUpperCase(); if(!q){ box.innerHTML=""; return; } const hits=US_STATES.filter(([a,n])=>a.startsWith(q)||n.toUpperCase().startsWith(q)).slice(0,8); box.innerHTML=hits.length?`<div class="search-res">${hits.map(([a,n])=>`<div onmousedown="document.getElementById('${id}').value='${a}';document.getElementById('${id}_sug').innerHTML=''"><span><b>${a}</b> ${esc(n)}</span></div>`).join("")}</div>`:""; }
function addrFields(prefix,c){ const p=c&&c.street!==undefined?{street:c.street||"",city:c.city||"",state:c.state||"",zip:c.zip||""}:(()=>{const pa=parseAddress((c&&c.address)||""); return {street:(pa.number?pa.number+" ":"")+pa.street,city:pa.city,state:pa.state,zip:pa.zip};})(); const d=localeDefaults(); return `<div class="field"><label class="f">Street address ${storeSettings().requireAddress==="always"?'<span style="color:var(--red)">*</span>':'<span class="muted">(needed for deliveries)</span>'}</label>${addrInput(prefix,p.street,"Number and street — suggestions appear as you type")}</div><div class="grid g3"><div class="field"><label class="f">City</label><input type="text" id="${prefix}_city" value="${esc(p.city||"")}" placeholder="${esc(d.city||"")}" autocomplete="off"></div><div class="field"><label class="f">State</label><div class="rel"><input type="text" id="${prefix}_state" value="${esc(p.state||"")}" placeholder="${esc(d.state||"PA")}" maxlength="20" autocomplete="off" oninput="stateSuggest('${prefix}_state')" onblur="setTimeout(()=>{const r=document.getElementById('${prefix}_state_sug');if(r)r.innerHTML='';const e=document.getElementById('${prefix}_state');if(e){const v=e.value.trim();const m=US_STATES.find(([a,n])=>a===v.toUpperCase()||n.toLowerCase()===v.toLowerCase());if(m)e.value=m[0];}},200)"><div id="${prefix}_state_sug"></div></div></div><div class="field"><label class="f">ZIP</label><input type="text" id="${prefix}_zip" value="${esc(p.zip||"")}" placeholder="${esc(d.zip||"")}" inputmode="numeric" autocomplete="off"></div></div>`; }
function readAddrFields(prefix){ const d=localeDefaults(); const street=fv(prefix).trim(); let city=fv(prefix+"_city").trim(), state=fv(prefix+"_state").trim().toUpperCase(), zip=fv(prefix+"_zip").trim(); if(street&&!city&&!state&&!zip){ const pa=parseAddress(street); if(pa.city||pa.zip){ return {street:(pa.number?pa.number+" ":"")+pa.street,city:pa.city,state:pa.state,zip:pa.zip,address:street}; } } if(street&&!city) city=d.city||""; if(street&&!state) state=d.state||""; if(street&&!zip&&city.toLowerCase()===(d.city||"").toLowerCase()) zip=d.zip||""; const address=[street,city,[state,zip].filter(Boolean).join(" ")].filter(Boolean).join(", "); return {street,city,state,zip,address}; }
let _addrIdx=-1;
function addrSuggest(id){ const el=document.getElementById(id); const box=document.getElementById(id+"_sug"); if(!el||!box) return; const list=addressSuggestions(el.value); _addrIdx=-1; box.innerHTML=list.length?`<div class="search-res">${list.map((s,i)=>`<div data-i="${i}" onmousedown="addrPick('${id}',${i})"><span>${esc(s.text)}</span><span class="muted small">${esc(s.note)}</span></div>`).join("")}</div>`:""; window._addrList=list; }
function addrPick(id,i){ const el=document.getElementById(id); const s=(window._addrList||[])[i]; if(el&&s){ const pa=parseAddress(s.text); const cityEl=document.getElementById(id+"_city"); if(cityEl){ el.value=(pa.number?pa.number+" ":"")+pa.street; cityEl.value=pa.city||cityEl.value; const st=document.getElementById(id+"_state"); if(st) st.value=pa.state||st.value; const z=document.getElementById(id+"_zip"); if(z) z.value=pa.zip||z.value; } else el.value=s.text; try{ el.dispatchEvent(new Event("change")); }catch(e){} } const box=document.getElementById(id+"_sug"); if(box) box.innerHTML=""; }
function addrKey(e,id){ const box=document.getElementById(id+"_sug"); const rows=box?[...box.querySelectorAll("[data-i]")]:[]; if(!rows.length) return; if(e.key==="ArrowDown"){ e.preventDefault(); _addrIdx=Math.min(rows.length-1,_addrIdx+1); } else if(e.key==="ArrowUp"){ e.preventDefault(); _addrIdx=Math.max(0,_addrIdx-1); } else if(e.key==="Enter"&&_addrIdx>=0){ e.preventDefault(); addrPick(id,_addrIdx); return; } else if(e.key==="Escape"){ box.innerHTML=""; return; } else return; rows.forEach((r,i)=>r.style.background=i===_addrIdx?"var(--sage2)":""); }
function addrMaps(id){ let v=(document.getElementById(id)||{}).value||""; if(document.getElementById(id+"_city")) v=readAddrFields(id).address; if(!v) return toast("Type the address first.",true); window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(v),"_blank"); }
function renderAddressSettings(){ const d=localeDefaults(); const n=streetBook().length; return `<h3 style="margin:14px 0 6px">Address suggestions</h3><p class="muted small">Addresses complete themselves from customers you've already entered and from a street list for your area. Load a street list once (one per line: <code>Street, City, ST, ZIP</code> — city/state/ZIP optional) — many counties publish one free, or paste from any spreadsheet.</p><div class="grid g3"><div class="field"><label class="f">Default city</label><input type="text" id="ad_city" value="${esc(d.city||"")}"></div><div class="field"><label class="f">State</label><input type="text" id="ad_state" value="${esc(d.state||"")}" maxlength="2"></div><div class="field"><label class="f">ZIP</label><input type="text" id="ad_zip" value="${esc(d.zip||"")}"></div></div><div class="field"><label class="f">Street list (${n} street${n===1?"":"s"} loaded)</label><textarea id="ad_streets" rows="4" placeholder="Main St, Pittsburgh, PA, 15201\nGrandview Ave, Pittsburgh, PA, 15211\nOak Hill Rd"></textarea></div><div class="row"><button class="btn fx" onclick="importStreets(false)">Add to street list</button><button class="btn fx" onclick="importStreets(true)">Replace street list</button>${n?`<button class="btn s d fx" onclick="confirmDo('Clear the street list?',()=>{const st=storeSettings();st.streets=[];save('settings',st).then(render)})">Clear</button>`:""}<span class="muted small">Defaults are saved with the Save button above.</span></div>`; }
async function importStreets(replace){ const txt=fv("ad_streets").trim(); if(!txt) return toast("Paste the street list first.",true); const rows=txt.split("\n").map(l=>l.trim()).filter(Boolean).map(l=>{ const parts=l.split(/,|\t/).map(x=>x.trim()); return {street:parts[0]||"",city:parts[1]||"",state:(parts[2]||"").toUpperCase(),zip:parts[3]||""}; }).filter(r=>r.street); const st=storeSettings(); const cur=replace?[]:(st.streets||[]); const key=r=>(r.street+"|"+r.city).toLowerCase(); const seen=new Set(cur.map(key)); let added=0; for(const r of rows){ if(seen.has(key(r))) continue; seen.add(key(r)); cur.push(r); added++; } st.streets=cur; await save("settings",st); render(); toast(`${added} street${added===1?"":"s"} added (${cur.length} total)`); }
