/* ============================================================
   PAID-IN-FULL RELEASE RULE, INLINE REFERRAL, LABEL PRINTING
   ============================================================ */
function releaseRule(){ const st=storeSettings(); return st.requirePaidToRelease!==false; }
function invBalance(inv){ return inv?invTotals(inv).balance:0; }
function releaseBlocked(d){ if(!releaseRule()||!d||!d.invoiceId) return false; if(d.releaseOverride) return false; const inv=byId("invoices",d.invoiceId); if(!inv) return false; if(inv.terms==="financing"||inv.terms==="lease"){ const T=invTotals(inv); return T.balance>0.005; } return invBalance(inv)>0.005; }
function releaseNote(d){ if(!releaseBlocked(d)) return ""; const inv=byId("invoices",d.invoiceId); return `<span class="tag bad" title="Store policy: goods are released only when paid in full">balance ${money(invBalance(inv))} — hold</span>`; }
function releaseAsk(msg,fn){ if(has("approve")){ if(confirm(msg+"\n\nRelease anyway?")) fn(); return; } managerOverride(msg,fn); }
function guardRelease(d,action,fn){ if(!releaseBlocked(d)) return fn(); const inv=byId("invoices",d.invoiceId); releaseAsk(`${inv.number} still has a balance of ${money(invBalance(inv))}. Store policy holds goods until paid in full.`,async()=>{ d.releaseOverride={by:session.staffId,at:todayISO(),action}; await save("deliveries",d); logAudit("release",`${inv.number} ${action} with balance ${money(invBalance(inv))}`,{invoiceId:inv.id,amount:invBalance(inv)}); fn(); }); }
async function markAllGuarded(tid,s){ const stops=dlv().filter(d=>d.date===delDate&&(d.truckId||"")===tid&&d.status!=="delivered"); const held=stops.filter(releaseBlocked); const ok=stops.filter(d=>!releaseBlocked(d)); for(const d of ok){ d.status=s; await save("deliveries",d); } render(); if(held.length) toast(`${held.length} stop${held.length===1?"":"s"} held — balance not paid in full (${held.map(d=>byId("invoices",d.invoiceId)?.number).join(", ")}). Collect payment or have a manager release.`,true); }
async function setCustomerReferral(cid,v){ const c=byId("customers",cid); if(!c) return; if(v==="Other"){ const t=(prompt("Where did they hear about us?")||"").trim(); if(!t) return; v=t; } c.referral=v; await save("customers",c); render(); }
function referralInline(c){ if(!c) return ""; const ask=storeSettings().askReferral||"optional"; if(ask==="off") return ""; const refs=referralSources(); return `<div class="field" style="margin-top:6px"><label class="f">How did they hear about us?${ask==="required"?' <span style="color:var(--red)">*</span>':' <span class="muted">(optional)</span>'}</label><select onchange="setCustomerReferral('${c.id}',this.value)" style="${ask==="required"?"border-color:var(--amber)":""}">${optsList(refs,c.referral||"","Choose…")}</select></div>`; }
/* ---- labels: sheet or Zebra label stock (browser print), or ZPL for Zebra ---- */
const LABEL_FORMATS={sheet:{name:"Letter sheet — 6 labels per page (4 × 2 in)",w:0,h:0},z225:{name:"Zebra 2.25 × 1.25 in",w:2.25,h:1.25},z32:{name:"Zebra 3 × 2 in",w:3,h:2},z42:{name:"Zebra 4 × 2 in",w:4,h:2},z43:{name:"Zebra 4 × 3 in",w:4,h:3},z46:{name:"Zebra 4 × 6 in (shipping)",w:4,h:6}};
function labelFormat(){ const st=storeSettings(); return LABEL_FORMATS[st.labelFormat]?st.labelFormat:"z42"; }
function labelText(x){ const p=x.p||{}; return {name:p.name||x.name||"",sku:p.sku||x.sku||"",vendorSku:p.vendorSku||"",model:p.model||"",attrs:[p.color,p.finish,p.size].filter(Boolean).join(" · "),bin:p.bin||"",loc:x.location||"",po:x.po||"",customer:x.customer||"",invoice:x.invoice||"",phone:x.phone||"",price:p.price?money(effectivePrice(p)):"",box:x.box||0,boxes:x.boxes||0,piece:x.piece||"",fulfil:x.fulfil||"",dims:p.dims||""}; }
function orderLabelItems(inv,opts){ opts=opts||{}; const items=[]; const c=byId("customers",inv.customerId); const d=deliveryOf(inv); const pk=pickupOf(inv); const fulfil=inv.delivery?(d&&d.date?`DELIVERY ${dateShort(d.date)}${d.winStart?" "+m2t(t2m(d.winStart))+"–"+m2t(t2m(d.winEnd)):""}${d.truckId?" · "+(byId("trucks",d.truckId)?.name||""):""}`:"DELIVERY — to be scheduled"):(pk&&pk.plannedDate?`PICKUP ${dateShort(pk.plannedDate)}`:"CUSTOMER PICKUP"); const lines=inv.lines.filter(l=>!l.service&&(opts.all||lineOpen(l))); const total=lines.reduce((a,l)=>a+l.qty*(l.pieces||1),0); let n=0; for(const l of lines){ const p=byId("products",l.productId)||{name:l.name,sku:l.sku}; const pieces=l.pieces||1; for(let i=0;i<l.qty;i++){ for(let j=0;j<pieces;j++){ n++; items.push({p,customer:custDisplay(c),phone:c?.phone||"",invoice:inv.number,location:l.locationId?locName(l.locationId):"",box:n,boxes:total,piece:pieces>1?`piece ${j+1} of ${pieces}`:"",fulfil}); } } } return items; }
function labelHTML(items,fmt){ fmt=fmt||labelFormat(); const F=LABEL_FORMATS[fmt]; const st=storeSettings(); const logo=st.labelLogo!==false&&st.logo?st.logo:"";
  if(fmt==="sheet"){ const pages=[]; for(let i=0;i<items.length;i+=6) pages.push(`<div class="page labelsheet">${items.slice(i,i+6).map(x=>{ const t=labelText(x); return `<div class="plabel">${logo?`<img src="${logo}" style="max-height:26px;max-width:120px;display:block;margin-bottom:3px">`:""}${t.customer?`<div class="big" style="font-size:18px">${t.boxes?`BOX ${t.box} OF ${t.boxes}`:"HOLD"}</div><div style="font-size:15px;font-weight:700">${esc(t.customer)}</div><div>${esc(t.invoice)}${t.fulfil?" · "+esc(t.fulfil):""}</div><div style="margin-top:3px">${esc(t.name)}${t.piece?" — "+esc(t.piece):""}</div>`:`<div style="font-size:15px;font-weight:700">${esc(t.name)}</div>`}<div class="muted small">${esc(t.sku)}${t.vendorSku?" · vendor "+esc(t.vendorSku):""}${t.model?" · "+esc(t.model):""}</div><div class="small">${esc(t.attrs)}${t.bin?" · bin "+esc(t.bin):""}${t.loc?" · "+esc(t.loc):""}</div>${t.po&&!t.customer?`<div class="small">${esc(t.po)}</div>`:""}${t.sku?`<svg class="bc" data-code="${esc(t.sku)}"></svg>`:""}${!t.customer&&t.price?`<div class="small">${t.price}</div>`:""}</div>`}).join("")}</div>`); return pages.join(""); }
  const small=F.h<=1.3; const tall=F.h>=5; const mid=!small&&!tall; const nameSize=small?10.5:tall?22:15, subSize=small?8.5:tall?14:10.5, bcH=small?30:tall?90:48, pad=small?0.06:0.1; const showLogo=logo&&!small;
  return `<style>@page{size:${F.w}in ${F.h}in;margin:0} body{margin:0} .zl{width:${F.w}in;height:${F.h}in;padding:${pad}in;box-sizing:border-box;overflow:hidden;page-break-after:always;font-family:Arial,Helvetica,sans-serif;color:#000;line-height:1.15;position:relative} .zl:last-child{page-break-after:auto} .zl .zn{font-weight:700;font-size:${nameSize}px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis} .zl .zs{font-size:${subSize}px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis} .zl .zh{font-weight:900;font-size:${small?14:tall?36:22}px;letter-spacing:.03em;white-space:nowrap;overflow:hidden} .zl .zbox{font-weight:900;font-size:${small?13:tall?40:26}px;border:2px solid #000;border-radius:6px;padding:1px 8px;display:inline-block;margin-bottom:2px} .zl .zhead{display:flex;align-items:center;justify-content:space-between;gap:6px;margin-bottom:2px} .zl .zhead img{max-height:${tall?60:30}px;max-width:${tall?200:120}px} .zl .zhead .st{font-size:${subSize}px;font-weight:700;text-align:right;white-space:nowrap;overflow:hidden} .zl svg{display:block;max-width:100%;height:${bcH+16}px;width:auto} @media screen{.zl{border:1px dashed #bbb;margin:6px auto}}</style>${items.map(x=>{ const t=labelText(x); return `<div class="zl">${showLogo||(!small&&!t.customer)?`<div class="zhead">${showLogo?`<img src="${logo}" alt="">`:`<span></span>`}<span class="st">${esc(st.name)}${t.customer&&st.phone?" · "+esc(st.phone):""}</span></div>`:""}${t.customer?`${t.boxes?`<span class="zbox">BOX ${t.box} OF ${t.boxes}</span>`:`<div class="zh">HOLD</div>`}<div class="zh">${esc(t.customer)}</div><div class="zs">${esc(t.invoice)}${t.phone?" · "+esc(t.phone):""}${t.fulfil?" · "+esc(t.fulfil):""}</div>`:""}<div class="zn">${esc(t.name)}${t.piece?" — "+esc(t.piece):""}</div><div class="zs">${esc(t.sku)}${t.vendorSku?" · "+esc(t.vendorSku):""}${t.model?" · "+esc(t.model):""}${t.dims&&!small?" · "+esc(t.dims):""}</div>${!small||!t.customer?`<div class="zs">${esc(t.attrs)}${t.bin?" · bin "+esc(t.bin):""}${t.loc?" · "+esc(t.loc):""}${t.po&&!t.customer?" · "+esc(t.po):""}${!t.customer&&t.price?" · "+t.price:""}</div>`:""}${t.sku?`<svg class="bc" data-code="${esc(t.sku)}" data-h="${bcH}"></svg>`:""}</div>`}).join("")}`; }
function zplEscape(s){ return String(s||"").replace(/[\^~\\]/g," "); }
let _logoZPL=null, _logoZPLsrc="";
function prepareLogoZPL(maxW){ const st=storeSettings(); const src=st.labelLogo!==false&&st.logo?st.logo:""; if(!src){ _logoZPL=null; _logoZPLsrc=""; return Promise.resolve(null); } if(_logoZPL&&_logoZPLsrc===src+"|"+maxW) return Promise.resolve(_logoZPL); return new Promise(res=>{ try{ const img=new Image(); img.onload=()=>{ try{ const scale=Math.min(1,maxW/img.width); const w=Math.max(8,Math.round(img.width*scale)), h=Math.max(8,Math.round(img.height*scale)); const cv=document.createElement("canvas"); cv.width=w; cv.height=h; const ctx=cv.getContext("2d"); ctx.fillStyle="#fff"; ctx.fillRect(0,0,w,h); ctx.drawImage(img,0,0,w,h); const d=ctx.getImageData(0,0,w,h).data; const bpr=Math.ceil(w/8); let hex=""; for(let y=0;y<h;y++){ for(let b=0;b<bpr;b++){ let byte=0; for(let bit=0;bit<8;bit++){ const x=b*8+bit; let on=0; if(x<w){ const i=(y*w+x)*4; const lum=(d[i]*299+d[i+1]*587+d[i+2]*114)/1000; const a=d[i+3]; on=a>128&&lum<160?1:0; } byte=(byte<<1)|on; } hex+=byte.toString(16).padStart(2,"0").toUpperCase(); } } _logoZPL={w,h,bpr,hex,total:bpr*h}; _logoZPLsrc=src+"|"+maxW; res(_logoZPL); }catch(e){ res(null); } }; img.onerror=()=>res(null); img.src=src; }catch(e){ res(null); } }); }
function labelZPL(items,fmt){ fmt=fmt||labelFormat(); const F=LABEL_FORMATS[fmt]; const st=storeSettings(); const dpi=+st.labelDpi||203; const w=F.w||4, h=F.h||2; const PW=Math.round(w*dpi), LL=Math.round(h*dpi); const small=h<=1.3, tall=h>=5; const m=Math.round(0.06*dpi); const fs=n=>Math.round(n*dpi/203); const nameF=fs(small?22:tall?44:30), subF=fs(small?18:tall?26:21), bcH=fs(small?46:tall?150:70); const logo=!small&&_logoZPL?_logoZPL:null;
  return items.map(x=>{ const t=labelText(x); let y=m; const out=[`^XA`,`^PW${PW}`,`^LL${LL}`,`^CI28`,`^LH0,0`]; const line=(txt,f,x0,maxW)=>{ if(!txt) return; out.push(`^FO${x0||m},${y}^A0N,${f},${f}^FB${maxW||(PW-2*m)},1,0,L,0^FD${zplEscape(txt)}^FS`); y+=Math.round(f*1.15); };
    if(logo){ out.push(`^FO${m},${y}^GFA,${logo.total},${logo.total},${logo.bpr},${logo.hex}^FS`); out.push(`^FO${m+logo.w+fs(10)},${y}^A0N,${subF},${subF}^FB${PW-2*m-logo.w-fs(10)},2,0,R,0^FD${zplEscape(st.name+(t.customer&&st.phone?"  "+st.phone:""))}^FS`); y+=logo.h+fs(6); } else if(!small&&!t.customer){ line(st.name,subF); }
    if(t.customer){ if(t.boxes){ const bf=fs(small?26:tall?60:40); out.push(`^FO${m},${y}^GB${fs(small?150:240)},${bf+fs(10)},${fs(3)}^FS`); out.push(`^FO${m+fs(8)},${y+fs(5)}^A0N,${bf},${bf}^FDBOX ${t.box} OF ${t.boxes}^FS`); y+=bf+fs(16); } else { line("HOLD",fs(small?26:tall?60:40)); } line(t.customer,fs(small?24:tall?48:34)); line([t.invoice,t.phone,t.fulfil].filter(Boolean).join("  "),subF); }
    line(t.name+(t.piece?" - "+t.piece:""),nameF); line([t.sku,t.vendorSku,t.model,(!small&&t.dims)||""].filter(Boolean).join("  "),subF); if(!small||!t.customer) line([t.attrs,t.bin?"bin "+t.bin:"",t.loc,(!t.customer&&t.po)||"",(!t.customer&&t.price)||""].filter(Boolean).join("  "),subF);
    if(t.sku){ const remaining=LL-y-m; const bh=Math.min(bcH,Math.max(fs(30),remaining-fs(24))); if(remaining>fs(40)) out.push(`^FO${m},${y}^BY${fs(2)},3,${bh}^BCN,${bh},Y,N,N^FD${zplEscape(t.sku)}^FS`); }
    out.push(`^XZ`); return out.join("\n"); }).join("\n"); }
let _labelItems=[], _labelTitle="";
function printLabelsFor(items,title){ if(!items.length) return toast("Nothing to label.",true); logAudit("print_labels",title||"Labels"); _labelItems=items; _labelTitle=title||"Labels"; const st=storeSettings(); const fmt=labelFormat(); const conn=st.labelConn||"driver"; modal(`<h2>${esc(_labelTitle)}</h2><p class="muted">${items.length} label${items.length===1?"":"s"} · ${esc(LABEL_FORMATS[fmt].name)} · ${conn==="browserprint"?"Zebra Browser Print":conn==="network"?"network Zebra (ZPL file)":"printer driver"}${st.logo&&st.labelLogo!==false?" · with logo":""} — <a href="#" onclick="closeModal();setTab='invsetup';go('settings');return false">change in Settings</a></p><div class="grid g2"><div class="field"><label class="f">Label stock</label><select id="lb_fmt">${Object.entries(LABEL_FORMATS).map(([k,f])=>`<option value="${k}" ${fmt===k?"selected":""}>${esc(f.name)}</option>`).join("")}</select></div><div class="field"><label class="f">Copies of each</label><input type="number" id="lb_copies" value="1" min="1" max="10"></div></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button>${conn==="browserprint"?`<button class="btn p" onclick="labelsGo('browserprint')">Send to Zebra</button><button class="btn" onclick="labelsGo('zpl')">Download ZPL</button><button class="btn" onclick="labelsGo('print')">Print via driver</button>`:conn==="network"?`<button class="btn p" onclick="labelsGo('zpl')">Download ZPL</button><button class="btn" onclick="labelsGo('print')">Print via driver</button>`:`<button class="btn p" onclick="labelsGo('print')">Print</button><button class="btn" onclick="labelsGo('zpl')">Download ZPL</button>`}</div>`); }
async function labelsGo(how){ const fmt=fv("lb_fmt")||labelFormat(); const copies=Math.max(1,Math.min(10,fnum("lb_copies")||1)); const st=storeSettings(); if(st.labelFormat!==fmt){ st.labelFormat=fmt; await save("settings",st); } closeModal(); let items=_labelItems; if(copies>1){ items=[]; _labelItems.forEach(x=>{ for(let i=0;i<copies;i++) items.push(x); }); }
  if(how==="print"){ printHTML(labelHTML(items,fmt),_labelTitle); return; }
  await prepareLogoZPL(Math.round(1.1*(+st.labelDpi||203))); const zpl=labelZPL(items,fmt);
  if(how==="browserprint"){ const ok=await sendToBrowserPrint(zpl); if(ok) return; toast("Couldn't reach Zebra Browser Print on this device — downloading the ZPL instead.",true); }
  saveFile(_labelTitle.replace(/[^A-Za-z0-9]+/g,"-").toLowerCase()+".zpl",zpl); }
async function sendToBrowserPrint(zpl){ const st=storeSettings(); const base="http://127.0.0.1:9100"; try{ const r=await fetch(base+"/available",{method:"GET"}); const j=await r.json(); const printers=(j.printer||[]); const dev=printers.find(p=>!st.labelPrinter||p.name===st.labelPrinter)||printers[0]; if(!dev) throw new Error("no printer"); const w=await fetch(base+"/write",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({device:dev,data:zpl})}); if(!w.ok) throw new Error("write failed"); toast(`Sent to ${dev.name}`); return true; }catch(e){ return false; } }
function labelsFromSelection(){ if(!tagSel.size) return toast("Tick items first (the tag checkbox on each card or row).",true); const items=[]; for(const id of tagSel){ const p=byId("products",id); if(!p) continue; const n=tagQty[id]||1; for(let i=0;i<n;i++) items.push({p}); } printLabelsFor(items,"Stock labels"); }
function labelsForItem(pid,n){ const p=byId("products",pid); if(!p) return; const q=n||Math.max(1,Math.min(p.stock||1,50)); const items=[]; for(let i=0;i<q;i++) items.push({p}); printLabelsFor(items,"Labels — "+p.name); }
function labelsForPO(id,receivedOnly){ const o=byId("purchaseOrders",id); const items=[]; for(const l of o.lines){ const p=byId("products",l.productId)||{name:l.desc,sku:l.vendorSku}; const n=receivedOnly?(l.received||0):l.qty; const inv=l.invoiceId?byId("invoices",l.invoiceId):null; if(inv){ const its=orderLabelItems(inv,{all:true}).filter(x=>x.p&&(x.p.id===l.productId||x.p.sku===p.sku)); const perUnit=its.length/Math.max(1,inv.lines.filter(x=>x.productId===l.productId).reduce((a,x)=>a+x.qty,0)); its.slice(0,Math.round(perUnit*n)).forEach(x=>items.push(Object.assign({},x,{po:o.number}))); } else { for(let i=0;i<n;i++) items.push({p,po:o.number,received:o.receivedAt}); } } printLabelsFor(items,"Labels — "+o.number); }
function labelsForOrder(invId){ const inv=byId("invoices",invId); if(!inv) return; printLabelsFor(orderLabelItems(inv),"Customer labels — "+inv.number); }
function labelsForDelivery(did){ const d=byId("deliveries",did); const inv=d&&byId("invoices",d.invoiceId); if(!inv) return toast("No invoice on this stop.",true); printLabelsFor(orderLabelItems(inv),"Delivery labels — "+inv.number); }
function labelsForDay(){ const items=[]; for(const d of dayStops().filter(d=>d.status!=="delivered")){ const inv=byId("invoices",d.invoiceId); if(inv) items.push(...orderLabelItems(inv)); } printLabelsFor(items,"Delivery labels — "+dateFmt(delDate)); }
function labelsModal(){ modal(`<h2>Print labels</h2><p class="muted">Scannable SKU labels for the warehouse — on label sheets or straight to a Zebra.</p><div class="grid g2" style="gap:8px"><button class="btn" onclick="closeModal();tagSel.size?labelsFromSelection():(toast('Tick items in the inventory list or catalog first, then come back.'),render())">Selected stock items (${tagSel.size})</button><button class="btn" onclick="closeModal();labelsRecentReceipts()">Items received in the last 7 days</button><button class="btn" onclick="closeModal();labelsAllLowStock()">Everything with stock on hand (one per unit)</button><button class="btn" onclick="closeModal();labelsHeldOrders()">Customer holds — items waiting for pickup/delivery</button></div><div class="actions"><button class="btn" onclick="closeModal()">Close</button></div>`); }
function labelsRecentReceipts(){ const since=addDays(todayISO(),-7); const items=[]; for(const p of S.products){ if(p.lastReceived&&p.lastReceived>=since){ for(let i=0;i<Math.max(1,Math.min(p.stock||0,10));i++) items.push({p,received:p.lastReceived}); } } for(const o of S.purchaseOrders){ if(o.receivedAt&&o.receivedAt>=since){ for(const l of o.lines){ if(!l.invoiceId) continue; const inv=byId("invoices",l.invoiceId); if(inv) items.push(...orderLabelItems(inv,{all:true}).filter(x=>x.p&&x.p.id===l.productId).map(x=>Object.assign({},x,{po:o.number}))); } } } printLabelsFor(items,"Labels — received this week"); }
function labelsAllLowStock(){ const items=[]; for(const p of S.products){ if(p.isKit) continue; for(let i=0;i<Math.min(p.stock||0,20);i++) items.push({p}); } printLabelsFor(items,"Stock labels"); }
function labelsHeldOrders(){ const items=[]; for(const inv of S.invoices){ if(["void","quote","draft"].includes(inv.status)) continue; if(!inv.lines.some(l=>lineOpen(l)&&!lineBlocked(l))) continue; items.push(...orderLabelItems(inv).filter(x=>true)); } printLabelsFor(items,"Customer hold labels"); }

function labelTestPrint(){ const p=S.products[0]||{name:"Sample sofa",sku:"TEST-0001",color:"Slate",dims:'86" × 38" × 34"'}; printLabelsFor([{p},{p,customer:"Sample Customer",phone:"412-555-0100",invoice:"INV-0000",box:1,boxes:3,piece:"piece 1 of 3",fulfil:"DELIVERY Sep 20 9:00 AM–1:00 PM · Truck 1"}],"Test labels"); }
