/* ============================================================
   CARD PROCESSING — terminal records, batch reconciliation,
   processor configuration ready for a relay/API
   ============================================================ */
const CARD_PROVIDERS=["PAX (semi-integrated)","Clover","Square Terminal","Stripe Terminal","Dejavoo","Ingenico / Worldpay","First Data / Fiserv","Elavon","Other"];
function cardPanelOn(){ const c=cardCfg(); return c.panel!=="off"; }
function cardCfg(){ const st=storeSettings(); return Object.assign({panel:"on",enabled:true,provider:"",merchantId:"",apiKey:"",relayUrl:"",terminals:[],requireRef:false,requireLast4:false,verifyAlert:true,fraudAlert:true,surchargePct:0,debitDiscount:false},st.cardCfg||{}); }
function renderCardSettings(){ const c=cardCfg(); return `<h3 style="margin:14px 0 6px">Card processing & terminals</h3><p class="muted small">Record which terminal took each card payment with its approval details, and reconcile daily batches. Live processing (the register telling the terminal to charge) needs a relay service that this hosted page can reach — enter the details below now and it switches on when a relay is connected.</p>
  <div class="chk" style="margin-bottom:6px"><input type="checkbox" id="cc_on" ${c.panel!=="off"?"checked":""}><label for="cc_on">Use the card panel at the register when Card is chosen (last 4 digits, card type, verification)</label></div><div class="grid g3" style="margin-bottom:8px"><div class="chk"><input type="checkbox" id="cc_l4" ${c.requireLast4!==false?"checked":""}><label for="cc_l4">Require the last 4 digits of the card</label></div><div class="chk"><input type="checkbox" id="cc_verify" ${c.verifyAlert!==false?"checked":""}><label for="cc_verify">Show the "verify name on card matches invoice" reminder</label></div><div class="chk"><input type="checkbox" id="cc_fraud" ${c.fraudAlert!==false?"checked":""}><label for="cc_fraud">Show the same-day pickup fraud caution</label></div></div><div class="grid g3"><div class="field"><label class="f">Processor</label><select id="cc_prov">${optsList(CARD_PROVIDERS,c.provider,"Not set")}</select></div><div class="field"><label class="f">Merchant ID (MID)</label><input type="text" id="cc_mid" value="${esc(c.merchantId)}"></div><div class="field"><label class="f">API key / auth token</label><input type="password" id="cc_key" value="${esc(c.apiKey)}" placeholder="kept for the relay"></div></div>
  <div class="grid g3"><div class="field"><label class="f">Relay / gateway URL</label><input type="url" id="cc_relay" value="${esc(c.relayUrl)}" placeholder="https://pay.yourcompany.com — leave blank until available"></div><div class="field"><label class="f">Card surcharge % (0 = none)</label><input type="number" step="0.1" id="cc_sur" value="${c.surchargePct||0}"></div><div class="field"><label class="f">&nbsp;</label><span class="muted small">Manual card machine: only the last 4 digits are required; auth/reference stay optional.</span><input type="hidden" id="cc_ref" value=""></div></div>
  <b class="small">Terminals</b><div class="tblwrap" style="margin-top:4px"><table><thead><tr><th>Name</th><th>Terminal / device ID</th><th>Location</th><th></th></tr></thead><tbody>${(c.terminals||[]).map((t,i)=>`<tr><td><input type="text" id="ct_n_${i}" value="${esc(t.name)}" placeholder="Front counter"></td><td><input type="text" id="ct_id_${i}" value="${esc(t.tid||"")}" placeholder="TID / serial"></td><td><input type="text" id="ct_l_${i}" value="${esc(t.location||"")}"></td><td><button class="btn s d" onclick="(async()=>{const st=storeSettings();const cfg=cardCfg();cfg.terminals.splice(${i},1);st.cardCfg=cfg;await save('settings',st);render()})()">✕</button></td></tr>`).join("")||`<tr><td colspan="4" class="empty">No terminals yet.</td></tr>`}</tbody></table></div><div class="row" style="margin-top:8px"><button class="btn s fx" onclick="(async()=>{const st=storeSettings();const cfg=cardCfg();cfg.terminals.push({id:uid(),name:'Terminal '+(cfg.terminals.length+1),tid:'',location:''});st.cardCfg=cfg;await save('settings',st);render()})()">+ Add terminal</button><span class="muted small">Saved with the Save button above.</span></div>`; }
function readCardForm(){ const c=cardCfg(); if(!document.getElementById("cc_prov")) return c; return Object.assign({},c,{panel:fchk("cc_on")?"on":"off",enabled:fchk("cc_on"),requireLast4:fchk("cc_l4"),verifyAlert:fchk("cc_verify"),fraudAlert:fchk("cc_fraud"),provider:fv("cc_prov"),merchantId:fv("cc_mid").trim(),apiKey:fv("cc_key"),relayUrl:fv("cc_relay").trim(),surchargePct:fnum("cc_sur"),requireRef:false,terminals:(c.terminals||[]).map((t,i)=>({id:t.id,name:fv("ct_n_"+i).trim()||t.name,tid:fv("ct_id_"+i).trim(),location:fv("ct_l_"+i).trim()}))}); }
function relayAvailable(){ return !!(cardCfg().relayUrl||(typeof platformRelay==="function"&&platformRelay())); }
/* register: card payment panel */
function sameDayPickup(){ if(!cur) return false; { const cc=byId("customers",cur.customerId); if(cc&&cc.trusted) return false; } if(cur.fulfillment==="now") return true; if(cur.lines.some(l=>!l.service&&(l.takeNow||(cur.fulfillment==="mixed"&&lineFulfil(cur,l)==="now")))) return true; if(cur.fulfillment==="pickup"&&cur.pickupDate&&cur.pickupDate<=todayISO()) return true; return false; }
function cardPanel(amount){ const c=cardCfg(); const sur=c.surchargePct?round2(amount*c.surchargePct/100):0; const tgt=window._cardTarget?byId("invoices",window._cardTarget):null; const cust=tgt?byId("customers",tgt.customerId):(cur?byId("customers",cur.customerId):null); const integrated=relayAvailable(); const term0=c.terminals&&c.terminals[0]?c.terminals[0].id:"";
  modal(`<h2>Card payment${integrated?"":" — manual"}</h2>${c.verifyAlert!==false?`<div class="muted small" style="margin-bottom:8px">Check the name on the card matches the invoice${cust?" ("+esc(cust.name)+")":""} and glance at photo ID.</div>`:""}${c.fraudAlert!==false&&sameDayPickup()&&(amount>=(+c.fraudMin||500))&&!(cust&&cust.trusted)?`<div class="notice" style="background:var(--red2);border-color:var(--red);margin-bottom:8px"><b>Same-day card + takes it today, ${money(amount)}:</b> a known fraud pattern. Verify photo ID matches the card and invoice, confirm the phone number, and get a manager to release the goods.</div>`:""}
  <div class="tot"><span>Amount</span><input type="number" step="0.01" id="cp_amt" value="${amount.toFixed(2)}" style="width:140px;text-align:right" oninput="cardPanelSur()"></div>${c.surchargePct?`<div class="tot muted small"><span>Card surcharge ${c.surchargePct}%</span><span id="cp_sur">${money(sur)}</span></div>`:""}
  ${integrated?`<div class="grid g2"><div class="field"><label class="f">Terminal</label><select id="cp_term">${opts(c.terminals||[],term0,t=>t.name+(t.tid?" · "+t.tid:""),t=>t.id,"— choose —")}</select></div><div class="field"><label class="f">Card type</label><select id="cp_brand">${optsList(cardBrands().concat(cardBrands().includes("Other")?[]:["Other"]),cardBrands()[0]||"Visa")}</select></div></div><div class="notice">Integrated terminal via ${esc(c.relayUrl)} — <b>Charge on terminal</b> sends the amount to the device and fills in the card type, last 4, auth code and reference automatically.</div><div class="row" style="margin-bottom:8px"><button class="btn p fx" onclick="cardCharge()">Charge on terminal</button><span class="muted small" id="cp_status"></span></div><div class="grid g3"><div class="field"><label class="f">Last 4 digits</label><input type="text" id="cp_last4" maxlength="4" inputmode="numeric"></div><div class="field"><label class="f">Auth code</label><input type="text" id="cp_auth"></div><div class="field"><label class="f">Reference / transaction #</label><input type="text" id="cp_ref"></div></div>`
  :`<input type="hidden" id="cp_term" value=""><p class="muted small">Run the card on your card machine, then enter the last 4 digits from the receipt.</p><div class="grid g3"><div class="field"><label class="f">Card type</label><select id="cp_brand">${optsList(cardBrands().concat(cardBrands().includes("Other")?[]:["Other"]),cardBrands()[0]||"Visa")}</select></div><div class="field"><label class="f">Last 4 digits of the card${c.requireLast4?' <span style="color:var(--red)">*</span>':' <span class="muted">(optional)</span>'}</label><input type="text" id="cp_last4" maxlength="4" inputmode="numeric" placeholder="1234" autofocus></div><div class="field"><label class="f">Name on card</label><input type="text" id="cp_name" value="${esc(cust?cust.name:"")}"></div></div><details style="margin-bottom:8px"><summary class="muted small" style="cursor:pointer">Add auth code / reference # (optional)</summary><div class="grid g2" style="margin-top:6px"><div class="field"><label class="f">Auth code</label><input type="text" id="cp_auth"></div><div class="field"><label class="f">Reference / transaction # (optional)</label><input type="text" id="cp_ref"></div></div></details>`}
  <div class="grid g2"><div class="field"><label class="f">Entry</label><select id="cp_entry">${optsList(["Tap","Chip","Swipe","Manual key-in","Online / phone"],"Tap")}</select></div>${integrated?`<div class="field"><label class="f">Name on card</label><input type="text" id="cp_name" value="${esc(cust?cust.name:"")}"></div>`:""}</div><div class="chk" style="margin:4px 0 8px"><input type="checkbox" id="cp_verified"><label for="cp_verified">Name on card matches the invoice and photo ID was checked</label></div>
  <div class="actions"><button class="btn" onclick="window._cardTarget=null;closeModal()">Cancel</button><button class="btn p" onclick="cardPanelSave()">Record card payment</button></div>`); }
function cardPanelSur(){ const c=cardCfg(); const el=document.getElementById("cp_sur"); if(el) el.textContent=money(round2((fnum("cp_amt")||0)*c.surchargePct/100)); }
async function cardCharge(){ const c=cardCfg(); const el=document.getElementById("cp_status"); el.textContent="Contacting terminal…"; try{ const body={amount:fnum("cp_amt"),terminalId:(c.terminals.find(t=>t.id===fv("cp_term"))||{}).tid,merchantId:c.merchantId,invoice:cur&&cur.number||"",ref:uid()}; const r=await fetch((c.relayUrl||platformRelay()).replace(/\/$/,"")+"/charge",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+c.apiKey},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok||!j.approved) throw new Error(j.message||"Declined"); document.getElementById("cp_last4").value=j.last4||""; document.getElementById("cp_auth").value=j.authCode||""; document.getElementById("cp_ref").value=j.reference||j.id||""; if(j.brand) document.getElementById("cp_brand").value=j.brand; el.textContent="Approved — details filled in"; }catch(e){ el.textContent="Couldn't reach the relay ("+(e.message||"blocked")+") — run the card on the terminal and enter the approval below."; } }
async function cardPanelSave(){ const c=cardCfg(); const amt=fnum("cp_amt"); if(!amt||amt<=0) return toast("Enter the amount.",true); const ref=fv("cp_ref").trim(); const last4=fv("cp_last4").trim(); if(c.requireLast4!==false&&!/^\d{4}$/.test(last4)) return toast("Enter the last 4 digits of the card.",true); if(last4&&!/^\d{4}$/.test(last4)) return toast("Last 4 should be four digits.",true); const term=(c.terminals||[]).find(t=>t.id===fv("cp_term")); const sur=c.surchargePct?round2(amt*c.surchargePct/100):0; if(sur&&!window._cardTarget&&cur){ cur.lines.push(svcLine(`Card surcharge ${c.surchargePct}%`,sur,{surcharge:true})); }
  const payment={method:"Card",amount:round2(amt+sur),date:todayISO(),by:session.staffId,card:{brand:fv("cp_brand"),last4,auth:fv("cp_auth").trim(),ref,entry:fv("cp_entry"),terminal:term?term.name:"",tid:term?term.tid:"",name:fv("cp_name").trim(),verifiedBy:fchk("cp_verified")?session.staffId:"",sameDayPickup:sameDayPickup(),mode:relayAvailable()?"integrated":"manual",at:Date.now()}};
  if(window._cardTarget){ const inv=byId("invoices",window._cardTarget); window._cardTarget=null; if(inv){ inv.payments.push(payment); if(invTotals(inv).balance<=0.005&&inv.status==="open") inv.status="paid"; await save("invoices",inv); closeModal(); openInvoice(inv.id); toast(`Card payment ${money(amt+sur)} recorded on ${inv.number}`); return; } }
  cur.payments.push(payment); closeModal(); render(); toast(`Card payment ${money(amt+sur)} recorded${term?" · "+term.name:""}`); }
function cardLabel(p){ if(!p.card) return ""; const c=p.card; return [c.brand,c.last4?"•••• "+c.last4:"",c.auth?"auth "+c.auth:"",c.ref?"ref "+c.ref:"",c.terminal].filter(Boolean).join(" · "); }
/* batch reconciliation */
function batchFor(date){ const st=storeSettings(); return (st.batches||{})[date]||{}; }
function renderBatchRecon(){ const ev=paymentEvents(payFrom,payTo).filter(e=>e.method==="Card"||e.method==="Refund"); const days=[...new Set(paymentEvents(payFrom,payTo).map(e=>e.date))].sort(); if(!days.length) return ""; const terms=cardCfg().terminals||[];
  return `<div class="card" style="margin-bottom:16px"><h2>Card batch reconciliation</h2><p class="muted small">Enter each day's settled batch total from the terminal (or processor portal). Variances usually mean a payment was recorded on the wrong day, a refund ran on the terminal but not in the register, or a tip/surcharge difference.</p><div class="tblwrap"><table><thead><tr><th>Day</th><th class="n">Card payments in register</th><th class="n">Refunds</th><th class="n">Net</th><th class="n">Terminal batch total</th><th class="n">Variance</th><th>Note</th></tr></thead><tbody>${days.map(d=>{ const rows=ev.filter(e=>e.date===d); const cards=rows.filter(e=>e.method==="Card").reduce((a,e)=>a+e.amount,0); const refunds=-rows.filter(e=>e.method==="Refund").reduce((a,e)=>a+e.amount,0); const net=cards-refunds; const b=batchFor(d); const v=b.total!==undefined&&b.total!==""?round2(b.total-net):null; return `<tr><td><b>${dateShort(d)}</b>${terms.length>1?`<div class="muted small">${terms.map(t=>`${esc(t.name)} ${money(rows.filter(e=>e.method==="Card"&&e.terminal===t.name).reduce((a,e)=>a+e.amount,0))}`).join(" · ")}</div>`:""}</td><td class="n">${money(cards)}</td><td class="n">${refunds?"-"+money(refunds):"—"}</td><td class="n"><b>${money(net)}</b></td><td class="n"><input type="number" step="0.01" value="${b.total??""}" style="width:120px;text-align:right;display:inline-block;padding:4px 8px" onchange="saveBatch('${d}','total',this.value)"></td><td class="n">${v===null?'<span class="muted">—</span>':`<span class="tag ${Math.abs(v)<0.01?"ok":"bad"}">${Math.abs(v)<0.01?"matches":(v>0?"+":"")+money(v)}</span>`}</td><td><input type="text" value="${esc(b.note||"")}" placeholder="e.g. tip adjust" style="min-width:140px;padding:4px 8px" onchange="saveBatch('${d}','note',this.value)"></td></tr>`}).join("")}</tbody></table></div></div>`; }
async function saveBatch(date,k,v){ const st=storeSettings(); st.batches=st.batches||{}; st.batches[date]=Object.assign({},st.batches[date]||{},{[k]:k==="total"?(v===""?"":+v):v,by:session.staffId,at:todayISO()}); await save("settings",st); render(); }
