/* ============================================================
   ACCOUNTING & TAX REPORT — for the CPA
   ============================================================ */
let acFrom=todayISO().slice(0,8)+"01", acTo=todayISO(), acPreset="month", acBasis="sale";
function acSet(k){ acPreset=k; const t=todayISO(); const d=new Date(t+"T00:00"); if(k==="month"){acFrom=t.slice(0,8)+"01";acTo=t;} else if(k==="lastmonth"){const y=d.getMonth()===0?d.getFullYear()-1:d.getFullYear();const m=d.getMonth()===0?12:d.getMonth();acFrom=`${y}-${String(m).padStart(2,"0")}-01`;acTo=`${y}-${String(m).padStart(2,"0")}-${String(new Date(y,m,0).getDate()).padStart(2,"0")}`;} else if(k==="quarter"){const q=Math.floor(d.getMonth()/3)*3;acFrom=`${d.getFullYear()}-${String(q+1).padStart(2,"0")}-01`;acTo=t;} else if(k==="lastquarter"){let q=Math.floor(d.getMonth()/3)*3-3; let y=d.getFullYear(); if(q<0){q=9;y--;} acFrom=`${y}-${String(q+1).padStart(2,"0")}-01`; acTo=`${y}-${String(q+3).padStart(2,"0")}-${String(new Date(y,q+3,0).getDate()).padStart(2,"0")}`;} else if(k==="year"){acFrom=t.slice(0,4)+"-01-01";acTo=t;} else if(k==="lastyear"){const y=d.getFullYear()-1;acFrom=`${y}-01-01`;acTo=`${y}-12-31`;} render(); }
function taxBreakdown(from,to){ const inv=S.invoices.filter(i=>["paid","open","financed","layaway"].includes(i.status)&&i.date>=from&&i.date<=to); const rets=S.returns.filter(r=>r.date>=from&&r.date<=to);
  const rows={taxable:{label:"Taxable sales",sales:0,tax:0,n:0},exempt:{label:"Tax-exempt customers (resale / non-profit)",sales:0,tax:0,n:0},zero:{label:"Zero-rate bracket (e.g. out of state)",sales:0,tax:0,n:0}}; const lessors={}; const brackets={}; let delivery=0, deliveryTax=0, gross=0, discounts=0;
  for(const i of inv){ const T=invTotals(i); gross+=T.sub; discounts+=T.disc; delivery+=T.delivery; const bk=(i.taxName||"Sales tax")+" "+(i.taxExempt?"exempt":i.taxRate+"%"); brackets[bk]=brackets[bk]||{name:(i.taxName||"Sales tax")+(i.taxExempt?" (tax-exempt customer)":""),rate:i.taxExempt?0:+i.taxRate,base:0,tax:0,n:0}; brackets[bk].n++;
    if(i.taxExempt){ rows.exempt.sales+=T.taxable; rows.exempt.n++; brackets[bk].base+=T.taxable; continue; }
    const fundedNoTax=(T.fundings||[]).filter(f=>!f.upfront); for(const f of fundedNoTax){ const k=f.src.name; lessors[k]=lessors[k]||{label:`Lease-to-own — ${f.src.name} (lessor remits tax)`,sales:0,tax:0,n:0}; lessors[k].sales+=f.taxable; lessors[k].n++; }
    const noTaxSum=fundedNoTax.reduce((a,f)=>a+f.taxable,0); const taxableBase=T.taxable-noTaxSum; if((+i.taxRate||0)===0){ rows.zero.sales+=taxableBase; rows.zero.n++; } else { rows.taxable.sales+=taxableBase; rows.taxable.tax+=T.tax-(storeSettings().taxDelivery?round2(T.delivery*(+i.taxRate||0)/100):0); rows.taxable.n++; }
    brackets[bk].base+=taxableBase; brackets[bk].tax+=T.tax; if(storeSettings().taxDelivery) deliveryTax+=round2(T.delivery*(+i.taxRate||0)/100); }
  const refundSub=rets.reduce((a,r)=>a+r.refundSub,0), refundTax=rets.reduce((a,r)=>a+r.refundTax,0);
  const collected=inv.reduce((a,i)=>a+invTotals(i).tax,0);
  return {inv,rets,rows:[rows.taxable,...Object.values(lessors),rows.exempt,rows.zero].filter(r=>r.n||r.sales),brackets:Object.values(brackets),delivery,deliveryTax,gross,discounts,refundSub,refundTax,collected,netDue:round2(collected-refundTax)}; }
function cogsFor(from,to,basis){ let rev=0,cogs=0,units=0,plans=0,svc=0,delivery=0; const lines=[]; if(basis==="delivered"){ for(const i of S.invoices){ if(["void","quote","draft"].includes(i.status)) continue; for(const l of i.lines){ if(l.service||!l.deliveredAt||l.deliveredAt<from||l.deliveredAt>to) continue; const e=lineEconomics(i,l); rev+=e.net; cogs+=(+l.cost||0)*l.qty; units+=l.qty; } } } else { for(const i of S.invoices){ if(!["paid","open","financed","layaway"].includes(i.status)||i.date<from||i.date>to) continue; const T=invTotals(i); rev+=T.merch; cogs+=T.cost; plans+=T.planRev; svc+=T.svcRev; delivery+=T.delivery; units+=i.lines.filter(l=>!l.service).reduce((a,l)=>a+l.qty,0); } } const rets=S.returns.filter(r=>r.date>=from&&r.date<=to); const retSub=rets.reduce((a,r)=>a+r.refundSub,0), retCost=rets.reduce((a,r)=>a+r.costBack,0); return {rev,cogs,units,plans,svc,delivery,retSub,retCost,netRev:rev-retSub,netCogs:cogs-retCost,gp:(rev-retSub)-(cogs-retCost)}; }
function inventoryPosition(){ const locs=feat("locations")&&locations().length?locations():[]; const onHand={units:0,cost:0,retail:0}; const byLoc=locs.map(l=>({l,units:0,cost:0,retail:0})); for(const p of S.products){ if(p.isKit) continue; const u=Math.max(0,p.stock||0); const lc=landedCost(p); onHand.units+=u; onHand.cost+=u*lc; onHand.retail+=u*(p.price||0); byLoc.forEach(b=>{ const q=stockAt(p,b.l.id); b.units+=q; b.cost+=q*lc; b.retail+=q*(p.price||0); }); }
  const committed={units:0,cost:0,retail:0,orders:new Set()}, backordered={units:0,cost:0,retail:0,orders:new Set()}, heldSpecial={units:0,cost:0,retail:0}; for(const i of S.invoices){ if(["void","quote","draft"].includes(i.status)) continue; for(const l of i.lines){ if(!lineOpen(l)) continue; const q=l.qty; if(lineBlocked(l)){ backordered.units+=q; backordered.cost+=(+l.cost||0)*q; backordered.retail+=(+l.price||0)*q; backordered.orders.add(i.id); } else if(l.special){ heldSpecial.units+=q; heldSpecial.cost+=(+l.cost||0)*q; heldSpecial.retail+=(+l.price||0)*q; } else { committed.units+=q; committed.cost+=(+l.cost||0)*q; committed.retail+=(+l.price||0)*q; committed.orders.add(i.id); } } }
  const onOrder={units:0,cost:0,pos:0}; for(const o of S.purchaseOrders){ if(!["sent","partial"].includes(o.status)) continue; onOrder.pos++; for(const l of o.lines){ const rem=Math.max(0,l.qty-(l.received||0)); onOrder.units+=rem; onOrder.cost+=rem*(+l.unitCost||0); } }
  return {onHand,byLoc,committed,backordered,heldSpecial,onOrder,available:{units:onHand.units-committed.units,cost:onHand.cost-committed.cost}}; }
function renderAccounting(){ const tb=taxBreakdown(acFrom,acTo); const cg=cogsFor(acFrom,acTo,acBasis); const ip=inventoryPosition(); const st=storeSettings();
  const preset=(k,l)=>`<button class="btn s ${acPreset===k?"p":""}" onclick="acSet('${k}')">${l}</button>`;
  return `<div class="toolbar"><div class="bgroup">${preset("month","This month")}${preset("lastmonth","Last month")}${preset("quarter","This quarter")}${preset("lastquarter","Last quarter")}${preset("year","This year")}${preset("lastyear","Last year")}</div><input type="date" value="${acFrom}" onchange="acFrom=this.value;acPreset='custom';render()" style="max-width:150px"><input type="date" value="${acTo}" onchange="acTo=this.value;acPreset='custom';render()" style="max-width:150px"><span class="grow"></span>${dd("Export",[["Sales tax report (CSV)","exportTaxCSV()"],["Sales & COGS summary (CSV)","exportCogsCSV()"],["Inventory position (CSV)","exportInventoryPositionCSV()"],["Print accounting pack","printAccounting()"]])}</div>
  <p class="muted small">${dateFmt(acFrom)} – ${dateFmt(acTo)} · sales are counted on the invoice date; returns on the return date. Inventory position is as of right now.</p>
  <div class="card" style="margin-bottom:16px"><h2>Sales tax</h2><div class="grid g4" style="margin-bottom:10px"><div class="stat"><div class="v">${money(tb.rows.filter(r=>r.label==="Taxable sales").reduce((a,r)=>a+r.sales,0)+(st.taxDelivery?tb.delivery:0))}</div><div class="l">Taxable sales${st.taxDelivery?" (incl. delivery)":""}</div></div><div class="stat b"><div class="v">${money(tb.rows.filter(r=>r.label!=="Taxable sales").reduce((a,r)=>a+r.sales,0)+(st.taxDelivery?0:tb.delivery))}</div><div class="l">Non-taxable sales</div></div><div class="stat t"><div class="v">${money(tb.collected)}</div><div class="l">Tax collected</div></div><div class="stat a"><div class="v">${money(tb.netDue)}</div><div class="l">Net tax due${tb.refundTax?` · after ${money(tb.refundTax)} refunded`:""}</div></div></div>
  <div class="tblwrap"><table><thead><tr><th>Sales by tax treatment</th><th class="n">Invoices</th><th class="n">Sales</th><th class="n">Tax</th></tr></thead><tbody>${tb.rows.map(r=>`<tr><td>${esc(r.label)}</td><td class="n">${r.n}</td><td class="n">${money(r.sales)}</td><td class="n">${money(r.tax)}</td></tr>`).join("")}<tr><td>Delivery fees (${st.taxDelivery?"taxed":"not taxed"})</td><td class="n"></td><td class="n">${money(tb.delivery)}</td><td class="n">${money(tb.deliveryTax)}</td></tr><tr><td>Returns / refunds</td><td class="n">${tb.rets.length}</td><td class="n">-${money(tb.refundSub)}</td><td class="n">-${money(tb.refundTax)}</td></tr></tbody></table></div>
  <h3 style="margin:14px 0 6px">By tax bracket</h3><div class="tblwrap"><table><thead><tr><th>Bracket</th><th class="n">Rate</th><th class="n">Invoices</th><th class="n">Taxable base</th><th class="n">Tax collected</th></tr></thead><tbody>${tb.brackets.map(b=>`<tr><td>${esc(b.name)}</td><td class="n">${b.rate}%</td><td class="n">${b.n}</td><td class="n">${money(b.base)}</td><td class="n">${money(b.tax)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty">No sales in this range.</td></tr>`}</tbody></table></div><p class="muted small">Lease-to-own items on companies that don't charge tax up front are listed separately — the lessor collects and remits tax on the lease payments. Tax-exempt customers are those marked exempt on their record (keep their certificates on file).</p></div>
  <div class="grid g2" style="margin-bottom:16px"><div class="card"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Revenue & cost of goods sold</h2><span class="fx bgroup"><button class="btn s ${acBasis==="sale"?"p":""}" onclick="acBasis='sale';render()">By sale date</button><button class="btn s ${acBasis==="delivered"?"p":""}" onclick="acBasis='delivered';render()">By delivery date</button></span></div><div class="tot"><span>Merchandise sales</span><span>${money(cg.rev)}</span></div><div class="tot muted"><span>Returns</span><span>-${money(cg.retSub)}</span></div><div class="tot"><span><b>Net merchandise sales</b></span><b>${money(cg.netRev)}</b></div><div class="tot"><span>Cost of goods sold (landed)</span><span>${money(cg.cogs)}</span></div><div class="tot muted"><span>Cost returned to stock</span><span>-${money(cg.retCost)}</span></div><div class="tot"><span><b>Net COGS</b></span><b>${money(cg.netCogs)}</b></div><div class="tot" style="border-top:1px solid var(--line);margin-top:6px;padding-top:6px"><span><b>Gross profit on merchandise</b></span><b>${money(cg.gp)} · ${pct(cg.netRev?cg.gp/cg.netRev:0)}</b></div>${acBasis==="sale"?`<div class="tot muted small" style="margin-top:8px"><span>Protection plans</span><span>${money(cg.plans)}</span></div><div class="tot muted small"><span>Services (setup, haul-away, other)</span><span>${money(cg.svc)}</span></div><div class="tot muted small"><span>Delivery fees</span><span>${money(cg.delivery)}</span></div><div class="tot"><span><b>Total gross revenue (before tax)</b></span><b>${money(cg.rev+cg.plans+cg.svc+cg.delivery)}</b></div><div class="tot muted small"><span>Sales tax collected</span><span>${money(tb.collected)}</span></div>`:`<p class="muted small" style="margin-top:8px">Delivery-date basis counts each item when it left the store — useful if your books recognize revenue on delivery.</p>`}</div>
  <div class="card"><h2>Inventory position (now)</h2><div class="tblwrap"><table><thead><tr><th></th><th class="n">Units</th><th class="n">At landed cost</th><th class="n">At retail</th></tr></thead><tbody><tr><td><b>On hand — all stock</b></td><td class="n">${ip.onHand.units}</td><td class="n"><b>${money(ip.onHand.cost)}</b></td><td class="n">${money(ip.onHand.retail)}</td></tr>${ip.byLoc.map(b=>`<tr><td style="padding-left:18px">${esc(b.l.name)}${isDisplayLoc(b.l)?' <span class="tag warn">showroom / display</span>':""}</td><td class="n">${b.units}</td><td class="n">${money(b.cost)}</td><td class="n">${money(b.retail)}</td></tr>`).join("")}<tr><td>Committed to customer orders (sold, not yet out)</td><td class="n">${ip.committed.units}</td><td class="n">${money(ip.committed.cost)}</td><td class="n">${money(ip.committed.retail)}</td></tr><tr><td><b>Available to sell</b></td><td class="n">${ip.available.units}</td><td class="n"><b>${money(ip.available.cost)}</b></td><td class="n"></td></tr><tr><td>Customer special orders received, waiting to go out (not in stock counts)</td><td class="n">${ip.heldSpecial.units}</td><td class="n">${money(ip.heldSpecial.cost)}</td><td class="n">${money(ip.heldSpecial.retail)}</td></tr><tr><td>Customer orders waiting on vendors (not in stock)</td><td class="n">${ip.backordered.units}</td><td class="n">${money(ip.backordered.cost)}</td><td class="n">${money(ip.backordered.retail)}</td></tr><tr><td>On order from vendors (${ip.onOrder.pos} PO${ip.onOrder.pos===1?"":"s"})</td><td class="n">${ip.onOrder.units}</td><td class="n">${money(ip.onOrder.cost)}</td><td class="n"></td></tr></tbody></table></div><p class="muted small">Inventory is valued at landed cost (vendor cost + freight + extras). ${ip.byLoc.length?"":"Turn on Multiple locations in Optional features to split showroom and warehouse."}</p></div></div>`; }
function exportTaxCSV(){ const tb=taxBreakdown(acFrom,acTo); const st=storeSettings(); const rows=[`Sales tax report,${st.name},${acFrom} to ${acTo}`,"","Treatment,Invoices,Sales,Tax"].concat(tb.rows.map(r=>`"${r.label}",${r.n},${r.sales.toFixed(2)},${r.tax.toFixed(2)}`)).concat([`Delivery fees (${st.taxDelivery?"taxed":"not taxed"}),,${tb.delivery.toFixed(2)},${tb.deliveryTax.toFixed(2)}`,`Returns / refunds,${tb.rets.length},${(-tb.refundSub).toFixed(2)},${(-tb.refundTax).toFixed(2)}`,"","Bracket,Rate,Invoices,Taxable base,Tax collected"]).concat(tb.brackets.map(b=>`"${b.name}",${b.rate},${b.n},${b.base.toFixed(2)},${b.tax.toFixed(2)}`)).concat(["",`Tax collected,,,${tb.collected.toFixed(2)}`,`Tax refunded,,,${(-tb.refundTax).toFixed(2)}`,`Net tax due,,,${tb.netDue.toFixed(2)}`,"","Invoice,Date,Customer,Bracket,Rate,Taxable,Tax,Exempt,Lease no-tax items"]).concat(tb.inv.map(i=>{const T=invTotals(i);const nt=(T.fundings||[]).filter(f=>!f.upfront).reduce((a,f)=>a+f.taxable,0);return `${i.number},${i.date},"${custName(i.customerId).replace(/"/g,'""')}","${i.taxName||"Sales tax"}",${i.taxExempt?0:i.taxRate},${(T.taxable-nt).toFixed(2)},${T.tax.toFixed(2)},${i.taxExempt?"yes":""},${nt?nt.toFixed(2):""}`})); saveFile(`sales-tax-${acFrom}-to-${acTo}.csv`,rows.join("\n")); }
function exportCogsCSV(){ const cg=cogsFor(acFrom,acTo,acBasis); const tb=taxBreakdown(acFrom,acTo); saveFile(`sales-cogs-${acFrom}-to-${acTo}.csv`,["Line,Amount",`Merchandise sales,${cg.rev.toFixed(2)}`,`Returns,${(-cg.retSub).toFixed(2)}`,`Net merchandise sales,${cg.netRev.toFixed(2)}`,`COGS (landed),${cg.cogs.toFixed(2)}`,`Cost returned,${(-cg.retCost).toFixed(2)}`,`Net COGS,${cg.netCogs.toFixed(2)}`,`Gross profit,${cg.gp.toFixed(2)}`,`Protection plans,${cg.plans.toFixed(2)}`,`Services,${cg.svc.toFixed(2)}`,`Delivery fees,${cg.delivery.toFixed(2)}`,`Total gross revenue,${(cg.rev+cg.plans+cg.svc+cg.delivery).toFixed(2)}`,`Sales tax collected,${tb.collected.toFixed(2)}`].join("\n")); }
function exportInventoryPositionCSV(){ const rows=["SKU,Item,Category,Vendor,On hand,Landed cost,Value at cost,Retail,Value at retail"+(feat("locations")&&locations().length?","+locations().map(l=>`"${l.name}"`).join(","):"")].concat(S.products.filter(p=>!p.isKit).map(p=>`"${p.sku}","${p.name.replace(/"/g,'""')}","${p.category||""}","${vendName(p.vendorId)}",${p.stock||0},${landedCost(p).toFixed(2)},${((p.stock||0)*landedCost(p)).toFixed(2)},${(p.price||0).toFixed(2)},${((p.stock||0)*(p.price||0)).toFixed(2)}`+(feat("locations")&&locations().length?","+locations().map(l=>stockAt(p,l.id)).join(","):""))); saveFile(`inventory-position-${todayISO()}.csv`,rows.join("\n")); }
function printAccounting(){ const el=document.createElement("div"); el.innerHTML=renderAccounting(); el.querySelectorAll(".toolbar,.dd,button,input,select").forEach(x=>x.remove()); printHTML(`<div class="page"><h1>Accounting pack</h1><p>${esc(storeSettings().name)} · ${dateFmt(acFrom)} – ${dateFmt(acTo)} · prepared ${dateFmt(todayISO())} by ${esc(me().name)}</p><style>.card{border:1px solid #ccc;border-radius:8px;padding:10px;margin-bottom:10px} .grid{display:grid;gap:10px} .g2{grid-template-columns:1fr 1fr} .g4{grid-template-columns:repeat(4,1fr)} .stat .v{font-size:18px;font-weight:800} .stat .l{font-size:11px;color:#444} table{width:100%;border-collapse:collapse;font-size:11px} th,td{border-bottom:1px solid #ccc;padding:4px} .n{text-align:right} .tot{display:flex;justify-content:space-between;padding:3px 0;font-size:12px} h2{font-size:14px;margin:0 0 6px} h3{font-size:12px} .muted{color:#555} .tag{font-size:10px}</style>${el.innerHTML}</div>`,"Accounting pack"); }
