/* ============================================================
   INVENTORY CSV UPLOADER — template, field cross-check, preview
   ============================================================ */
const IMPORT_FIELDS=[
 {key:"sku",label:"SKU",req:true,aliases:["sku","item number","item #","item no","code","item code"]},
 {key:"barcode",label:"Barcode / UPC",aliases:["barcode","upc","ean","gtin","scan code"]},
 {key:"name",label:"Item name",req:true,aliases:["name","item","description","item name","product","product name","title"]},
 {key:"category",label:"Category",aliases:["category","dept","department","cat"]},
 {key:"subcategory",label:"Sub-category",aliases:["subcategory","sub-category","sub category","subcat","type"]},
 {key:"collection",label:"Collection",aliases:["collection","group","series","line"]},
 {key:"model",label:"Model #",aliases:["model","model #","model number","style","style #"]},
 {key:"vendor",label:"Supplier / vendor",aliases:["vendor","supplier","manufacturer","brand"]},
 {key:"vendorSku",label:"Vendor item #",aliases:["vendor sku","vendor item","vendor item #","supplier sku","mfr #","mfg #","mfg part"]},
 {key:"color",label:"Color",aliases:["color","colour"]},
 {key:"finish",label:"Cover / finish",aliases:["finish","cover","fabric","material"]},
 {key:"size",label:"Size",aliases:["size","mattress size"]},
 {key:"dims",label:"Dimensions",aliases:["dims","dimensions","w x d x h","wxdxh","measurements"]},
 {key:"cost",label:"Vendor cost",num:true,aliases:["cost","vendor cost","unit cost","wholesale","landed cost","cost price"]},
 {key:"freight",label:"Freight $ (per unit)",num:true,aliases:["freight","shipping","freight cost"]},
 {key:"price",label:"Selling price (blank = auto)",num:true,aliases:["price","retail","sell price","selling price","sale price","retail price"]},
 {key:"msrp",label:"MSRP / compare at",num:true,aliases:["msrp","compare at","list price","list","suggested retail"]},
 {key:"map",label:"MAP (minimum advertised price)",num:true,aliases:["map","minimum advertised price","min price","floor price"]},
 {key:"photo",label:"Image URL",aliases:["image","image url","photo","photo url","picture","img","image link","thumbnail"]},
 {key:"weightLbs",label:"Weight (lbs)",num:true,aliases:["weight","weight lbs","lbs","ship weight"]},
 {key:"stock",label:"Stock on hand",num:true,aliases:["stock","qty","quantity","on hand","qoh","inventory","units"]},
 {key:"reorderAt",label:"Reorder point",num:true,aliases:["reorder","reorder point","reorder at","min","minimum"]},
 {key:"bin",label:"Warehouse bin",aliases:["bin","location","shelf","aisle"]},
 {key:"pieces",label:"Pieces per unit",num:true,aliases:["pieces","pcs","boxes","cartons"]},
 {key:"warrantyYears",label:"Warranty (years)",num:true,aliases:["warranty","warranty years"]},
 {key:"comfort",label:"Mattress comfort",aliases:["comfort","feel","firmness"]},
 {key:"matType",label:"Mattress type",aliases:["mattress type","mat type","construction"]},
 {key:"notes",label:"Notes",aliases:["notes","comments","remarks"]}];
function importTemplateCSV(){ const head=IMPORT_FIELDS.map(f=>f.key).join(","); const row=o=>IMPORT_FIELDS.map(f=>{ const v=o[f.key]??""; return /[",\n]/.test(String(v))?'"'+String(v).replace(/"/g,'""')+'"':String(v); }).join(","); const ex=row({sku:'HT-1001',barcode:'024052325317',name:'Alder queen platform bed',category:'Bedroom',subcategory:'Beds',collection:'Alder',model:'ALD-QB',vendor:'Ashwood Manufacturing',vendorSku:'V213',color:'Natural',finish:'Alder wood',size:'Queen',dims:'64" x 86" x 48"',cost:390,price:'',msrp:1299,map:999,photo:'https://example.com/images/ald-qb.jpg',weightLbs:82,stock:3,reorderAt:1,bin:'C1',pieces:3,warrantyYears:1}); const ex2=row({sku:'HT-1020',name:'Serenity Hybrid Queen',category:'Mattress',subcategory:'Mattresses',collection:'Serenity Hybrid',model:'SH-Q',vendor:'Serenity Sleep Co.',vendorSku:'SS-Q',size:'Queen',cost:380,freight:25,msrp:1599,stock:6,reorderAt:2,bin:'M1',pieces:1,warrantyYears:10,comfort:'Medium',matType:'Hybrid',notes:'100-night trial'}); saveFile("inventory-template.csv",head+"\n"+ex+"\n"+ex2+"\n"); }
function normHeader(h){ return String(h||"").trim().toLowerCase().replace(/[_\-\.]/g," ").replace(/\s+/g," "); }
function autoMap(headers){ const map={}; const used=new Set(); for(const f of IMPORT_FIELDS){ const hit=headers.find((h,i)=>!used.has(i)&&(normHeader(h)===f.key.toLowerCase()||f.aliases.includes(normHeader(h)))); if(hit!==undefined){ map[f.key]=hit; used.add(headers.indexOf(hit)); } } return map; }
let _imp={rows:[],headers:[],map:{}};
function importProducts(){ modal(`<h2>Upload inventory (CSV)</h2><p class="muted">Use the template so the columns line up, or upload any spreadsheet exported as CSV — you'll match its columns to our fields before anything is imported. Existing SKUs are updated; new SKUs are created.</p><div class="row" style="margin-bottom:10px"><button class="btn fx" onclick="importTemplateCSV()">Download template</button><input type="file" accept=".csv,text/csv,.txt" onchange="importFileChosen(this)"><span class="muted small">or paste below</span></div><textarea id="imp_csv" rows="7" placeholder="sku,name,category,cost,price,stock,vendor…"></textarea><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="importCheck()">Check columns →</button></div>`,true); }
function importFileChosen(input){ const f=input.files&&input.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{ const el=document.getElementById("imp_csv"); if(el) el.value=String(r.result||""); importCheck(); }; r.readAsText(f); }
function importCheck(){ const txt=fv("imp_csv").trim(); if(!txt) return toast("Paste the CSV or choose a file first.",true); let rows; try{ rows=parseCSV(txt); }catch(e){ return toast("Couldn't read that CSV: "+e.message,true); } if(!rows.length) return toast("No rows found under the header.",true); const headers=Object.keys(rows[0]); _imp={rows,headers,map:autoMap(headers)}; renderImportMap(); }
function renderImportMap(){ const {rows,headers,map}=_imp; const unmatched=headers.filter(h=>!Object.values(map).includes(h)); const missingReq=IMPORT_FIELDS.filter(f=>f.req&&!map[f.key]);
  modal(`<h2>Match columns</h2><p class="muted">${rows.length} row${rows.length===1?"":"s"} · ${headers.length} column${headers.length===1?"":"s"} found. Every field below shows which column it will read from — change any that guessed wrong.</p>${missingReq.length?`<div class="notice" style="background:var(--red2);border-color:var(--red)">Required: ${missingReq.map(f=>f.label).join(", ")} — choose the column${missingReq.length===1?"":"s"} that holds ${missingReq.length===1?"it":"them"}.</div>`:`<div class="notice">Required fields matched. ${unmatched.length?`Columns not used: ${unmatched.map(esc).join(", ")} — pick a field for them if they matter, otherwise they're ignored.`:"All columns matched."}</div>`}
  <div class="tblwrap" style="max-height:340px;overflow:auto"><table><thead><tr><th>Our field</th><th>Column in your file</th><th>Sample values</th></tr></thead><tbody>${IMPORT_FIELDS.map(f=>`<tr><td>${esc(f.label)}${f.req?' <span style="color:var(--red)">*</span>':""}</td><td><select onchange="_imp.map['${f.key}']=this.value;renderImportMap()"><option value="" ${map[f.key]?"":"selected"}>— not in file —</option>${headers.map(h=>`<option value="${esc(h)}" ${map[f.key]===h?"selected":""}>${esc(h)}</option>`).join("")}</select></td><td class="muted small">${map[f.key]?esc(rows.slice(0,3).map(r=>r[map[f.key]]).filter(x=>x!==undefined&&x!=="").join(" · ")):""}</td></tr>`).join("")}</tbody></table></div>
  <div class="actions"><button class="btn" onclick="importProducts()">← Back</button><button class="btn p" onclick="importPreview()" ${missingReq.length?"disabled":""}>Preview & validate →</button></div>`,true); }
function importValidate(){ const {rows,map}=_imp; const cats=categoryNames(); const out=[]; const seen=new Set(); for(let i=0;i<rows.length;i++){ const r=rows[i]; const g=k=>map[k]?String(r[map[k]]??"").trim():""; const issues=[]; const sku=g("sku"), name=g("name"); if(!sku) issues.push("missing SKU"); if(!name) issues.push("missing name"); if(sku&&seen.has(sku.toLowerCase())) issues.push("duplicate SKU in file"); seen.add(sku.toLowerCase()); for(const f of IMPORT_FIELDS){ if(f.num&&g(f.key)!==""&&isNaN(parseFloat(g(f.key).replace(/[$,]/g,"")))) issues.push(`${f.label} isn't a number ("${g(f.key)}")`); } const cat=g("category"); let catNote=""; if(cat&&!cats.includes(cat)){ const near=cats.find(c=>c.toLowerCase()===cat.toLowerCase()); if(near) catNote=`category → ${near}`; else issues.push(`unknown category "${cat}" (will be created)`); } const vend=g("vendor"); const v=vend?S.vendors.find(x=>x.name.toLowerCase()===vend.toLowerCase()):null; if(vend&&!v) issues.push(`unknown supplier "${vend}" (will be created)`); const existing=sku?S.products.find(p=>p.sku.toLowerCase()===sku.toLowerCase()):null; out.push({i,r,g,issues,warn:issues.filter(x=>/will be created|category →/.test(x)),errors:issues.filter(x=>!/will be created|category →/.test(x)),existing,catNote}); } return out; }
function importPreview(){ const v=importValidate(); const errs=v.filter(x=>x.errors.length), warns=v.filter(x=>x.warn.length&&!x.errors.length), ok=v.filter(x=>!x.issues.length); const news=v.filter(x=>!x.existing&&!x.errors.length).length, upd=v.filter(x=>x.existing&&!x.errors.length).length; _imp.validated=v;
  modal(`<h2>Preview</h2><div class="grid g4" style="margin-bottom:10px"><div class="stat"><div class="v">${v.length}</div><div class="l">rows</div></div><div class="stat t"><div class="v">${news}</div><div class="l">new items</div></div><div class="stat b"><div class="v">${upd}</div><div class="l">existing SKUs updated</div></div><div class="stat ${errs.length?"r":"a"}"><div class="v">${errs.length}</div><div class="l">rows with problems (skipped)</div></div></div>${warns.length?`<div class="notice">${warns.length} row${warns.length===1?"":"s"} reference a category or supplier that doesn't exist yet — they'll be created automatically.</div>`:""}
  <div class="tblwrap" style="max-height:320px;overflow:auto"><table><thead><tr><th>#</th><th>SKU</th><th>Name</th><th>Category</th><th>Supplier</th><th class="n">Cost</th><th class="n">Price</th><th class="n">Stock</th><th>Result</th></tr></thead><tbody>${v.slice(0,200).map(x=>`<tr style="${x.errors.length?"background:var(--red2)":""}"><td class="muted">${x.i+2}</td><td>${esc(x.g("sku"))}</td><td>${esc(x.g("name"))}</td><td>${esc(x.g("category"))}${x.g("subcategory")?" › "+esc(x.g("subcategory")):""}</td><td>${esc(x.g("vendor"))}</td><td class="n">${esc(x.g("cost"))}</td><td class="n">${x.g("price")||'<span class="muted">auto</span>'}</td><td class="n">${esc(x.g("stock"))}</td><td class="small">${x.errors.length?`<span class="tag bad">skip</span> ${esc(x.errors.join("; "))}`:`<span class="tag ${x.existing?"info":"ok"}">${x.existing?"update":"new"}</span>${x.warn.length?" "+esc(x.warn.join("; ")):""}${x.catNote?" "+esc(x.catNote):""}`}</td></tr>`).join("")}</tbody></table></div>${v.length>200?`<p class="muted small">Showing the first 200 rows.</p>`:""}
  <div class="grid g2" style="margin-top:10px"><div class="chk"><input type="checkbox" id="imp_stock" checked><label for="imp_stock">Set stock on hand from the file (untick to keep current stock)</label></div><div class="chk"><input type="checkbox" id="imp_price" checked><label for="imp_price">Auto-price items that have no price in the file</label></div></div>
  <div class="actions"><button class="btn" onclick="renderImportMap()">← Columns</button><button class="btn p" onclick="importCommit()" ${news+upd?"":"disabled"}>Import ${news+upd} item${news+upd===1?"":"s"}</button></div>`,true); }
async function importCommit(){ const v=_imp.validated||importValidate(); const setStock=fchk("imp_stock"), autoPrice=fchk("imp_price"); let created=0,updated=0,skipped=0,newCats=0,newVend=0; const st=storeSettings(); const cats=categories();
  for(const x of v){ if(x.errors.length){ skipped++; continue; } const g=x.g; const num=k=>{ const s=g(k).replace(/[$,]/g,""); return s===""?"":(+s||0); };
    let cat=g("category"); if(cat){ const near=cats.find(c=>c.name.toLowerCase()===cat.toLowerCase()); if(near) cat=near.name; else { cats.push({name:cat,subs:[]}); newCats++; } } const sub=g("subcategory"); if(cat&&sub){ const c=cats.find(c=>c.name===cat); if(c&&!c.subs.some(s=>s.toLowerCase()===sub.toLowerCase())) c.subs.push(sub); }
    let vendorId=""; const vend=g("vendor"); if(vend){ let vv=S.vendors.find(y=>y.name.toLowerCase()===vend.toLowerCase()); if(!vv){ vv=await save("vendors",{id:uid(),name:vend,contact:"",email:"",phone:"",leadDays:21}); newVend++; } vendorId=vv.id; }
    const p=Object.assign({},x.existing||{id:uid(),reorderAt:1,pieces:1,createdAt:todayISO(),stock:0},{sku:g("sku"),name:g("name")}); if(cat) p.category=cat; if(sub) p.subcategory=(cats.find(c=>c.name===cat)?.subs.find(s=>s.toLowerCase()===sub.toLowerCase()))||sub; for(const k of ["collection","model","vendorSku","color","finish","size","dims","bin","comfort","matType","notes","barcode"]){ if(g(k)!=="") p[k]=g(k); } if(g("photo")!==""){ const u=g("photo"); if(/^https?:\/\//i.test(u)||/^data:image\//i.test(u)) p.photo=u; } if(vendorId) p.vendorId=vendorId; for(const k of ["cost","freight","msrp","map","reorderAt","pieces","warrantyYears","weightLbs"]){ if(g(k)!=="") p[k]=num(k); } if(setStock&&g("stock")!==""){ if(feat("locations")&&locations().length){ if(!x.existing) p.stockBy={}; setStockTotal(p,num("stock")); } else p.stock=num("stock"); }
    normalizeCategory(p); p.landed=landedCost(p); if(g("price")!==""){ p.price=num("price"); p.priceManual=true; } else if(autoPrice&&(!x.existing||!p.priceManual)) p.price=suggestPrice(p); if(p.category==="Mattress"&&p.trial===undefined) p.trial=true;
    await save("products",p); if(x.existing) updated++; else created++; }
  if(newCats){ st.categories=cats; await save("settings",st); } closeModal(); render(); toast(`Imported: ${created} new, ${updated} updated${skipped?", "+skipped+" skipped":""}${newCats?", "+newCats+" categor"+(newCats===1?"y":"ies")+" added":""}${newVend?", "+newVend+" supplier"+(newVend===1?"":"s")+" added":""}`); }
