/* ============================================================
   WAREHOUSE — put-away, storage bins, picking, staging (optional)
   ============================================================ */
let whTab="pick", whDate=todayISO(), whScan="";
function whBins(){ return storeSettings().bins||[]; }
CHIP_LISTS.bins={get:()=>whBins().slice(),set:async l=>{ const st=storeSettings(); st.bins=l; await save("settings",st); }};
CHIP_LISTS.staging={get:()=>(storeSettings().stagingAreas||["Staging A","Staging B","Will-call"]).slice(),set:async l=>{ const st=storeSettings(); st.stagingAreas=l; await save("settings",st); }};
function stagingAreas(){ return storeSettings().stagingAreas||["Staging A","Staging B","Will-call"]; }
function whOrders(date){ const out=[]; for(const d of dlv().filter(d=>d.date===date&&d.status!=="delivered")){ const inv=byId("invoices",d.invoiceId); if(inv) out.push({kind:"delivery",d,inv,lines:itemsOf(d).filter(l=>lineOpen(l)&&!lineBlocked(l)&&!l.haulAway)}); } for(const p of pickups().filter(p=>(p.status==="ready"||p.status==="partready")&&(!p.plannedDate||p.plannedDate<=date))){ const inv=byId("invoices",p.invoiceId); if(inv) out.push({kind:"pickup",d:p,inv,lines:inv.lines.filter(l=>lineOpen(l)&&!lineBlocked(l)&&!l.service)}); } return out.filter(o=>o.lines.length); }
function pickState(o){ const n=o.lines.length, done=o.lines.filter(l=>l.pickedAt).length; return {n,done,all:n&&done===n,staged:!!o.d.staged}; }
async function whPick(invId,lineId,on){ const inv=byId("invoices",invId); const l=inv.lines.find(x=>x.lineId===lineId); if(!l) return; if(on){ l.pickedAt=todayISO(); l.pickedBy=session.staffId; } else { delete l.pickedAt; delete l.pickedBy; } await save("invoices",inv); render(); }
async function whScanCode(code){ code=String(code||"").trim(); if(!code) return; const lc=code.toLowerCase(); for(const o of whOrders(whDate)){ const l=o.lines.find(l=>!l.pickedAt&&String(l.sku||"").toLowerCase()===lc); if(l){ await whPick(o.inv.id,l.lineId,true); toast(`Picked ${l.name} for ${custName(o.inv.customerId)}`); return; } } toast("No unpicked item with that SKU on today's list.",true); }
async function whStage(did,area){ const d=byId("deliveries",did); d.staged=area||stagingAreas()[0]; d.stagedAt=todayISO(); d.stagedBy=session.staffId; await save("deliveries",d); render(); toast("Staged at "+d.staged); }
async function whUnstage(did){ const d=byId("deliveries",did); delete d.staged; delete d.stagedAt; await save("deliveries",d); render(); }
function renderWarehouse(){ const tabs=[["pick","Pick & stage"],["putaway","Put-away"],["bins","Storage bins"],["lookup","Find an item"]]; const body=({pick:renderWhPick,putaway:renderWhPutaway,bins:renderWhBins,lookup:renderWhLookup})[whTab]||renderWhPick; return `<div class="topbar"><h1>Warehouse</h1><span class="muted">Put-away, storage, picking and staging</span></div><div class="sub">${tabs.map(([k,l])=>`<button class="${whTab===k?"on":""}" onclick="whTab='${k}';render()">${l}</button>`).join("")}</div>${body()}`; }
function renderWhPick(){ const orders=whOrders(whDate); const staged=orders.filter(o=>o.d.staged), open=orders.filter(o=>!o.d.staged);
  return `<div class="toolbar"><input type="date" value="${whDate}" onchange="whDate=this.value;render()" style="max-width:160px"><input type="search" id="wh_scan" placeholder="Scan or type a SKU to pick it…" onkeydown="if(event.key==='Enter'){whScanCode(this.value);this.value=''}" style="max-width:300px"><span class="grow muted small">${orders.length} order${orders.length===1?"":"s"} to pull for ${dateFmt(whDate)} · ${staged.length} staged</span><button class="btn" onclick="delDate=whDate;printPickList()">Print pick list</button><button class="btn" onclick="delDate=whDate;labelsForDay()">Labels for the day</button></div>
  ${open.map(o=>{ const s=pickState(o); const c=byId("customers",o.inv.customerId); return `<div class="card" style="margin-bottom:12px"><div class="row" style="margin-bottom:6px"><div><b>${esc(custDisplay(c))}</b> <span class="muted">· ${esc(o.inv.number)} · ${o.kind==="delivery"?`delivery${o.d.winStart?" "+m2t(t2m(o.d.winStart))+"–"+m2t(t2m(o.d.winEnd)):""}${o.d.truckId?" · "+esc(byId("trucks",o.d.truckId)?.name||""):""}`:"customer pickup"+(o.d.plannedDate?" "+dateShort(o.d.plannedDate):"")}</span>${releaseNote(o.d)}</div><span class="fx row" style="gap:8px"><span class="tag ${s.all?"ok":s.done?"warn":""}">${s.done}/${s.n} picked</span>${s.all?`<select id="stg_${o.d.id}" style="width:auto;padding:4px 8px">${optsList(stagingAreas(),stagingAreas()[0])}</select><button class="btn s p" onclick="whStage('${o.d.id}',fv('stg_${o.d.id}'))">Stage</button>`:""}</span></div><div class="tblwrap"><table><thead><tr><th style="width:36px"></th><th>Item</th><th>Location · bin</th><th class="n">Qty · pieces</th><th>Picked</th></tr></thead><tbody>${o.lines.map(l=>{ const p=byId("products",l.productId); return `<tr><td><input type="checkbox" ${l.pickedAt?"checked":""} onchange="whPick('${o.inv.id}','${l.lineId}',this.checked)"></td><td>${esc(l.name)}${l.kit?`<div class="muted small">kit: ${l.kit.map(k=>k.qty+"× "+esc(byId("products",k.productId)?.name||"")).join(", ")}</div>`:""}<div class="muted small">${esc(l.sku||"")}</div></td><td>${l.locationId?esc(locName(l.locationId))+" · ":""}${p?.bin?`<b>${esc(p.bin)}</b>`:'<span class="tag warn">no bin</span>'}</td><td class="n">${l.qty} · ${(l.pieces||1)*l.qty} pc</td><td class="small">${l.pickedAt?`${esc(firstName(staffName(l.pickedBy)))} · ${dateShort(l.pickedAt)}`:""}</td></tr>`}).join("")}</tbody></table></div></div>`}).join("")||`<div class="card empty">Nothing to pick for this date. Scheduled deliveries and ready pickups appear here.</div>`}
  ${staged.length?`<h3 style="margin:16px 0 8px">Staged — ready to load / hand over</h3>${table(staged,[["Customer",o=>`<b>${esc(custDisplay(byId("customers",o.inv.customerId)))}</b><div class="muted small">${esc(o.inv.number)} · ${o.kind}</div>`],["Where",o=>`<b>${esc(o.d.staged)}</b>`],["Pieces",o=>o.lines.reduce((a,l)=>a+(l.pieces||1)*l.qty,0),"n"],["Staged",o=>`${dateShort(o.d.stagedAt)}${o.d.stagedBy?" · "+esc(firstName(staffName(o.d.stagedBy))):""}`],["",o=>`<div class="bgroup"><button class="btn s" onclick="labelsForOrder('${o.inv.id}')">Labels</button><button class="btn s" onclick="whUnstage('${o.d.id}')">Un-stage</button></div>`]],"")}`:""}`; }
function renderWhPutaway(){ const since=addDays(todayISO(),-30); const rows=[]; for(const o of S.purchaseOrders){ if(!o.receivedAt&&!o.receipts) continue; for(const l of o.lines){ if(!(l.received||0)) continue; const p=byId("products",l.productId); if(!p) continue; if(p.bin&&(p.binSetAt||"")>=(o.receivedAt||since)) continue; if(!p.bin||(o.receivedAt||since)>=since) rows.push({o,l,p}); } } const noBin=S.products.filter(p=>!p.isKit&&(p.stock||0)>0&&!p.bin); const seen=new Set(); const list=rows.filter(r=>{ if(seen.has(r.p.id)) return false; seen.add(r.p.id); return true; });
  return `<p class="muted" style="margin:-6px 0 12px">Assign a storage bin to what came in so pickers can find it. Bins you've set up: ${whBins().length?whBins().map(esc).join(", "):"none yet — add them on the Storage bins tab"}.</p><div class="card">${table(list.concat(noBin.filter(p=>!seen.has(p.id)).map(p=>({p}))),[["Item",r=>`<b>${esc(r.p.name)}</b><div class="muted small">${esc(r.p.sku)}${r.o?" · "+esc(r.o.number)+" received "+dateShort(r.o.receivedAt||todayISO()):""}</div>`],["On hand",r=>r.p.stock||0,"n"],["Current bin",r=>r.p.bin?esc(r.p.bin):'<span class="tag warn">none</span>'],["Put away in",r=>`<div class="row" style="flex-wrap:nowrap"><input type="text" list="binlist" id="pa_${r.p.id}" value="${esc(r.p.bin||"")}" placeholder="e.g. A-12" style="max-width:150px"><button class="btn s p fx" onclick="(async()=>{const p=byId('products','${r.p.id}');p.bin=fv('pa_${r.p.id}').trim();p.binSetAt=todayISO();await save('products',p);render();toast('Bin saved')})()">Save</button></div>`]],"Nothing waiting for put-away.")}<datalist id="binlist">${whBins().map(b=>`<option value="${esc(b)}">`).join("")}</datalist></div>`; }
function renderWhBins(){ const bins=whBins(); const byBin={}; for(const p of S.products){ if(p.bin){ (byBin[p.bin]=byBin[p.bin]||[]).push(p); } } const all=[...new Set(bins.concat(Object.keys(byBin)))].sort();
  return `<div class="card" style="margin-bottom:16px"><h2>Storage bins & zones</h2><p class="muted small">Name your racks, aisles and floor spots (A-01, Rack 3, Mezzanine, Floor-East…). Items get a bin during put-away or on the item form.</p>${chipList("bins",bins,{placeholder:"Add a bin or zone…"})}<h3 style="margin:14px 0 6px">Staging areas</h3><p class="muted small">Where picked orders wait to be loaded or handed over.</p>${chipList("staging",stagingAreas(),{placeholder:"Add a staging area…"})}</div><div class="card"><h2>What's in each bin</h2>${table(all.map(b=>({b,items:byBin[b]||[]})),[["Bin",x=>`<b>${esc(x.b)}</b>`],["Items",x=>x.items.map(p=>`${esc(p.name)} <span class="muted">×${p.stock||0}</span>`).join("<br>")||'<span class="muted">empty</span>'],["Units",x=>x.items.reduce((a,p)=>a+(p.stock||0),0),"n"],["Value at cost",x=>money(x.items.reduce((a,p)=>a+(p.stock||0)*landedCost(p),0)),"n"]],"No bins yet.")}</div>`; }
function renderWhLookup(){ const q=whScan.toLowerCase(); const hits=q?S.products.filter(p=>[p.sku,p.name,p.model,p.bin,p.collection].join(" ").toLowerCase().includes(q)).slice(0,30):[]; return `<div class="toolbar"><input type="search" id="q_whScan" placeholder="Scan or type a SKU, name or bin…" value="${esc(whScan)}" oninput="whScan=this.value;render()" style="max-width:360px"></div><div class="card">${q?table(hits,[["Item",p=>`<b>${esc(p.name)}</b><div class="muted small">${esc(p.sku)}${p.model?" · "+esc(p.model):""}</div>`],["Bin",p=>p.bin?`<b>${esc(p.bin)}</b>`:'<span class="tag warn">none</span>'],["Stock",p=>stockLabel(p)],["Committed",p=>{const n=S.invoices.filter(i=>!["void","quote","draft"].includes(i.status)).reduce((a,i)=>a+i.lines.filter(l=>l.productId===p.id&&lineOpen(l)&&!lineBlocked(l)).reduce((x,l)=>x+l.qty,0),0);return n?`${n} on customer orders`:"—"}],["",p=>`<button class="btn s" onclick="labelsForItem('${p.id}',1)">Label</button>`]],"No matches."):`<div class="empty">Type or scan to find where something is.</div>`}</div>`; }
