/* ============================================================
   HOME WIDGETS, GOALS, NOTICES (announcement banner & attention board)
   TRUCK GPS FROM THE CREW PHONE, CREW CLOCK
   ============================================================ */
const HOME_WIDGETS=[["banner","Announcement banner from management"],["notify","Customers to notify (arrivals, ETA changes, ready for pickup)"],["today","Today's sales"],["goal","Monthly goal thermometer"],["compare","This month vs last month & last year"],["kpis","Month KPIs (net sales, margin, deliveries, attention count)"],["delayed","Delayed items — priority"],["attention","Attention board (finance codes, reminders, policy changes)"],["ups","Ups today"],["needs","Needs attention list"],["deliveries","Today's deliveries"],["timeclock","Time clock — who's in"],["notes","Sticky notes for the team"]];
function homeWidgets(){ const st=storeSettings(); const w=st.homeWidgets; const def=["banner","notify","today","goal","compare","kpis","delayed","attention","ups","needs","deliveries","timeclock"]; return Array.isArray(w)&&w.length?w:def; }
function widgetOn(k){ return homeWidgets().includes(k); }
function customizeHome(){ const on=homeWidgets(); modal(`<h2>Customize Home</h2><p class="muted small">Tick the widgets this store wants on the home screen. Applies to everyone in the store.</p>${HOME_WIDGETS.map(([k,l])=>`<label class="chk" style="margin-bottom:6px"><input type="checkbox" class="hw" value="${k}" ${on.includes(k)?"checked":""}> ${esc(l)}</label>`).join("")}<div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{const st=storeSettings();st.homeWidgets=[...document.querySelectorAll('.hw')].filter(x=>x.checked).map(x=>x.value);await save('settings',st);closeModal();render()})()">Save</button></div>`); }
function salesBetween(from,to){ let net=0,n=0; for(const i of S.invoices){ if(!["paid","open","financed","layaway"].includes(i.status)||i.date<from||i.date>to) continue; net+=invTotals(i).taxable; n++; } for(const r of S.returns){ if(r.date>=from&&r.date<=to) net-=r.refundSub; } return {net,n}; }
function goals(){ return Object.assign({monthly:0,staff:{}},storeSettings().goals||{}); }
function goalsModal(){ const gl=goals(); const sellers=S.staff.filter(s=>s.active!==false&&s.role!=="driver"); modal(`<h2>Sales goals</h2><div class="field" style="max-width:260px"><label class="f">Store goal this month ($ net sales)</label><input type="number" id="gl_month" value="${gl.monthly||""}"></div><b class="small">Per salesperson (optional)</b><div class="grid g3" style="margin-top:6px">${sellers.map(s=>`<div class="field"><label class="f">${esc(s.name)}</label><input type="number" id="gl_${s.id}" value="${gl.staff[s.id]||""}"></div>`).join("")}</div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{const st=storeSettings();const g2={monthly:fnum('gl_month'),staff:{}};${sellers.map(s=>`g2.staff['${s.id}']=fnum('gl_${s.id}');`).join("")}st.goals=g2;await save('settings',st);closeModal();render()})()">Save goals</button></div>`); }
function thermo(pct,label,color){ const p=Math.max(0,Math.min(1,pct)); return `<div style="display:flex;align-items:center;gap:10px"><div style="flex:1;height:18px;background:var(--sage2);border-radius:9px;overflow:hidden;position:relative"><div style="width:${(p*100).toFixed(1)}%;height:100%;background:${color||"var(--mint)"};border-radius:9px;transition:width .4s"></div></div><b class="small" style="min-width:44px;text-align:right">${(p*100).toFixed(0)}%</b></div>${label?`<div class="muted small" style="margin-top:3px">${label}</div>`:""}`; }
function widgetToday(){ const t=todayISO(); const s=salesBetween(t,t); const lastWeek=addDays(t,-7); const lw=salesBetween(lastWeek,lastWeek); const diff=lw.net?(s.net-lw.net)/lw.net:null; return `<div class="card"><div class="row" style="margin-bottom:4px"><h2 style="margin:0">Today</h2><span class="fx muted small">${dateFmt(t)}</span></div><div><div style="font-size:30px;font-weight:800;color:var(--ink)">${money(s.net)}</div><div class="muted small">${s.n} ticket${s.n===1?"":"s"}${s.n?" · avg "+money(s.net/s.n):""}${diff!==null?` · <span style="color:${diff>=0?"var(--green)":"var(--red)"}">${diff>=0?"▲":"▼"} ${pct(Math.abs(diff))} vs last ${new Date(t+"T00:00").toLocaleDateString(undefined,{weekday:"long"})}</span>`:""}</div></div></div>`; }
function widgetGoal(){ const t=todayISO(); const m=t.slice(0,7); const gl=goals(); const mtd=salesBetween(m+"-01",t); const d=new Date(t+"T00:00"); const dim=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(); const pace=gl.monthly?gl.monthly*d.getDate()/dim:0; const mine=session&&session.kind==="staff"&&gl.staff[session.staffId]; const myMtd=mine?S.invoices.filter(i=>["paid","open","financed","layaway"].includes(i.status)&&i.date>=m+"-01"&&i.date<=t).reduce((a,i)=>a+invTotals(i).taxable*salesShare(i,session.staffId),0):0;
  return `<div class="card"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Monthly goal</h2>${has("settings")?`<button class="btn s fx" onclick="goalsModal()">Set goals</button>`:""}</div>${gl.monthly?`<div class="small" style="margin-bottom:4px"><b>${money(mtd.net)}</b> of ${money(gl.monthly)} · ${mtd.net>=pace?"ahead of":"behind"} pace by ${money(Math.abs(mtd.net-pace))}</div>${thermo(mtd.net/gl.monthly,`Day ${d.getDate()} of ${dim} · on-pace mark ${money(pace)} · ${money(Math.max(0,gl.monthly-mtd.net))} to go`,mtd.net>=pace?"var(--mint)":"var(--amber)")}`:`<p class="muted small">No goal set yet${has("settings")?" — click Set goals":""}.</p>`}${mine?`<div style="margin-top:10px" class="small"><b>You:</b> ${money(myMtd)} of ${money(mine)}</div>${thermo(myMtd/mine,"",myMtd/mine>=d.getDate()/dim?"var(--mint)":"var(--amber)")}`:""}${(()=>{ const rows=Object.entries(gl.staff).filter(([id,v])=>v>0&&S.staff.find(s=>s.id===id)&&(has("commissions_all")||has("settings"))).map(([id,v])=>{ const mt=S.invoices.filter(i=>["paid","open","financed","layaway"].includes(i.status)&&i.date>=m+"-01"&&i.date<=t).reduce((a,i)=>a+invTotals(i).taxable*salesShare(i,id),0); return `<div class="row small" style="gap:8px;margin-top:6px"><span style="width:90px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(firstName(staffName(id)))}</span><div style="flex:1">${thermo(mt/v,"",mt/v>=d.getDate()/dim?"var(--mint)":"var(--amber)")}</div><span class="muted" style="width:120px;text-align:right">${money(mt)} / ${money(v)}</span></div>`; }); return rows.length?`<div style="margin-top:10px"><b class="small">Team</b>${rows.join("")}</div>`:""; })()}</div>`; }
function widgetCompare(){ const t=todayISO(); const d=new Date(t+"T00:00"); const m=t.slice(0,7); const dom=d.getDate(); const lm=new Date(d.getFullYear(),d.getMonth()-1,1); const lmKey=`${lm.getFullYear()}-${String(lm.getMonth()+1).padStart(2,"0")}`; const lmDays=new Date(lm.getFullYear(),lm.getMonth()+1,0).getDate(); const ly=`${d.getFullYear()-1}-${m.slice(5)}`; const lyDays=new Date(d.getFullYear()-1,d.getMonth()+1,0).getDate();
  const cur=salesBetween(m+"-01",t), last=salesBetween(lmKey+"-01",lmKey+"-"+String(Math.min(dom,lmDays)).padStart(2,"0")), lastFull=salesBetween(lmKey+"-01",lmKey+"-"+lmDays), lyMtd=salesBetween(ly+"-01",ly+"-"+String(Math.min(dom,lyDays)).padStart(2,"0")), lyFull=salesBetween(ly+"-01",ly+"-"+lyDays);
  const bar=(label,v,max,color)=>`<div class="row small" style="gap:8px;margin-top:6px"><span style="width:150px">${label}</span><div style="flex:1;height:14px;background:var(--sage2);border-radius:7px;overflow:hidden"><div style="width:${max?Math.min(100,v/max*100).toFixed(1):0}%;height:100%;background:${color}"></div></div><b style="width:90px;text-align:right">${money(v)}</b></div>`; const max=Math.max(cur.net,last.net,lastFull.net,lyMtd.net,lyFull.net,1); const dlt=(a,b)=>b?`<span style="color:${a>=b?"var(--green)":"var(--red)"}">${a>=b?"▲":"▼"} ${pct(Math.abs((a-b)/b))}</span>`:"";
  return `<div class="card"><h2>Month to date — day ${dom}</h2>${bar("This month",cur.net,max,"var(--teal)")}${bar("Last month, same day",last.net,max,"var(--mint)")}${bar("Same month last year, same day",lyMtd.net,max,"var(--sage3)")}<div class="muted small" style="margin-top:8px">vs last month ${dlt(cur.net,last.net)||"—"} · vs last year ${dlt(cur.net,lyMtd.net)||"—"} · last month finished at ${money(lastFull.net)}${lyFull.net?" · last year's month "+money(lyFull.net):""}</div></div>`; }
/* notices: banner + attention board */
function notices(){ return (S.notices||[]).filter(n=>!n.expires||n.expires>=todayISO()).sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||(b.created||"").localeCompare(a.created||"")); }
function noticeModal(id){ const n=byId("notices",id)||{kind:"note",title:"",body:"",category:"General",pinned:false,expires:""}; modal(`<h2>${id?"Edit":"New"} ${n.kind==="banner"?"announcement":"notice"}</h2><div class="grid g3"><div class="field"><label class="f">Type</label><select id="nt_kind"><option value="note" ${n.kind==="note"?"selected":""}>Attention board notice</option><option value="banner" ${n.kind==="banner"?"selected":""}>Announcement banner (top of Home)</option></select></div><div class="field"><label class="f">Category</label><input type="text" id="nt_cat" value="${esc(n.category||"")}" list="ntcats" placeholder="Finance, Policy, Product…"><datalist id="ntcats">${["Finance","Policy","Product","Delivery","Promotion","General"].map(c=>`<option value="${c}">`).join("")}</datalist></div><div class="field"><label class="f">Show until (optional)</label><input type="date" id="nt_exp" value="${n.expires||""}"></div></div><div class="field"><label class="f">Title</label><input type="text" id="nt_title" value="${esc(n.title)}" placeholder="e.g. New Synchrony trans code for customer payments"></div><div class="field"><label class="f">Details</label><textarea id="nt_body" rows="4">${esc(n.body||"")}</textarea></div><div class="chk"><input type="checkbox" id="nt_pin" ${n.pinned?"checked":""}><label for="nt_pin">Pin to the top</label></div><div class="actions">${id?`<button class="btn d" onclick="confirmDo('Remove this notice?',()=>{remove('notices','${id}');closeModal();render()})">Remove</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="saveNotice('${id||""}')">Save</button></div>`); }
async function saveNotice(id){ const prev=byId("notices",id)||{id:uid(),created:todayISO(),by:session.staffId,readBy:[]}; const n=Object.assign({},prev,{kind:fv("nt_kind"),category:fv("nt_cat").trim()||"General",expires:fv("nt_exp"),title:fv("nt_title").trim(),body:fv("nt_body").trim(),pinned:fchk("nt_pin"),updated:todayISO()}); if(!n.title) return toast("Give it a title.",true); if(!id) n.readBy=[]; await save("notices",n); closeModal(); render(); }
async function ackNotice(id){ const n=byId("notices",id); if(!n) return; n.readBy=[...new Set((n.readBy||[]).concat([session.staffId]))]; await save("notices",n); render(); }
function widgetBanner(){ const list=notices().filter(n=>n.kind==="banner"); if(!list.length) return has("settings")?`<div class="row" style="margin-bottom:10px"><span class="muted small">No announcement — </span><a href="#" class="small" onclick="noticeModal();return false">post one for the team</a></div>`:""; return list.map(n=>{ const read=(n.readBy||[]).includes(session.staffId); return `<div class="notice" style="margin-bottom:10px;border-left:5px solid var(--amber);display:flex;gap:12px;align-items:flex-start"><div style="flex:1"><b>${esc(n.title)}</b>${n.body?`<div class="small" style="margin-top:3px;white-space:pre-wrap">${esc(n.body)}</div>`:""}<div class="muted small" style="margin-top:4px">${esc(firstName(staffName(n.by)))} · ${dateShort(n.created)}${n.expires?" · until "+dateShort(n.expires):""} · seen by ${(n.readBy||[]).length}</div></div><div class="bgroup">${read?'<span class="tag ok">Got it</span>':`<button class="btn s p" onclick="ackNotice('${n.id}')">Got it</button>`}${has("settings")?`<button class="btn s" onclick="noticeModal('${n.id}')">Edit</button>`:""}</div></div>`; }).join(""); }
function damagedAttentionHTML(){ const n=typeof damagedOnHold==="function"?damagedOnHold().length:0; return n?`<div class="row" style="gap:8px;padding:6px 0"><span class="tag bad">${n}</span><span style="flex:1">damaged piece${n===1?"":"s"} on hold — resolve (as-is, repaired, write-off)</span><a href="#" class="small" onclick="go('stock');stockFilter='damaged';render();return false">open</a></div>`:""; }
function widgetAttention(){ const list=notices().filter(n=>n.kind==="note"); return `<div class="card"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Attention board</h2>${has("settings")?`<button class="btn s fx" onclick="noticeModal()">+ Notice</button>`:""}</div>${list.length?list.map(n=>{ const read=(n.readBy||[]).includes(session.staffId); return `<div style="padding:8px 0;border-top:1px solid var(--line)"><div style="display:flex;gap:8px;align-items:flex-start"><div style="flex:1"><span class="tag ${n.pinned?"warn":""}" style="margin-right:6px">${esc(n.category||"General")}</span><b>${esc(n.title)}</b></div><div class="bgroup" style="flex:none">${read?'<span class="tag ok">read</span>':`<button class="btn s" onclick="ackNotice('${n.id}')">Mark read</button>`}${has("settings")?`<button class="btn s" onclick="noticeModal('${n.id}')">Edit</button>`:""}</div></div>${n.body?`<div class="small" style="margin-top:4px;white-space:pre-wrap">${esc(n.body)}</div>`:""}<div class="muted small" style="margin-top:3px">${esc(firstName(staffName(n.by)))} · ${dateShort(n.created)}${n.expires?" · until "+dateShort(n.expires):""} · read by ${(n.readBy||[]).length} of ${S.staff.filter(s=>s.active!==false).length}</div></div>`; }).join(""):`<p class="muted small">Nothing posted. Use this for things everyone must know: new finance trans codes, policy changes, promo rules, delivery reminders.</p>`}</div>`; }
function widgetTimeclock(){ if(!feat("timeclock")) return ""; const openAll=S.timeclock.filter(t=>!t.out); const mine=clockStatus(); return `<div class="card"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Time clock</h2><button class="btn s ${mine?"":"p"} fx" onclick="clockToggle()">${mine?"Clock out":"Clock in"}</button></div>${mine?`<div class="small" style="margin-bottom:6px">You clocked in at ${mine.in.slice(11,16)}</div>`:""}<div class="small">${openAll.length?openAll.map(t=>`<span class="tag ok" style="margin:2px 4px 2px 0">${esc(firstName(staffName(t.staffId)))} · ${t.in.slice(11,16)}</span>`).join(""):'<span class="muted">Nobody clocked in right now.</span>'}</div></div>`; }
function widgetNotes(){ const st=storeSettings(); return `<div class="card"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Team notes</h2></div><textarea rows="4" style="width:100%" placeholder="Shared scratchpad — anything the team should see today" onchange="(async()=>{const st=storeSettings();st.teamNotes=this.value;await save('settings',st)})()">${esc(st.teamNotes||"")}</textarea></div>`; }
function setupChecklist(){ const st=storeSettings(); if(st.setupDismissed||!has("settings")) return ""; const items=[
  ["Store map pin & address",!!(st.lat&&st.address),"setTab='store';go('settings')"],
  ["Tax brackets named (default set)",!!(taxBrackets().length&&taxBrackets()[0].name&&taxBrackets()[0].name!=="Sales tax"),"setTab='tax';go('settings')"],
  ["Suppliers entered",S.vendors.length>0,"go('vendors')"],
  ["Items in inventory (add or upload a CSV)",S.products.length>0,"go('inventory')"],
  ["Trucks & delivery days",S.trucks.length>0&&(st.deliveryDays||[]).length>0,"setTab='delivery';go('settings')"],
  ["Payment methods & finance companies",!!(st.fundingSources&&st.fundingSources.length)||!!(st.lists&&st.lists.tenders),"setTab='payments';go('settings')"],
  ["Staff with PINs",S.staff.filter(s=>s.active!==false).length>1,"setTab='staff';go('settings')"],
  ["Logo & colors",!!st.logo,"setTab='store';go('settings')"],
  ["Terms & conditions reviewed",!!(st.terms&&st.terms.version),"setTab='terms';go('settings')"]];
  const done=items.filter(x=>x[1]).length; if(done===items.length) return ""; return `<div class="card" style="margin-bottom:16px;border-left:5px solid var(--mint)"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Getting started — ${done} of ${items.length} done</h2><button class="btn s fx" onclick="(async()=>{const st=storeSettings();st.setupDismissed=true;await save('settings',st);render()})()">Hide</button></div><div class="grid g3">${items.map(([l,ok,fn])=>`<a href="#" class="small" style="text-decoration:none;color:inherit;display:flex;gap:6px;align-items:center;padding:4px 0" onclick="${fn};return false"><span class="tag ${ok?"ok":"warn"}" style="min-width:20px;text-align:center">${ok?"✓":"·"}</span>${l}</a>`).join("")}</div></div>`; }
function widgetNotify(){ const types=["Special order arrived","Ready for pickup","ETA change — notify","Pickup reminder"]; const list=S.followups.filter(f=>{ if(f.status!=="open"||!types.includes(f.type)) return false; const inv=f.invoiceId?byId("invoices",f.invoiceId):null; if(inv&&!inv.lines.some(lineOpen)){ f.status="done"; f.doneAt=todayISO(); f.outcome="Order completed"; save("followups",f); return false; } return true; }).sort((a,b)=>(a.due||"").localeCompare(b.due||"")).slice(0,8); if(!list.length) return ""; return `<div class="card" style="margin-bottom:16px;border-left:5px solid var(--amber)"><div class="row" style="margin-bottom:6px"><h2 style="margin:0">Customers to notify</h2><span class="fx muted small">${list.length} waiting</span></div>${list.map(f=>{ const c=byId("customers",f.customerId); const txt=followupText(f); return `<div class="row" style="gap:8px;padding:6px 0;border-top:1px solid var(--line)"><div style="flex:1"><b>${esc(c?.name||"")}</b> <span class="muted small">· ${esc(f.type)}</span><div class="small">${esc(f.note)}</div></div><div class="bgroup">${c?.phone?`<a class="btn s p" href="sms:${esc(c.phone)}?&body=${encodeURIComponent(txt)}" onclick="doneFollowup('${f.id}')">Text</a>`:""}${c?.email?`<a class="btn s" href="mailto:${esc(c.email)}?subject=${encodeURIComponent("Update on your order")}&body=${encodeURIComponent(txt)}" onclick="doneFollowup('${f.id}')">Email</a>`:""}<button class="btn s" onclick="doneFollowup('${f.id}')">Done</button></div></div>`; }).join("")}</div>`; }
function homeExtras(){ const top=[]; const row=[]; if(widgetOn("banner")) top.push(widgetBanner()); top.push(setupChecklist()); if(widgetOn("notify")) top.push(widgetNotify()); if(widgetOn("today")) row.push(widgetToday()); if(widgetOn("goal")) row.push(widgetGoal()); if(widgetOn("compare")) row.push(widgetCompare()); const row2=[]; if(widgetOn("attention")) row2.push(widgetAttention()); if(widgetOn("timeclock")) row2.push(widgetTimeclock()); if(widgetOn("notes")) row2.push(widgetNotes()); return {top:top.join(""),row:row.length?`<div class="grid g${Math.min(3,row.length)}" style="margin-bottom:16px">${row.join("")}</div>`:"",row2:row2.filter(Boolean).length?`<div class="grid g${Math.min(2,row2.filter(Boolean).length)}" style="margin-bottom:16px">${row2.filter(Boolean).join("")}</div>`:""}; }
/* ---- truck GPS from the crew phone ---- */
let _geoWatch=null, _geoLast=0;
function shareLocation(on){ const tid=crewTruck; if(on){ if(!tid) return toast("Pick your truck first.",true); if(!navigator.geolocation) return toast("This device has no location service.",true); _geoWatch=navigator.geolocation.watchPosition(async pos=>{ const now=Date.now(); if(now-_geoLast<45000) return; _geoLast=now; const t=byId("trucks",tid); if(!t) return; t.lastPos={lat:pos.coords.latitude,lng:pos.coords.longitude,at:now,by:session.staffId,acc:pos.coords.accuracy||0}; await save("trucks",t); const el=document.getElementById("geo_status"); if(el) el.textContent="Location shared "+new Date(now).toTimeString().slice(0,5); },err=>{ toast("Location not available: "+(err.message||""),true); },{enableHighAccuracy:true,maximumAge:30000}); localStorage.setItem("ht_geo","1"); toast("Sharing this phone's location with the store while the crew view is open"); } else { if(_geoWatch!==null){ navigator.geolocation.clearWatch(_geoWatch); _geoWatch=null; } localStorage.setItem("ht_geo","0"); } render(); }
function truckPosLabel(t){ if(!t||!t.lastPos) return ""; const ago=Math.round((Date.now()-t.lastPos.at)/60000); return `${ago<1?"just now":ago+" min ago"} · ${esc(firstName(staffName(t.lastPos.by)))}`; }
function crewHeaderExtras(){ const sharing=_geoWatch!==null; const t=byId("trucks",crewTruck); return `<div class="row" style="gap:8px;margin:0 0 10px;flex-wrap:wrap">${feat("timeclock")?`<button class="btn ${clockStatus()?"":"p"}" onclick="clockToggle()">${clockStatus()?"Clock out ("+clockStatus().in.slice(11,16)+")":"Clock in"}</button>`:""}<button class="btn ${sharing?"":"s"}" onclick="shareLocation(${sharing?"false":"true"})">${sharing?"📍 Sharing location — stop":"Share truck location"}</button><span class="muted small" id="geo_status">${t&&t.lastPos?"Last shared "+truckPosLabel(t):""}</span></div>`; }
