/* ============================================================
   SECURITY — audit log, function-level permission checks
   ============================================================ */
async function logAudit(type,detail,refs){ try{ if(!tenantId) return; const e={id:uid(),at:Date.now(),date:todayISO(),time:new Date().toTimeString().slice(0,8),type,detail:String(detail||"").slice(0,400),by:session&&session.kind==="staff"?session.staffId:"",support:!!(session&&session.support),adminId:session&&session.adminId||"",device:deviceInfo(),approvedBy:refs&&refs.approvedBy||"",invoiceId:refs&&refs.invoiceId||"",amount:refs&&refs.amount!==undefined?round2(+refs.amount||0):undefined,ref:refs&&refs.ref||""}; await save("audit",e); if(S.audit&&S.audit.length>5000) S.audit.splice(0,S.audit.length-5000); }catch(err){} }
function denied(what){ toast(`Your login isn't allowed to ${what}. Ask a manager.`,true); logAudit("denied",what); return false; }
function requirePerm(key,what){ if(has(key)) return true; return denied(what); }
const AUDIT_TYPES={sale:"Sale completed",void:"Invoice voided",return:"Return / refund",payment:"Payment recorded",override:"Manager approval used",release:"Goods released with a balance",discount:"Discount over limit",price:"Price changed on a line",stock:"Stock adjusted",count:"Stock count applied",credit:"Store credit changed",customer_credit:"Customer credit edited",settings:"Settings changed",staff:"Staff / permissions changed",receive:"Shipment received",po_cancel:"PO cancelled",deposit_waived:"Deposit waived",takes_now:"Out-of-stock item taken at sale",denied:"Blocked — no permission",negative_line:"Negative charge on a sale",floor_markdown:"Floor-sample markdown applied",timeclock_edit:"Time clock edited",login_fail:"Wrong PIN attempts"};
let auditFrom=addDays(todayISO(),-30), auditTo=todayISO(), auditType="", auditWho="";
function renderAudit(){ if(!has("audit")) return `<div class="card empty">The audit log is for managers.</div>`; const rows=(S.audit||[]).filter(e=>e.date>=auditFrom&&e.date<=auditTo&&(!auditType||e.type===auditType)&&(!auditWho||e.by===auditWho)).sort((a,b)=>b.at-a.at).slice(0,500); const counts={}; (S.audit||[]).filter(e=>e.date>=auditFrom&&e.date<=auditTo).forEach(e=>counts[e.type]=(counts[e.type]||0)+1);
  return `<div class="toolbar"><input type="date" value="${auditFrom}" onchange="auditFrom=this.value;render()" style="max-width:150px"><input type="date" value="${auditTo}" onchange="auditTo=this.value;render()" style="max-width:150px"><select onchange="auditType=this.value;render()" style="max-width:260px"><option value="">All events</option>${Object.entries(AUDIT_TYPES).map(([k,l])=>`<option value="${k}" ${auditType===k?"selected":""}>${esc(l)}${counts[k]?" ("+counts[k]+")":""}</option>`).join("")}</select><select onchange="auditWho=this.value;render()" style="max-width:200px"><option value="">Everyone</option>${S.staff.map(s=>`<option value="${s.id}" ${auditWho===s.id?"selected":""}>${esc(s.name)}</option>`).join("")}</select><span class="grow"></span><button class="btn" onclick="exportAudit()">Export CSV</button></div>
  <div class="grid g4" style="margin-bottom:12px">${[["void","Voids"],["return","Returns / refunds"],["override","Manager approvals"],["denied","Blocked attempts"]].map(([k,l])=>`<div class="card stat ${k==="denied"?"r":k==="override"?"a":""}"><div class="v">${counts[k]||0}</div><div class="l">${l}</div></div>`).join("")}</div>
  <div class="card">${table(rows,[["When",e=>`${dateShort(e.date)} ${e.time}`],["Event",e=>`<span class="tag ${["void","return","denied","negative_line","deposit_waived","takes_now"].includes(e.type)?"bad":["override","release","discount","price","stock","credit","customer_credit","floor_markdown"].includes(e.type)?"warn":""}">${esc(AUDIT_TYPES[e.type]||e.type)}</span>`],["Who",e=>esc(e.support?"Support (admin)":staffName(e.by))+(e.approvedBy?`<div class="muted small">approved by ${esc(staffName(e.approvedBy))}</div>`:"")],["Device",e=>e.device?`${esc(e.device.name||e.device.id)}<div class="muted small">${esc(e.device.browser)} / ${esc(e.device.os)}</div>`:""],["Details",e=>`${esc(e.detail)}${e.invoiceId?` <a href="#" onclick="openInvoice('${e.invoiceId}');return false">${esc(byId("invoices",e.invoiceId)?.number||"")}</a>`:""}`],["Amount",e=>e.amount!==undefined?money(e.amount):"","n"]],"Nothing logged in this range.")}</div>`; }
function exportAudit(){ const rows=(S.audit||[]).filter(e=>e.date>=auditFrom&&e.date<=auditTo).sort((a,b)=>b.at-a.at); saveFile(`audit-${auditFrom}-to-${auditTo}.csv`,["Date,Time,Event,Who,Approved by,Details,Invoice,Amount"].concat(rows.map(e=>[e.date,e.time,AUDIT_TYPES[e.type]||e.type,e.support?"Support":staffName(e.by),e.approvedBy?staffName(e.approvedBy):"",e.detail,byId("invoices",e.invoiceId)?.number||"",e.amount!==undefined?e.amount.toFixed(2):""].map(x=>`"${String(x).replace(/"/g,'""')}"`).join(","))).join("\n")); }
/* guarded wrappers */
function guardedReceive(id){ if(!requirePerm("receive","receive shipments")) return; receiveModal(id); }
/* ---- device identity ---- */
function deviceInfo(){ let id=""; try{ id=localStorage.getItem("ht_device_id"); if(!id){ id=uid()+uid(); localStorage.setItem("ht_device_id",id); } }catch(e){ id="nolocal"; } let name=""; try{ name=localStorage.getItem("ht_device_name")||""; }catch(e){} const nav=typeof navigator!=="undefined"?navigator:{}; const ua=nav.userAgent||""; let brand=""; try{ brand=(nav.userAgentData&&nav.userAgentData.brands&&nav.userAgentData.brands.map(b=>b.brand).filter(b=>!/Not|Brand/.test(b)).join(" "))||""; }catch(e){} if(!brand) brand=/Edg\//.test(ua)?"Edge":/Chrome\//.test(ua)?"Chrome":/Safari\//.test(ua)?"Safari":/Firefox\//.test(ua)?"Firefox":"Browser"; const os=(nav.userAgentData&&nav.userAgentData.platform)||(/iPhone|iPad/.test(ua)?"iOS":/Android/.test(ua)?"Android":/Windows/.test(ua)?"Windows":/Mac/.test(ua)?"macOS":/Linux/.test(ua)?"Linux":""); let scr=""; try{ scr=(typeof screen!=="undefined"&&screen.width)?screen.width+"×"+screen.height:""; }catch(e){} let tz=""; try{ tz=Intl.DateTimeFormat().resolvedOptions().timeZone||""; }catch(e){} return {id:String(id).slice(0,12),name,browser:brand,os,screen:scr,tz}; }
function nameThisDevice(){ const cur0=deviceInfo(); modal(`<h2>Name this device</h2><p class="muted">Shows in the audit log next to everything done from this register, tablet or phone.</p><div class="field"><label class="f">Device name</label><input type="text" id="dv_name" value="${esc(cur0.name)}" placeholder="Front counter iPad, Office PC, Truck 1 phone…"></div><p class="muted small">Device id ${esc(cur0.id)} · ${esc(cur0.browser)} on ${esc(cur0.os)} · ${esc(cur0.screen)}</p><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(function(){try{localStorage.setItem('ht_device_name',fv('dv_name').trim())}catch(e){}closeModal();toast('Device named');render()})()">Save</button></div>`); }
/* ---- record-level change tracking ---- */
const DIFF_FIELDS={settings:null,staff:["name","role","pin","active","rate","planRate","perms","limits"],products:["name","sku","cost","price","priceManual","floorSample","vendorId","category","bin","map","msrp"],customers:["name","first","last","company","phone","email","address","credit","taxExempt","taxRate","taxId","referral"],invoices:["status","salesId","splits","discount","payments","taxRate","taxExempt","fundingId","approvals","signature","deliveryFee"],purchaseOrders:["status","expected","lines","bill","ack","confirmation"],deliveries:["status","date","truckId","releaseOverride","staged","lineIds"],trucks:["name","capacity","crew"],vendors:["name","costRules","multiplier","freightPct","extraPct","surcharge"]};
const DIFF_SKIP=new Set(["logo","photo","photos","signature","idPhoto","lastPos","teamNotes","batches","streets","_migrated","updated","at","lastActivity"]);
function summarize(v){ if(v===undefined||v===null||v==="") return "—"; if(typeof v==="number") return String(Math.round(v*100)/100); if(typeof v==="boolean") return v?"yes":"no"; if(typeof v==="string") return v.length>40?v.slice(0,37)+"…":v; if(Array.isArray(v)) return v.length+" item"+(v.length===1?"":"s")+(v.length&&typeof v[0]==="object"&&v[0]&&v[0].amount!==undefined?" · $"+Math.round(v.reduce((a,x)=>a+(+x.amount||0),0)*100)/100:""); if(typeof v==="object") return Object.keys(v).length+" fields"; return String(v); }
function changeLog(coll,prev,doc){ try{ if(!prev||coll==="audit"||window._silentAudit) return; const fields=DIFF_FIELDS[coll]; if(fields===undefined) return; const keys=fields||[...new Set(Object.keys(prev).concat(Object.keys(doc)))].filter(k=>!DIFF_SKIP.has(k)&&!k.startsWith("_")&&!/^next[A-Z]/.test(k)); const changes=[]; for(const k of keys){ const a=prev[k], b=doc[k]; if(k==="pin"){ if(String(a||"")!==String(b||"")) changes.push("PIN changed"); continue; } const sa=JSON.stringify(a===undefined?null:a), sb=JSON.stringify(b===undefined?null:b); if(sa!==sb){ if(typeof a==="object"&&a&&typeof b==="object"&&b&&!Array.isArray(a)){ const sub=[...new Set(Object.keys(a).concat(Object.keys(b)))].filter(x=>JSON.stringify(a[x])!==JSON.stringify(b[x])&&!DIFF_SKIP.has(x)).slice(0,8); if(sub.length) changes.push(k+" ("+sub.join(", ")+")"); } else changes.push(`${k} ${summarize(a)} → ${summarize(b)}`); } if(changes.length>=10){ changes.push("…"); break; } } if(!changes.length) return; if(coll==="invoices"&&["draft","quote"].includes(prev.status)) return; const label=coll==="settings"?"Store settings":(doc.name||doc.number||doc.sku||doc.id); logAudit("edit",`${coll}: ${label} — ${changes.join("; ")}`,{invoiceId:coll==="invoices"?doc.id:""}); }catch(e){} }
AUDIT_TYPES.edit="Record changed"; AUDIT_TYPES.sign_request="Remote signature"; AUDIT_TYPES.print="Document printed"; AUDIT_TYPES.vendor_stock="Vendor stock checked"; AUDIT_TYPES.print_labels="Labels printed"; AUDIT_TYPES.training="Training mode";
/* ---- admin: audit across all dealers ---- */
let gaFrom=addDays(todayISO(),-14), gaTo=todayISO(), gaDealer="", gaType="", gaQ="", gaRows=null, gaLoading=false;
async function loadGlobalAudit(){ gaLoading=true; render(); const rows=[]; for(const t of platform.tenants){ let list=[]; try{ if(tenantId===t.id&&S.audit) list=S.audit; else if(db){ list=await readCollection(`tenants/${t.id}/audit`); } else { const ls=localStorage.getItem("ht_tenant:"+t.id); if(ls){ const o=JSON.parse(ls); list=o.audit||[]; } } }catch(e){} for(const e of list) rows.push(Object.assign({tenant:t},e)); } gaRows=rows.sort((a,b)=>(b.at||0)-(a.at||0)); gaLoading=false; render(); }
function staffNameIn(tenant,id){ try{ if(!id) return ""; if(tenantId===tenant.id) return staffName(id); const ls=localStorage.getItem("ht_tenant:"+tenant.id); if(ls){ const o=JSON.parse(ls); const s=(o.staff||[]).find(x=>x.id===id); if(s) return s.name; } }catch(e){} return id; }
function renderGlobalAudit(){ if(gaRows===null&&!gaLoading){ setTimeout(loadGlobalAudit,10); return `<div class="card empty">Loading audit logs from every dealer…</div>`; } if(gaLoading) return `<div class="card empty">Loading audit logs from every dealer…</div>`; const q=gaQ.toLowerCase(); const rows=gaRows.filter(e=>e.date>=gaFrom&&e.date<=gaTo&&(!gaDealer||e.tenant.id===gaDealer)&&(!gaType||e.type===gaType)&&(!q||[e.detail,staffNameIn(e.tenant,e.by),e.device&&e.device.name,e.device&&e.device.id,e.tenant.name].join(" ").toLowerCase().includes(q))).slice(0,800);
  return `<div class="topbar"><h1>Audit — all dealers</h1><span class="muted">Every logged action with date, time, user, device and dealer</span></div><div class="toolbar"><select onchange="gaDealer=this.value;render()" style="max-width:220px"><option value="">All dealers</option>${platform.tenants.map(t=>`<option value="${t.id}" ${gaDealer===t.id?"selected":""}>${esc(t.name)}</option>`).join("")}</select><input type="date" value="${gaFrom}" onchange="gaFrom=this.value;render()" style="max-width:150px"><input type="date" value="${gaTo}" onchange="gaTo=this.value;render()" style="max-width:150px"><select onchange="gaType=this.value;render()" style="max-width:220px"><option value="">All events</option>${Object.entries(AUDIT_TYPES).map(([k,l])=>`<option value="${k}" ${gaType===k?"selected":""}>${esc(l)}</option>`).join("")}</select><input type="search" id="q_gaQ" placeholder="Search user, device, details…" value="${esc(gaQ)}" oninput="gaQ=this.value;render()" style="max-width:240px"><span class="grow"></span><button class="btn" onclick="gaRows=null;render()">Refresh</button><button class="btn" onclick="exportGlobalAudit()">Export CSV</button></div>
  <p class="muted small">IP addresses aren't available to a page hosted here (they need a server). Each register, tablet and phone carries a device id and a name set on the device (account menu → Name this device), plus browser, OS and screen size, so you can tell which machine did what.</p>
  <div class="card">${table(rows,[["When",e=>`${dateShort(e.date)} ${e.time}<div class="muted small">${e.device&&e.device.tz?esc(e.device.tz):""}</div>`],["Dealer",e=>esc(e.tenant.name)],["Event",e=>`<span class="tag ${["void","return","denied","negative_line","deposit_waived","takes_now"].includes(e.type)?"bad":["override","release","discount","price","stock","credit","customer_credit","floor_markdown","edit","settings","staff"].includes(e.type)?"warn":""}">${esc(AUDIT_TYPES[e.type]||e.type)}</span>`],["User",e=>`${esc(e.support?"Support (administrator)":staffNameIn(e.tenant,e.by))}${e.approvedBy?`<div class="muted small">approved by ${esc(staffNameIn(e.tenant,e.approvedBy))}</div>`:""}`],["Device",e=>e.device?`<b>${esc(e.device.name||"unnamed")}</b><div class="muted small">${esc(e.device.id)} · ${esc(e.device.browser)} / ${esc(e.device.os)}${e.device.screen?" · "+esc(e.device.screen):""}</div>`:'<span class="muted">—</span>'],["Details",e=>esc(e.detail)],["Amount",e=>e.amount!==undefined?money(e.amount):"","n"]],"Nothing in this range.")}</div>`; }
function exportGlobalAudit(){ const rows=(gaRows||[]).filter(e=>e.date>=gaFrom&&e.date<=gaTo&&(!gaDealer||e.tenant.id===gaDealer)); saveFile(`audit-all-dealers-${gaFrom}-to-${gaTo}.csv`,["Date,Time,Timezone,Dealer,Event,User,Approved by,Device name,Device id,Browser,OS,Screen,Details,Amount"].concat(rows.map(e=>[e.date,e.time,e.device&&e.device.tz||"",e.tenant.name,AUDIT_TYPES[e.type]||e.type,e.support?"Support (administrator)":staffNameIn(e.tenant,e.by),e.approvedBy?staffNameIn(e.tenant,e.approvedBy):"",e.device&&e.device.name||"",e.device&&e.device.id||"",e.device&&e.device.browser||"",e.device&&e.device.os||"",e.device&&e.device.screen||"",e.detail,e.amount!==undefined?e.amount.toFixed(2):""].map(x=>`"${String(x).replace(/"/g,'""')}"`).join(","))).join("\n")); }
