/* ============================================================
   TRAINING MODE — a sandbox copy of the store for practice
   ============================================================ */
let trainingMode=false;
const isTrainingId=id=>/^tr_/.test(String(id||""));
function trainingTenantFor(realId){ const real=platform.tenants.find(t=>t.id===realId); return {id:"tr_"+realId,name:"Training — "+(real?real.name:"store"),code:"TRAIN",training:true,realId}; }
async function openTraining(){ if(!session||session.kind!=="staff") return; if(!has("pos")) return denied("use training mode"); const realId=tenantId; const staffId=session.staffId; const me0=me(); const realSettings=clone(storeSettings()); const realStaff=clone(S.staff); const realVendors=clone(S.vendors); const realProducts=clone(S.products); const realTrucks=clone(S.trucks); const realLocs=clone(S.locations||[]); const tr=trainingTenantFor(realId); let existing=null; try{ existing=localStorage.getItem("ht_tenant:"+tr.id); }catch(e){}
  trainingMode=true; window._trainingReturn={realId,staffId}; try{ localStorage.setItem("ht_training_return",JSON.stringify(window._trainingReturn)); }catch(e){}
  if(!platform.tenants.some(t=>t.id===tr.id)) platform.tenants=platform.tenants.concat([tr]);
  if(existing){ loadTenantLocal(tr.id); if(!S.staff.some(s=>s.id===staffId)&&me0){ S.staff.push(clone(me0)); } }
  else { tenantId=tr.id; COLLS.forEach(c=>S[c]=[]); S.settings=[Object.assign({},realSettings,{id:"store",name:"Training — "+realSettings.name,setupDismissed:true,training:true,trainingStart:Date.now(),trainingStartDate:todayISO()})]; S.staff=realStaff.length?realStaff:[]; if(me0&&!S.staff.some(s=>s.id===me0.id)) S.staff.push(clone(me0)); S.vendors=realVendors; S.products=realProducts.map(p=>Object.assign({},p,{stock:p.stock&&p.stock>0?p.stock:3})); S.trucks=realTrucks; S.locations=realLocs; saveLocal(); if(!S.products.length||!S.customers.length){ try{ await loadSample(true); }catch(e){} } }
  setSession({kind:"staff",tenantId:tr.id,staffId,at:Date.now(),training:true}); view="dashboard"; render(); toast("Training mode — practice freely, nothing here is real"); logAudit("training","Entered training mode"); }
async function resetTraining(){ if(!trainingMode) return; if(!confirm("Reset the training store to fresh sample data? Everyone's practice work here is erased.")) return; const tr=tenantId; const staffId=session.staffId; const keepStaff=clone(S.staff); const keepSettings=clone(storeSettings()); try{ localStorage.removeItem("ht_tenant:"+tr); }catch(e){} COLLS.forEach(c=>S[c]=[]); keepSettings.trainingStart=Date.now(); keepSettings.trainingStartDate=todayISO(); S.settings=[keepSettings]; S.staff=keepStaff; saveLocal(); try{ await loadSample(true); }catch(e){} setSession({kind:"staff",tenantId:tr,staffId,at:Date.now(),training:true}); view="dashboard"; render(); toast("Training store reset"); }
function exitTraining(){ const ret=window._trainingReturn||(()=>{ try{ return JSON.parse(localStorage.getItem("ht_training_return")||"null"); }catch(e){ return null; } })(); trainingMode=false; try{ localStorage.removeItem("ht_training_return"); }catch(e){} platform.tenants=platform.tenants.filter(t=>!t.training); setSession(null); cur=null; if(ret&&ret.realId){ try{ localStorage.setItem("ht_last_code",(platform.tenants.find(t=>t.id===ret.realId)||{}).code||""); }catch(e){} } location.reload(); }
function trainingBanner(){ if(!trainingMode) return ""; return `<div id="training-banner" style="position:sticky;top:0;z-index:60;background:#7A3E9D;color:#fff;padding:8px 14px;font-size:14px;display:flex;gap:12px;align-items:center;flex-wrap:wrap"><b>🎓 TRAINING MODE</b><span>Practice freely — nothing here is real, prints are watermarked, no reports or customers are affected.</span><span style="flex:1"></span><button class="btn s" style="background:#fff;color:#7A3E9D;border-color:#fff" onclick="trainingTasks()">Practice tasks</button><button class="btn s" style="background:transparent;color:#fff;border-color:#fff" onclick="resetTraining()">Reset</button><button class="btn s" style="background:transparent;color:#fff;border-color:#fff" onclick="exitTraining()">Exit training</button></div>`; }
/* practice tasks — detected from the data the trainee actually creates */
const tStart=()=>+(storeSettings().trainingStart||0), tDate=()=>storeSettings().trainingStartDate||"0000-00-00";
const TRAINING_TASKS=[
 {id:"customer",title:"Add a new customer",how:"Customers → Add customer. Fill first/last name, phone, address and how they heard about us.",done:(me)=>S.customers.some(c=>c.createdBy===me)},
 {id:"sale_now",title:"Ring a sale the customer takes today",how:"New sale → pick a customer → add an in-stock item → Fulfillment: Customer takes it today → Cash → Complete.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&i.fulfillment==="now"&&i.status!=="void")},
 {id:"sale_delivery",title:"Ring a sale with home delivery",how:"Same, but choose Home delivery and pick the delivery method.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&i.delivery)},
 {id:"card",title:"Take a card payment (last 4 digits)",how:"On a sale choose Card → Add → enter the last 4 and record.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&(i.payments||[]).some(p=>p.card&&p.card.last4))},
 {id:"plan",title:"Add a protection plan",how:"Use the Protection plan chip under the item search.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&i.lines.some(l=>l.plan))},
 {id:"lease",title:"Sell with lease-to-own and enter the approved amount",how:"Payment terms → Lease-to-own → pick the company → type the approved amount → assign items.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&i.lines.some(l=>l.fundingId)&&i.approvals&&Object.keys(i.approvals).length)},
 {id:"special",title:"Sell an item that must be ordered from the supplier",how:"Add an item with 0 stock — it shows 'order from supplier'. Complete with a deposit.",done:(me)=>S.invoices.some(i=>i.completedBy===me&&(i.completedAt||0)>=tStart()&&i.lines.some(l=>l.special))},
 {id:"po",title:"Create the purchase order and mark it ordered",how:"Purchasing → Needs ordering → Create POs → open the PO → Mark as ordered.",done:(me)=>S.purchaseOrders.some(o=>o.orderedBy===me&&(o.orderedAt||"")>=tDate())},
 {id:"receive",title:"Receive the shipment",how:"Open the PO → Receive items… → tick what arrived → Receive.",done:(me)=>S.purchaseOrders.some(o=>(o.receipts||[]).some(r=>r.by===me&&r.date>=tDate()))},
 {id:"schedule",title:"Schedule a delivery and choose the items on the trip",how:"Deliveries → To schedule → Schedule → date, window, truck → Save.",done:(me)=>S.deliveries.some(d=>d.date&&d.truckId&&d.scheduledBy===me)},
 {id:"complete_stop",title:"Complete a delivery stop with a signature",how:"Crew → open the day → Complete stop → tick items, sign, Mark delivered.",done:(me)=>S.deliveries.some(d=>d.status==="delivered"&&d.deliveredBy===me&&d.signature&&(d.deliveredAt||"")>=tDate())},
 {id:"pickup",title:"Complete a customer pickup",how:"Deliveries → Pickups → Pick up → checklist → sign → done.",done:(me)=>S.deliveries.some(d=>d.kind==="pickup"&&d.status==="pickedup"&&(d.pickedUpStaff===me||(d.pickups||[]).some(r=>r.staff===me)))},
 {id:"return",title:"Process a return or exchange",how:"Invoices → open a paid invoice → More → Return / exchange.",done:(me)=>S.returns.some(r=>r.by===me&&r.date>=tDate())},
 {id:"quote",title:"Save a quote and reopen it",how:"Build a sale → Save quote; later Invoices → Quotes → Open in register.",done:(me)=>S.invoices.some(i=>i.status==="quote"&&i.quotedBy===me&&i.date>=tDate())},
 {id:"labels",title:"Print labels for an order",how:"Invoices → open an order → More → Print labels.",done:(me)=>(S.audit||[]).some(e=>e.type==="print_labels"&&e.by===me&&(e.at||0)>=tStart())}];
function trainingTasks(){ const me0=session.staffId; const done=TRAINING_TASKS.filter(t=>{ try{ return t.done(me0); }catch(e){ return false; } }).length; modal(`<h2>Practice tasks — ${done} of ${TRAINING_TASKS.length} done</h2><p class="muted">Work through these in the training store. They tick off automatically when you've actually done them (as ${esc(me().name)}).</p><div style="max-height:420px;overflow:auto">${TRAINING_TASKS.map((t,i)=>{ let ok=false; try{ ok=t.done(me0); }catch(e){} return `<div style="display:flex;gap:10px;padding:8px 0;border-top:1px solid var(--line);align-items:flex-start"><span class="tag ${ok?"ok":""}" style="min-width:26px;text-align:center">${ok?"✓":i+1}</span><div><b>${esc(t.title)}</b><div class="muted small">${esc(t.how)}</div></div></div>`; }).join("")}</div><div class="actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn p" onclick="closeModal();printTrainingCard()">Print progress</button></div>`,true); }
function printTrainingCard(){ const me0=session.staffId; printHTML(`<div class="page"><h1>Training progress — ${esc(me().name)}</h1><p>${esc(storeSettings().name)} · ${dateFmt(todayISO())}</p><table class="ptable"><tr><th></th><th>Task</th></tr>${TRAINING_TASKS.map(t=>{ let ok=false; try{ ok=t.done(me0); }catch(e){} return `<tr><td>${ok?"✓":"☐"}</td><td>${esc(t.title)}</td></tr>`; }).join("")}</table></div>`,"Training progress"); }
