/* ============================================================
   LANGUAGES — per-person preference, store default, live toggle
   ============================================================ */
const LANGS={en:"English",es:"Español"};
const DICT={es:{
 // navigation & sections
 "Home":"Inicio","New sale":"Nueva venta","Catalog":"Catálogo","To fulfill":"Por entregar","Invoices":"Facturas","Customers":"Clientes","Deliveries":"Entregas","Crew":"Equipo de reparto","Warehouse":"Bodega","Inventory":"Inventario","Purchase orders":"Órdenes de compra","Service":"Servicio","Reports":"Reportes","Settings":"Configuración","Sell":"Vender","Operate":"Operar","Manage":"Administrar","Administration":"Administración","Console":"Consola","Dealers":"Concesionarios",
 // sign-in
 "Tap your name to sign in":"Toque su nombre para iniciar sesión","Enter your PIN":"Ingrese su PIN","Sign in":"Iniciar sesión","Wrong PIN":"PIN incorrecto","Change store":"Cambiar tienda","Store code":"Código de tienda","Connecting to your store…":"Conectando con su tienda…","Software administrator":"Administrador del software",
 // register
 "Customer":"Cliente","Salesperson":"Vendedor","Date":"Fecha","Add item — type SKU, name or size; scan; or press Enter":"Agregar artículo — escriba SKU, nombre o tamaño; escanee; o presione Enter","Search inventory…":"Buscar en inventario…","Add a charge":"Agregar cargo","Add package":"Agregar paquete","Suggested:":"Sugerido:","Items":"Artículos","Tick items to bundle them into one package price":"Marque artículos para agruparlos en un solo precio de paquete","Group as package":"Agrupar como paquete","Subtotal":"Subtotal","Discount":"Descuento","set %":"fijar %","Fulfillment":"Entrega","Method":"Método","Delivery fee":"Costo de entrega","Delivery paid by":"Entrega pagada por","Tax":"Impuesto","Total":"Total","Payment terms":"Condiciones de pago","Pay now":"Pagar ahora","Financing":"Financiamiento","Lease-to-own":"Arrendamiento con opción a compra","Layaway":"Apartado","Payment now":"Pago ahora","Add":"Agregar","Notes on invoice":"Notas en la factura","Complete sale":"Completar venta","Preview":"Vista previa","Save quote":"Guardar cotización","Scan":"Escanear","Clear":"Limpiar","New":"Nuevo","+ New":"+ Nuevo","Split":"Dividir","in stock":"en existencia","order instead":"pedir al proveedor","order from supplier":"pedir al proveedor","customer takes it now":"el cliente se lo lleva ahora","change to in stock":"cambiar a en existencia","Takes today":"Se lo lleva hoy","Takes today ✓":"Se lo lleva hoy ✓","Floor sample":"Muestra de piso","As-is":"Tal como está","Customer pays":"Paga el cliente","Choose… (required)":"Elegir… (obligatorio)","Choose…":"Elegir…","Customer takes it today":"El cliente se lo lleva hoy","Hold for pickup later":"Guardar para recoger después","Home delivery":"Entrega a domicilio","Walk-in":"Sin registro","Card":"Tarjeta","Cash":"Efectivo","Check":"Cheque","Gift card":"Tarjeta de regalo","Store credit":"Crédito de tienda","Protection plan":"Plan de protección","Card: Add opens the card panel (last 4 digits, card type, ID check).":"Tarjeta: Agregar abre el panel de tarjeta (últimos 4 dígitos, tipo, verificación de ID).","Required before completing: customer (name, phone, address) · fulfillment":"Requerido antes de completar: cliente (nombre, teléfono, dirección) · entrega",
 // card panel
 "Card payment — manual":"Pago con tarjeta — manual","Card payment":"Pago con tarjeta","Amount":"Monto","Card type":"Tipo de tarjeta","Last 4 digits of the card":"Últimos 4 dígitos de la tarjeta","Name on card":"Nombre en la tarjeta","Entry":"Forma de captura","Record card payment":"Registrar pago con tarjeta","Name on card matches the invoice and photo ID was checked":"El nombre en la tarjeta coincide con la factura y se verificó la identificación","Run the card on your card machine, then enter the last 4 digits from the receipt.":"Pase la tarjeta en su terminal y luego ingrese los últimos 4 dígitos del recibo.",
 // common buttons
 "Close":"Cerrar","Save":"Guardar","Cancel":"Cancelar","Print":"Imprimir","Sign":"Firmar","Signed ✓":"Firmado ✓","More":"Más","Labels":"Etiquetas","Edit":"Editar","Delete":"Eliminar","Remove":"Quitar","Open":"Abrir","Back":"Atrás","Next":"Siguiente","Done":"Listo","Apply":"Aplicar","Search":"Buscar","Refresh":"Actualizar","Export CSV":"Exportar CSV","Email":"Correo","Text":"Mensaje","Call":"Llamar","Schedule":"Programar","Receive":"Recibir","Receive a shipment":"Recibir un envío","📦 Receive a shipment":"📦 Recibir un envío","New purchase order":"Nueva orden de compra","Reorder suggestions":"Sugerencias de reposición","Mark as ordered":"Marcar como pedido","Receive items…":"Recibir artículos…","Vendor acknowledged…":"Proveedor confirmó…","Customize":"Personalizar","Set goals":"Fijar metas","Got it":"Enterado","Mark read":"Marcar leído","Hide":"Ocultar","Add customer":"Agregar cliente","Add item":"Agregar artículo","Add staff":"Agregar empleado","Optimize routes":"Optimizar rutas","Log an up":"Registrar visita","Pick up":"Entregar al cliente","Pick up what's in":"Entregar lo que llegó","Text ready":"Avisar: listo","Update ETA":"Actualizar fecha","Set ETA":"Fijar fecha","Load sample data":"Cargar datos de ejemplo",
 // crew
 "Navigate to customer":"Ir al cliente","Call customer":"Llamar al cliente","Text customer: on our way":"Mensaje al cliente: vamos en camino","Arrived — let the store know":"Llegamos — avisar a la tienda","Complete stop — customer signs":"Completar parada — el cliente firma","Can't deliver — send back to store":"No se pudo entregar — devolver a la tienda","Navigate route":"Navegar ruta","Clock in":"Registrar entrada","Clock out":"Registrar salida","Share truck location":"Compartir ubicación del camión","All trucks":"Todos los camiones","Complete stop":"Completar parada","Mark delivered":"Marcar entregado","Proof of delivery photos (up to 4 — placement in the room, doorstep, packaging)":"Fotos de prueba de entrega (hasta 4 — ubicación, entrada, empaque)","How did the delivery go? (hand the phone or tablet to the customer)":"¿Cómo estuvo la entrega? (entregue la tableta al cliente)","Any remarks from the customer (optional)":"Comentarios del cliente (opcional)","Customer signature — receipt of goods":"Firma del cliente — recibo de mercancía","Received by":"Recibido por","General notes":"Notas generales","Damage / issue with this item":"Daño / problema con este artículo",
 // account menu
 "Lock register / switch user":"Bloquear caja / cambiar usuario","Lock console":"Bloquear consola","Toggle dark mode":"Modo oscuro","Name this device":"Nombrar este dispositivo","🎓 Training mode":"🎓 Modo de práctica","Exit training":"Salir de práctica","Practice tasks":"Tareas de práctica","Reset":"Reiniciar","Back to admin console":"Volver a la consola","Language":"Idioma",
 // headings & tabs
 "Orders to fulfill":"Órdenes por entregar","Open — grouped":"Abiertas — agrupadas","ETA due":"Fecha próxima","Awaiting stock":"Esperando mercancía","Part delivered":"Entrega parcial","Part picked up":"Recogida parcial","Ready for pickup":"Listo para recoger","Part ready":"Parcialmente listo","To schedule":"Por programar","Scheduled":"Programado","Completed (history)":"Completadas (historial)","Calendar":"Calendario","Route day":"Ruta del día","Pickups":"Recogidas","Upcoming":"Próximas","Kits":"Kits","Packages":"Paquetes","Suppliers":"Proveedores","Price tags":"Etiquetas de precio","Promotions":"Promociones","Stock counts":"Conteos de inventario","All":"Todos","Received":"Recibidas","Needs ordering":"Falta pedir","Needs attention":"Requiere atención","Today's deliveries":"Entregas de hoy","Delayed items — priority":"Artículos retrasados — prioridad","Ups today":"Visitas de hoy","Monthly goal":"Meta mensual","Attention board":"Tablero de avisos","Time clock":"Reloj checador","Getting started":"Primeros pasos","Customers to notify":"Clientes por avisar","Today":"Hoy","Pick & stage":"Surtir y preparar","Put-away":"Acomodar","Storage bins":"Ubicaciones","Find an item":"Buscar artículo","Sales analytics":"Análisis de ventas","Top sellers":"Más vendidos","Payments":"Pagos","Tax & accounting":"Impuestos y contabilidad","Operations & Z report":"Operaciones y reporte Z","Commissions":"Comisiones","Audit log":"Registro de auditoría","Follow-ups":"Seguimientos","Sleep trials":"Pruebas de colchón","Returns":"Devoluciones","Warranty claims":"Reclamos de garantía",
 // settings tabs
 "Store":"Tienda","Tax & customers":"Impuestos y clientes","Register":"Caja","Payments & financing":"Pagos y financiamiento","Pricing":"Precios","Inventory setup":"Configuración de inventario","Delivery & routing":"Entregas y rutas","Mattress & returns":"Colchones y devoluciones","Service & messaging":"Servicio y mensajes","Terms & documents":"Términos y documentos","Staff & permissions":"Personal y permisos","Optional features":"Funciones opcionales","Data & backup":"Datos y respaldo",
 // customer form
 "New customer":"Nuevo cliente","Edit customer":"Editar cliente","First name":"Nombre","Last name":"Apellido","Mobile phone":"Teléfono celular","Company / business":"Empresa / negocio","How did they hear about us?":"¿Cómo nos conoció?","Street address":"Dirección","City":"Ciudad","State":"Estado","ZIP":"Código postal","Address":"Dirección","Phone":"Teléfono","Notes":"Notas","Full name":"Nombre completo",
 // statuses / tags
 "paid":"pagada","open":"abierta","void":"anulada","quote":"cotización","layaway":"apartado","financed":"financiada","delivered":"entregado","scheduled":"programado","loaded":"cargado","out":"en ruta","unscheduled":"sin programar","awaiting":"en espera","ready":"listo","Draft":"Borrador","Ordered":"Pedido","Partially received":"Recibido parcialmente","Cancelled":"Cancelada","Delivered":"Entregado","Picked up":"Recogido","Taken at sale":"Entregado en la venta","balance":"saldo","hold":"retener",
 // misc
 "Yes":"Sí","No":"No","Name":"Nombre","Role":"Puesto","PIN":"PIN","Active":"Activo","Owner":"Propietario","Manager":"Gerente","Sales associate":"Vendedor","Cashier":"Cajero","Delivery driver":"Chofer de reparto","Preferred language":"Idioma preferido","Store default language":"Idioma predeterminado de la tienda","Search order, customer, item…":"Buscar orden, cliente, artículo…","Search number, customer…":"Buscar número, cliente…","Search SKU, name, size…":"Buscar SKU, nombre, tamaño…","Search name, phone, email…":"Buscar nombre, teléfono, correo…","Nothing matches.":"Sin resultados.","Balance":"Saldo","Paid":"Pagado","Sold":"Vendido","Status":"Estado","Outstanding items":"Artículos pendientes","Order":"Orden","Item":"Artículo","Qty":"Cant.","Price":"Precio","Stock":"Existencia","Vendor":"Proveedor","Supplier":"Proveedor","Expected":"Esperado","Promised":"Prometido"
}};

const RULES={es:[
 [/^Good (morning|afternoon|evening), (.+)$/,(m)=>({morning:"Buenos días",afternoon:"Buenas tardes",evening:"Buenas noches"}[m[1]])+", "+m[2]],
 [/^Getting started — (\d+) of (\d+) done$/,(m)=>`Primeros pasos — ${m[1]} de ${m[2]} listos`],
 [/^Net sales this month · (\d+) invoices?$/,(m)=>`Ventas netas del mes · ${m[1]} facturas`],
 [/^Deliveries today · (\d+) done$/,(m)=>`Entregas de hoy · ${m[1]} hechas`],
 [/^Gross margin · (.+)$/,(m)=>`Margen bruto · ${m[1]}`],
 [/^(\d+) tickets? · avg (.+)$/,(m)=>`${m[1]} ventas · promedio ${m[2]}`],
 [/^(\d+) tickets?$/,(m)=>`${m[1]} ventas`],
 [/^Month to date — day (\d+)$/,(m)=>`Mes a la fecha — día ${m[1]}`],
 [/^Last month, same day$/,()=>"Mes pasado, mismo día"],[/^Same month last year, same day$/,()=>"Mismo mes del año pasado, mismo día"],
 [/^No goal set yet( — click Set goals)?\.$/,()=>"Aún no hay meta — toque Fijar metas."],
 [/^alerts (\d+) days before an ETA$/,(m)=>`alertas ${m[1]} días antes de la fecha`],[/^open orders board$/,()=>"ver órdenes"],
 [/^sold (.+)$/,(m)=>`vendido ${m[1]}`],[/^Sold (.+)$/,(m)=>`Vendido ${m[1]}`],[/^expected (.+)$/,(m)=>`esperado ${m[1]}`],
 [/^(\d+) of (\d+) delivered · (\d+) pieces$/,(m)=>`${m[1]} de ${m[2]} entregadas · ${m[3]} piezas`],
 [/^Window (.+)$/,(m)=>`Horario ${m[1]}`],[/^Stop (\d+)$/,(m)=>`Parada ${m[1]}`],
 [/^(\d+) of (\d+)$/,(m)=>`${m[1]} de ${m[2]}`],[/^(\d+) still coming$/,(m)=>`${m[1]} por llegar`],[/^placed (\d+)d ago$/,(m)=>`pedido hace ${m[1]} días`],
 [/^Balance (.+)$/,(m)=>`Saldo ${m[1]}`],[/^Collect (.+)$/,(m)=>`Cobrar ${m[1]}`],[/^Scheduled (.+)$/,(m)=>`Programado ${m[1]}`],[/^Delivered (.+)$/,(m)=>`Entregado ${m[1]}`],[/^Ready for pickup · (.+)$/,(m)=>`Listo para recoger · ${m[1]}`],[/^Awaiting stock · ETA (.+)$/,(m)=>`Esperando mercancía · fecha ${m[1]}`],[/^ETA (.+)$/,(m)=>`Fecha ${m[1]}`]
]};
function customerLang(){ const st=tenantId?storeSettings():null; return (st&&st.customerLang)||"en"; }
function customerModal(html,wide){ const cl=customerLang(); modal(cl==="en"?`<div data-notr>${html}</div>`:html,wide); }
function currentLang(){ try{ const dev=localStorage.getItem("ht_lang"); if(dev) return dev; }catch(e){} const s=session&&session.kind==="staff"?me():null; if(s&&s.lang) return s.lang; const st=tenantId?storeSettings():null; return (st&&st.lang)||"en"; }
function t(s){ const L=currentLang(); if(L==="en") return s; const d=DICT[L]||{}; return d[s]||s; }
function setDeviceLang(l){ try{ if(l) localStorage.setItem("ht_lang",l); else localStorage.removeItem("ht_lang"); }catch(e){} render(); }
function toggleLang(){ const L=currentLang(); setDeviceLang(L==="es"?"en":"es"); }
function translateDOM(root){ const L=currentLang(); if(L==="en"||!root) return; const d=DICT[L]||{}; const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{ const p=n.parentElement; if(!p) return NodeFilter.FILTER_REJECT; const tag=p.tagName; if(tag==="SCRIPT"||tag==="STYLE"||tag==="TEXTAREA"||p.closest("[data-notr]")) return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT; }}); const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode); for(const n of nodes){ const raw=n.nodeValue; const s=raw.trim(); if(!s) continue; let tr=d[s]; if(!tr&&/ ▾$/.test(s)&&d[s.replace(/ ▾$/,"")]) tr=d[s.replace(/ ▾$/,"")]+" ▾"; if(!tr&&/:$/.test(s)&&d[s.slice(0,-1)]) tr=d[s.slice(0,-1)]+":"; if(!tr&&/^Goes with this/.test(s)) tr=s.replace(/^Goes with this/,"Combina con"); if(!tr&&/^Protection plan /.test(s)) tr=s.replace(/^Protection plan/,"Plan de protección"); if(tr){ n.nodeValue=raw.replace(s,tr); continue; } const m=s.match(/^(.*?)( \(\d+\))$/); if(m&&d[m[1]]){ n.nodeValue=raw.replace(s,d[m[1]]+m[2]); continue; } for(const [re,fn] of (RULES[L]||[])){ const mm=s.match(re); if(mm){ n.nodeValue=raw.replace(s,fn(mm)); break; } } } for(const el of root.querySelectorAll("[placeholder],[title]")){ for(const a of ["placeholder","title"]){ const v=el.getAttribute(a); if(v&&d[v]) el.setAttribute(a,d[v]); } } for(const o of root.querySelectorAll("option")){ const s=o.textContent.trim(); if(d[s]) o.textContent=d[s]; } }
function langMenuLabel(){ const L=currentLang(); return L==="es"?"Switch to English":"Cambiar a Español"; }

Object.assign(DICT.es,{
 "Deliveries & pickups":"Entregas y recogidas","Awaiting stock / payment":"Esperando mercancía / pago","All loaded":"Todo cargado","Truck departed":"Camión salió","Open in Google Maps":"Abrir en Google Maps","Optimize this truck":"Optimizar este camión","Text ETA":"Enviar hora estimada","Map":"Mapa","Confirm windows":"Confirmar horarios","Pick list":"Lista de surtido","Delivery slips":"Comprobantes de entrega","Route sheets":"Hojas de ruta","Trucks & crews":"Camiones y equipos","Waiting to be picked up":"Pendiente de recoger","Planned":"Planeado","Slip":"Comprobante","Hold tags":"Etiquetas de apartado",
 "Purchase order":"Orden de compra","Ordered · expected":"Pedido · esperado","Vendor bill":"Factura del proveedor","Vendor bills to pay":"Facturas por pagar","not recorded":"sin registrar","still coming":"por llegar","Receive shipment":"Recibir envío","Arrived now":"Llegó ahora","Already in":"Ya recibido","If fewer arrived":"Si llegaron menos","Packing slip / BOL #":"No. de lista de empaque","Received on":"Recibido el","Carrier / notes":"Transportista / notas","all":"todo","How it flows:":"Cómo funciona:",
 "Sales by day":"Ventas por día","Net sales":"Ventas netas","Gross margin":"Margen bruto","Gross profit":"Utilidad bruta","This month":"Este mes","Last month":"Mes pasado","This week":"Esta semana","This year":"Este año","Quarter":"Trimestre","Last year":"Año pasado","Earned":"Ganado","Plans":"Planes","Due":"Por pagar","Chargebacks":"Devoluciones","Commission rules":"Reglas de comisión",
 "Follow-ups due":"Seguimientos pendientes","Deliveries to schedule":"Entregas por programar","Invoices with a balance":"Facturas con saldo","Items at reorder point":"Artículos en punto de reorden","Customer orders to place with suppliers":"Pedidos de clientes por hacer a proveedores","Purchase orders late from the vendor":"Órdenes de compra atrasadas del proveedor","Orders the vendor hasn't acknowledged":"Órdenes sin confirmar por el proveedor","Ready for pickup — customer not told yet":"Listo para recoger — cliente no avisado","Net sales this month":"Ventas netas del mes","Deliveries today":"Entregas de hoy","Things needing attention":"Pendientes por atender","No announcement —":"Sin anuncio —","post one for the team":"publicar uno para el equipo","Nothing scheduled for today.":"Nada programado para hoy.","Delivery calendar":"Calendario de entregas","Nobody clocked in right now.":"Nadie ha registrado entrada.",
 "Print labels":"Imprimir etiquetas","Stock labels":"Etiquetas de inventario","Label stock":"Tipo de etiqueta","Copies of each":"Copias de cada una","Download ZPL":"Descargar ZPL","Print via driver":"Imprimir por controlador","Send to Zebra":"Enviar a Zebra",
 "Return / exchange":"Devolución / cambio","Warranty claim":"Reclamo de garantía","Void this invoice":"Anular esta factura","Email receipt":"Enviar recibo por correo","Text receipt":"Enviar recibo por mensaje","Print labels for this order":"Imprimir etiquetas de esta orden","Change to pickup":"Cambiar a recogida","Change to delivery":"Cambiar a entrega","Set ETA / notify customer":"Fijar fecha / avisar al cliente","Schedule delivery":"Programar entrega","Complete pickup":"Completar recogida","Hold for pickup":"Guardar para recoger","Open in register":"Abrir en la caja","Record payment":"Registrar pago",
 "Add follow-up":"Agregar seguimiento","New warranty claim":"Nuevo reclamo de garantía","Export delivered customers":"Exportar clientes entregados","Items received in the last 7 days":"Artículos recibidos en los últimos 7 días",
 "Who pays for this item?":"¿Quién paga este artículo?","Customer pays (taxed normally)":"Paga el cliente (con impuesto normal)","Approved":"Aprobado","Approved amount":"Monto aprobado","left":"restante","OVER by":"EXCEDE por",
 "Manager approval":"Aprobación de gerente","Approve":"Aprobar","Confirm it's you":"Confirme que es usted","Confirm":"Confirmar",
 "Customize Home":"Personalizar inicio","Sales goals":"Metas de ventas","Save goals":"Guardar metas","Team":"Equipo","You:":"Usted:","Month to date":"Mes a la fecha"
});