/* ============================================================
   SELF-HOSTED DEPLOYMENT — Firebase database adapter, relay URL,
   vendor live stock through the relay
   ============================================================ */
function hsConfig(){ return (typeof window!=="undefined"&&window.HS_CONFIG)||{}; }
function loadScript(src){ return new Promise((res,rej)=>{ const s=document.createElement("script"); s.src=src; s.onload=res; s.onerror=()=>rej(new Error("failed "+src)); document.head.appendChild(s); }); }
async function initFirebaseDb(){ const cfg=hsConfig().firebase; if(!cfg||!cfg.projectId) return null; try{ if(!window.firebase){ await loadScript("https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js"); await loadScript("https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore-compat.js"); await loadScript("https://www.gstatic.com/firebasejs/10.12.0/firebase-auth-compat.js"); } if(!firebase.apps.length) firebase.initializeApp(cfg); const existing=await new Promise(res=>{ let done=false; const off=firebase.auth().onAuthStateChanged(u=>{ if(!done){ done=true; off(); res(u); } }); setTimeout(()=>{ if(!done){ done=true; res(null); } },4000); }); if(!existing){ try{ await firebase.auth().signInAnonymously(); }catch(e){ console.warn("anonymous sign-in failed",e); } } const fs=firebase.firestore(); try{ fs.settings({ignoreUndefinedProperties:true}); }catch(e){} return fs; }catch(e){ console.warn("Firebase init failed",e); return null; } }
function platformRelay(){ const c=hsConfig(); return (platform&&platform.config&&platform.config.relayUrl)||c.relayUrl||""; }
async function relayFetch(path,opts){ const base=platformRelay().replace(/\/$/,""); if(!base) throw new Error("No relay configured"); const r=await fetch(base+path,Object.assign({headers:Object.assign({"Content-Type":"application/json","X-Tenant":tenantId||"","X-Relay-Token":hsConfig().relayToken||""},(opts&&opts.headers)||{})},opts||{})); const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j.error||("HTTP "+r.status)); return j; }
/* vendor live stock: GET {relay}/vendor/{integrationId}/stock?sku=... → {available, onOrder, nextDate, note} */
const _stockCache=new Map();
async function vendorStock(integrationId,sku,force){ const key=integrationId+"|"+sku; const c=_stockCache.get(key); if(!force&&c&&Date.now()-c.at<10*60000) return c.data; const data=await relayFetch(`/vendor/${encodeURIComponent(integrationId)}/stock?sku=${encodeURIComponent(sku)}`); _stockCache.set(key,{at:Date.now(),data}); return data; }
function integrationForProduct(p){ const v=p&&byId("vendors",p.vendorId); if(!v||!v.integrationId) return null; return (platform.integrations||[]).find(i=>i.id===v.integrationId&&i.active!==false)||null; }
function stockLabelHTML(d){ if(!d) return ""; const n=+d.available; const cls=isNaN(n)?"":n>0?"ok":"bad"; return `<span class="tag ${cls}">vendor: ${isNaN(n)?esc(String(d.available||"?")):n+" available"}</span>${d.onOrder?` <span class="muted small">${esc(String(d.onOrder))} on order</span>`:""}${d.nextDate?` <span class="muted small">next ${dateShort(d.nextDate)}</span>`:""}${d.note?` <span class="muted small">${esc(d.note)}</span>`:""}${d.schedule&&d.schedule.length?` <a href="#" class="small" onclick="stockTableModal(${JSON.stringify(d).replace(/"/g,"&quot;")},this.closest('[data-sku]')?this.closest('[data-sku]').dataset.sku:'');return false">see dates</a>`:""}`; }
function stockTableHTML(d,needQty){ const rows=[{date:"Now",qty:+d.available||0}].concat((d.schedule||[]).map(s=>({date:s.date,qty:+s.qty||0}))); let run=0, covered=null; return `<table style="width:100%;border-collapse:collapse;font-size:13px"><tr style="background:var(--sage2)"><th style="text-align:left;padding:6px">Date</th><th style="text-align:right;padding:6px">Qty</th><th style="text-align:right;padding:6px">Running total</th></tr>${rows.map(r=>{ run+=r.qty; const hit=needQty&&covered===null&&run>=needQty; if(hit) covered=r.date; return `<tr style="${hit?"background:var(--mint2);font-weight:700":""}"><td style="padding:6px;border-top:1px solid var(--line)">${r.date==="Now"?"<b>In stock now</b>":dateShort(r.date)}</td><td style="padding:6px;text-align:right;border-top:1px solid var(--line)">${r.qty}</td><td style="padding:6px;text-align:right;border-top:1px solid var(--line)">${run}</td></tr>`; }).join("")}</table>${needQty?`<p class="muted small" style="margin:6px 0 0">${covered?(covered==="Now"?"Your quantity is available now.":"Your "+needQty+" would be covered by <b>"+dateShort(covered)+"</b>."):"Not enough on the vendor's schedule to cover "+needQty+"."}</p>`:""}<p class="muted small" style="margin:4px 0 0">Checked ${d.checkedAt?new Date(d.checkedAt).toLocaleTimeString():"just now"} · vendor figures, not a reservation.</p>`; }
function stockTableModal(d,sku,needQty,lineIdx){ modal(`<h2>Vendor availability${sku?" — "+esc(sku):""}</h2>${stockTableHTML(d,needQty)}<div class="actions"><button class="btn" onclick="closeModal()">Close</button>${lineIdx!==undefined&&cur&&cur.lines[lineIdx]?`<button class="btn p" onclick="(function(){ const rows=[{date:'',qty:${+d.available||0}}].concat(${JSON.stringify((d.schedule||[]).map(s=>({date:s.date,qty:+s.qty||0})))}); let run=0; const need=cur.lines[${lineIdx}].qty||1; let pick=''; for(const r of rows){ run+=r.qty; if(run>=need){ pick=r.date; break; } } if(pick){ cur.lines[${lineIdx}].expected=pick; closeModal(); render(); toast('ETA set to '+dateShort(pick)); } else toast('Vendor schedule doesn\\'t cover this quantity yet',true); })()">Use as ETA for this line</button>`:""}</div>`); }
async function checkVendorStock(pid,targetId,lineIdx){ const p=byId("products",pid); const integ=integrationForProduct(p); const el=document.getElementById(targetId); if(!integ){ if(el) el.innerHTML='<span class="muted small">no live stock for this supplier</span>'; return; } if(!platformRelay()){ if(el) el.innerHTML='<span class="muted small">live stock needs the relay (Administration → Software settings)</span>'; return; } if(el) el.innerHTML='<span class="muted small">checking…</span>'; try{ const d=await vendorStock(integ.id,p.vendorSku||p.sku,true); if(el) el.innerHTML=stockLabelHTML(d)+(d.nextDate&&lineIdx!==undefined&&cur&&cur.lines[lineIdx]?` <a href="#" class="small" onclick="cur.lines[${lineIdx}].expected='${d.nextDate}';render();return false">use as ETA</a>`:""); if(d.schedule&&d.schedule.length&&lineIdx!==undefined&&cur&&cur.lines[lineIdx]) stockTableModal(d,p.vendorSku||p.sku,cur.lines[lineIdx].qty||1,lineIdx); logAudit("vendor_stock",`${p.name}: ${JSON.stringify(d).slice(0,120)}`); }catch(e){ if(el) el.innerHTML=`<span class="tag bad">vendor check failed</span> <span class="muted small">${esc(e.message)}</span>`; } }
function vendorStockButton(p,lineIdx){ const integ=integrationForProduct(p); if(!integ) return ""; const id="vs_"+(p.id)+"_"+(lineIdx===undefined?"x":lineIdx); return `<span id="${id}"><a href="#" class="small" onclick="checkVendorStock('${p.id}','${id}',${lineIdx===undefined?"undefined":lineIdx});return false" title="Ask ${esc(integ.name)} how many are available right now">live stock</a></span>`; }
async function checkPOAvailability(poId){ const o=byId("purchaseOrders",poId); const v=byId("vendors",o.vendorId); const integ=v&&v.integrationId?(platform.integrations||[]).find(i=>i.id===v.integrationId):null; if(!integ) return toast("This supplier has no live stock connection.",true); if(!platformRelay()) return toast("Live stock needs the relay service — see Administration → Software settings.",true); toast("Checking availability with "+integ.name+"…"); const rows=[]; for(const l of o.lines){ try{ const d=await vendorStock(integ.id,l.vendorSku||l.desc,true); rows.push({l,d}); }catch(e){ rows.push({l,d:null,err:e.message}); } } modal(`<h2>Availability — ${esc(integ.name)}</h2>${table(rows,[["Item",r=>esc(r.l.desc)],["Ordered",r=>r.l.qty,"n"],["Vendor says",r=>r.d?stockLabelHTML(r.d):`<span class="tag bad">no answer</span> <span class="muted small">${esc(r.err||"")}</span>`]],"")}<div class="actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn p" onclick="(async()=>{ const o=byId('purchaseOrders','${poId}'); const dates=${JSON.stringify(rows.map(r=>r.d&&r.d.nextDate||""))}; const best=dates.filter(Boolean).sort().slice(-1)[0]; if(best){ o.expected=best; await save('purchaseOrders',o); toast('Expected date set to '+dateShort(best)); } closeModal(); openPO('${poId}'); })()">Use vendor dates as ETA</button></div>`,true); }

/* ---- public store sign-in: exact code lookup, no enumeration, rate-limited ---- */
function codeLock(){ try{ return JSON.parse(localStorage.getItem("ht_code_lock")||"{}"); }catch(e){ return {}; } }
function codeLockSave(o){ try{ localStorage.setItem("ht_code_lock",JSON.stringify(o)); }catch(e){} }
function codeLockRemaining(){ const o=codeLock(); return o.until&&o.until>Date.now()?Math.ceil((o.until-Date.now())/1000):0; }
function codeAttemptFailed(){ const o=codeLock(); o.n=(o.n||0)+1; if(o.n>=5){ const step=Math.min(600,30*Math.pow(2,o.n-5)); o.until=Date.now()+step*1000; } codeLockSave(o); }
function codeAttemptOk(){ codeLockSave({}); }
const _inflightCodes=new Map();
async function lookupStoreCode(code){ code=String(code||"").trim().toUpperCase(); if(!/^[A-Z0-9-]{2,12}$/.test(code)) return null; const local=(platform.tenants||[]).find(x=>String(x.code||"").toUpperCase()===code); if(local) return local; if(!db||!(typeof hsConfig==="function"&&hsConfig().firebase)) return null; if(_inflightCodes.has(code)) return _inflightCodes.get(code); const p=(async()=>{ try{ const ref=await readDoc("tenantCodes/"+code); if(!ref||!ref.tenantId) return null; const t=await readDoc("tenants/"+ref.tenantId); if(!t) return null; if(!platform.tenants.some(x=>x.id===t.id)) platform.tenants.push(t); savePlatformLocal(); return t; }catch(e){ return null; } finally{ _inflightCodes.delete(code); } })(); _inflightCodes.set(code,p); return p; }

/* ---- administrator sign-in with a real account (Firebase email/password) when self-hosted ---- */
function adminNeedsAccount(){ try{ return !!(hsConfig().firebase&&window.firebase&&!(firebase.auth().currentUser&&firebase.auth().currentUser.email)); }catch(e){ return false; } }
function adminAccountForm(brand){ return `<div class="login admin"><div class="box">${loginLogoHTML(56)}<div style="height:10px"></div><span class="adminbadge">ADMINISTRATION</span><h2 style="margin:6px 0 4px">Owner account</h2><p class="muted">Sign in with the owner email and password from your Firebase project. Store registers never see this screen.</p><div class="field"><label class="f">Email</label><input type="email" id="fa_email" autocomplete="username"></div><div class="field"><label class="f">Password</label><input type="password" id="fa_pass" autocomplete="current-password" onkeydown="if(event.key==='Enter')adminAccountSignIn()"></div><div class="msg" id="fa_msg"></div><button class="btn p w" onclick="adminAccountSignIn()">Continue</button></div></div>`; }
async function adminAccountSignIn(){ const m=document.getElementById("fa_msg"); const btn=document.querySelector(".login .btn.p"); try{ if(btn){ btn.disabled=true; btn.textContent="Signing in…"; } await firebase.auth().signInWithEmailAndPassword(fv("fa_email").trim(),fv("fa_pass")); platform={config:null,tenants:[],integrations:[]}; try{ await connectShared(); }catch(e){} platformLoaded=true; if(!platform.config) forceSetup=true; renderLogin(); }catch(e){ if(btn){ btn.disabled=false; btn.textContent="Continue"; } if(m) m.textContent=/network/i.test(e&&e.code||"")?"Can't reach Firebase — check the connection and that app.homestorepos.com is an authorized domain.":"Sign-in failed. Check the email and password."; } }

/* dealer-specific vendor credentials: written to vendorCredentials/{tenantId}_{integrationId}; clients cannot read it back (rules), the relay can */
async function saveVendorCredentials(intId,creds){ const key=tenantId+"_"+intId; const doc={tenantId,integrationId:intId,creds,updatedAt:Date.now(),updatedBy:session&&session.staffId||""}; if(db&&typeof hsConfig==="function"&&hsConfig().firebase){ await db.collection("vendorCredentials").doc(key).set(doc); } else if(db){ await db.collection("vendorCredentials").doc(key).set(doc); } else { const v=S.vendors.find(v=>v.integrationId===intId); if(v){ v.credsLocal=creds; await save("vendors",v); } } logAudit("settings",`Vendor API access saved for ${intId}`); }
/* ---- photo & signature storage: Firebase Storage when self-hosted (link in the record), inline data otherwise ---- */
let _storageReady=null;
async function storageRef(){ if(!(typeof hsConfig==="function"&&hsConfig().firebase)||!window.firebase) return null; if(!_storageReady){ _storageReady=(async()=>{ try{ if(!firebase.storage) await loadScript("https://www.gstatic.com/firebasejs/10.12.0/firebase-storage-compat.js"); return firebase.storage(); }catch(e){ return null; } })(); } return _storageReady; }
function dataUrlToBlob(d){ const [meta,b64]=d.split(","); const mime=(meta.match(/data:([^;]+)/)||[])[1]||"image/jpeg"; const bin=atob(b64); const arr=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) arr[i]=bin.charCodeAt(i); return new Blob([arr],{type:mime}); }
async function storeImage(kind,ownerId,dataUrl,idx){ if(!dataUrl||!/^data:/.test(dataUrl)) return dataUrl||""; const st=await storageRef(); if(!st) return dataUrl; try{ const ext=/image\/png/.test(dataUrl)?"png":"jpg"; const path=`tenants/${tenantId}/${kind}/${ownerId}/${Date.now()}_${idx||0}.${ext}`; const ref=st.ref().child(path); await ref.put(dataUrlToBlob(dataUrl),{contentType:ext==="png"?"image/png":"image/jpeg",cacheControl:"public,max-age=31536000"}); return await ref.getDownloadURL(); }catch(e){ console.warn("photo upload failed, keeping inline",e); return dataUrl; } }
async function storeImages(kind,ownerId,list){ const out=[]; for(let i=0;i<(list||[]).length;i++) out.push(await storeImage(kind,ownerId,list[i],i)); return out; }
/* ---- photo retention: delivery / damage photos are removed automatically after N months; signatures and records stay ---- */
function photoRetentionMonths(){ const st=tenantId?storeSettings():null; const v=st&&st.photoRetentionMonths; return v===undefined||v===null||v===""?24:+v; }
function purgedNote(d){ return d&&d.photosPurged?`<span class="muted small" style="color:#8a949a">Photos removed after ${d.photosPurged.months} months (retention policy) · ${d.photosPurged.n} photo${d.photosPurged.n===1?"":"s"}</span>`:""; }
async function deleteStoredImage(url){ try{ if(!/^https?:\/\//.test(url)) return; const st=await storageRef(); if(!st) return; await st.refFromURL(url).delete(); }catch(e){} }
async function purgeOldPhotos(force){ const months=photoRetentionMonths(); if(!months||months<=0) return 0; const key="ht_photo_purge:"+tenantId; try{ const last=localStorage.getItem(key); if(!force&&last===todayISO()) return 0; localStorage.setItem(key,todayISO()); }catch(e){} const cutoff=(()=>{ const d=new Date(); d.setMonth(d.getMonth()-months); return d.toISOString().slice(0,10); })(); let n=0, docs=0; for(const d of S.deliveries){ const when=d.deliveredAt||d.pickedUpAt||d.date; if(!when||when>=cutoff) continue; const photos=(d.photos||[]).filter(Boolean); const dmg=(d.itemIssues||[]).flatMap(x=>x.photos||[]).filter(Boolean); if(!photos.length&&!dmg.length) continue; for(const u of photos.concat(dmg)) await deleteStoredImage(u); n+=photos.length+dmg.length; d.photos=[]; (d.itemIssues||[]).forEach(x=>{ x.photos=[]; }); d.photosPurged={at:todayISO(),months,n:photos.length+dmg.length}; docs++; await save("deliveries",d); } if(n){ logAudit("settings",`Retention: removed ${n} delivery photo${n===1?"":"s"} older than ${months} months on ${docs} deliver${docs===1?"y":"ies"}`); } return n; }
/* ---- update notice: registers check version.txt every 15 minutes and offer to reload ---- */
const BUILD_VERSION="__BUILD__";
let _updateTimer=null, _updateShown=false;
async function checkForUpdate(){ if(!(typeof hsConfig==="function"&&hsConfig().firebase)) return; if(BUILD_VERSION.indexOf("__")===0) return; try{ const r=await fetch("version.txt?t="+Date.now(),{cache:"no-store"}); if(!r.ok) return; const v=(await r.text()).trim(); if(!v||v===BUILD_VERSION||_updateShown) return; let tried=null; try{ tried=JSON.parse(localStorage.getItem("ht_update_tried")||"null"); }catch(e){} if(tried&&tried.v===v&&Date.now()-tried.at<20*60000) return; _updateShown=true; showUpdateBanner(v); }catch(e){} }
function showUpdateBanner(v){ let b=document.getElementById("update-banner"); if(b) return; b=document.createElement("div"); b.id="update-banner"; b.style.cssText="position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:2600;background:#222E38;color:#fff;padding:10px 16px;border-radius:12px;box-shadow:0 6px 24px rgba(0,0,0,.25);font-size:14px;display:flex;gap:12px;align-items:center"; b.innerHTML=`<span>A new version of HomeStore POS is ready.</span><button class="btn s" style="background:#37A598;color:#fff;border-color:#37A598" onclick="applyUpdate('${v}')">Update now</button><button class="btn s" style="background:transparent;color:#fff;border-color:#fff" onclick="this.parentElement.remove()">Later</button>`; document.body.appendChild(b); }
function startUpdateChecks(){ if(_updateTimer) return; _updateTimer=setInterval(checkForUpdate,15*60000); setTimeout(checkForUpdate,20000); }
try{ if(typeof window!=="undefined") window.addEventListener("load",()=>{ try{ startUpdateChecks(); }catch(e){} }); }catch(e){}
/* ---- Google address autocomplete (self-hosted only; key restricted to your domain in Google Cloud) ---- */
let _gmapsLoading=null;
function googleMapsKey(){ return hsConfig().googleMapsKey||""; }
function loadGoogleMaps(){ if(!googleMapsKey()) return Promise.resolve(false); if(window.google&&google.maps&&google.maps.places&&google.maps.places.Autocomplete) return Promise.resolve(true); if(_gmapsLoading) return _gmapsLoading; _gmapsLoading=new Promise(res=>{ const s=document.createElement("script"); s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleMapsKey())}&libraries=places&loading=async`; s.onload=async()=>{ try{ if(google.maps.importLibrary) await google.maps.importLibrary("places"); let tries=0; while(!(google.maps.places&&google.maps.places.Autocomplete)&&tries++<50) await new Promise(r=>setTimeout(r,100)); res(!!(google.maps.places&&google.maps.places.Autocomplete)); }catch(e){ console.warn("maps load",e); res(false); } }; s.onerror=()=>res(false); document.head.appendChild(s); }); return _gmapsLoading; }
async function attachGoogleAutocomplete(prefix,coordsId){ if(!googleMapsKey()) return; const ok=await loadGoogleMaps(); if(!ok) return; const el=document.getElementById(prefix); if(!el||el.dataset.gac) return; el.dataset.gac="1"; try{ const st=tenantId?storeSettings():null; const opts={fields:["address_components","geometry","formatted_address"],types:["address"],componentRestrictions:{country:(hsConfig().country||"us")}}; const ac=new google.maps.places.Autocomplete(el,opts); if(st&&st.lat&&st.lng){ const c=new google.maps.LatLng(+st.lat,+st.lng); ac.setBounds(new google.maps.LatLngBounds(new google.maps.LatLng(+st.lat-1,+st.lng-1),new google.maps.LatLng(+st.lat+1,+st.lng+1))); } ac.addListener("place_changed",()=>{ const p=ac.getPlace(); if(!p||!p.address_components) return; const g=t=>{ const c=p.address_components.find(x=>x.types.includes(t)); return c?c:null; }; const num=g("street_number"), route=g("route"), city=g("locality")||g("sublocality")||g("postal_town")||g("administrative_area_level_3"), state=g("administrative_area_level_1"), zip=g("postal_code"); el.value=[num&&num.long_name,route&&route.long_name].filter(Boolean).join(" "); const set=(id,v)=>{ const e=document.getElementById(id); if(e&&v) e.value=v; }; set(prefix+"_city",city&&city.long_name); set(prefix+"_state",state&&state.short_name); set(prefix+"_zip",zip&&zip.long_name); if(coordsId&&p.geometry&&p.geometry.location){ const e=document.getElementById(coordsId); if(e) e.value=p.geometry.location.lat().toFixed(6)+", "+p.geometry.location.lng().toFixed(6); } const sug=document.getElementById(prefix+"_sug"); if(sug) sug.innerHTML=""; }); el.placeholder="Start typing — Google suggests the address"; el.oninput=null; }catch(e){ console.warn("autocomplete",e); } }

function applyUpdate(v){ try{ localStorage.setItem("ht_update_tried",JSON.stringify({v,at:Date.now()})); }catch(e){} try{ if(window.caches&&caches.keys) caches.keys().then(ks=>ks.forEach(k=>caches.delete(k))); }catch(e){} const u=new URL(location.href); u.searchParams.set("v",v); location.replace(u.toString()); }
