/* ============================================================
   SPLIT INVOICE DOCUMENTS — one numbered document per payer
   (lease / finance companies need an invoice with only their items)
   ============================================================ */
function payerParts(inv){ const T=invTotals(inv); const funds=T.fundings||[]; if(!funds.length) return []; const parts=[]; let n=1;
  for(const f of funds){ const lines=inv.lines.filter(l=>lineFundingId(inv,l)===f.src.id||(l.appFee&&l.appFeeFor===f.src.id)); parts.push({n:n++,key:f.src.id,label:f.src.name,kind:f.src.type==="lease"?"Lease-to-own":"Financing",src:f.src,lines,deliv:f.deliv||0,appFee:f.appFee||0,amount:f.amount}); }
  const custLines=inv.lines.filter(l=>!lineFundingId(inv,l)&&!l.appFee); const custDeliv=(inv.delivery&&!funds.some(f=>f.deliv))?(+inv.deliveryFee||0):0; const custAmt=round2(T.total-T.fundedAmount-(T.appFees||0));
  if(custLines.length||custDeliv||custAmt>0.005) parts.push({n:n++,key:"customer",label:custDisplay(byId("customers",inv.customerId))||"Customer",kind:"Customer",src:null,lines:custLines,deliv:custDeliv,amount:custAmt});
  return parts.length>1?parts:[]; }
function partNumber(inv,part){ return `${inv.number}-${part.n}`; }
function partInvoice(inv,part){ const clone=JSON.parse(JSON.stringify(inv)); clone.number=partNumber(inv,part); clone.partOf=inv.number; clone.partLabel=`${part.kind} — ${part.label}`; clone.partIndex=part.n; clone.partCount=payerParts(inv).length; clone.lines=part.lines.map(l=>JSON.parse(JSON.stringify(l))); clone.discount=0; clone.deliveryFee=part.deliv||0; clone.delivery=!!(part.deliv)||(part.src?false:inv.delivery); if(part.src){ clone.fundingId=part.src.id; clone.deliveryFundingId=part.deliv?part.src.id:""; clone.lines.forEach(l=>{ if(!l.appFee) l.fundingId=part.src.id; }); clone.payments=(inv.payments||[]).filter(p=>String(p.method||"").toLowerCase().includes(String(part.label).toLowerCase())); } else { clone.fundingId=""; clone.deliveryFundingId=""; clone.lines.forEach(l=>{ delete l.fundingId; delete l.funded; }); clone.payments=(inv.payments||[]).filter(p=>!(invTotals(inv).fundings||[]).some(f=>String(p.method||"").toLowerCase().includes(String(f.src.name).toLowerCase()))); } clone.notes=inv.notes; return clone; }
function partSignatureBlockHTML(inv){ const signed=!!inv.signature; return `<div style="margin-top:22px;page-break-inside:avoid"><div style="font-size:11px;margin-bottom:6px">I confirm the items, quantities and amounts on this document (${esc(inv.number)}) are correct and agree to the store's terms &amp; conditions${inv.partLabel?` and to payment through ${esc(inv.partLabel.replace(/^[^—]+— /,""))}`:""}.</div><div style="display:flex;gap:28px;align-items:flex-end"><div style="flex:2">${signed?`<img src="${inv.signature}" style="height:56px;display:block">`:`<div style="height:56px"></div>`}<div style="border-top:1px solid #000;padding-top:3px;font-size:10px">Customer signature${signed?` — ${esc(inv.signedName||"")}${inv.signedRemote?" (signed electronically)":""}`:""}</div></div><div style="flex:1"><div style="height:56px;display:flex;align-items:flex-end;font-size:12px">${signed&&inv.signedAt?dateFmt(inv.signedAt):""}</div><div style="border-top:1px solid #000;padding-top:3px;font-size:10px">Date</div></div><div style="flex:1"><div style="height:56px"></div><div style="border-top:1px solid #000;padding-top:3px;font-size:10px">Store representative</div></div></div></div>`; }
function partDocHTML(inv,part){ window._noSigPage=part.src?true:false; try{ return printInvoice(partInvoice(inv,part),{returnHtml:true}); } finally{ window._noSigPage=false; } }
function printInvoicePart(invId,n){ const inv=byId("invoices",invId); const part=payerParts(inv).find(p=>p.n===n); if(!part) return; printHTML(partDocHTML(inv,part),partNumber(inv,part)); logAudit("print",`Printed ${partNumber(inv,part)} (${part.label})`,{invoiceId:invId}); }
function allPartsHTML(inv){ return payerParts(inv).map(p=>partDocHTML(inv,p)).join(""); }
function printAllParts(invId){ const inv=byId("invoices",invId); const parts=payerParts(inv); if(!parts.length) return; printHTML(allPartsHTML(inv),`${inv.number} — ${parts.length} documents`); logAudit("print",`Printed all ${parts.length} documents for ${inv.number}`,{invoiceId:invId}); }
function partsPanelHTML(inv){ const parts=payerParts(inv); if(!parts.length) return ""; return `<div class="card" style="padding:10px 12px;margin:10px 0;background:var(--sage2)"><div class="row" style="margin-bottom:4px;gap:6px"><b class="small" style="flex:1">Separate invoice documents — one per payer</b><button class="btn s" onclick="sendDocuments('${inv.id}')" title="One link the customer opens on their phone to view / save every document">Send all by text / email</button><button class="btn s p" onclick="printAllParts('${inv.id}')">Print all ${parts.length}</button></div><p class="muted small" style="margin:0 0 6px">Each lease / finance company gets its own numbered invoice showing only its items and total, as their contracts require. The combined invoice ${esc(inv.number)} stays the store record.</p>${parts.map(p=>`<div class="row" style="gap:8px;padding:5px 0;border-top:1px solid var(--line)"><b>${esc(partNumber(inv,p))}</b><span style="flex:1">${esc(p.kind)}${p.src?" — "+esc(p.label):" — "+esc(p.label)}<span class="muted small"> · ${p.lines.filter(l=>!l.appFee).length} item${p.lines.filter(l=>!l.appFee).length===1?"":"s"}${p.deliv?" + delivery":""}${p.appFee?" · includes "+money(p.appFee)+" application fee collected in store":""}</span></span><b>${money(p.amount)}</b><button class="btn s" onclick="printInvoicePart('${inv.id}',${p.n})">Print</button></div>`).join("")}</div>`; }
function partsPromptAfterSale(invId){ const inv=byId("invoices",invId); const parts=payerParts(inv); if(!parts.length) return false; modal(`<h2>${esc(inv.number)} — ${parts.length} invoice documents</h2><p class="muted">This sale is paid by more than one company, so each gets its own invoice with only its items. Print them for the lease/finance paperwork; the combined invoice is your store copy.</p>${partsPanelHTML(inv)}<div class="actions"><button class="btn" onclick="closeModal();printInvoice(byId('invoices','${invId}'))">Print combined (store copy)</button><button class="btn p" onclick="closeModal();printAllParts('${invId}')">Print all documents</button></div>`,true); return true; }
