/* ============================================================
   ADMINISTRATION (software owner): dealers, administrators
   ============================================================ */
let adminTab="dealers";
function renderAdminShell(){
  const who=me(); const brand=platform.config.softwareName||"POS";
  applyPalette(PALETTES[0]);
  const nav=`<div class="brand" style="${softwareLogo(true)?"flex-direction:column;align-items:flex-start;gap:4px":""}">${brandMark(brand,true)}<div>${softwareLogo(true)?"":esc(brand)}<small>Administration console</small></div></div><div class="sec">Console</div>${[["dealers","Dealers","admin"],["audit","Audit — all dealers","reports"],["integrations","Vendor integrations","vendors"],["admins","Administrators","customers"],["platform","Software settings","settings"]].map(([k,l,i])=>`<button class="${adminTab===k?"on":""}" onclick="adminTab='${k}';render()">${ico(i)}<span class="lbl">${l}</span>${k==="dealers"?`<span class="tag">${platform.tenants.length}</span>`:""}</button>`).join("")}<div class="spacer"></div><div class="usercard"><span class="avatar">${esc(who.name[0])}</span><div class="who"><b>${esc(who.name)}</b><span>Administrator</span></div><button title="Account" onclick="userMenu()">⋯</button></div><div class="status"><span class="syncpill"></span></div>`;
  const body=adminTab==="admins"?renderAdmins():adminTab==="platform"?renderPlatformSettings():adminTab==="integrations"?renderIntegrations():adminTab==="audit"?renderGlobalAudit():renderDealers();
  document.getElementById("root").innerHTML=`<div class="app"><div class="topbar-m"><button class="ham" onclick="document.body.classList.toggle('nav-open')" aria-label="Menu">☰</button><div class="ttl">Administration<span class="sub">${esc(brand)}</span></div></div><div class="nav-scrim" onclick="document.body.classList.remove('nav-open')"></div><nav onclick="if(event.target.closest('button')) document.body.classList.remove('nav-open')">${nav}</nav><main><div class="content">${body}</div></main></div>`;
  syncStatus();
}
function tenantState(t){ if(t.status!=="active") return t.status; if(t.expires&&t.expires<todayISO()) return "expired"; return "active"; }
function renderDealers(){
  const ts=platform.tenants.slice().sort((a,b)=>a.name.localeCompare(b.name)); const week=addDays(todayISO(),-7);
  return `<div class="topbar"><h1>Dealers</h1><button class="btn" onclick="importDealerBackup()">Restore a dealer from backup</button><button class="btn p" onclick="editDealer()">Add dealer</button></div>
  <div class="grid g4" style="margin-bottom:16px"><div class="card stat"><div class="v">${ts.length}</div><div class="l">Dealers on the platform</div></div><div class="card stat t"><div class="v">${ts.filter(t=>tenantState(t)==="active").length}</div><div class="l">Active</div></div><div class="card stat a"><div class="v">${ts.filter(t=>tenantState(t)!=="active").length}</div><div class="l">Suspended or expired</div></div><div class="card stat b"><div class="v">${ts.filter(t=>t.stats?.lastActive>=week).length}</div><div class="l">Active in the last 7 days</div></div></div>
  <div class="card">${table(ts,[["Code",t=>`<b>${esc(t.code)}</b>`],["Business",t=>`<b>${esc(t.name)}</b><div class="muted">${esc(t.contact||"")}${t.email?" · "+esc(t.email):""}${t.phone?" · "+esc(t.phone):""}</div>`],["Plan",t=>esc(t.plan||"—")],["Status",t=>statusTag(tenantState(t))],["Expires",t=>t.expires?dateShort(t.expires):"—"],["Activity",t=>t.stats?.lastActive?`${dateShort(t.stats.lastActive)}<div class="muted small">${t.stats.invoices||0} invoices · ${t.stats.staff||0} staff</div>`:'<span class="muted">none yet</span>'],["",t=>`<div class="bgroup"><button class="btn s p" onclick="openDealer('${t.id}')">Open</button><button class="btn s" onclick="dealerSignInInfo('${t.id}')" title="Store code and sign-in address to give the dealer">Sign-in info</button><button class="btn s" onclick="editDealer('${t.id}')">Edit</button><button class="btn s" onclick="dealerMenu('${t.id}')">More</button></div>`]],"No dealers yet. Add your first dealer — they'll sign in with the store code you give them.")}</div>
  <p class="muted small" style="margin-top:12px">Each dealer's data is kept in its own namespace and is only reachable through its store code and staff PINs. For dealers that need a fully separate deployment, use Export to move their data into their own copy of the software.</p>`;
}
function editDealer(id){
  const t=platform.tenants.find(x=>x.id===id)||{name:"",code:"",plan:"Standard",status:"active",contact:"",email:"",phone:"",expires:"",notes:"",address:"",taxRate:8.25};
  modal(`<h2>${id?"Edit dealer":"Add dealer"}</h2>
  <div class="grid g2"><div class="field"><label class="f">Business name</label><input type="text" id="td_name" value="${esc(t.name)}" oninput="if(!'${id||""}')document.getElementById('td_code').value=makeCode(this.value)"></div><div class="field"><label class="f">Store code (what staff type to sign in)</label><input type="text" id="td_code" value="${esc(t.code)}" style="text-transform:uppercase"></div></div>
  <div class="grid g3"><div class="field"><label class="f">Plan</label><input type="text" id="td_plan" value="${esc(t.plan||"")}" list="plans"><datalist id="plans"><option value="Starter"><option value="Standard"><option value="Pro"><option value="Enterprise"></datalist></div><div class="field"><label class="f">Status</label><select id="td_status">${optsList(["active","suspended","trial"],t.status)}</select></div><div class="field"><label class="f">Access expires (optional)</label><input type="date" id="td_exp" value="${t.expires||""}"></div></div>
  <div class="grid g3"><div class="field"><label class="f">Owner / contact</label><input type="text" id="td_contact" value="${esc(t.contact)}"></div><div class="field"><label class="f">Email</label><input type="email" id="td_email" value="${esc(t.email)}"></div><div class="field"><label class="f">Phone</label><input type="tel" id="td_phone" value="${esc(t.phone)}"></div></div>
  ${id?"":`<div class="grid g2"><div class="field"><label class="f">Store address</label><input type="text" id="td_addr" value="${esc(t.address)}"></div><div class="field"><label class="f">Sales tax %</label><input type="number" step="0.001" id="td_tax" value="${t.taxRate}"></div></div>
  <h3 style="margin:6px 0 8px">Owner login for this dealer (they add their managers and staff inside the store)</h3><div class="grid g2"><div class="field"><label class="f">Owner name</label><input type="text" id="td_mname" placeholder="e.g. Sam"></div><div class="field"><label class="f">Owner PIN (4–8 digits)</label><input type="text" id="td_mpin" inputmode="numeric" placeholder="e.g. 4321"></div></div>
  <div class="chk" style="margin-bottom:8px"><input type="checkbox" id="td_sample"><label for="td_sample">Load sample furniture & mattress data so they can explore (demo stores only — not for a real dealer)</label></div>`}
  <div class="field"><label class="f">Notes (internal)</label><input type="text" id="td_notes" value="${esc(t.notes||"")}"></div>
  <div class="msg" id="td_msg"></div>
  <div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" id="td_go" onclick="saveDealer('${id||""}')">${id?"Save":"Create dealer"}</button></div>`,true);
}
async function saveDealer(id){
  const msg=document.getElementById("td_msg"); const say=t=>{ if(msg) msg.textContent=t; toast(t,true); };
  const name=fv("td_name").trim(), code=fv("td_code").trim().toUpperCase(); if(!name) return say("Business name is required."); if(!/^[A-Z0-9-]{2,10}$/.test(code)) return say("Store code: 2–10 letters or numbers.");
  if(platform.tenants.some(x=>x.code===code&&x.id!==id)) return say("That store code is already used.");
  const btn=document.getElementById("td_go"); if(btn){ btn.disabled=true; btn.textContent="Working…"; }
  try{
    if(id){ const t=platform.tenants.find(x=>x.id===id); Object.assign(t,{name,code,plan:fv("td_plan"),status:fv("td_status"),expires:fv("td_exp"),contact:fv("td_contact"),email:fv("td_email"),phone:fv("td_phone"),notes:fv("td_notes")}); saveTenant(t); closeModal(); render(); return; }
    const mname=fv("td_mname").trim(), mpin=fv("td_mpin").trim(); if(!mname) throw new Error("Enter the owner's name."); if(mpin&&!/^\d{4,8}$/.test(mpin)) throw new Error("Owner PIN must be 4–8 digits.");
    const t={id:uid(),name,code,plan:fv("td_plan"),status:fv("td_status"),expires:fv("td_exp"),contact:fv("td_contact"),email:fv("td_email"),phone:fv("td_phone"),notes:fv("td_notes"),created:todayISO(),createdBy:session.adminId,stats:{}};
    saveTenant(t);
    // provision the dealer's namespace
    tenantId=t.id; COLLS.forEach(c=>S[c]=[]);
    const st=storeSettings(); st.name=name; st.address=fv("td_addr"); st.taxRate=fnum("td_tax")||st.taxRate; st.skuPrefix=code.replace(/[^A-Z0-9]/g,"").slice(0,4)||"SKU"; await save("settings",st);
    await save("staff",{id:uid(),name:mname,role:"owner",pin:mpin,commType:"sales",rate:0,active:true});
    if(fchk("td_sample")) await loadSample(true);
    t.stats={invoices:S.invoices.length,staff:S.staff.length,lastActive:""}; saveTenant(t);
    clearTimeout(saveT); try{ localStorage.setItem("ht_tenant:"+t.id,JSON.stringify(S)); }catch(e){}
    tenantId=""; COLLS.forEach(c=>S[c]=[]);
    closeModal(); render(); toast(`${name} created — store code ${code}`);
  }catch(e){ say(e.message||String(e)); if(btn){ btn.disabled=false; btn.textContent=id?"Save":"Create dealer"; } }
}
async function withTenant(tid,fn){ const prev=tenantId; tenantId=tid; loadTenantLocal(tid); await loadTenantShared(tid); try{ await fn(); } finally{ clearTimeout(saveT); try{ localStorage.setItem("ht_tenant:"+tid,JSON.stringify(S)); }catch(e){} tenantId=prev; COLLS.forEach(c=>S[c]=[]); } }
async function openDealer(id){ const t=platform.tenants.find(x=>x.id===id); toast("Opening "+t.name+"…"); tenantId=t.id; loadTenantLocal(t.id); await loadTenantShared(t.id); setSession({kind:"staff",tenantId:t.id,staffId:"support",support:true,adminId:session.adminId,at:Date.now()}); view="dashboard"; render(); }
function backToAdmin(){ const adminId=session.adminId; cur=null; tenantId=""; COLLS.forEach(c=>S[c]=[]); setSession({kind:"admin",adminId,at:Date.now()}); view="admin"; render(); }
function dealerMenu(id){ const t=platform.tenants.find(x=>x.id===id);
  modal(`<h2>${esc(t.name)} <span class="muted">· ${esc(t.code)}</span></h2><p class="muted">${esc(t.plan||"")} · ${statusTag(tenantState(t))} · created ${dateShort(t.created||"")}${t.notes?" · "+esc(t.notes):""}</p>
  <div class="grid g2" style="gap:8px">
    <button class="btn" onclick="toggleDealer('${id}')">${t.status==="active"?"Suspend access":"Reactivate access"}</button>
    <button class="btn" onclick="resetDealerPin('${id}')">Reset a staff PIN</button>
    <button class="btn" onclick="exportDealer('${id}')">Export data (backup)</button>
    <button class="btn" onclick="dealerStats('${id}')">Usage summary</button>
    <button class="btn" onclick="dealerLink('${id}')">Sign-in link & instructions</button>
    <button class="btn d" onclick="deleteDealer('${id}')">Delete dealer and all data</button>
  </div><div class="actions"><button class="btn" onclick="closeModal()">Close</button></div>`);
}
function dealerLink(id){ const t=platform.tenants.find(x=>x.id===id); const base=location.href.split('#')[0]; const link=base+'#store/'+encodeURIComponent(t.code); const txt=`${platform.config.softwareName||'POS'} — sign-in for ${t.name}\n\nOpen this link on each register, tablet or phone:\n${link}\n\nStore code: ${t.code}\nTap your name and enter your PIN. Managers add staff and PINs under Settings → Staff & PINs.${platform.config.support?'\n\nSupport: '+platform.config.support:''}`; modal(`<h2>Sign-in link — ${esc(t.name)}</h2><p class="muted">Send this to the dealer. Their devices remember the store, so staff only ever see their own store's sign-in.</p><textarea rows="7" style="width:100%" id="dl_txt">${esc(txt)}</textarea><div class="actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="(async()=>{try{await navigator.clipboard.writeText(document.getElementById('dl_txt').value);toast('Copied')}catch(e){toast('Select the text and copy it',true)}})()">Copy</button>${t.email?`<a class="btn p" href="mailto:${esc(t.email)}?subject=${encodeURIComponent('Your '+(platform.config.softwareName||'POS')+' sign-in')}&body=${encodeURIComponent(txt)}">Email dealer</a>`:''}</div>`); }
function toggleDealer(id){ const t=platform.tenants.find(x=>x.id===id); t.status=t.status==="active"?"suspended":"active"; saveTenant(t); closeModal(); render(); toast(`${t.name}: ${t.status}`); }
async function resetDealerPin(id){ closeModal(); await withTenant(id,async()=>{ const staff=S.staff.slice(); await new Promise(res=>{ modal(`<h2>Reset PIN</h2><div class="field"><label class="f">Staff member</label><select id="rp_who">${opts(staff,"",x=>x.name+" ("+(ROLES[x.role]||x.role)+")")}</select></div><div class="field"><label class="f">New PIN (4–8 digits, blank = none)</label><input type="text" id="rp_pin" inputmode="numeric"></div><div class="actions"><button class="btn" onclick="closeModal();window._rpDone()">Cancel</button><button class="btn p" onclick="window._rpSave()">Save</button></div>`); window._rpDone=res; window._rpSave=async()=>{ const s=byId("staff",fv("rp_who")); const pin=fv("rp_pin").trim(); if(pin&&!/^\d{4,8}$/.test(pin)) return toast("PIN must be 4–8 digits.",true); if(s){ s.pin=pin; await save("staff",s); toast("PIN updated for "+s.name); } closeModal(); res(); }; }); }); }
async function exportDealer(id){ closeModal(); const t=platform.tenants.find(x=>x.id===id); await withTenant(id,async()=>{ saveFile(`${t.code}-backup-${todayISO()}.json`,JSON.stringify(Object.assign({_dealer:{name:t.name,code:t.code,plan:t.plan}},S),null,2)); }); }
async function dealerStats(id){ closeModal(); const t=platform.tenants.find(x=>x.id===id); await withTenant(id,async()=>{ const month=todayISO().slice(0,7); const inv=S.invoices.filter(i=>!["void","quote"].includes(i.status)); const m=inv.filter(i=>i.date.startsWith(month)); modal(`<h2>${esc(t.name)} — usage</h2><div class="grid g2"><div class="card stat plain"><div class="v">${inv.length}</div><div class="l">Invoices all time</div></div><div class="card stat plain"><div class="v">${money(m.reduce((a,i)=>a+invTotals(i).taxable,0))}</div><div class="l">Sales this month (${m.length} invoices)</div></div><div class="card stat plain"><div class="v">${S.products.length}</div><div class="l">Items in inventory</div></div><div class="card stat plain"><div class="v">${S.staff.length}</div><div class="l">Staff accounts · ${S.trucks.length} trucks</div></div></div><p class="muted small" style="margin-top:10px">Customers ${S.customers.length} · deliveries ${S.deliveries.length} · open follow-ups ${S.followups.filter(f=>f.status==="open").length}</p><div class="actions"><button class="btn" onclick="closeModal()">Close</button></div>`); t.stats=Object.assign(t.stats||{},{invoices:inv.length,staff:S.staff.length}); saveTenant(t); }); }
async function deleteDealer(id){ const t=platform.tenants.find(x=>x.id===id); closeModal(); if(!confirm(`Delete ${t.name} (${t.code}) and ALL of its data? This cannot be undone.`)) return; if(prompt("Type the store code to confirm:")!==t.code) return toast("Cancelled.");
  await withTenant(id,async()=>{ for(const c of COLLS) for(const d of S[c].slice()) await remove(c,d.id); }); try{ localStorage.removeItem("ht_tenant:"+id); }catch(e){}
  platform.tenants=platform.tenants.filter(x=>x.id!==id); savePlatformLocal(); if(db){ queueWrite("tenants",id,null); if(t.code) queueWrite("tenantCodes",String(t.code).toUpperCase(),null); } render(); toast(t.name+" deleted"); }
function importDealerBackup(){ modal(`<h2>Restore a dealer from backup</h2><p class="muted">Paste a dealer backup file (from Export, or from a dealer's own Settings → Back up). A new dealer is created with its data.</p><div class="grid g2"><div class="field"><label class="f">Business name</label><input type="text" id="ib_name"></div><div class="field"><label class="f">Store code</label><input type="text" id="ib_code" style="text-transform:uppercase"></div></div><textarea id="ib_json" rows="8" placeholder="{ ... }"></textarea><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="doImportDealer()">Create dealer from backup</button></div>`,true); }
async function doImportDealer(){ let o; try{ o=JSON.parse(fv("ib_json")); if(!o.products||!o.staff) throw 0; }catch(e){ return toast("That doesn't look like a backup file.",true); } const name=fv("ib_name").trim()||o._dealer?.name||"Restored store"; let code=fv("ib_code").trim().toUpperCase()||makeCode(name); if(platform.tenants.some(t=>t.code===code)) return toast("Store code already in use.",true);
  const t={id:uid(),name,code,plan:o._dealer?.plan||"Standard",status:"active",contact:"",email:"",phone:"",expires:"",notes:"Restored from backup "+todayISO(),created:todayISO(),createdBy:session.adminId,stats:{}}; saveTenant(t);
  tenantId=t.id; COLLS.forEach(c=>S[c]=Array.isArray(o[c])?o[c]:[]); for(const c of COLLS) for(const d of S[c]) if(db) queueWrite(tpath(c),d.id,clone(d)); if(!S.staff.some(s=>s.role==="manager"||s.role==="owner")&&S.staff.length){ S.staff[0].role="owner"; queueWrite(tpath("staff"),S.staff[0].id,clone(S.staff[0])); }
  clearTimeout(saveT); try{ localStorage.setItem("ht_tenant:"+t.id,JSON.stringify(S)); }catch(e){} t.stats={invoices:S.invoices.length,staff:S.staff.length,lastActive:""}; saveTenant(t); tenantId=""; COLLS.forEach(c=>S[c]=[]); closeModal(); render(); toast(`${name} restored — store code ${code}`); }
function renderAdmins(){ const admins=platform.config.admins||[]; return `<div class="topbar"><h1>Administrators</h1><button class="btn p" onclick="editAdmin()">Add administrator</button></div><div class="card"><p class="muted">Administrators own the software: they create dealers, suspend access, reset PINs and can open any dealer in a support session.</p>${table(admins,[["Name",a=>`<b>${esc(a.name)}</b>${a.id===session.adminId?' <span class="tag ok">you</span>':""}`],["Added",a=>dateShort(a.created||"")],["PIN",a=>a.pin?"set":'<span class="tag warn">none</span>'],["",a=>`<button class="btn s" onclick="editAdmin('${a.id}')">Edit</button>`]],"")}</div>`; }
function editAdmin(id){ const a=(platform.config.admins||[]).find(x=>x.id===id)||{name:"",pin:""}; modal(`<h2>${id?"Edit administrator":"Add administrator"}</h2><div class="grid g2"><div class="field"><label class="f">Name</label><input type="text" id="ad_name" value="${esc(a.name)}"></div><div class="field"><label class="f">PIN (4–8 digits)</label><input type="password" id="ad_pin" inputmode="numeric" value="${esc(a.pin||"")}"></div></div><div class="actions">${id&&id!==session.adminId?`<button class="btn d" onclick="confirmDo('Remove this administrator?',()=>{const c=platform.config;c.admins=c.admins.filter(x=>x.id!=='${id}');savePlatformConfig(c);closeModal();render()})">Remove</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="saveAdmin('${id||""}')">Save</button></div>`); }
function saveAdmin(id){ const name=fv("ad_name").trim(), pin=fv("ad_pin").trim(); if(!name) return toast("Name is required.",true); if(!/^\d{4,8}$/.test(pin)) return toast("PIN must be 4–8 digits.",true); const c=platform.config; c.admins=c.admins||[]; const a=c.admins.find(x=>x.id===id); if(a){ a.name=name; a.pin=pin; } else c.admins.push({id:uid(),name,pin,created:todayISO()}); savePlatformConfig(c); closeModal(); render(); }
function publicSignInUrl(){ try{ const o=location.origin+location.pathname; if(/homestorepos\.com/.test(o)) return "https://app.homestorepos.com/signin"; return o.replace(/index\.html$/,"")+"#signin"; }catch(e){ return "https://app.homestorepos.com/signin"; } }
function dealerSignInInfo(id){ const t=platform.tenants.find(x=>x.id===id); if(!t) return; const url=publicSignInUrl(); const base=url.replace(/\/signin$/,"").replace(/#signin$/,""); const direct=base.replace(/\/$/,"")+"/#store/"+encodeURIComponent(t.code); const msg="Welcome to HomeStore POS!\n\nOn each register, tablet or phone, open this link once — it opens your store's sign-in directly and the device remembers it:\n"+direct+"\n\nIf you ever need it, the general sign-in page is "+url+" and your store code is "+t.code+".\n\nTap your name and enter your PIN to start."; window._welcomeMsg=msg; window._directLink=direct; modal(`<h2>${esc(t.name)} — sign-in details</h2><div class="grid g2"><div><div class="field"><label class="f">Public sign-in address</label><input type="text" value="${esc(url)}" readonly onclick="this.select()"></div><div class="field"><label class="f">Store code</label><input type="text" value="${esc(t.code)}" readonly onclick="this.select()" style="font-size:22px;font-weight:800;letter-spacing:.08em"></div><div class="field"><label class="f">Direct link (opens this store's sign-in straight away)</label><input type="text" value="${esc(direct)}" readonly onclick="this.select()"></div></div><div style="text-align:center"><img src="https://api.qrserver.com/v1/create-qr-code/?size=170x170&data=${encodeURIComponent(direct)}" alt="QR" style="width:170px;height:170px;border:1px solid var(--line);border-radius:8px" onerror="this.style.display='none'"><div class="muted small">Scan with a phone or tablet to open the store</div></div></div><div class="actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="navigator.clipboard&&navigator.clipboard.writeText(window._welcomeMsg).then(()=>toast('Message copied — paste it into an email or text'))">Copy welcome message</button><button class="btn p" onclick="navigator.clipboard&&navigator.clipboard.writeText(window._directLink).then(()=>toast('Link copied'))">Copy direct link</button></div>`,true); }
function renderPlatformSettings(){ const c=platform.config; return `<div class="topbar"><h1>Software settings</h1></div><div class="card" style="max-width:720px"><div class="field"><label class="f">Software name (shown on every sign-in screen)</label><input type="text" id="ps_name" value="${esc(c.softwareName||"")}"></div><div class="field"><label class="f">Support contact shown to dealers</label><input type="text" id="ps_support" value="${esc(c.support||"")}" placeholder="e.g. support@yourcompany.com · 800-555-0100"></div><div class="field"><label class="f">Relay service URL (vendor APIs, live stock, card terminals, address lookup)</label><input type="url" id="ps_relay" value="${esc(c.relayUrl||"")}" placeholder="https://relay.homestorepos.com"><div class="muted small">Leave blank until the relay is deployed. Dealers can still set their own card relay under Settings → Payments.</div></div><div class="field"><label class="f">Tagline (sign-in screens)</label><input type="text" id="ps_tag" value="${esc(c.tagline||"Sell more. Run smarter.")}"></div><div class="field"><label class="f">Software logo (PNG/SVG, shown on the console and every sign-in screen)</label><input type="file" accept="image/*" onchange="(function(inp){const f=inp.files&&inp.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const c=platform.config;c.softwareLogo=String(r.result);savePlatformConfig(c);render();toast('Logo saved')};r.readAsDataURL(f)})(this)"><div style="margin-top:6px">${c.softwareLogo?`<img src="${c.softwareLogo}" style="max-height:60px;background:#fff;padding:6px;border-radius:8px;border:1px solid var(--line)"> <a href="#" class="small" onclick="const c=platform.config;delete c.softwareLogo;savePlatformConfig(c);render();return false">remove</a>`:'<span class="muted small">Using the built-in HomeStore POS logo — upload a file to replace it.</span>'}</div></div><button class="btn p" onclick="const c=platform.config;c.softwareName=fv('ps_name').trim()||c.softwareName;c.support=fv('ps_support');c.tagline=fv('ps_tag').trim();c.relayUrl=fv('ps_relay').trim();savePlatformConfig(c);render();toast('Saved')">Save</button>
  <h3 style="margin:18px 0 8px">How access works</h3><p class="muted small">Dealers sign in with their store code, then tap their name and enter their PIN. Each dealer's inventory, customers, invoices, deliveries and staff live in a separate namespace. Suspending a dealer blocks sign-in immediately; expiring access does the same on the date you set. Use Export before deleting a dealer if you may need their records.</p>
  <h3 style="margin:18px 0 8px">Data</h3><div class="row"><button class="btn fx" onclick="saveFile('platform-'+todayISO()+'.json',JSON.stringify(platform,null,2))">Back up dealer list & admins</button></div></div>`; }
