/* ============================================================
   OPTIONAL MODULES (per-dealer toggles in Settings → Features)
   promotions · locations & transfers · ups/close rate · stock counts
   inventory analysis & scorecards · accounting export · time clock
   quote follow-up · branding · route export · delivery zones
   ============================================================ */
const FEATURES=[["promotions","Promotions & sale pricing","Date-ranged sales by item or category; POS and price tags apply them automatically."],["locations","Multiple locations & transfers","Track stock per showroom / warehouse and move it with transfer sheets."],["ups","Ups & close rate","Salespeople log walk-ins; reports show close rate and average ticket."],["counts","Physical stock counts","Count sheets by bin, blind counts, one-click adjustments."],["analysis","Inventory analysis & scorecards","Aging, turns, GMROI, dead stock, vendor performance, team scorecards."],["accounting","Accounting export","Sales journal CSV and QuickBooks IIF for the bookkeeper."],["timeclock","Time clock","Clock in/out from the register; hours by staff."],["warehouse","Warehouse picking & storage","For stores with a real warehouse: storage bins and zones, put-away on receiving, daily pick lists with scan-to-pick, and staging areas for orders waiting to be loaded or handed over."]];
const feat=k=>!!(storeSettings().features||{})[k];
const LOC_COLLS=["promotions","locations","transfers","ups","counts","timeclock"];
LOC_COLLS.forEach(c=>{ if(!COLLS.includes(c)) COLLS.push(c); if(!S[c]) S[c]=[]; });

/* ---------- promotions ---------- */
function activePromos(){ const t=todayISO(); return S.promotions.filter(p=>p.active!==false&&(!p.start||p.start<=t)&&(!p.end||p.end>=t)); }
function promoFor(p){ if(!feat("promotions")||!p) return null; const ps=activePromos().filter(x=>x.scope==="all"||(x.scope==="category"&&x.category===p.category)||(x.scope==="items"&&(x.itemIds||[]).includes(p.id))); if(!ps.length) return null; return ps.map(x=>({x,price:promoPrice(p,x)})).sort((a,b)=>a.price-b.price)[0].x; }
function promoPrice(p,x){ return x.type==="pct"?round2(p.price*(1-x.value/100)):round2(Math.max(0,p.price-x.value)); }
function effectivePrice(p){ const x=promoFor(p); let v=x?promoPrice(p,x):p.price; if(p&&p.map&&v<+p.map) v=+p.map; return v; }
function renderPromotions(){ const t=todayISO(); return `<div class="toolbar"><span class="grow muted">Sales apply automatically at the register and on printed tags while they're running.</span><button class="btn p" onclick="editPromo()">New promotion</button></div><div class="card">${table(S.promotions.slice().sort((a,b)=>String(b.start).localeCompare(String(a.start))),[["Promotion",x=>`<b>${esc(x.name)}</b><div class="muted">${x.type==="pct"?x.value+"% off":money(x.value)+" off"} · ${x.scope==="all"?"everything":x.scope==="category"?esc(x.category):(x.itemIds||[]).length+" items"}</div>`],["Runs",x=>`${x.start?dateShort(x.start):"now"} – ${x.end?dateShort(x.end):"open"}`],["Status",x=>statusTag(x.active===false?"paused":(x.start&&x.start>t)?"scheduled":(x.end&&x.end<t)?"ended":"active")],["",x=>`<button class="btn s" onclick="editPromo('${x.id}')">Edit</button> <button class="btn s" onclick="(async()=>{const p=byId('promotions','${x.id}');p.active=p.active===false;await save('promotions',p);render()})()">${x.active===false?"Resume":"Pause"}</button>`]],"No promotions yet.")}</div>`; }
function editPromo(id){ const x=byId("promotions",id)||{name:"",type:"pct",value:10,scope:"category",category:"Mattresses",itemIds:[],start:todayISO(),end:addDays(todayISO(),14),active:true,tagLine:"SALE"};
  modal(`<h2>${id?"Edit promotion":"New promotion"}</h2><div class="grid g2"><div class="field"><label class="f">Name</label><input type="text" id="pr_name" value="${esc(x.name)}" placeholder="Labor Day Sale"></div><div class="field"><label class="f">Tag wording</label><input type="text" id="pr_tag" value="${esc(x.tagLine||"SALE")}"></div></div>
  <div class="grid g3"><div class="field"><label class="f">Discount</label><select id="pr_type"><option value="pct" ${x.type==="pct"?"selected":""}>Percent off</option><option value="amount" ${x.type==="amount"?"selected":""}>Dollars off</option></select></div><div class="field"><label class="f">Value</label><input type="number" step="0.01" id="pr_val" value="${x.value}"></div><div class="field"><label class="f">Applies to</label><select id="pr_scope" onchange="document.getElementById('pr_cat').style.display=this.value==='category'?'':'none';document.getElementById('pr_items').style.display=this.value==='items'?'':'none'"><option value="all" ${x.scope==="all"?"selected":""}>Everything</option><option value="category" ${x.scope==="category"?"selected":""}>A category</option><option value="items" ${x.scope==="items"?"selected":""}>Specific items</option></select></div></div>
  <div class="field" id="pr_cat" style="${x.scope==="category"?"":"display:none"}"><label class="f">Category</label><select id="pr_catv">${optsList(categoryNames(),x.category)}</select></div>
  <div class="field" id="pr_items" style="${x.scope==="items"?"":"display:none"}"><label class="f">Items (tick)</label><div style="max-height:200px;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:8px">${S.products.map(p=>`<label class="chk" style="margin-bottom:4px"><input type="checkbox" class="pr_item" value="${p.id}" ${(x.itemIds||[]).includes(p.id)?"checked":""}> ${esc(p.sku)} ${esc(p.name)} <span class="muted">${money(p.price)}</span></label>`).join("")}</div></div>
  <div class="grid g2"><div class="field"><label class="f">Starts</label><input type="date" id="pr_start" value="${x.start||""}"></div><div class="field"><label class="f">Ends</label><input type="date" id="pr_end" value="${x.end||""}"></div></div>
  <div class="actions">${id?`<button class="btn d" onclick="confirmDo('Delete promotion?',()=>{remove('promotions','${id}');closeModal();render()})">Delete</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="savePromo('${id||""}')">Save</button></div>`,true); }
async function savePromo(id){ const x=Object.assign({},byId("promotions",id)||{active:true},{id:id||undefined,name:fv("pr_name").trim(),tagLine:fv("pr_tag").trim()||"SALE",type:fv("pr_type"),value:fnum("pr_val"),scope:fv("pr_scope"),category:fv("pr_catv"),itemIds:[...document.querySelectorAll(".pr_item:checked")].map(e=>e.value),start:fv("pr_start"),end:fv("pr_end")}); if(!x.name) return toast("Name is required.",true); if(x.value<=0) return toast("Enter a discount value.",true); await save("promotions",x); closeModal(); render(); }

/* ---------- locations & transfers ---------- */
function locations(){ return S.locations.slice().sort((a,b)=>(b.isDefaultSale?1:0)-(a.isDefaultSale?1:0)||a.name.localeCompare(b.name)); }
function defaultLoc(kind){ const ls=locations(); if(!ls.length) return null; if(kind==="receive") return ls.find(l=>l.isDefaultReceive)||ls.find(l=>l.type==="warehouse")||ls[0]; return ls.find(l=>l.isDefaultSale)||ls[0]; }
function locName(id){ return byId("locations",id)?.name||"—"; }
function stockAt(p,locId){ return (p.stockBy||{})[locId]||0; }
function ensureStockBy(p){ if(!feat("locations")) return; if(!p.stockBy){ const d=defaultLoc("receive"); p.stockBy=d?{[d.id]:p.stock||0}:{}; } }
const isDisplayLoc=l=>!!(l&&(l.display||(l.type==="showroom"&&l.display!==false)));
function deliverableStock(p){ if(!feat("locations")||!locations().length||!p.stockBy) return p.stock||0; return locations().filter(l=>!isDisplayLoc(l)).reduce((a,l)=>a+stockAt(p,l.id),0); }
function floorStock(p){ if(!feat("locations")||!locations().length||!p.stockBy) return 0; return locations().filter(isDisplayLoc).reduce((a,l)=>a+stockAt(p,l.id),0); }
function stockMove(p,delta,locId){ if(feat("locations")&&locations().length){ ensureStockBy(p); let loc=locId; if(!loc){ const sellable=locations().filter(l=>!isDisplayLoc(l)); const d=delta<0?(sellable.find(l=>stockAt(p,l.id)>=-delta&&l.isDefaultSale)||sellable.find(l=>stockAt(p,l.id)>=-delta)||locations().find(l=>stockAt(p,l.id)>=-delta)||defaultLoc("sale")):defaultLoc("receive"); loc=d?d.id:null; } if(loc){ p.stockBy[loc]=(p.stockBy[loc]||0)+delta; p.stock=Object.values(p.stockBy).reduce((a,n)=>a+n,0); return loc; } } p.stock=(p.stock||0)+delta; return ""; }
function setStockTotal(p,n,locId){ if(feat("locations")&&locations().length){ ensureStockBy(p); const cur=p.stock||0; stockMove(p,n-cur,locId); } else p.stock=n; }
function stockLabel(p){ if(!feat("locations")||!locations().length) return String(p.stock||0); return `${p.stock||0}<div class="muted small">${locations().map(l=>`${esc(l.name.slice(0,10))} ${stockAt(p,l.id)}${isDisplayLoc(l)?" (floor)":""}`).join(" · ")}</div>`; }
function renderLocations(){ return `<div class="toolbar"><span class="grow muted">Stock is tracked per location. Sales pull from the default sale location, receiving lands in the default receiving location.</span><button class="btn" onclick="editLocation()">Add location</button><button class="btn p" onclick="newTransfer()">New transfer</button></div>
  <div class="grid g2"><div class="card"><h2>Locations</h2>${table(locations(),[["Name",l=>`<b>${esc(l.name)}</b><div class="muted">${esc(l.type)}${l.address?" · "+esc(l.address):""}</div>`],["Role",l=>`${isDisplayLoc(l)?'<span class="tag warn">display floor</span> ':""}${l.isDefaultSale?'<span class="tag ok">sales</span> ':""}${l.isDefaultReceive?'<span class="tag info">receiving</span>':""}`],["On hand",l=>S.products.reduce((a,p)=>a+stockAt(p,l.id),0),"n"],["Value (cost)",l=>money(S.products.reduce((a,p)=>a+stockAt(p,l.id)*(p.cost||0),0)),"n"],["",l=>`<button class="btn s" onclick="editLocation('${l.id}')">Edit</button>`]],"Add your showroom and warehouse(s).")}</div>
  <div class="card"><h2>Transfers</h2>${table(S.transfers.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30),[["Date",t=>dateShort(t.date)],["From → To",t=>`${esc(locName(t.from))} → ${esc(locName(t.to))}`],["Items",t=>t.lines.map(l=>`${l.qty}× ${esc(l.name)}`).join(", ")],["By",t=>esc(staffName(t.by))],["",t=>`<button class="btn s" onclick="printTransfer('${t.id}')">Print</button>`]],"No transfers yet.")}</div></div>`; }
function editLocation(id){ const l=byId("locations",id)||{name:"",type:"warehouse",address:"",isDefaultSale:!S.locations.length,isDefaultReceive:!S.locations.length}; modal(`<h2>${id?"Edit location":"Add location"}</h2><div class="grid g2"><div class="field"><label class="f">Name</label><input type="text" id="lo_name" value="${esc(l.name)}" placeholder="Main warehouse"></div><div class="field"><label class="f">Type</label><select id="lo_type">${optsList(["showroom","warehouse","outlet"],l.type)}</select></div></div><div class="field"><label class="f">Address</label><input type="text" id="lo_addr" value="${esc(l.address)}"></div><div class="chk" style="margin-bottom:6px"><input type="checkbox" id="lo_display" ${isDisplayLoc(l)?"checked":""}><label for="lo_display">Display floor — units here are floor models, shown in the catalog as "on the floor" and not counted as deliverable stock</label></div><div class="chk" style="margin-bottom:6px"><input type="checkbox" id="lo_sale" ${l.isDefaultSale?"checked":""}><label for="lo_sale">Default location sales pull from</label></div><div class="chk"><input type="checkbox" id="lo_recv" ${l.isDefaultReceive?"checked":""}><label for="lo_recv">Default location for receiving</label></div><div class="actions">${id&&S.locations.length>1?`<button class="btn d" onclick="confirmDo('Remove this location? Its stock counts move to the default location.',()=>removeLocation('${id}'))">Remove</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="saveLocation('${id||""}')">Save</button></div>`); }
async function saveLocation(id){ const l=Object.assign({},byId("locations",id)||{},{id:id||undefined,name:fv("lo_name").trim(),type:fv("lo_type"),address:fv("lo_addr"),display:fchk("lo_display"),isDefaultSale:fchk("lo_sale"),isDefaultReceive:fchk("lo_recv")}); if(!l.name) return toast("Name is required.",true); await save("locations",l); for(const o of S.locations){ if(o.id!==l.id){ let ch=false; if(l.isDefaultSale&&o.isDefaultSale){o.isDefaultSale=false;ch=true;} if(l.isDefaultReceive&&o.isDefaultReceive){o.isDefaultReceive=false;ch=true;} if(ch) await save("locations",o); } } closeModal(); render(); }
async function removeLocation(id){ const d=S.locations.find(l=>l.id!==id); for(const p of S.products){ if(p.stockBy&&p.stockBy[id]){ p.stockBy[d.id]=(p.stockBy[d.id]||0)+p.stockBy[id]; delete p.stockBy[id]; await save("products",p); } } await remove("locations",id); closeModal(); render(); }
function newTransfer(){ const ls=locations(); if(ls.length<2) return toast("Add at least two locations first.",true); window._tr=[]; modal(`<h2>Transfer stock</h2><div class="grid g2"><div class="field"><label class="f">From</label><select id="tr_from">${opts(ls,ls[0].id)}</select></div><div class="field"><label class="f">To</label><select id="tr_to">${opts(ls,ls[1].id)}</select></div></div><div class="field rel"><label class="f">Add item</label><input type="text" id="tr_q" placeholder="Search…" oninput="trSearch(this.value)" autocomplete="off"><div id="tr_res"></div></div><div id="tr_lines"></div><div class="field"><label class="f">Notes</label><input type="text" id="tr_notes"></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="doTransfer()">Transfer</button></div>`,true); }
function trSearch(q){ q=q.toLowerCase(); const r=document.getElementById("tr_res"); if(!q){r.innerHTML="";return} const from=fv("tr_from"); const hits=S.products.filter(p=>[p.sku,p.name].join(" ").toLowerCase().includes(q)).slice(0,8); r.innerHTML=`<div class="search-res">${hits.map(p=>`<div onmousedown="trAdd('${p.id}')"><span><b>${esc(p.sku)}</b> ${esc(p.name)}</span><span class="muted">${stockAt(p,from)} at source</span></div>`).join("")}</div>`; }
function trAdd(pid){ const p=byId("products",pid); const ex=window._tr.find(l=>l.productId===pid); if(ex) ex.qty++; else window._tr.push({productId:pid,sku:p.sku,name:p.name,qty:1}); document.getElementById("tr_q").value=""; document.getElementById("tr_res").innerHTML=""; trRender(); }
function trRender(){ document.getElementById("tr_lines").innerHTML=window._tr.map((l,i)=>`<div class="row" style="padding:6px 0;border-bottom:1px solid var(--line2)"><span>${esc(l.name)}</span><input type="number" min="1" value="${l.qty}" style="max-width:80px" onchange="window._tr[${i}].qty=+this.value||1"><button class="btn s fx" onclick="window._tr.splice(${i},1);trRender()">✕</button></div>`).join("")||`<p class="muted">No items yet.</p>`; }
async function doTransfer(){ const from=fv("tr_from"), to=fv("tr_to"); if(from===to) return toast("Pick two different locations.",true); if(!window._tr.length) return toast("Add items.",true); for(const l of window._tr){ const p=byId("products",l.productId); if(stockAt(p,from)<l.qty) return toast(`Only ${stockAt(p,from)} of ${p.name} at ${locName(from)}.`,true); } for(const l of window._tr){ const p=byId("products",l.productId); stockMove(p,-l.qty,from); stockMove(p,l.qty,to); await save("products",p); } const t=await save("transfers",{id:uid(),date:todayISO(),from,to,lines:window._tr,notes:fv("tr_notes"),by:session.staffId}); closeModal(); render(); toast("Transfer recorded"); printTransfer(t.id); }
function printTransfer(id){ const t=byId("transfers",id); printHTML(`<div class="page"><h1>Transfer sheet</h1><p>${esc(storeSettings().name)} · ${dateFmt(t.date)} · ${esc(locName(t.from))} → ${esc(locName(t.to))} · by ${esc(staffName(t.by))}</p><table class="ptable"><tr><th>SKU</th><th>Item</th><th class="n">Qty</th><th>Loaded ☐</th><th>Received ☐</th></tr>${t.lines.map(l=>`<tr><td>${esc(l.sku)}</td><td>${esc(l.name)}</td><td class="n">${l.qty}</td><td>☐</td><td>☐</td></tr>`).join("")}</table>${t.notes?`<p>${esc(t.notes)}</p>`:""}<p style="margin-top:30px">Driver: ______________ &nbsp; Received by: ______________</p></div>`); }

/* ---------- ups & close rate ---------- */
function logUp(){ modal(`<h2>Log an up</h2><div class="grid g3"><div class="field"><label class="f">Salesperson</label><select id="up_who">${opts(S.staff.filter(s=>s.active!==false&&s.role!=="driver"),session.staffId)}</select></div><div class="field"><label class="f">Source</label><select id="up_src">${optsList(["Walk-in","Phone","Web lead","Be-back"],"Walk-in")}</select></div><div class="field"><label class="f">Looking for</label><input type="text" id="up_note" placeholder="Queen mattress, sectional…"></div></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{await save('ups',{id:uid(),date:todayISO(),time:new Date().toTimeString().slice(0,5),staffId:fv('up_who'),source:fv('up_src'),note:fv('up_note'),outcome:'pending'});closeModal();render();toast('Up logged')})()">Log</button></div>`); }
async function upSold(inv){ if(!feat("ups")) return; const u=S.ups.filter(x=>x.staffId===inv.salesId&&x.outcome==="pending"&&x.date===todayISO()).pop(); if(u){ u.outcome="sold"; u.invoiceId=inv.id; await save("ups",u); } }
function upsStats(from,to){ return S.staff.filter(s=>s.role!=="driver").map(s=>{ const ups=S.ups.filter(u=>u.staffId===s.id&&u.date>=from&&u.date<=to); const inv=S.invoices.filter(i=>salesShare(i,s.id)>0&&["paid","open","financed","layaway"].includes(i.status)&&i.date>=from&&i.date<=to); const sales=inv.reduce((a,i)=>a+invTotals(i).taxable*salesShare(i,s.id),0); const items=inv.reduce((a,i)=>a+i.lines.filter(l=>!l.service).reduce((x,l)=>x+l.qty,0),0); return {s,ups:ups.length,sold:inv.length,close:ups.length?Math.min(1,inv.length/ups.length):null,avg:inv.length?sales/inv.length:0,items:inv.length?items/inv.length:0,sales}; }); }
function renderUpsToday(){ if(!feat("ups")) return ""; const t=todayISO(); const mine=S.ups.filter(u=>u.date===t&&(isManager()||u.staffId===session.staffId)); return `<div class="card" style="margin-bottom:16px"><div class="row"><div><h2 style="margin:0">Ups today</h2><span class="muted">${mine.length} logged · ${mine.filter(u=>u.outcome==="sold").length} sold${mine.length?` · close rate ${pct(mine.filter(u=>u.outcome==="sold").length/mine.length)}`:""}</span></div><span class="fx"><button class="btn p" onclick="logUp()">Log an up</button></span></div>${mine.length?`<div class="chips" style="margin-top:8px">${mine.map(u=>`<button class="chip ${u.outcome==="sold"?"on":""}" onclick="upOutcome('${u.id}')">${u.time} ${esc(firstName(staffName(u.staffId)))} · ${esc(u.source)}${u.note?" · "+esc(u.note):""} · ${u.outcome}</button>`).join("")}</div>`:""}</div>`; }
function upOutcome(id){ const u=byId("ups",id); modal(`<h2>Up — ${esc(staffName(u.staffId))} ${u.time}</h2><p class="muted">${esc(u.source)}${u.note?" · "+esc(u.note):""}</p><div class="field"><label class="f">Outcome</label><select id="uo">${optsList(["pending","sold","be-back","lost"],u.outcome)}</select></div><div class="actions"><button class="btn d" onclick="remove('ups','${id}');closeModal();render()">Delete</button><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{const u=byId('ups','${id}');u.outcome=fv('uo');await save('ups',u);closeModal();render()})()">Save</button></div>`); }

/* ---------- physical stock counts ---------- */
function startCount(){ const open=S.counts.find(c=>c.status==="open"); if(open) return openCount(open.id); modal(`<h2>Start a stock count</h2><div class="grid g2"><div class="field"><label class="f">Scope</label><select id="ct_scope"><option value="all">All items</option>${categoryNames().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("")}</select></div>${feat("locations")&&locations().length?`<div class="field"><label class="f">Location</label><select id="ct_loc">${opts(locations(),defaultLoc("receive")?.id)}</select></div>`:""}</div><div class="chk"><input type="checkbox" id="ct_blind" checked><label for="ct_blind">Blind count (hide expected quantities on the sheet)</label></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{const scope=fv('ct_scope');const loc=fv('ct_loc');const items=S.products.filter(p=>scope==='all'||p.category===scope).sort((a,b)=>String(a.bin).localeCompare(String(b.bin))||a.sku.localeCompare(b.sku));const c=await save('counts',{id:uid(),date:todayISO(),status:'open',scope,locationId:loc||'',blind:fchk('ct_blind'),by:session.staffId,lines:items.map(p=>({productId:p.id,sku:p.sku,name:p.name,bin:p.bin||'',expected:loc?stockAt(p,loc):(p.stock||0),counted:null}))});closeModal();openCount(c.id)})()">Start</button></div>`); }
function openCount(id){ const c=byId("counts",id); const done=c.lines.filter(l=>l.counted!==null).length; modal(`<h2>Stock count — ${dateShort(c.date)} ${statusTag(c.status)}</h2><p class="muted">${c.scope==="all"?"All items":esc(c.scope)}${c.locationId?" · "+esc(locName(c.locationId)):""} · ${done}/${c.lines.length} counted${c.blind?" · blind":""}</p><div class="row" style="margin-bottom:8px"><input type="text" id="ct_q" placeholder="Jump to SKU or scan…" oninput="ctFilter(this.value)"><button class="btn fx" onclick="openScanner(v=>{const i=document.querySelector('[data-sku=\\''+v.replace(/'/g,'')+'\\']');if(i){i.focus();i.select()}else toast('Not on this count',true)})">Scan</button><button class="btn fx" onclick="printCountSheet('${id}')">Print sheet</button></div>
  <div class="tblwrap" style="max-height:55vh;overflow:auto"><table><thead><tr><th>Bin</th><th>SKU</th><th>Item</th>${c.blind?"":'<th class="n">Expected</th>'}<th class="n">Counted</th></tr></thead><tbody>${c.lines.map((l,i)=>`<tr class="ctrow" data-k="${esc((l.sku+" "+l.name+" "+l.bin).toLowerCase())}"><td>${esc(l.bin)}</td><td>${esc(l.sku)}</td><td>${esc(l.name)}</td>${c.blind?"":`<td class="n">${l.expected}</td>`}<td class="n"><input type="number" data-sku="${esc(l.sku)}" value="${l.counted===null?"":l.counted}" style="width:80px" onchange="(function(v){const c=byId('counts','${id}');c.lines[${i}].counted=v===''?null:+v;save('counts',c)})(this.value)"></td></tr>`).join("")}</tbody></table></div>
  <div class="actions">${c.status==="open"?`<button class="btn d" onclick="confirmDo('Discard this count?',()=>{remove('counts','${id}');closeModal();render()})">Discard</button>`:""}<button class="btn" onclick="closeModal()">Close</button>${c.status==="open"?`<button class="btn p" onclick="applyCount('${id}')">Review & apply</button>`:""}</div>`,true); }
function ctFilter(q){ q=q.toLowerCase(); document.querySelectorAll(".ctrow").forEach(r=>{ r.style.display=!q||r.dataset.k.includes(q)?"":"none"; }); }
function applyCount(id){ const c=byId("counts",id); const diffs=c.lines.filter(l=>l.counted!==null&&l.counted!==l.expected); modal(`<h2>Count variances</h2><p class="muted">${c.lines.filter(l=>l.counted!==null).length} counted · ${diffs.length} differ from the system. Uncounted items are left unchanged.</p>${table(diffs,[["SKU",l=>esc(l.sku)],["Item",l=>esc(l.name)],["System",l=>l.expected,"n"],["Counted",l=>l.counted,"n"],["Change",l=>`<b style="color:${l.counted>l.expected?"var(--mint3)":"var(--red)"}">${l.counted-l.expected>0?"+":""}${l.counted-l.expected}</b>`,"n"],["Cost impact",l=>money((l.counted-l.expected)*(byId("products",l.productId)?.cost||0)),"n"]],"No variances — stock matches.")}<div class="actions"><button class="btn" onclick="openCount('${id}')">Back</button><button class="btn p" onclick="(async()=>{const c=byId('counts','${id}');for(const l of c.lines){ if(l.counted===null||l.counted===l.expected) continue; const p=byId('products',l.productId); if(!p) continue; stockMove(p,l.counted-l.expected,c.locationId||undefined); (p.adjustments=p.adjustments||[]).push({date:todayISO(),n:l.counted-l.expected,reason:'Physical count',by:session.staffId}); if(p.adjustments.length>20)p.adjustments=p.adjustments.slice(-20); await save('products',p);} c.status='applied'; c.appliedAt=todayISO(); await save('counts',c); closeModal(); render(); toast('Stock updated from count')})()">Apply adjustments</button></div>`,true); }
function printCountSheet(id){ const c=byId("counts",id); printHTML(`<div class="page"><h1>Count sheet</h1><p>${esc(storeSettings().name)} · ${dateFmt(c.date)} · ${c.scope==="all"?"all items":esc(c.scope)}${c.locationId?" · "+esc(locName(c.locationId)):""}</p><table class="ptable"><tr><th>Bin</th><th>SKU</th><th>Item</th>${c.blind?"":'<th class="n">Expected</th>'}<th class="n">Counted</th><th>Init.</th></tr>${c.lines.map(l=>`<tr><td>${esc(l.bin)}</td><td>${esc(l.sku)}</td><td>${esc(l.name)}</td>${c.blind?"":`<td class="n">${l.expected}</td>`}<td class="n" style="width:70px"></td><td style="width:40px"></td></tr>`).join("")}</table></div>`); }
function renderCounts(){ return `<div class="toolbar"><span class="grow muted">Print a sheet, walk the floor and warehouse, key the counts, then apply the variances.</span><button class="btn p" onclick="startCount()">${S.counts.some(c=>c.status==="open")?"Continue count":"Start a count"}</button></div><div class="card">${table(S.counts.slice().sort((a,b)=>b.date.localeCompare(a.date)),[["Date",c=>dateShort(c.date)],["Scope",c=>`${c.scope==="all"?"All items":esc(c.scope)}${c.locationId?" · "+esc(locName(c.locationId)):""}`],["Progress",c=>`${c.lines.filter(l=>l.counted!==null).length}/${c.lines.length}`],["Variances",c=>c.lines.filter(l=>l.counted!==null&&l.counted!==l.expected).length,"n"],["Status",c=>statusTag(c.status)],["",c=>`<button class="btn s" onclick="openCount('${c.id}')">Open</button>`]],"No counts yet.")}</div>`; }

/* ---------- inventory analysis, vendor performance, team scorecards ---------- */
function renderAnalysis(){
  const today=todayISO(), d90=addDays(today,-90); const inv=S.invoices.filter(i=>["paid","open","financed","layaway"].includes(i.status)&&i.date>=d90);
  const sold={}; inv.forEach(i=>i.lines.forEach(l=>{ if(!l.productId) return; sold[l.productId]=sold[l.productId]||{q:0,rev:0,cost:0}; sold[l.productId].q+=l.qty; sold[l.productId].rev+=lineRevenue(i,l); sold[l.productId].cost+=l.cost*l.qty; }));
  const rows=S.products.map(p=>{ const s=sold[p.id]||{q:0,rev:0,cost:0}; const onhand=p.stock||0; const invCost=onhand*(p.cost||0); const since=p.lastReceived||p.createdAt||today; const age=daysBetween(since,today); const turns=onhand>0?(s.q/90*365)/Math.max(onhand,1):null; const gm=s.rev-s.cost; const gmroi=invCost>0?(gm/90*365)/invCost:null; return {p,s,onhand,invCost,age,turns,gm,gmroi,dead:onhand>0&&s.q===0&&age>=90}; });
  const totalInv=rows.reduce((a,r)=>a+r.invCost,0); const dead=rows.filter(r=>r.dead); const deadVal=dead.reduce((a,r)=>a+r.invCost,0);
  const vend=S.vendors.map(v=>{ const vr=rows.filter(r=>r.p.vendorId===v.id); const rev=vr.reduce((a,r)=>a+r.s.rev,0), gm=vr.reduce((a,r)=>a+r.gm,0); const pos=S.purchaseOrders.filter(o=>o.vendorId===v.id&&o.status==="received"&&o.expected&&o.receivedAt); const onTime=pos.filter(o=>o.receivedAt<=o.expected).length; return {v,rev,gm,inv:vr.reduce((a,r)=>a+r.invCost,0),pos:pos.length,onTime,dead:vr.filter(r=>r.dead).length}; }).sort((a,b)=>b.rev-a.rev);
  const team=upsStats(d90,today).map(t=>{ const inv=S.invoices.filter(i=>salesShare(i,t.s.id)>0&&["paid","open","financed","layaway"].includes(i.status)&&i.date>=d90); const gm=inv.reduce((a,i)=>a+invTotals(i).margin*salesShare(i,t.s.id),0); const mats=inv.filter(i=>i.lines.some(l=>l.mattress)); const prot=mats.filter(i=>i.lines.some(isProtector)).length; const plans=inv.filter(i=>i.lines.some(l=>l.plan)).length; return Object.assign(t,{gm,mPct:t.sales?gm/t.sales:0,attach:mats.length?prot/mats.length:null,plans:inv.length?plans/inv.length:0}); }).sort((a,b)=>b.sales-a.sales);
  return `<p class="muted small">Last 90 days. Turns and GMROI are annualized from that window; age counts from the last receipt.</p>
  <div class="grid g4" style="margin-bottom:16px"><div class="card stat"><div class="v">${money(totalInv)}</div><div class="l">Inventory at cost · ${rows.reduce((a,r)=>a+r.onhand,0)} units</div></div><div class="card stat t"><div class="v">${(()=>{const t=rows.filter(r=>r.turns!==null);return t.length?(t.reduce((a,r)=>a+r.turns,0)/t.length).toFixed(1):"–"})()}</div><div class="l">Avg annual turns (stocked items)</div></div><div class="card stat ${dead.length?"r":""}"><div class="v">${money(deadVal)}</div><div class="l">Dead stock · ${dead.length} items with no sales in 90 days</div></div><div class="card stat b"><div class="v">${(()=>{const g=rows.filter(r=>r.gmroi!==null);return g.length?(g.reduce((a,r)=>a+r.gmroi,0)/g.length).toFixed(2):"–"})()}</div><div class="l">Avg GMROI ($ margin per $ inventory / yr)</div></div></div>
  ${feat("locations")&&locations().length?`<div class="card" style="margin-bottom:16px"><h2>Stock by location</h2>${table(locations().map(l=>({l,units:S.products.reduce((a,p)=>a+stockAt(p,l.id),0),value:S.products.reduce((a,p)=>a+stockAt(p,l.id)*landedCost(p),0),retail:S.products.reduce((a,p)=>a+stockAt(p,l.id)*(p.price||0),0)})),[["Location",x=>`<b>${esc(x.l.name)}</b> ${isDisplayLoc(x.l)?'<span class="tag warn">display floor</span>':""}`],["Units",x=>x.units,"n"],["At landed cost",x=>money(x.value),"n"],["At retail",x=>money(x.retail),"n"],["Share of value",x=>pct(totalInv?x.value/totalInv:0),"n"]],"")}</div>`:""}
  <div class="card" style="margin-bottom:16px"><h2>Team scorecard</h2>${table(team,[["Salesperson",t=>`<b>${esc(t.s.name)}</b>`],["Sales",t=>money(t.sales),"n"],...(has("margin")?[["Margin",t=>pct(t.mPct),"n"]]:[]),["Tickets",t=>t.sold,"n"],["Avg ticket",t=>money(t.avg),"n"],["Items / ticket",t=>t.items.toFixed(1),"n"],["Close rate",t=>t.close===null?'<span class="muted">log ups</span>':pct(t.close),"n"],["Protector attach",t=>t.attach===null?"—":pct(t.attach),"n"],["Plan attach",t=>pct(t.plans),"n"]],"No sales yet.")}</div>
  <div class="grid g2"><div class="card"><h2>Slow & dead stock</h2>${table(rows.filter(r=>r.onhand>0).sort((a,b)=>(a.turns??0)-(b.turns??0)||b.age-a.age).slice(0,15),[["Item",r=>`${esc(r.p.name)}<div class="muted small">${esc(r.p.sku)} · ${r.onhand} on hand · ${r.age} days</div>`],["Sold 90d",r=>r.s.q,"n"],["Turns",r=>r.turns===null?"—":r.turns.toFixed(1),"n"],["At cost",r=>money(r.invCost),"n"],["",r=>r.dead?'<span class="tag bad">dead</span>':r.turns!==null&&r.turns<1?'<span class="tag warn">slow</span>':""]],"Nothing on hand.")}</div>
  <div class="card"><h2>Best performers (GMROI)</h2>${table(rows.filter(r=>r.gmroi!==null).sort((a,b)=>b.gmroi-a.gmroi).slice(0,15),[["Item",r=>`${esc(r.p.name)}<div class="muted small">${esc(r.p.sku)}</div>`],["Sold 90d",r=>r.s.q,"n"],["Margin 90d",r=>money(r.gm),"n"],["GMROI",r=>r.gmroi.toFixed(2),"n"]],"Need sales and stock to compute.")}</div>
  <div class="card" style="grid-column:1/-1"><h2>Vendor performance</h2>${table(vend,[["Vendor",x=>`<b>${esc(x.v.name)}</b>`],["Sales 90d",x=>money(x.rev),"n"],["Margin",x=>`${money(x.gm)} <span class="muted">${pct(x.rev?x.gm/x.rev:0)}</span>`,"n"],["Inventory at cost",x=>money(x.inv),"n"],["Dead items",x=>x.dead,"n"],["POs on time",x=>x.pos?`${x.onTime}/${x.pos}`:"—","n"]],"No vendors.")}</div></div>`;
}

/* ---------- accounting export ---------- */
function journalRows(from,to){ const days={}; const add=(d,acct,debit,credit,memo)=>{ (days[d]=days[d]||[]).push({date:d,account:acct,debit:round2(debit),credit:round2(credit),memo}); };
  for(const i of S.invoices){ if(!["paid","open","financed","layaway"].includes(i.status)||i.date<from||i.date>to) continue; const T=invTotals(i); const svc=i.lines.filter(l=>l.service).reduce((a,l)=>a+lineRevenue(i,l),0); add(i.date,"Accounts Receivable",T.total,0,i.number); add(i.date,"Sales — Merchandise",0,T.sub-svc,i.number); if(svc) add(i.date,"Sales — Services & Plans",0,svc,i.number); if(T.disc) add(i.date,"Sales Discounts",T.disc,0,i.number); if(T.delivery) add(i.date,"Delivery Income",0,T.delivery,i.number); if(T.tax) add(i.date,"Sales Tax Payable",0,T.tax,i.number); if(T.cost){ add(i.date,"Cost of Goods Sold",T.cost,0,i.number); add(i.date,"Inventory",0,T.cost,i.number); } }
  for(const i of S.invoices){ if(i.status==="void") continue; for(const p of (i.payments||[])){ if(p.date<from||p.date>to) continue; const m=p.method.replace(/ \(on delivery\)/,""); const acct=/^Financing/.test(m)?"Financing Receivable":/Exchange credit|Store credit/.test(m)?"Customer Credits":/Cash/.test(m)?"Cash on Hand":/Check/.test(m)?"Undeposited Funds — Checks":/Gift/.test(m)?"Gift Card Liability":"Undeposited Funds — Cards"; add(p.date,acct,p.amount,0,i.number+" "+m); add(p.date,"Accounts Receivable",0,p.amount,i.number+" "+m); } }
  for(const r of S.returns){ if(r.date<from||r.date>to) continue; add(r.date,"Sales Returns",r.refundSub,0,r.number); if(r.refundTax) add(r.date,"Sales Tax Payable",r.refundTax,0,r.number); if(r.fee) add(r.date,"Restocking / Exchange Fees",0,r.fee,r.number); add(r.date,r.method==="Original payment"?"Undeposited Funds — Cards":"Customer Credits",0,r.refundTotal,r.number); if(r.costBack){ add(r.date,"Inventory",r.costBack,0,r.number); add(r.date,"Cost of Goods Sold",0,r.costBack,r.number); } }
  return Object.keys(days).sort().flatMap(d=>days[d]); }
function exportJournalCSV(){ const rows=journalRows(rFrom,rTo); if(!rows.length) return toast("Nothing in this range.",true); saveFile(`sales-journal-${rFrom}-to-${rTo}.csv`,["Date,Account,Debit,Credit,Memo"].concat(rows.map(r=>`${r.date},"${r.account}",${r.debit||""},${r.credit||""},"${r.memo}"`)).join("\n")); }
function exportIIF(){ const rows=journalRows(rFrom,rTo); if(!rows.length) return toast("Nothing in this range.",true); const st=storeSettings(); const byDay={}; rows.forEach(r=>(byDay[r.date]=byDay[r.date]||[]).push(r)); const f=d=>{const [y,m,dd]=d.split("-");return `${m}/${dd}/${y}`}; let out="!TRNS\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tMEMO\n!SPL\tTRNSTYPE\tDATE\tACCNT\tNAME\tAMOUNT\tMEMO\n!ENDTRNS\n"; for(const d of Object.keys(byDay).sort()){ const rs=byDay[d]; const acc={}; rs.forEach(r=>acc[r.account]=(acc[r.account]||0)+r.debit-r.credit); const entries=Object.entries(acc).filter(([,a])=>Math.abs(a)>0.004); entries.forEach(([a,amt],i)=>{ out+=`${i===0?"TRNS":"SPL"}\tGENERAL JOURNAL\t${f(d)}\t${a}\t${st.name}\t${amt.toFixed(2)}\tPOS daily summary\n`; }); out+="ENDTRNS\n"; } saveFile(`quickbooks-${rFrom}-to-${rTo}.iif`,out); }

/* ---------- time clock ---------- */
function clockStatus(){ return S.timeclock.find(t=>t.staffId===session.staffId&&!t.out); }
async function clockToggle(){ const open=clockStatus(); const now=new Date(); const ts=now.toISOString(); if(open){ open.out=ts; open.hours=round2((new Date(ts)-new Date(open.in))/3600000); await save("timeclock",open); toast(`Clocked out — ${open.hours} h`); } else { await save("timeclock",{id:uid(),staffId:session.staffId,date:todayISO(),in:ts,out:""}); toast("Clocked in"); } render(); }
function renderTimesheet(){ const rows=S.staff.map(s=>{ const es=S.timeclock.filter(t=>t.staffId===s.id&&t.date>=rFrom&&t.date<=rTo); return {s,n:es.length,hours:es.reduce((a,t)=>a+(t.hours||(t.out?0:round2((Date.now()-new Date(t.in))/3600000))),0),open:es.some(t=>!t.out)}; }).filter(r=>r.n); return `<div class="card"><div class="row" style="margin-bottom:8px"><h2 style="margin:0">Hours</h2><span class="fx"><button class="btn s" onclick="printTimesheet()">Print timesheets</button></span></div>${table(rows,[["Staff",r=>`<b>${esc(r.s.name)}</b>${r.open?' <span class="tag ok">clocked in</span>':""}`],["Shifts",r=>r.n,"n"],["Hours",r=>r.hours.toFixed(2),"n"]],"No clock entries in this range.")}</div>`; }
function printTimesheet(){ printHTML(`<div class="page"><h1>Timesheets</h1><p>${esc(storeSettings().name)} · ${dateFmt(rFrom)} – ${dateFmt(rTo)}</p>${S.staff.map(s=>{ const es=S.timeclock.filter(t=>t.staffId===s.id&&t.date>=rFrom&&t.date<=rTo).sort((a,b)=>a.in.localeCompare(b.in)); if(!es.length) return ""; return `<h3 style="margin-top:14px">${esc(s.name)}</h3><table class="ptable"><tr><th>Date</th><th>In</th><th>Out</th><th class="n">Hours</th></tr>${es.map(t=>`<tr><td>${dateShort(t.date)}</td><td>${new Date(t.in).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</td><td>${t.out?new Date(t.out).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</td><td class="n">${(t.hours||0).toFixed(2)}</td></tr>`).join("")}<tr><td colspan="3" class="n"><b>Total</b></td><td class="n"><b>${es.reduce((a,t)=>a+(t.hours||0),0).toFixed(2)}</b></td></tr></table>`; }).join("")}<p style="margin-top:24px">Employee: ______________ &nbsp; Manager: ______________</p></div>`); }

/* ---------- branding: logo upload ---------- */
function uploadLogo(input){ const f=input.files&&input.files[0]; if(!f) return; const img=new Image(); const url=URL.createObjectURL(f); img.onload=async()=>{ const s=Math.min(1,320/Math.max(img.width,img.height)); const cv=document.createElement("canvas"); cv.width=img.width*s; cv.height=img.height*s; cv.getContext("2d").drawImage(img,0,0,cv.width,cv.height); const st=storeSettings(); st.logo=cv.toDataURL("image/png"); URL.revokeObjectURL(url); await save("settings",st); render(); toast("Logo saved"); }; img.src=url; }
async function removeLogo(){ const st=storeSettings(); st.logo=''; await save('settings',st); render(); }
const logoHTML=(h=48)=>{ const st=storeSettings(); return st.logo?`<img src="${st.logo}" style="height:${h}px;max-width:200px;object-fit:contain;display:block;margin-bottom:6px">`:""; };

/* ---------- route export for third-party dispatch ---------- */
function exportRouteCSV(){ const stops=dayStops(); if(!stops.length) return toast("No stops that day.",true); const rows=["Truck,Stop,Customer,Phone,Address,Latitude,Longitude,Window start,Window end,ETA,Pieces,Haul-away,Setup,Balance due,Notes,Invoice"].concat(stops.map(d=>{const c=custOf(d);const inv=byId("invoices",d.invoiceId);const bal=inv?invTotals(inv).balance:0;return [truckName(d.truckId),d.order||"",c?.name||"",c?.phone||"",c?.address||"",c?.lat||"",c?.lng||"",d.winStart,d.winEnd,d.eta?m2t(d.eta):"",piecesOf(d),d.haulAway||0,d.setup?"yes":"no",bal.toFixed(2),(d.notes||"").replace(/"/g,"'"),inv?.number||""].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")})); saveFile(`route-${delDate}.csv`,rows.join("\n")); }

/* ---------- features settings tab ---------- */
function renderFeaturesSettings(){ const st=storeSettings(); const f=st.features||{}; return `<div class="card" style="max-width:820px"><p class="muted">Switch on the modules this store wants. Everything else stays out of the way.</p>${FEATURES.map(([k,l,d])=>`<label class="chk" style="align-items:flex-start;padding:10px 0;border-bottom:1px solid var(--line2)"><input type="checkbox" ${f[k]?"checked":""} onchange="toggleFeature('${k}',this.checked)" style="margin-top:4px"><span><b>${l}</b><div class="muted small">${d}</div></span></label>`).join("")}${f.locations?`<div style="margin-top:14px"><button class="btn" onclick="stockTab='locations';go('stock')">Manage locations & transfers</button></div>`:""}</div>`; }
async function toggleFeature(k,on){ const st=storeSettings(); st.features=st.features||{}; st.features[k]=on; if(k==="locations"&&on&&!S.locations.length){ const w=await save("locations",{id:uid(),name:"Warehouse",type:"warehouse",address:st.address,isDefaultSale:true,isDefaultReceive:true,display:false}); await save("locations",{id:uid(),name:"Showroom",type:"showroom",address:st.address,isDefaultSale:false,isDefaultReceive:false,display:true}); for(const p of S.products){ p.stockBy={[w.id]:p.stock||0}; await save("products",p); } toast("Created Warehouse and Showroom (display floor) — all stock placed in Warehouse; transfer floor models to the Showroom"); } await save("settings",st); render(); }
