/* ============================================================
   VENDOR INTEGRATIONS — set up once by the software owner,
   assigned to dealers; catalogs live in the platform namespace
   ============================================================ */
const catalogCache={};
const safeId=s=>String(s).replace(/[^A-Za-z0-9_\-]/g,"_").slice(0,120)||uid();
const integrationsFor=()=>(platform.integrations||[]).filter(i=>i.active!==false&&(i.dealers==="all"||(i.dealerIds||[]).includes(tenantId)));
function saveIntegration(i){ platform.integrations=platform.integrations||[]; const k=platform.integrations.findIndex(x=>x.id===i.id); if(k>=0) platform.integrations[k]=i; else platform.integrations.push(i); savePlatformLocal(); if(db) queueWrite("integrations",i.id,clone(i)); }
function integrationName(id){ return (platform.integrations||[]).find(i=>i.id===id)?.name||"—"; }
function relayCatalogItem(x){ return {id:x.sku,sku:x.vendorSku||x.sku,name:x.name||x.sku,category:x.category||"Accessories",subcategory:x.subcategory||"",cost:+x.cost||0,freight:x.freight,surcharge:x.surcharge,landed:x.landed,msrp:+x.msrp||0,map:+x.map||0,size:x.size||"",stock:x.unavailableAtWarehouse?"unavailable":(x.active?"available":"—"),photo:x.thumb||x.image||"",image:x.image||"",barcode:x.upc||"",collection:x.collection||"",color:x.color||"",finish:x.finish||"",material:x.material||"",dims:x.dims||"",weightLbs:x.weightLbs||0,warrantyYears:x.warrantyYears||1,pieces:x.pieces||1,isKit:!!x.isKit,kitIncludes:x.kitIncludes||[],customerSku:x.customerSku||"",customerUpc:x.customerUpc||"",chairPair:!!x.chairPair,expressShip:!!x.expressShip,dropShipOnly:!!x.dropShipOnly,active:x.active!==false,status:x.status||"",lastModified:x.lastModified||""}; }
async function readCatalog(intId,force){ if(catalogCache[intId]&&!force) return catalogCache[intId]; const i=(platform.integrations||[]).find(x=>x.id===intId); if(i&&i.adapter){ if(!platformRelay()) throw new Error("This vendor's catalog comes through the relay service, which isn't set up yet (Administration → Software settings)."); const v=S.vendors.find(v=>v.integrationId===intId); if(v&&i.credMode==="dealer"&&!v.credsSet) throw new Error("Add your "+i.name+" API access on this supplier first (Inventory → Suppliers → Add API access)."); const j=await relayFetch(`/vendor/${encodeURIComponent(intId)}/catalog`); const items=(j.items||[]).map(relayCatalogItem); catalogCache[intId]=items; return items; } if(!db) throw new Error("The shared store isn't connected on this device, so vendor catalogs can't be read here."); const items=await readCollection(`catalogs/${intId}/items`); catalogCache[intId]=items; return items; }
function productFromCatalogItem(it,v){ const p={id:uid(),sku:(it.customerSku&&!S.products.some(x=>x.sku===it.customerSku))?it.customerSku:storeSettings().skuPrefix+"-"+it.sku,vendorSku:it.sku,vendorId:v.id,name:it.name,category:it.category||"Accessories",cost:it.cost,msrp:it.msrp,stock:0,reorderAt:0,pieces:it.pieces||1,warrantyYears:it.warrantyYears||1,createdAt:todayISO()}; if(it.subcategory) p.subcategory=it.subcategory; if(it.map) p.map=it.map; if(it.photo) p.photo=it.photo; if(it.customerUpc||it.barcode) p.barcode=it.customerUpc||it.barcode; if(it.collection) p.collection=it.collection; if(it.color) p.color=it.color; if(it.finish) p.finish=it.finish; if(it.material) p.material=it.material; if(it.dims) p.dims=it.dims; if(it.weightLbs) p.weightLbs=it.weightLbs; if(it.freight!==undefined&&it.freight!==null&&it.freight!=="") p.freight=+it.freight; if(it.surcharge) p.surcharge=+it.surcharge; if(it.expressShip) p.expressShip=true; if(it.dropShipOnly) p.dropShipOnly=true; if(it.chairPair) p.note="Sold in pairs — 1 = 2 chairs (vendor carton)"; normalizeCategory(p); if(it.category==="Mattresses"||it.size){ p.size=it.size; p.comfort=it.comfort; if(it.category==="Mattresses") p.trial=true; } if(it.isKit&&it.kitIncludes&&it.kitIncludes.length){ const comps=it.kitIncludes.map(c=>{ const cp=S.products.find(x=>x.vendorId===v.id&&x.vendorSku===(c.sku||c)); return cp?{productId:cp.id,qty:+(c.quantity||1)}:null; }).filter(Boolean); if(comps.length===it.kitIncludes.length){ p.isKit=true; p.kit=comps; } else { p.note=((p.note||"")+" Vendor kit: "+it.kitIncludes.map(c=>(c.quantity||1)+"× "+(c.sku||c)).join(", ")).trim(); } } p.landed=landedCost(p); p.price=suggestPrice(p); return p; }

/* ---------- admin console ---------- */
function renderIntegrations(){ const list=(platform.integrations||[]).slice().sort((a,b)=>a.name.localeCompare(b.name));
  return `<div class="topbar"><h1>Vendor integrations</h1><button class="btn p" onclick="editIntegration()">Add vendor integration</button></div>
  <p class="muted">Enter a vendor's API details once, load their catalog, and assign it to dealers. Dealers then pull items into their own inventory at their own markup and send purchase orders in the vendor's format.</p>
  <div class="card">${table(list,[["Vendor",i=>`<b>${esc(i.name)}</b><div class="muted">${esc(i.contact||"")}${i.orderEmail?" · "+esc(i.orderEmail):""}</div>`],["API",i=>i.apiUrl?`<span class="tag ok">configured</span><div class="muted small">${esc(i.apiUrl)}</div>`:'<span class="tag">manual feed</span>'],["Catalog",i=>i.itemCount?`${i.itemCount} items<div class="muted small">updated ${new Date(i.lastSync).toLocaleDateString()}</div>`:'<span class="tag warn">not loaded</span>'],["Dealers",i=>i.dealers==="all"?"All dealers":`${(i.dealerIds||[]).length} assigned`],["Status",i=>statusTag(i.active===false?"paused":"active")],["",i=>`<div class="bgroup"><button class="btn s p" onclick="loadCatalogModal('${i.id}')">Load catalog</button><button class="btn s" onclick="editIntegration('${i.id}')">Edit</button></div>`]],"No vendor integrations yet.")}</div>`; }
const INTEGRATION_PRESETS={ashley:{name:"Ashley Furniture",adapter:"ashley",apiUrl:"https://apigw3.ashleyfurniture.com/productinformation",authType:"basic",extraHeaders:"Client_Id={clientId}, Accept-Encoding=gzip,deflate, Accept-Language=en",catalogPath:"/Products?Customer={customer}&ShipTo={shipto}&Status=current",stockPath:"/Products?Customer={customer}&ShipTo={shipto}&Skus={sku}&Warehouse={warehouse}",stockMap:"",credMode:"dealer",credFields:"username, password, customer, shipto, warehouse",apiFormat:"json",notes:"Ashley Product Syndication API (PSAPI): REST catalog (/Products, /Packages, /Series, /Masters) + GraphQL prices (netPriceBeforeFreight, freight, surcharge, totalNetPrice per account). Dealers enter their AshleyDirect username/password, customer account number, ship-to number and servicing warehouse (e.g. 17 = Advance NC). Client ID comes from Ashley Content Services at onboarding. Live stock shows orderable / unavailable at the dealer's warehouse (PSAPI has no quantities). Images from cdn.ashley.com."}};
function applyIntegrationPreset(key){ const p=INTEGRATION_PRESETS[key]; if(!p) return; if(p.adapter){ window._intPrefill=Object.assign({},p); closeModal(); editIntegration(""); toast("Ashley preset loaded — add your Client ID, then Save"); return; } const set=(id,v)=>{ const e=document.getElementById(id); if(e&&v!==undefined) e.value=v; }; set("in_name",p.name); set("in_url",p.apiUrl); set("in_adapter",p.adapter||""); set("in_authtype",p.authType); set("in_xhdr",p.extraHeaders); set("in_cat",p.catalogPath); set("in_stock",p.stockPath); set("in_stockmap",p.stockMap); set("in_credmode",p.credMode); set("in_credfields",p.credFields); set("in_notes",p.notes); toast("Ashley preset filled in — add your Client ID, then Save"); }
function editIntegration(id){ const i=(platform.integrations||[]).find(x=>x.id===id)||(window._intPrefill?(()=>{ const x=window._intPrefill; window._intPrefill=null; return Object.assign({contact:"",orderEmail:"",phone:"",apiKey:"",authHeader:"Authorization",authPrefix:"Bearer ",orderPath:"/orders",dealers:"all",active:true},x); })():null)||{name:"",contact:"",orderEmail:"",phone:"",apiUrl:"",apiKey:"",authHeader:"Authorization",authPrefix:"Bearer ",catalogPath:"",orderPath:"",apiFormat:"json",map:{sku:"sku",name:"name",cost:"cost",msrp:"msrp",category:"category",stock:"qty",size:"size",comfort:"comfort"},dealers:"all",dealerIds:[],active:true,orderTemplate:'{"poNumber":"{{poNumber}}","account":"{{account}}","shipTo":"{{shipTo}}","lines":{{lines}}}',notes:""};
  const m=i.map||{};
  modal(`<h2>${id?"Edit integration":"Add vendor integration"}</h2>${id?"":`<div class="row" style="gap:8px;margin-bottom:8px"><span class="muted small">Start from a preset:</span><button class="btn s" onclick="applyIntegrationPreset('ashley')">Ashley Furniture (PSAPI)</button></div>`}
  <div class="grid g2"><div class="field"><label class="f">Vendor name</label><input type="text" id="in_name" value="${esc(i.name)}"></div><div class="field"><label class="f">Rep / contact</label><input type="text" id="in_contact" value="${esc(i.contact)}"></div></div>
  <div class="grid g2"><div class="field"><label class="f">Order email (fallback when the API can't be reached)</label><input type="email" id="in_email" value="${esc(i.orderEmail)}"></div><div class="field"><label class="f">Phone</label><input type="tel" id="in_phone" value="${esc(i.phone)}"></div></div>
  ${i.adapter?`<div class="notice" style="margin:8px 0"><b>Built-in connection: ${esc(i.name)}</b> — the relay knows this vendor's API (catalog, pricing, packages, availability). You only need the <b>Client ID</b> below; each dealer enters: <b>${esc(i.credFields||"")}</b>.</div>`:""}<div class="field" style="max-width:420px"><label class="f">Client ID <span class="muted">(issued by the vendor to the software; a dealer can override with its own)</span></label><input type="text" id="in_clientid" value="${esc(i.clientId||"")}" placeholder="from the vendor's onboarding email"></div><details ${i.adapter?"":"open"} style="margin:8px 0"><summary style="cursor:pointer;font-weight:700;margin:8px 0">API connection${i.adapter?" (advanced — preset values, normally leave as is)":""}</summary>
  <div class="grid g2"><div class="field"><label class="f">Base URL</label><input type="url" id="in_url" value="${esc(i.apiUrl)}" placeholder="https://api.vendor.com/v1"></div><div class="field"><label class="f">API key / token</label><input type="password" id="in_key" value="${esc(i.apiKey)}"></div></div>
  <div class="grid g2"><div class="field"><label class="f">API credentials</label><select id="in_credmode"><option value="shared" ${(i.credMode||"shared")==="shared"?"selected":""}>One key for all dealers (entered here)</option><option value="dealer" ${i.credMode==="dealer"?"selected":""}>Dealer-specific — each dealer enters its own account</option></select></div><div class="field"><label class="f">What each dealer must enter <span class="muted">(comma list; use as {name} in paths/headers)</span></label><input type="text" id="in_credfields" value="${esc(i.credFields||"apiKey, dealerId")}" placeholder="apiKey, dealerId"></div></div><div class="grid g2"><div class="field"><label class="f">Live stock path <span class="muted">(use {sku})</span></label><input type="text" id="in_stock" value="${esc(i.stockPath||"")}" placeholder="/inventory/{sku}"></div><div class="field"><label class="f">Stock fields: available · next date · on order · <span class="muted">schedule list · date · qty</span></label><input type="text" id="in_stockmap" value="${esc(i.stockMap||"")}" placeholder="qtyAvailable, nextAvailableDate, onOrderQty, availabilityByDate, date, quantity"><div class="muted small">The last three are optional: the vendor's list of future arrivals and the field names inside it — that's what shows the date/quantity table.</div></div></div><div class="grid g4"><div class="field"><label class="f">Auth type</label><select id="in_authtype"><option value="apikey" ${(i.authType||"apikey")==="apikey"?"selected":""}>API key in a header</option><option value="basic" ${i.authType==="basic"?"selected":""}>Basic (username : password)</option><option value="none" ${i.authType==="none"?"selected":""}>None</option></select></div><input type="hidden" id="in_adapter" value="${esc(i.adapter||"")}"><div class="field"><label class="f">Extra headers <span class="muted">(name=value, comma-separated; {placeholders} allowed)</span></label><input type="text" id="in_xhdr" value="${esc(i.extraHeaders||"")}" placeholder="client_id={clientId}, Accept-Encoding=gzip,deflate"></div><div class="field"><label class="f">Auth header</label><input type="text" id="in_hdr" value="${esc(i.authHeader||"Authorization")}"></div><div class="field"><label class="f">Header prefix</label><input type="text" id="in_pre" value="${esc(i.authPrefix??"Bearer ")}" placeholder="Bearer "></div><div class="field"><label class="f">Catalog path</label><input type="text" id="in_cat" value="${esc(i.catalogPath)}" placeholder="/catalog"></div><div class="field"><label class="f">Orders path</label><input type="text" id="in_ord" value="${esc(i.orderPath)}" placeholder="/orders"></div></div>
  <div class="field"><label class="f">Catalog format</label><select id="in_fmt"><option value="json" ${i.apiFormat==="json"?"selected":""}>JSON array of items</option><option value="csv" ${i.apiFormat==="csv"?"selected":""}>CSV with header row</option></select></div>
  <label class="f">Field mapping — the vendor's field name for each of ours</label><div class="grid g4">${["sku","name","cost","msrp","category","stock","size","comfort"].map(k=>`<div class="field"><label class="f">${k}</label><input type="text" id="in_map_${k}" value="${esc(m[k]||"")}"></div>`).join("")}</div>
  <div class="field"><label class="f">Order payload template (JSON; placeholders: {{poNumber}} {{account}} {{shipTo}} {{dealer}} {{date}} {{lines}})</label><textarea id="in_tpl" rows="3">${esc(i.orderTemplate||"")}</textarea></div>
  </details><h3 style="margin:8px 0">Assign to dealers</h3><div class="chk" style="margin-bottom:6px"><input type="checkbox" id="in_all" ${i.dealers==="all"?"checked":""} onchange="document.getElementById('in_dlist').style.display=this.checked?'none':''"><label for="in_all">All dealers</label></div>
  <div id="in_dlist" style="${i.dealers==="all"?"display:none":""};max-height:160px;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:8px">${platform.tenants.map(t=>`<label class="chk" style="margin-bottom:4px"><input type="checkbox" class="in_dealer" value="${t.id}" ${(i.dealerIds||[]).includes(t.id)?"checked":""}> ${esc(t.name)} <span class="muted">${esc(t.code)}</span></label>`).join("")||`<span class="muted">No dealers yet.</span>`}</div>
  <div class="grid g2" style="margin-top:10px"><div class="field"><label class="f">Notes</label><input type="text" id="in_notes" value="${esc(i.notes||"")}"></div><div class="chk" style="margin-top:20px"><input type="checkbox" id="in_active" ${i.active!==false?"checked":""}><label for="in_active">Active (visible to dealers)</label></div></div>
  <div class="actions">${id?`<button class="btn d" onclick="confirmDo('Remove this integration? Dealers keep items already imported.',()=>removeIntegration('${id}'))">Remove</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn" onclick="testConnection()">Test connection</button><button class="btn p" onclick="saveIntegrationForm('${id||""}')">Save</button></div>`,true); }
function readIntegrationForm(id){ const prev=(platform.integrations||[]).find(x=>x.id===id)||{}; return Object.assign({},prev,{id:id||uid(),name:fv("in_name").trim(),contact:fv("in_contact"),orderEmail:fv("in_email"),phone:fv("in_phone"),apiUrl:fv("in_url").trim().replace(/\/$/,""),apiKey:fv("in_key"),authType:fv("in_authtype")||"apikey",extraHeaders:fv("in_xhdr").trim(),clientId:fv("in_clientid").trim(),adapter:fv("in_adapter").trim(),authHeader:fv("in_hdr").trim()||"Authorization",authPrefix:fv("in_pre"),catalogPath:fv("in_cat").trim(),orderPath:fv("in_ord").trim(),stockPath:fv("in_stock").trim(),stockMap:fv("in_stockmap").trim(),credMode:fv("in_credmode")||"shared",credFields:fv("in_credfields").trim(),apiFormat:fv("in_fmt"),map:Object.fromEntries(["sku","name","cost","msrp","category","stock","size","comfort"].map(k=>[k,fv("in_map_"+k).trim()])),orderTemplate:fv("in_tpl"),dealers:fchk("in_all")?"all":"some",dealerIds:[...document.querySelectorAll(".in_dealer:checked")].map(e=>e.value),notes:fv("in_notes"),active:fchk("in_active"),created:prev.created||todayISO()}); }
function saveIntegrationForm(id){ const i=readIntegrationForm(id); if(!i.name) return toast("Vendor name is required.",true); saveIntegration(i); closeModal(); render(); }
async function removeIntegration(id){ platform.integrations=(platform.integrations||[]).filter(x=>x.id!==id); savePlatformLocal(); if(db) queueWrite("integrations",id,null); closeModal(); render(); }
async function apiFetch(i,path,opts){ const url=(i.apiUrl||"")+(path||""); const headers=Object.assign({"Content-Type":"application/json"},i.apiKey?{[i.authHeader||"Authorization"]:(i.authPrefix||"")+i.apiKey}:{}); const r=await fetch(url,Object.assign({headers},opts||{})); if(!r.ok) throw new Error("HTTP "+r.status); return r.text(); }
async function testConnection(){ const i=readIntegrationForm(""); if(!i.apiUrl) return toast("Enter the base URL first.",true); toast("Testing…"); try{ const t=await apiFetch(i,i.catalogPath); toast(`Connected — ${t.length.toLocaleString()} characters returned`); }catch(e){ toast("Couldn't reach the vendor from this page ("+(e.message||"blocked")+"). Hosted pages can't call outside services directly — load the catalog by pasting the vendor's export instead.",true); } }
function loadCatalogModal(id){ const i=(platform.integrations||[]).find(x=>x.id===id); modal(`<h2>Load catalog — ${esc(i.name)}</h2><p class="muted">Items are keyed by the vendor's SKU. Loading replaces the stored catalog; dealers then update their inventory from it.${i.itemCount?` Currently ${i.itemCount} items (updated ${new Date(i.lastSync).toLocaleString()}).`:""}</p>
  <div class="row"><button class="btn" onclick="fetchCatalog('${id}')" ${i.apiUrl?"":"disabled"}>Fetch from API</button><span class="muted">or paste the vendor's ${i.apiFormat==="csv"?"CSV":"JSON"} export below</span></div><div id="cat_msg" class="muted" style="margin:8px 0"></div>
  <textarea id="cat_text" rows="10" placeholder='${i.apiFormat==="csv"?"sku,name,cost,msrp,category,qty,size,comfort":'[{"sku":"...","name":"...","cost":0,"msrp":0,"category":"...","qty":0}]'}'></textarea>
  <div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="importCatalogText('${id}')">Load into catalog</button></div>`,true); }
async function fetchCatalog(id){ const i=(platform.integrations||[]).find(x=>x.id===id); const msg=document.getElementById("cat_msg"); msg.textContent="Connecting…"; try{ document.getElementById("cat_text").value=await apiFetch(i,i.catalogPath); msg.textContent="Feed loaded — review and load into catalog."; }catch(e){ msg.innerHTML=`Couldn't reach the vendor from this page (${esc(e.message||"blocked")}). Download the export from the vendor portal and paste it here.`; } }
function normalizeItems(i,txt){ let items=i.apiFormat==="csv"?parseCSV(txt):JSON.parse(txt); if(!Array.isArray(items)) items=items.items||items.data||items.products||items.results||[]; const m=i.map||{}; const g=(it,k)=>{ const f=m[k]; if(!f) return undefined; return f.split(".").reduce((o,p)=>o==null?undefined:o[p],it); };
  return items.map(it=>{ const sku=String(g(it,"sku")??"").trim(); if(!sku) return null; const cat=String(g(it,"category")||""); return {id:safeId(sku),sku,name:String(g(it,"name")||sku),cost:parseFloat(g(it,"cost"))||0,msrp:parseFloat(g(it,"msrp"))||0,category:categoryNames().includes(cat)?cat:(cat||""),stock:parseFloat(g(it,"stock"))||0,size:String(g(it,"size")||""),comfort:String(g(it,"comfort")||""),updated:todayISO()}; }).filter(Boolean); }
async function importCatalogText(id){ const i=(platform.integrations||[]).find(x=>x.id===id); const txt=fv("cat_text").trim(); if(!txt) return toast("Paste or fetch the catalog first.",true); let items; try{ items=normalizeItems(i,txt); }catch(e){ return toast("Could not parse the feed: "+e.message,true); } if(!items.length) return toast("No items found — check the field mapping (sku is required).",true); if(!db) return toast("The shared store isn't connected, so the catalog can't be published to dealers from this device.",true);
  const old=catalogCache[id]||[]; const seen=new Set(items.map(x=>x.id)); for(const o of old) if(!seen.has(o.id)) queueWrite(`catalogs/${id}/items`,o.id,null); for(const it of items) queueWrite(`catalogs/${id}/items`,it.id,clone(it)); catalogCache[id]=items;
  i.itemCount=items.length; i.lastSync=Date.now(); saveIntegration(i); closeModal(); render(); toast(`${items.length} items loading into ${i.name}'s catalog — dealers can update once syncing finishes`); }

/* ---------- dealer side ---------- */
function credFieldList(i){ return String(i.credFields||"apiKey").split(",").map(s=>s.trim()).filter(Boolean); }
function vendorCredsModal(intId){ const i=(platform.integrations||[]).find(x=>x.id===intId); const v=S.vendors.find(v=>v.integrationId===intId); modal(`<h2>${esc(i.name)} — your API access</h2><p class="muted small">Stored write-only; the relay uses it for live stock and orders on your behalf. ${v&&v.credsSet?"Saved "+dateShort(v.credsAt)+" — enter again to replace.":"Not set yet."}</p><div class="grid g2">${credFieldList(i).map(f=>`<div class="field"><label class="f">${esc(f)}</label><input type="${/key|secret|token|pass/i.test(f)?"password":"text"}" id="vc_${esc(f)}" autocomplete="off"></div>`).join("")}</div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{ const creds={}; credFieldList((platform.integrations||[]).find(x=>x.id==='${intId}')).forEach(f=>{ creds[f]=fv('vc_'+f).trim(); }); if(!Object.values(creds).some(Boolean)) return toast('Enter your access details.',true); await saveVendorCredentials('${intId}',creds); const v=S.vendors.find(v=>v.integrationId==='${intId}'); if(v){ v.credsSet=true; v.credsAt=todayISO(); await save('vendors',v); } closeModal(); render(); toast('Vendor access saved'); })()">Save</button></div>`); }
function renderDealerIntegrations(){ const list=integrationsFor(); if(!list.length) return ""; return `<div class="card" style="margin-bottom:16px"><h2>Vendor catalogs from your software provider</h2><p class="muted small">These vendors were connected by the administrator. Pull their catalog into your inventory at your markup; purchase orders can be sent in the vendor's format.</p>${table(list,[["Vendor",i=>`<b>${esc(i.name)}</b><div class="muted small">${i.itemCount||0} items${i.lastSync?" · updated "+new Date(i.lastSync).toLocaleDateString():""}</div>`],["In your inventory",i=>{const v=S.vendors.find(v=>v.integrationId===i.id); const n=v?S.products.filter(p=>p.vendorId===v.id).length:0; return v?`${n} items${v.lastCatalogSync&&i.lastSync>v.lastCatalogSync?' <span class="tag warn">catalog updated</span>':""}`:'<span class="tag">not connected</span>'}],["",i=>{const v=S.vendors.find(v=>v.integrationId===i.id); return `<div class="bgroup">${v?`${i.credMode==="dealer"?`<button class="btn s ${v.credsSet?"":"d"}" onclick="vendorCredsModal('${i.id}')" title="${v.credsSet?"Your account is on file":"This vendor needs your own API account"}">${v.credsSet?"API access ✓":"Add API access"}</button>`:""}<button class="btn s p" onclick="syncFromIntegration('${i.id}')">Update from catalog</button><button class="btn s" onclick="browseCatalog('${i.id}')">Browse</button>${i.adapter?`<button class="btn s" onclick="importVendorPackages('${i.id}')" title="Bring in the vendor's package deals as packages (pieces must be in inventory first)">Packages</button>`:""}`:`<button class="btn s p" onclick="connectIntegration('${i.id}')">Connect</button>`}</div>`}]],"")}</div>`; }
async function connectIntegration(intId){ const i=(platform.integrations||[]).find(x=>x.id===intId); const st=storeSettings(); modal(`<h2>Connect ${esc(i.name)}</h2><div class="grid g2"><div class="field"><label class="f">Price multiplier for this supplier</label><input type="number" step="0.05" id="ci_mk" value="${costRules().multiplier}"></div><div class="field"><label class="f">Lead time (days)</label><input type="number" id="ci_lead" value="21"></div></div><div class="field"><label class="f">Your account # with this vendor</label><input type="text" id="ci_acct"></div>${i.credMode==="dealer"?`<div class="card" style="padding:10px 12px;background:var(--sage2)"><b class="small">Your ${esc(i.name)} API access</b><p class="muted small" style="margin:2px 0 8px">This vendor gives each dealer its own API account. Enter yours — it's stored write-only and used by the relay on your behalf; other stores can never see it.</p><div class="grid g2">${credFieldList(i).map(f=>`<div class="field"><label class="f">${esc(f)}</label><input type="${/key|secret|token|pass/i.test(f)?"password":"text"}" id="ci_cred_${esc(f)}" autocomplete="off"></div>`).join("")}</div></div>`:""}<div class="chk"><input type="checkbox" id="ci_import" checked><label for="ci_import">Import the whole catalog into my inventory now (stock starts at 0)</label></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="doConnectIntegration('${intId}')">Connect</button></div>`); }
async function doConnectIntegration(intId){ const i=(platform.integrations||[]).find(x=>x.id===intId); const v=await save("vendors",{id:uid(),name:i.name,contact:i.contact||"",email:i.orderEmail||"",phone:i.phone||"",account:fv("ci_acct"),multiplier:fnum("ci_mk")||"",leadDays:fnum("ci_lead")||21,integrationId:intId,apiUrl:"",apiFormat:"json",map:{}}); if(i.credMode==="dealer"){ const creds={}; credFieldList(i).forEach(f=>{ creds[f]=fv("ci_cred_"+f).trim(); }); if(Object.values(creds).some(Boolean)){ await saveVendorCredentials(intId,creds); v.credsSet=true; v.credsAt=todayISO(); await save("vendors",v); } } closeModal(); if(fchk("ci_import")) await syncFromIntegration(intId,{importAll:true}); else { render(); toast(i.name+" connected"); } }
async function syncFromIntegration(intId,o){ o=o||{}; const i=(platform.integrations||[]).find(x=>x.id===intId); const v=S.vendors.find(v=>v.integrationId===intId); if(!v) return; toast("Reading "+i.name+" catalog…"); let items; try{ items=await readCatalog(intId,true); }catch(e){ return toast(e.message,true); } if(!items.length) return toast("The catalog is empty — ask the administrator to load it.",true);
  const mine=S.products.filter(p=>p.vendorId===v.id); const changes=[]; let added=0; const priceFor=it=>suggestPrice({cost:it.cost,vendorId:v.id,category:it.category||"Accessories"});
  for(const it of items){ const p=mine.find(x=>x.vendorSku===it.sku); if(p){ if(Math.abs((p.cost||0)-it.cost)>0.004||(it.msrp&&it.msrp!==p.msrp)){ changes.push({p,it}); } } else if(o.importAll||o.addNew){ added++; } }
  if(!o.importAll&&!o.apply){ return modal(`<h2>Update from ${esc(i.name)}</h2><p class="muted">${items.length} items in the vendor catalog · ${mine.length} in your inventory · ${changes.length} cost/MSRP change${changes.length===1?"":"s"} · ${items.filter(it=>!mine.find(x=>x.vendorSku===it.sku)).length} not in your inventory</p>${changes.length?`<div class="tblwrap" style="max-height:260px;overflow:auto"><table><thead><tr><th>Item</th><th class="n">Cost now</th><th class="n">New cost</th><th class="n">Your price</th><th class="n">Suggested</th></tr></thead><tbody>${changes.slice(0,200).map(c=>`<tr><td>${esc(c.p.name)}</td><td class="n">${money(c.p.cost)}</td><td class="n"><b>${money(c.it.cost)}</b></td><td class="n">${money(c.p.price)}</td><td class="n">${money(priceFor(c.it))}</td></tr>`).join("")}</tbody></table></div>`:""}<div class="chk" style="margin-top:10px"><input type="checkbox" id="si_reprice"><label for="si_reprice">Re-price changed items using this supplier's rules</label></div><div class="chk"><input type="checkbox" id="si_add"><label for="si_add">Add catalog items I don't carry yet (stock 0)</label></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="syncFromIntegration('${intId}',{apply:true,reprice:fchk('si_reprice'),addNew:fchk('si_add')})">Apply</button></div>`,true); }
  items=items.slice().sort((a,b)=>(a.isKit?1:0)-(b.isKit?1:0));
  let upd=0; added=0; for(const it of items){ let p=mine.find(x=>x.vendorSku===it.sku); if(p){ const chg=Math.abs((p.cost||0)-it.cost)>0.004||(it.msrp&&it.msrp!==p.msrp)||(it.map&&it.map!==p.map)||(it.freight!==undefined&&it.freight!==""&&it.freight!==null&&+it.freight!==+(p.freight||0)); if(chg){ p.cost=it.cost; if(it.msrp) p.msrp=it.msrp; if(it.map) p.map=it.map; if(it.freight!==undefined&&it.freight!==""&&it.freight!==null) p.freight=+it.freight; if(it.surcharge!==undefined) p.surcharge=+it.surcharge||0; if(!p.photo&&it.photo) p.photo=it.photo; if(it.active===false&&!p.discontinued){ p.discontinued=true; } p.landed=landedCost(p); if(o.reprice&&!p.priceManual) p.price=suggestPrice(p); upd++; await save("products",p); } } else if(o.importAll||o.addNew){ if(it.active===false) continue; const sku=storeSettings().skuPrefix+"-"+it.sku; if(S.products.some(x=>x.sku===sku)) continue; p=productFromCatalogItem(it,v); added++; await save("products",p); } }
  v.lastCatalogSync=Date.now(); await save("vendors",v); closeModal(); render(); toast(`${i.name}: ${added} added, ${upd} updated`); }
async function importVendorPackages(intId){ const i=(platform.integrations||[]).find(x=>x.id===intId); const v=S.vendors.find(v=>v.integrationId===intId); if(!i||!v||!i.adapter) return toast("This vendor doesn't offer packages through its API.",true); if(!platformRelay()) return toast("Packages come through the relay service — not set up yet.",true); toast("Reading "+i.name+" packages…"); let j; try{ j=await relayFetch(`/vendor/${encodeURIComponent(intId)}/packages`); }catch(e){ return toast(e.message,true); } const pks=j.packages||[]; if(!pks.length) return toast("No packages found for your account.",true); let added=0, skipped=0; for(const pk of pks){ if(S.packages.some(x=>x.vendorPackageId===pk.id)){ skipped++; continue; } const items=pk.pieces.map(pc=>{ const p=S.products.find(x=>x.vendorId===v.id&&x.vendorSku===pc.sku); return p?{productId:p.id,qty:pc.qty||1}:null; }); if(items.some(x=>!x)){ skipped++; continue; } const sum=items.reduce((a,x)=>a+(byId("products",x.productId).price||0)*x.qty,0); const rec={id:uid(),vendorPackageId:pk.id,vendorId:v.id,name:pk.name,description:pk.description||"",items:items,cost:pk.cost,price:round2(sum),active:true,photo:pk.image||"",series:pk.series||"",expressShip:pk.expressShip,createdAt:todayISO()}; await save("packages",rec); added++; } render(); toast(`${i.name} packages: ${added} added${skipped?", "+skipped+" skipped (already added or pieces not in inventory)":""}`); }
async function browseCatalog(intId){ const i=(platform.integrations||[]).find(x=>x.id===intId); let items; try{ items=await readCatalog(intId); }catch(e){ return toast(e.message,true); } window._cat={intId,items}; modal(`<h2>${esc(i.name)} catalog</h2><input type="search" id="cb_q" placeholder="Search ${items.length} items…" oninput="catFilter()"><div id="cb_list" style="margin-top:10px"></div><div class="actions"><button class="btn" onclick="closeModal()">Close</button></div>`,true); catFilter(); }
function catFilter(){ const q=(fv("cb_q")||"").toLowerCase(); const {intId,items}=window._cat; const v=S.vendors.find(v=>v.integrationId===intId); const hits=items.filter(it=>!q||[it.sku,it.name,it.category,it.size].join(" ").toLowerCase().includes(q)).slice(0,60); document.getElementById("cb_list").innerHTML=table(hits,[["SKU",it=>esc(it.sku)],["Item",it=>`<div class="row" style="gap:8px;align-items:center">${it.photo?`<img src="${esc(it.photo)}" style="width:44px;height:44px;object-fit:cover;border-radius:6px">`:""}<div>${esc(it.name)}<div class="muted small">${esc(it.category||"")}${it.size?" · "+esc(it.size):""}${it.comfort?" · "+esc(it.comfort):""}${it.map?" · MAP "+money(it.map):""}${it.status==="D"?" · <span class=\"tag bad\">discontinued</span>":""}</div></div></div>`],["Vendor stock",it=>it.stock,"n"],...(seesCost()?[["Cost",it=>money(it.cost),"n"]]:[]),["Your price",it=>money(suggestPrice({cost:it.cost,vendorId:v?.id,category:it.category||"Accessories"})),"n"],["",it=>{const have=S.products.find(p=>p.vendorId===v?.id&&p.vendorSku===it.sku); return have?'<span class="tag ok">in inventory</span>':`<button class="btn s p" onclick="catAdd('${esc(it.id)}')">Add</button>`}]],"No matches."); }
async function catAdd(itemId){ const {intId,items}=window._cat; const it=items.find(x=>x.id===itemId); const v=S.vendors.find(v=>v.integrationId===intId); if(!it||!v) return; const p=productFromCatalogItem(it,v); await save("products",p); toast(it.name+" added to inventory"); catFilter(); }
function buildOrderPayload(o){ const v=byId("vendors",o.vendorId); const i=(platform.integrations||[]).find(x=>x.id===v?.integrationId); const st=storeSettings(); const lines=JSON.stringify(o.lines.map(l=>({sku:l.vendorSku,description:l.desc,qty:l.qty,unitCost:l.unitCost}))); const tpl=(i?.orderTemplate||'{"poNumber":"{{poNumber}}","account":"{{account}}","shipTo":"{{shipTo}}","lines":{{lines}}}'); return tpl.replace(/{{poNumber}}/g,o.number).replace(/{{account}}/g,v?.account||"").replace(/{{shipTo}}/g,(st.address||"").replace(/"/g,'\\"')).replace(/{{dealer}}/g,(st.name||"").replace(/"/g,'\\"')).replace(/{{date}}/g,o.date).replace(/{{lines}}/g,lines); }
async function sendPOviaAPI(id){ const o=byId("purchaseOrders",id); const v=byId("vendors",o.vendorId); const i=(platform.integrations||[]).find(x=>x.id===v?.integrationId); if(!i) return toast("This vendor isn't connected to an integration.",true); const payload=buildOrderPayload(o); try{ JSON.parse(payload); }catch(e){ return toast("The order template doesn't produce valid JSON — ask the administrator to fix it.",true); }
  if(i.apiUrl&&i.orderPath){ toast("Sending to "+i.name+"…"); try{ const resp=await apiFetch(i,i.orderPath,{method:"POST",body:payload}); o.status=o.status==="draft"?"sent":o.status; o.sentAt=todayISO(); o.apiResponse=String(resp).slice(0,500); o.sentVia="api"; await savePOEdits(id); await save("purchaseOrders",o); closeModal(); render(); return toast("Order accepted by "+i.name); }catch(e){ /* fall through to file */ } }
  modal(`<h2>Order for ${esc(i.name)}</h2><p class="muted">This page can't reach the vendor's API directly, so the order is ready in ${esc(i.name)}'s format — send it by email or upload it to their portal.</p><textarea rows="10" style="width:100%">${esc(payload)}</textarea><div class="actions"><button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="saveFile('${esc(o.number)}-${esc(i.name.replace(/[^A-Za-z0-9]/g,""))}.json',buildOrderPayload(byId('purchaseOrders','${id}')))">Download JSON</button>${i.orderEmail?`<a class="btn" href="mailto:${esc(i.orderEmail)}?subject=${encodeURIComponent("Purchase order "+o.number+" — "+storeSettings().name)}&body=${encodeURIComponent(payload)}">Email to vendor</a>`:""}<button class="btn p" onclick="(async()=>{const o=byId('purchaseOrders','${id}');if(o.status==='draft')o.status='sent';o.sentAt=todayISO();o.sentVia='file';await save('purchaseOrders',o);closeModal();render()})()">Mark as sent</button></div>`,true); }
