/* ============================================================
   FULFILLMENT — pickups and deliveries as one tracked process
   ============================================================ */
const dlv=()=>S.deliveries.filter(d=>d.kind!=="pickup");
const pickups=()=>S.deliveries.filter(d=>d.kind==="pickup");
const fulfillmentOf=inv=>inv.fulfillment||(inv.delivery?"delivery":"now");
function lineFulfil(inv,l){ if(l.service) return ""; if(l.fulfil) return l.fulfil; if(l.takeNow) return "now"; const f=fulfillmentOf(inv); return f==="mixed"?"pickup":f; }
function pickupLines(inv){ return inv.lines.filter(l=>lineOpen(l)&&lineFulfil(inv,l)!=="delivery"); }
function fulfilCounts(inv){ const c={now:0,pickup:0,delivery:0}; inv.lines.filter(l=>!l.service).forEach(l=>{ const f=lineFulfil(inv,l); if(c[f]!==undefined) c[f]++; }); return c; }
const lineOpen=l=>!l.service&&!l.deliveredAt;
const lineBlocked=l=>l.special&&l.specialStatus!=="arrived";
function pickupOf(inv){ return S.deliveries.find(d=>d.invoiceId===inv.id&&d.kind==="pickup"); }
function deliveryOf(inv){ const all=S.deliveries.filter(d=>d.invoiceId===inv.id&&d.kind!=="pickup"); return all.find(d=>d.status!=="delivered")||all.sort((a,b)=>String(b.deliveredAt||"").localeCompare(String(a.deliveredAt||"")))[0]; }
function deliveriesOf(inv){ return S.deliveries.filter(d=>d.invoiceId===inv.id&&d.kind!=="pickup"); }
function pickupStatusFor(inv){ const open=pickupLines(inv); if(!open.length) return "pickedup"; if(inv.status==="layaway") return "awaiting"; const blocked=open.filter(lineBlocked).length; return blocked===open.length?"awaiting":blocked?"partready":"ready"; }
async function ensurePickup(inv,extra){ let p=pickupOf(inv); if(!p){ p=await save("deliveries",Object.assign({id:uid(),kind:"pickup",invoiceId:inv.id,customerId:inv.customerId,date:"",status:pickupStatusFor(inv),plannedDate:"",notes:"",created:todayISO()},extra||{})); } return p; }
async function refreshPickup(inv){ const p=pickupOf(inv); if(!p) return; const s=pickupStatusFor(inv); if(s!==p.status&&p.status!=="pickedup"){ if(s==="ready"&&p.status!=="ready"){ p.readyAt=todayISO(); p.notified=""; await addFollowup(inv.customerId,inv.id,"Ready for pickup",`${inv.number} is ready — let the customer know.`,todayISO()); } if(s==="partready"&&p.status==="awaiting"){ await addFollowup(inv.customerId,inv.id,"Ready for pickup",`Part of ${inv.number} is in (the rest is still on order) — ask the customer if they want to collect what's here.`,todayISO()); } p.status=s; await save("deliveries",p); } }
function fulfillmentLabel(inv){
  if(["void","quote","draft"].includes(inv.status)) return "";
  const lines=inv.lines.filter(l=>!l.service); const done=lines.filter(l=>l.deliveredAt).length; const partial=done>0&&done<lines.length; const f=fulfillmentOf(inv); const eta=etaOf(inv); const cap=s=>s.charAt(0).toUpperCase()+s.slice(1); const rest=(s)=>partial?`Partially delivered · rest ${s}`:cap(s);
  if(f==="mixed"){ const d=deliveryOf(inv), p=pickupOf(inv); const bits=[]; if(d){ const dl=d.status==="delivered"?"delivered "+dateShort(d.deliveredAt||d.date):d.status==="awaiting"?"awaiting stock"+(eta?" · ETA "+eta:""):d.status==="unscheduled"?"to schedule":d.status==="missed"?"missed — reschedule":d.status==="out"?"out for delivery":d.status==="loaded"?"loaded "+dateShort(d.date):"scheduled "+dateShort(d.date); bits.push((d.status==="delivered"?"Delivered":cap(dl))+(d.status==="delivered"?"":"")); if(d.status!=="delivered") bits[bits.length-1]=cap(dl); } if(p){ const pl=p.status==="pickedup"?"picked up "+dateShort(p.pickedUpAt):p.status==="awaiting"?"pickup awaiting stock":p.status==="partready"?"part ready for pickup":"ready for pickup"; bits.push(d&&d.status!=="delivered"?"pickup: "+pl:cap(pl)); } const now=inv.lines.filter(l=>!l.service&&l.takenAtSale).length; if(now) bits.push(now+" taken at sale"); if(!bits.length) return done===lines.length?"Taken at sale":"Mixed"; return bits.join(" · "); }
  if(f==="delivery"){ const d=deliveryOf(inv); if(!d) return done===lines.length&&lines.length?"Delivered":partial?"Partially delivered":"Delivery"; if(d.status==="delivered") return partial?"Partially delivered":"Delivered "+dateShort(d.deliveredAt||d.date); if(d.status==="awaiting") return inv.status==="layaway"?"Held — layaway":rest("awaiting stock"+(eta?" · ETA "+eta:"")); if(d.status==="unscheduled") return rest("to schedule"); if(d.status==="missed") return rest("missed — reschedule"); if(d.status==="out") return rest("out for delivery"); if(d.status==="loaded") return rest("loaded · "+dateShort(d.date)); return rest("scheduled "+dateShort(d.date)); }
  const p=pickupOf(inv); const restP=(s)=>partial?`Partially picked up · rest ${s}`:cap(s);
  if(!p){ return done===lines.length?"Taken at sale":partial?"Partially taken":"Taken at sale"; }
  if(p.status==="pickedup") return "Picked up "+dateShort(p.pickedUpAt); if(p.status==="awaiting") return inv.status==="layaway"?"Held — layaway":restP("awaiting stock"+(eta?" · ETA "+eta:"")); if(p.status==="partready"){ const inN=inv.lines.filter(l=>lineOpen(l)&&!lineBlocked(l)).length, waitN=inv.lines.filter(l=>lineOpen(l)&&lineBlocked(l)).length; return restP(`part ready for pickup (${inN} in, ${waitN} still on order${eta?" · ETA "+eta:""})`); } return restP("ready for pickup"+(p.plannedDate?" · "+dateShort(p.plannedDate):"")); }
function fulfillmentTag(inv){ const l=fulfillmentLabel(inv); if(!l) return ""; const cls=/^Partially/.test(l)?"warn":/Delivered|Picked up|Taken/.test(l)?"ok":/Awaiting|Held|Missed|To schedule/.test(l)?"warn":/Ready|Scheduled|Out|Loaded|Partial/.test(l)?"info":""; return `<span class="tag ${cls}">${esc(l)}</span>`; }
function fulfillmentStepper(inv){
  const f=fulfillmentOf(inv); const lines=inv.lines.filter(l=>!l.service); const allDone=lines.length&&lines.every(l=>l.deliveredAt); const anyDone=lines.some(l=>l.deliveredAt); const stockReady=!lines.some(l=>lineOpen(l)&&lineBlocked(l))&&inv.status!=="layaway"; const eta=etaOf(inv);
  let steps;
  if(f==="mixed"){ const d=deliveryOf(inv), p=pickupOf(inv); const bits=[]; if(d){ const dl=d.status==="delivered"?"delivered "+dateShort(d.deliveredAt||d.date):d.status==="awaiting"?"awaiting stock"+(eta?" · ETA "+eta:""):d.status==="unscheduled"?"to schedule":d.status==="missed"?"missed — reschedule":d.status==="out"?"out for delivery":d.status==="loaded"?"loaded "+dateShort(d.date):"scheduled "+dateShort(d.date); bits.push((d.status==="delivered"?"Delivered":cap(dl))+(d.status==="delivered"?"":"")); if(d.status!=="delivered") bits[bits.length-1]=cap(dl); } if(p){ const pl=p.status==="pickedup"?"picked up "+dateShort(p.pickedUpAt):p.status==="awaiting"?"pickup awaiting stock":p.status==="partready"?"part ready for pickup":"ready for pickup"; bits.push(d&&d.status!=="delivered"?"pickup: "+pl:cap(pl)); } const now=inv.lines.filter(l=>!l.service&&l.takenAtSale).length; if(now) bits.push(now+" taken at sale"); if(!bits.length) return done===lines.length?"Taken at sale":"Mixed"; return bits.join(" · "); }
  if(f==="delivery"){ const d=deliveryOf(inv); const sched=d&&["scheduled","loaded","out","delivered"].includes(d.status)&&d.status!=="delivered"; steps=[["Sold",true],["Stock ready"+(!stockReady&&!allDone&&eta?" · ETA "+eta:""),stockReady||allDone],[sched?(anyDone?"Rest scheduled · ":"Scheduled · ")+dateShort(d.date):(anyDone&&!allDone?"Schedule the rest":"Scheduled"),!!sched||allDone],[allDone?"Delivered · "+dateShort(lines.map(l=>l.deliveredAt).sort().pop()):anyDone?"Partially delivered":"Delivered",!!allDone]]; }
  else { const p=pickupOf(inv); steps=[["Sold",true],["Stock ready"+(!stockReady&&!allDone&&eta?" · ETA "+eta:""),stockReady||allDone],[p?.plannedDate?"Pickup planned · "+dateShort(p.plannedDate):"Customer notified",!!(p&&(p.notified||p.plannedDate))||allDone],[allDone?"Picked up · "+dateShort(p?.pickedUpAt||lines.map(l=>l.deliveredAt).sort().pop()):anyDone?"Partially picked up":"Picked up",!!allDone]]; }
  let cur=steps.findIndex(s=>!s[1]); if(cur<0) cur=steps.length;
  return `<div class="stepper">${steps.map((s,i)=>`<div class="step ${s[1]?"done":i===cur?"cur":""}"><span class="dot">${s[1]?"✓":i+1}</span><span>${esc(s[0])}</span></div>`).join("")}</div>`;
}
/* ---- delayed items: ETA and customer notice ---- */
function delayText(inv,lines){ const c=byId("customers",inv.customerId); const st=storeSettings(); const eta=lines.map(l=>l.expected).filter(Boolean).sort()[0]; return `Hi ${firstName(c?.name)}, an update from ${st.name} on order ${inv.number}: ${lines.map(l=>l.qty+"× "+l.name).join(", ")} ${lines.length===1?"is":"are"} still on the way${eta?" — we expect "+dateFmt(eta):""}. We'll reach out to ${inv.delivery?"schedule delivery":"arrange pickup"} as soon as it lands. Thank you for your patience!`; }
function setEta(invId){ const inv=byId("invoices",invId); if(!inv) return; const open=inv.lines.filter(lineOpen); if(!open.length) return toast("Nothing outstanding on this invoice."); const c=byId("customers",inv.customerId);
  modal(`<h2>Outstanding items — ${esc(inv.number)}</h2><p class="muted">Set the expected date for each delayed item and let the customer know. Dates show on the invoice, the fulfillment tracker and the awaiting lists.</p><div class="tblwrap"><table><thead><tr><th>Item</th><th>Why</th><th>Expected</th></tr></thead><tbody>${open.map((l,i)=>`<tr><td>${esc(l.name)}<div class="muted small">${l.special?"Special order · "+esc(l.specialStatus||"pending"):"In stock"}</div></td><td><input type="text" id="eta_r_${i}" value="${esc(l.delayReason||"")}" placeholder="${l.special?"Vendor lead time":"e.g. damaged in transit, reorder"}"></td><td><input type="date" id="eta_d_${i}" value="${l.expected||""}"></td></tr>`).join("")}</tbody></table></div>
  <div class="actions"><button class="btn" onclick="closeModal()">Cancel</button>${c?.phone?`<a class="btn" href="#" onclick="saveEta('${invId}',true);return false">Save & text customer</a>`:""}<button class="btn p" onclick="saveEta('${invId}')">Save</button></div>`,true); }
async function saveEta(invId,text){ const inv=byId("invoices",invId); const open=inv.lines.filter(lineOpen); const days=storeSettings().etaAlertDays||3; open.forEach((l,i)=>{ l.expected=fv("eta_d_"+i)||l.expected||""; l.delayReason=fv("eta_r_"+i); }); await save("invoices",inv); for(const l of open){ if(l.expected) await addFollowup(inv.customerId,inv.id+":eta:"+l.lineId,"ETA check",`${l.name} expected ${dateShort(l.expected)} — confirm with the vendor and line up ${inv.delivery?"delivery":"pickup"}.`,addDays(l.expected,-days)); } for(const d of S.deliveries.filter(x=>x.invoiceId===invId&&!["delivered","pickedup"].includes(x.status))){ const eta=open.map(l=>l.expected).filter(Boolean).sort()[0]; d.expectedDate=eta||""; await save("deliveries",d); } closeModal(); render(); toast("Expected dates saved"); if(text){ const c=byId("customers",inv.customerId); if(c?.phone) location.href=`sms:${c.phone}?&body=${encodeURIComponent(delayText(inv,open))}`; } }
function etaOf(inv){ const open=inv.lines.filter(lineOpen); const d=open.map(l=>l.expected).filter(Boolean).sort()[0]; return d?dateShort(d):""; }
/* ---- pickup actions ---- */
function readyText(inv,partial){ if(partial){ const c=byId("customers",inv.customerId); const st=storeSettings(); const inL=inv.lines.filter(l=>lineOpen(l)&&!lineBlocked(l)).map(l=>l.name).join(", "); const waitL=inv.lines.filter(l=>lineOpen(l)&&lineBlocked(l)); const eta=waitL.map(l=>l.expected).filter(Boolean).sort()[0]; return `Hi ${firstName(c?.name)}, it's ${st.name}. Part of your order is in and ready to pick up (${inL}). The rest is still on order${eta?" and expected around "+dateShort(eta):""} — let us know if you'd like to collect what's here now or wait for everything.`; } const c=byId("customers",inv.customerId); const st=storeSettings(); return `Hi ${firstName(c?.name)}, good news — your order ${inv.number} is ready for pickup at ${st.name}${st.address?", "+st.address:""}. Please bring your invoice number and a vehicle that fits your items. Reply with a day that suits you!`; }
async function markNotified(pid){ const p=byId("deliveries",pid); p.notified=todayISO(); await save("deliveries",p); const inv=byId("invoices",p.invoiceId); for(const f of S.followups.filter(f=>f.status==="open"&&f.invoiceId===inv?.id&&f.type==="Ready for pickup")){ f.status="done"; f.doneAt=todayISO(); await save("followups",f); } render(); }
function planPickup(pid){ const p=byId("deliveries",pid); modal(`<h2>Pickup date</h2><div class="grid g2"><div class="field"><label class="f">Planned date</label><input type="date" id="pp_date" value="${p.plannedDate||""}"></div><div class="field"><label class="f">Time (optional)</label><input type="time" id="pp_time" value="${p.plannedTime||""}"></div></div><div class="field"><label class="f">Notes (vehicle, who's coming…)</label><input type="text" id="pp_notes" value="${esc(p.notes||"")}"></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn p" onclick="(async()=>{const p=byId('deliveries','${pid}');p.plannedDate=fv('pp_date');p.plannedTime=fv('pp_time');p.notes=fv('pp_notes');await save('deliveries',p);if(p.plannedDate){await addFollowup(p.customerId,p.invoiceId+':pk',"Pickup reminder","Remind the customer about tomorrow's pickup.",addDays(p.plannedDate,-1));}closeModal();render()})()">Save</button></div>`); }
function splitLineQty(inv,l,takeQty){ takeQty=Math.max(0,Math.min(l.qty,Math.floor(+takeQty||0))); if(takeQty<=0||takeQty>=l.qty) return null; const rest=Object.assign({},l,{lineId:uid(),qty:l.qty-takeQty,splitFrom:l.lineId}); delete rest.deliveredAt; delete rest.takenAtSale; l.qty=takeQty; const idx=inv.lines.indexOf(l); inv.lines.splice(idx+1,0,rest); for(const d of S.deliveries.filter(x=>x.invoiceId===inv.id&&x.lineIds&&x.lineIds.includes(l.lineId))){ d.lineIds=[...new Set(d.lineIds.concat([rest.lineId]))]; } return rest; }
function completePickup(pid){ const p=byId("deliveries",pid); const inv=byId("invoices",p.invoiceId); const c=byId("customers",inv.customerId); const open=pickupLines(inv); const T=invTotals(inv);
  customerModal(`<h2>Pickup — ${esc(c?.name||"Walk-in")} · ${esc(inv.number)}</h2>${inv.status==="layaway"?`<div class="notice">Layaway balance ${money(T.balance)} — items are released after the final payment.</div>`:""}
  <div class="small" style="margin-bottom:8px">${open.map((l,i)=>`<div class="row" style="gap:8px;margin-bottom:4px;flex-wrap:nowrap"><label class="chk" style="margin:0;flex:1"><input type="checkbox" id="pk_i_${i}" ${lineBlocked(l)?"disabled":"checked"}> ${l.qty}× ${esc(l.name)}${lineBlocked(l)?' <span class="tag warn">not received yet</span>':""}</label>${!lineBlocked(l)&&l.qty>1?`<span class="muted small" style="white-space:nowrap">taking now</span><input type="number" id="pk_q_${i}" min="1" max="${l.qty}" value="${l.qty}" style="width:64px;padding:3px 6px"><span class="muted small">of ${l.qty}</span>`:""}</div>`).join("")||`<p class="muted">Nothing left to pick up.</p>`}</div><p class="muted small" style="margin:-4px 0 8px">Taking fewer than the full quantity? Lower the number — the rest stays on the pickup list for next time.</p>
  ${T.balance>0.005&&inv.status!=="layaway"?`<div class="notice">Balance due ${money(T.balance)} <select id="pk_paym" style="width:auto;display:inline-block;padding:3px 6px;margin-left:6px"><option>Card</option><option>Cash</option><option>Check</option></select> <label class="chk" style="display:inline-flex;margin-left:8px"><input type="checkbox" id="pk_paid" checked> collected</label></div>`:""}
  <div class="grid g2"><div class="field"><label class="f">Picked up by</label><input type="text" id="pk_by" value="${esc(c?.name||"")}"></div><div class="field"><label class="f">ID / vehicle noted</label><input type="text" id="pk_id" placeholder="e.g. DL ending 4471, silver F-150"></div></div>
  <label class="f">Customer signature (inspected and received in good condition)</label><canvas class="sig" id="sigpad"></canvas><div class="row" style="margin:6px 0 10px"><button class="btn s fx" onclick="sigClear()">Clear</button><span class="muted small">Sign with a finger or mouse</span></div>
  <div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn" onclick="printPickupSlip('${pid}')">Print pickup slip</button><button class="btn p" onclick="finishPickup('${pid}')" ${inv.status==="layaway"||!open.some(l=>!lineBlocked(l))?"disabled":""}>Mark picked up</button></div>`,true); setTimeout(sigInit,50); }
async function finishPickup(pid){ const p=byId("deliveries",pid); const inv=byId("invoices",p.invoiceId); const open=pickupLines(inv); const taken=open.filter((l,i)=>!lineBlocked(l)&&fchk("pk_i_"+i)); if(!taken.length) return toast("Tick at least one item.",true); const qtyNow=open.map((l,i)=>{ const el=document.getElementById("pk_q_"+i); return el?Math.max(1,Math.min(l.qty,Math.floor(+el.value||l.qty))):l.qty; }); window._pkQty=qtyNow; { const T0=invTotals(inv); const collecting=T0.balance>0.005&&fchk("pk_paid"); if(releaseRule()&&T0.balance>0.005&&!collecting&&!p.releaseOverride) return releaseAsk(`${inv.number} still owes ${money(T0.balance)}. Store policy releases goods only when paid in full — collect the balance in this window, or release with manager approval.`,async()=>{ p.releaseOverride={by:session.staffId,at:todayISO(),action:"pickup"}; await save("deliveries",p); finishPickup(pid); }); } if(sigEmpty&&!confirm("No signature captured. Complete anyway?")) return;
  const today=todayISO(); { const q=window._pkQty||[]; taken.forEach(l=>{ const idx=open.indexOf(l); const want=q[idx]; if(want&&want<l.qty) splitLineQty(inv,l,want); }); } taken.forEach(l=>l.deliveredAt=today); const T=invTotals(inv); if(T.balance>0.005&&fchk("pk_paid")){ inv.payments.push({method:fv("pk_paym")+" (at pickup)",amount:T.balance,date:today,by:session.staffId}); if(invTotals(inv).balance<=0.005&&inv.status==="open") inv.status="paid"; }
  try{ await closeStaleFollowups(inv.id,"Picked up"); }catch(e){}
  await save("invoices",inv); const cv=document.getElementById("sigpad"); const rec={date:today,time:new Date().toTimeString().slice(0,5),by:fv("pk_by"),idNote:fv("pk_id"),items:taken.map(l=>l.qty+"× "+l.name),signature:await storeImage("signatures",p.id,sigEmpty?"":cv.toDataURL("image/png")),staff:session.staffId}; (p.events=p.events||[]).push(rec);
  const all=pickupLines(inv).length===0; if(all){ p.status="pickedup"; p.pickedUpAt=today; p.pickedUpBy=rec.by; p.pickedUpStaff=session.staffId; p.signature=rec.signature; } else { p.status=pickupStatusFor(inv); }
  await save("deliveries",p);
  for(const f of S.followups.filter(f=>f.status==="open"&&(f.invoiceId===inv.id||f.invoiceId===inv.id+":pk")&&["Ready for pickup","Special order arrived","Pickup reminder"].includes(f.type))){ f.status="done"; f.doneAt=today; await save("followups",f); }
  if(all){ await addFollowup(inv.customerId,inv.id,"Review request","Ask for a review.",addDays(today,14)); if(inv.lines.some(l=>l.mattress&&l.trial)) await addFollowup(inv.customerId,inv.id,"Sleep trial ending soon","Check in before the comfort trial ends.",addDays(today,Math.max(7,storeSettings().trialNights-14))); }
  closeModal(); render(); toast(all?"Picked up — order complete":`${taken.length} item${taken.length===1?"":"s"} picked up · ${inv.lines.filter(lineOpen).length} still to come`); printPickupSlip(pid,rec); }
function printPickupSlip(pid,rec){ const p=byId("deliveries",pid); const inv=byId("invoices",p.invoiceId); const c=byId("customers",inv.customerId); const st=storeSettings(); const items=rec?rec.items:inv.lines.filter(lineOpen).filter(l=>!lineBlocked(l)).map(l=>l.qty+"× "+l.name); printHTML(`<div class="page"><div style="display:flex;justify-content:space-between"><div>${logoHTML(48)}<h1>${esc(st.name)}</h1><div>${esc(st.address)}${st.phone?" · "+esc(st.phone):""}</div></div><div style="text-align:right"><h2>Pickup slip</h2><div>${esc(inv.number)} · ${dateFmt(rec?rec.date:todayISO())}${rec?" "+rec.time:""}</div></div></div><p style="margin:16px 0"><b>${esc(c?.name||"Walk-in")}</b><br>${esc(c?.phone||"")}</p><table class="ptable"><tr><th>Item</th><th>Released ☐</th></tr>${items.map(i=>`<tr><td>${esc(i)}</td><td>☐</td></tr>`).join("")}</table><p style="margin-top:12px">Picked up by: <b>${esc(rec?rec.by:"____________________")}</b>${rec?.idNote?" · "+esc(rec.idNote):""}</p>${rec?.signature?`<img class="sigimg" src="${rec.signature}" style="max-height:70px">`:`<p style="margin-top:30px">Customer signature: ____________________________</p>`}<p style="font-size:11px;margin-top:14px">Merchandise inspected and received in good condition. ${esc(st.footer)}</p></div>`); }
function printHoldTags(){ const list=pickups().filter(p=>p.status!=="pickedup"); if(!list.length) return toast("No holds to tag.",true); const tags=[]; list.forEach(p=>{ const inv=byId("invoices",p.invoiceId); if(!inv) return; inv.lines.filter(lineOpen).forEach(l=>{ for(let i=0;i<l.qty;i++) tags.push({p,inv,l}); }); }); const pages=[]; for(let i=0;i<tags.length;i+=6) pages.push(`<div class="page labelsheet">${tags.slice(i,i+6).map(x=>`<div class="plabel"><div class="big">HOLD</div><div style="font-size:18px;font-weight:700">${esc(custName(x.inv.customerId))}</div><div>${esc(x.inv.number)} · sold ${dateShort(x.inv.date)}</div><div style="margin-top:8px">${esc(x.l.name)}</div><div style="font-size:12px">${x.l.locationId?esc(locName(x.l.locationId))+(x.l.bin?" · bin "+esc(x.l.bin):""):(x.l.bin?"Bin "+esc(x.l.bin):"")}</div><div style="font-size:14px">${x.p.plannedDate?"Pickup "+dateFmt(x.p.plannedDate):"Pickup date TBD"}${lineBlocked(x.l)?" · awaiting stock":""}</div>${x.l.sku?`<svg class="bc" data-code="${esc(x.l.sku)}"></svg>`:""}</div>`).join("")}</div>`); printHTML(pages.join("")); }
async function convertToPickup(invId){ const inv=byId("invoices",invId); const d=deliveryOf(inv); if(d&&["loaded","out","delivered"].includes(d.status)) return toast("This delivery is already on its way.",true); if(d) await remove("deliveries",d.id); inv.fulfillment="pickup"; inv.delivery=false; inv.deliveryFee=0; await save("invoices",inv); await ensurePickup(inv); closeModal(); render(); toast("Changed to pickup"); }
async function convertPickupToDelivery(invId){ const inv=byId("invoices",invId); const p=pickupOf(inv); if(p&&p.status!=="pickedup") await remove("deliveries",p.id); inv.fulfillment="delivery"; inv.delivery=true; if(!inv.deliveryFee){ const z=zoneFee(byId("customers",inv.customerId)); inv.deliveryFee=(z&&z.fee!==null)?z.fee:storeSettings().deliveryFee; } await save("invoices",inv); const c=byId("customers",inv.customerId); const d=await save("deliveries",{id:uid(),invoiceId:inv.id,customerId:inv.customerId,date:"",winStart:c?.prefStart||"09:00",winEnd:c?.prefEnd||"17:00",truckId:"",status:inv.lines.some(l=>lineOpen(l)&&lineBlocked(l))||inv.status==="layaway"?"awaiting":"unscheduled",order:0,notes:c?.notes||"",haulAway:inv.lines.filter(l=>l.haulAway).length}); closeModal(); if(d.status==="unscheduled") editDelivery(d.id); else { render(); toast("Delivery will be schedulable once the items arrive"); } }
/* ---- pickups tab ---- */
function renderPickups(){ const list=pickups().filter(p=>byId("invoices",p.invoiceId)).sort((a,b)=>(a.status==="pickedup")-(b.status==="pickedup")||String(a.plannedDate||"9").localeCompare(String(b.plannedDate||"9"))); const open=list.filter(p=>p.status!=="pickedup"); const done=list.filter(p=>p.status==="pickedup").slice(0,20);
  const row=p=>{ const inv=byId("invoices",p.invoiceId); const c=byId("customers",inv.customerId); const rem=inv.lines.filter(lineOpen); const T=invTotals(inv); return `<tr><td><b>${esc(c?.name||"Walk-in")}</b><div class="muted small">${c?.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:""} · <a href="#" onclick="openInvoice('${inv.id}');return false">${esc(inv.number)}</a> · sold ${dateShort(inv.date)}</div></td><td>${rem.map(l=>`${l.qty}× ${esc(l.name)}${lineBlocked(l)?' <span class="tag warn">'+esc(l.specialStatus||"ordered")+(l.expected?" · ETA "+dateShort(l.expected):" · no ETA")+"</span>":""}`).join("<br>")||'<span class="muted">all picked up</span>'}${T.balance>0.005?`<div class="small" style="color:var(--red)">Balance ${money(T.balance)}</div>`:""}</td><td>${p.status==="pickedup"?statusTag("picked up")+`<div class="muted small">${dateShort(p.pickedUpAt)} · ${esc(p.pickedUpBy||"")}</div>`:p.status==="awaiting"?statusTag(inv.status==="layaway"?"held":"awaiting")+(inv.status==="layaway"?'<div class="muted small">layaway</div>':""):p.status==="partready"?'<span class="tag warn">part ready</span><div class="muted small">rest still on order</div>':statusTag("ready")+(p.notified?`<div class="muted small">notified ${dateShort(p.notified)}</div>`:'<div class="small" style="color:var(--amber)">not notified</div>')}</td><td>${p.plannedDate?`<b>${dateShort(p.plannedDate)}</b>${p.plannedTime?" "+m2t(t2m(p.plannedTime)):""}`:"—"}${p.notes?`<div class="muted small">${esc(p.notes)}</div>`:""}</td><td>${p.status==="pickedup"?`<button class="btn s" onclick="printPickupSlip('${p.id}',byId('deliveries','${p.id}').events.slice(-1)[0])">Slip</button>`:`<div class="bgroup">${p.status==="ready"&&c?.phone?`<a class="btn s" href="sms:${esc(c.phone)}?&body=${encodeURIComponent(readyText(inv))}" onclick="markNotified('${p.id}')">Text ready</a>`:""}${p.status==="awaiting"?`<button class="btn s" onclick="setEta('${inv.id}')">ETA</button>`:""}<button class="btn s" onclick="planPickup('${p.id}')">Date</button><button class="btn s p" onclick="completePickup('${p.id}')" ${p.status==="ready"||p.status==="partready"?"":"disabled"}>${p.status==="partready"?"Pick up what's in":"Pick up"}</button>${releaseNote(p)}${dd("⋯",[["Convert to delivery",`convertPickupToDelivery('${inv.id}')`],["Print pickup slip",`printPickupSlip('${p.id}')`]],"s")}</div>`}</td></tr>`; };
  return `<div class="card"><div class="tblwrap"><table><thead><tr><th>Customer</th><th>Waiting to be picked up</th><th>Status</th><th>Planned</th><th></th></tr></thead><tbody>${open.map(row).join("")||`<tr><td colspan="5" class="empty">No open pickups. Sales set to "Hold for pickup" appear here, as do special orders the customer will collect.</td></tr>`}</tbody></table></div>${done.length?`<h3 style="margin:16px 0 8px">Recently picked up</h3><div class="tblwrap"><table><tbody>${done.map(row).join("")}</tbody></table></div>`:""}</div>`; }
